### ISSUE TITLE
Zanran: Url escaping issue with API requests

### ISSUE THREAD

**Issue by taw** [duckduckgo/zeroclickinfo-spice#102]
I've seen a ton of malformatted URLs in logs coming from DDG plugin for zanran.

I thought it might be an error in the plugin, but it doesn't seem so.

When I search for:

  saudi arabia "oil production"

with duckpan server, this apparently correct URL gets generated:

  GET /search/simple_json?callback=ddg_spice_zanran&q=saudi%20arabia%20%22oil%20production%22
HTTP/1.1

then zanran API returns correct result, and everything works.

But the same search on duckduckgo.com generates this:

  GET /search/simple_json?callback=ddg_spice_zanran&q=saudi%20arabia%20"oil%20production"
HTTP/1.0

With nothing except spaces escaped, and server returns error due to
malformatted URL.

I think any query with weird characters like quotation marks in it is
likely to be affected.

It's not a big deal since it's presumably only a tiny fraction of all queries,
but it might affect other plugins as well, and it's probably pretty
simple to fix.

Or as a workaround zanran plugin's spice.js could just replace most punctuation
with spaces before sending API request instead of after.
(zanran API tries to handle punctuation semi-intelligently replacing & with and,
stripping 's etc., but it probably doesn't matter all that much,
it's just a series of preprocessing regexps).

**Comment by javathunderman** [comment]
@moollaza Has this been fixed?

**Comment by moollaza** [comment]
@javathunderman I don't think so, will need to verify.

@taw are you still seeing this on your logs?

**Comment by javathunderman** [comment]
@moollaza ping, don't think this has been resolved yet.

**Comment by taw** [comment]
@moollaza I don't have access to zanran logs any more (well, not directly, I could always ask).

It seems to still be a problem as `saudi arabia oil production` returns zanran results while `saudi arabia "oil production"` doesn't.

Assuming my original report was correct, it was a difference between duckpan server and live ddg server behaviour, so the problem is probably not in this repository.
