### ISSUE TITLE
NJTransit multi-leg options?

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#1044]
I was using it IRL yesterday to get from NY Penn Station to Asbury Park. There's very few direct options from NYC to jersey shore. However, there's lots of options (found via NJTransit.com) if you transfer in Newark. None of these options show up in our IA.

------ 

IA Page:  https://duck.co/ia/view/transit_njt

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are only accepting issues for essential bugs/fixes.
