### ISSUE TITLE
Movie / InTheaters: Text overflows on mobile view sometimes

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1140]
![img_0325](https://cloud.githubusercontent.com/assets/81969/4513078/0632cd76-4b48-11e4-8fd1-69ee9367fb74.PNG)

https://duck.co/ia/view/movie
https://duck.co/ia/view/in_theaters

**Comment by MrChrisW** [comment]
@moollaza @jagtalon Fixed in #1442 ?

**Comment by moollaza** [comment]
@jagtalon @MrChrisW just tested on BrowserStack and it doesn't look like it:
![2015-02-09_18h31_27](https://cloud.githubusercontent.com/assets/873785/6118276/fad86286-b089-11e4-9d81-fd6754fb716f.png)
