### ISSUE TITLE
Definition: for languages other than English use Wiktionary

### ISSUE THREAD

**Issue by jc86035** [duckduckgo/zeroclickinfo-spice#1161]
Currently all dictionary definitions are sourced from Wordnik (and to a small extent Urban Dictionary). If Wiktionary (https://www.wiktionary.org) is used as a source the number of definitions would be increased substantially, as Wordnik (and Urban Dictionary) only contain English definitions. This could also be used to improve definitions in other language editions.

------ 

IA Page:  https://duck.co/ia/view/dictionary_definition

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are only accepting issues for essential bugs/fixes.
