### ISSUE TITLE
Improve Currency Triggers

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#1175]
Review and refine the currency names, things like: ```10 dollars to pounds``` or ```juan to dollars``` should work.

Also should ideally work with symbols, i.e. ```$10 to euro```

https://duck.co/ia/view/currency

**Comment by mrshu** [comment]
I just tried the following query today and would assume some Currency Conversion IA to show up

https://duckduckgo.com/?q=AU+%2434.93+to+USD

@bsstoner told me to send this example here so that there are example to test any new improvements against.

**Comment by MrChrisW** [comment]
@mrshu Interesting example. Are you searching for AUD to USD? 

AU isn't a recognised currency code, while the Currency Spice could be improved to trigger in this case, I'm not sure "AU $" is correct terminolog?

**Comment by mrshu** [comment]
@MrChrisW Yes, that's what I was searching for and that's a very good point. I think I saw that on eBay or somewhere like that and just copied it. 

While I understand your point, that other big search engine does show some sort of currency IA which is what I would just expect to see for this query too.

That being said, feel free to ignore this example, I can see how difficult it is to account for all these strange ways of expressing currencies.

**Comment by MrChrisW** [comment]
@mrshu Don't want to ignore the example! It would be great to support they types of queries, it would just mean using the `Locale::Country` package or a list of two letter country and matching the query, definitely possible :smile:

Speaking of other search engines supporting these types of queries, I've checked and some of the results can be strange! https://duckduckgo.com/?q=BR+34.93+to+USD+!g :confused:

**Comment by nilnilnil** [comment]
"@__nil my example above was "£40 in aud". Google does better at AU-centric searching. I'll try to send you them as I find them if you like…"
https://twitter.com/peternlewis/status/583286866549420032

**Comment by stephenjudge** [comment]
Is there any particular reason why the old currency triggers like $20=€ to get a Dollar to Euro conversion, that used to work, now no longer work? I do remember that the information displayed was coming from Wolfram Alpha and I haven't seen any Wolfram Alpha information come up again in a long time. Has DDG lost licensing rights to Wolfram Alpha information?

**Comment by moollaza** [comment]
@stephenjudge we no longer use WolframAlpha, we've since switched to use other APIs for the various niches Wolfram covered. For currency, we've moved to an open-source Spice Instant Answer which uses the XE.com API.

**Comment by stephenjudge** [comment]
@moollaza Thanks for the explainer. I got quit used to using the $20=€ input, do you think this could be replicated with the new XE.com API? Or what would the closest valid input to that one be? Ironically when DDG stopped working for me for currency conversion I switched to using an XE.com Firefox Search Plugin, but I much preferred using DDG.

**Comment by moollaza** [comment]
Yup that should be possible. We'll need a way to map a currency symbol to a country/region though.

**Comment by stephenjudge** [comment]
@moollaza I'm glad it's possible. I'm afraid I wouldn't know what to do to help you with the currency symblol mapping, I hope you can figure it out though. What would be the best input value to achieve the same result using the current spice?

**Comment by moollaza** [comment]
>What would be the best input value to achieve the same result using the current spice?

@stephenjudge "20 dollars to EUR", https://duckduckgo.com/?q=20+dollars+to+EUR&ia=currency

**Comment by stephenjudge** [comment]
@moollaza Great thanks. So I guess all currency acronyms work, so I could also do 20 USD to EUR or 20 GBP to EUR. I could get used to that.

**Comment by moollaza** [comment]
Yup currency names work as well, "20 yen to euros", https://duckduckgo.com/?q=20+yen+to+euros&ia=currency

**Comment by stephenjudge** [comment]
@moollaza Cool, how do you get around the many currencies that are also called dollars, like Canadian Dollars or Australian Dollars? If using just the word dollars defaults to US Dollars.

**Comment by moollaza** [comment]
You can just specify, "20 canadian dollars to AUD", https://duckduckgo.com/?q=12+canadian+dollars+to+aud&ia=currency

**Comment by anupamsr** [comment]
Neither '9 usd into inr' nor '9 usd to inr' work. This used to work previously, but hasn't in many months.

**Comment by MrChrisW** [comment]
@anupamsr `9 usd to inr` works.
https://duckduckgo.com/?q=9+usd+to+inr&ia=currency

`into` isn't supported at the moment. Thanks for the suggestion!

**Comment by anupamsr** [comment]
Hmm. It does seem to work on IE - I had no idea.

http://s188.photobucket.com/user/anupamsr/media/strangeissue.png.html

**Comment by anupamsr** [comment]
@MrChrisW Hmm. It does seem to work on IE - I had no idea.

http://s188.photobucket.com/user/anupamsr/media/strangeissue.png.html

**Comment by MrChrisW** [comment]
@anupamsr Are you running any extensions on Pale Moon? What version are you running? Does the Currency Instant Answer still not load?

**Comment by anupamsr** [comment]
@MrChrisW Not sure. Even safe mode doesn't work.

http://i188.photobucket.com/albums/z89/anupamsr/strangeissue2.png

**Comment by MrChrisW** [comment]
Closing as the original queries mentioned by @bsstoner are now working. 

+ https://duckduckgo.com/?q=%2410+to+euro
+ https://duckduckgo.com/?q=10+dollars+to+pounds

**Comment by bsstoner** [comment]
:+1:
