### ISSUE TITLE
Currency: Use high-resolution XE favicon for Retina screens

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1197]
The XE favicon right beside the "More at ..." link looks blurry and pixelated on Retina screens.

![img_0031](https://cloud.githubusercontent.com/assets/81969/4762895/9e89d2ac-5b08-11e4-8d72-0b94881a8fa1.png)

https://duck.co/ia/view/currency

**Comment by ScreapDK** [comment]
Shouldn't we just fetch all favicons through the [getFavicon](https://getfavicon.appspot.com/)-service, via the DDG reverse proxy.

AFAIK, the service grabs them in the best available size, in fact I think it grabs **all sizes**... but that's for **favicons only**, not other icons, like Apple Touch icons. Which is unfortunate, since they are usually available in large sizes.

**Comment by MrChrisW** [comment]
@ScreapDK That's what the IA is currently doing by using [`sourceIconUrl`](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/currency/currency.js#L128) the problem is the favicon is only 16x16 so on mobile it looks bad, "apparently" especially on retina screens :laughing:

**Comment by ScreapDK** [comment]
@MrChrisW Quick question: Doesn't the service support favicons in larger sizes?

**Comment by MrChrisW** [comment]
@ScreapDK You mean the getFavicon service you mentioned above? Maybe. 

The problem is the source favicon provided by XE.com is only in one size 16x16 so we can't just resize it we require a larger source icon.

**Comment by ScreapDK** [comment]
Hmm... what I mean was that when you specify all multi-size favicon, e.g. just we ourselves (at DDG) (see `<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" sizes="16x16 24x24 32x32 64x64"/>` of [DDG homepage](https://duckduckgo.com/))

...then getFavicon, the source of our favicons (cf. this [DDG help page](https://duck.co/help/features/favicons))... should be able to extract all sizes! :) ...like this: ![ddg favicon](https://icons.duckduckgo.com/ip2/duckduckgo.com.ico) <-- that icon *should* support all those 4 sizes. I'll report on whether it does!

**Comment by ScreapDK** [comment]
@MrChrisW (see [above comment](https://github.com/duckduckgo/zeroclickinfo-spice/issues/1197#issuecomment-96146308)) It does! I tried opening it in "[Windows Photo Viewer](https://en.wikipedia.org/wiki/Windows_Photo_Viewer)" on Windows 7, giving me this result showcasing the biggest size included in that favicon:
![proof](http://i.scrp.dk/za9G8v1.png)

**Comment by ScreapDK** [comment]
@MrChrisW BTW, I can't even find any favicon code on the EX.com website, maybe we should just use custom-applied assets, like when showing favicons of certain websites in SERPs (this is the case with Wikipedia, which I assume is because the Wikipedia-Instant Answer is displayed so much).

**Comment by MrChrisW** [comment]
@ScreapDK Sure, I understand what you mean by multiple sized icons, unfortunately XE.com doesn't provide the favicon in any other sizes. We will likely need to use the custom logo assets fro.

**Comment by MrChrisW** [comment]
@ScreapDK Great news! Turns out we can update the `sourceIcon` as it's actually specified in the template! I've made a pull request with the changes. :+1: 

Thanks again for your suggestions, pushed me to checkout the code again and make the changes.
