### ISSUE TITLE
Quixey: iOS apps not being shown in app search when multi-platform?

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1234]
![american_idol_app_at_duckduckgo](https://cloud.githubusercontent.com/assets/81969/4961229/39dad4da-66cc-11e4-9581-e34536c1510e.png)
![social_networking_app_at_duckduckgo-3](https://cloud.githubusercontent.com/assets/81969/4961231/39e190d6-66cc-11e4-894a-d27f05cd3394.png)
![tinder_app_at_duckduckgo](https://cloud.githubusercontent.com/assets/81969/4961230/39e050d6-66cc-11e4-829a-db54ab6668cd.png)

https://duck.co/ia/view/quixey

**Comment by moollaza** [comment]
API seems to be working correctly now!
