### ISSUE TITLE
AlternativeTo: Should decode entities

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1305]
![screen shot 2014-12-02 at 1 42 31 pm](https://cloud.githubusercontent.com/assets/81969/5268650/3d04c7ea-7a29-11e4-841f-2fd1cc35a39c.png)

https://duck.co/ia/view/alternative_to

**Comment by marianosimone** [comment]
@jagtalon `strip_html` is NOT supposed to unescape html entities, so I think that what we are missing is a call to some kind of `unescape` (e.g. underscore's [unescape](http://underscorejs.org/#unescape))

I (think I) remember underscore being one of the available packages, but I couldn't find any reference to it.
