### ISSUE TITLE
Twitter: Title should probably be a link

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1309]
Clicking on the header doesn't let me go to Twitter.

![screen shot 2014-12-02 at 4 03 56 pm](https://cloud.githubusercontent.com/assets/81969/5270845/dfb159fa-7a3c-11e4-8723-e254c07bcce3.png)

**Comment by javathunderman** [comment]
@jagtalon Should I create a .t file for #1386?

**Comment by jagtalon** [comment]
@javathunderman the change is JavaScript, and unfortunately we can't test that from the .t file.

**Comment by jagtalon** [comment]
This has been fixed by @laouji in #1386

**Comment by javathunderman** [comment]
Oh, right.
