### ISSUE TITLE
InTheaters: Show more movies

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1310]
Would be great if we could show more than 12 movies.

![screen shot 2014-12-02 at 4 11 00 pm](https://cloud.githubusercontent.com/assets/81969/5270961/d6fcff84-7a3d-11e4-90f6-2d7f7f9a7036.png)

https://duck.co/ia/view/in_theaters

**Comment by NeoSilky** [comment]
Just fixing this now, watch out for the pull request!

**Comment by jagtalon** [comment]
Fixed by @NeoSilky in #1453
