### ISSUE TITLE
Plos: Needs a facelift -- Move towards canonical Text tile

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1311]
https://duckduckgo.com/?q=plos+dinosaurs

Currently the Tile is just a large link with a year, which looks bad. This should be updated to look more like similar/related, text-only tile view Instant Answers. Also there's tons of data in the API response that we're not using -- let's improve this IA and give it a much needed facelift :smile:

**Comment by laouji** [comment]
Hi. Please check out my pull request referenced above.

**Comment by jagtalon** [comment]
Fixed by #1410
