### ISSUE TITLE
Quixey: Updates required to API call for iOS Apps and results specific to user's mobile device

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1316]
Two important fixes are required to ensure iOS apps are properly displayed in desktop results, and only relevant, platform-specific results are displayed for mobile searches:
1. For generic app queries, e.g. "racing apps", `custom_id` is not necessary and should be removed.
   
   For platform specific queries, e.g. "android data usage app", the `custom_id` (along with the appropriate platform id) should be added to limit the results to App editions that are appropriate for the requested device. For example, a search for Android apps, should have `&platform_ids=[2005]&custom_id=75675980` to only return Google Play results.
2. `edition_limit` should be passed and it's value set to 0 (i.e. `edition_limit=0`). 

//cc @jagtalon

------ 

IA Page:  https://duck.co/ia/view/quixey

**Comment by marianosimone** [comment]
These seem to be many different issues into one... Let's see if I can help with them:

1. `custom_id` can be removed from generic searches... Agree with that, and it's simple to do
2. For platform specific queries (e.g. "android data usage app", the `platform_ids` and `custom_id` ARE being sent, and there's a bunch of test verifying that
3. I couldn't find any documentation on the `edition_limit` param for the Quixey API. Is that still relevant?
4. I don't know how to detect the platform of the search (to include the params to make it platform-specific). Any pointers?

**Comment by moollaza** [comment]
@marianosimone I don't recall what the `edition_limit` does exactly either. I believe Quixey's API docs are not available online either, but they had told me we should make these changes.

>I don't know how to detect the platform of the search (to include the params to make it platform-specific). Any pointers?

There's already a bunch of code in the Perl that does this. We basically check if any word in the query is the name of a platform :+1:

**Comment by moollaza** [comment]
This IA was removed a long time ago.
