### ISSUE TITLE
SteamSpecials: Not showing on SERP?

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1349]
Looks like the API result is there, but it's not appearing on the SERP. I see no JS errors in the console. Not sure why it's not displaying...

cc// @killerfish 

https://duck.co/ia/view/steam_specials

**Comment by javathunderman** [comment]
@moollaza @killerfish Any update on this?

**Comment by killerfish** [comment]
@javathunderman unfortunately, none so far, but thanks for reminding me, let me ping again

**Comment by russellholt** [comment]
steam was removed, apparently
#1403
