### ISSUE TITLE
Forecast: Triggers on "weather network"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1353]
https://duckduckgo.com/?q=weather+network&t=ffab&ia=weather

It shouldn't ;)

Our relevancy checking should have thrown that out because it's showing weather for "Nova Odessa, Brazil" which is nothing like "network"...

//cc @jagtalon 

https://duck.co/ia/view/forecast

**Comment by killerfish** [comment]
We can always throw all [city abbreviations] (http://globalinkllc.com/useful-info/weblinks/codes-of-abbreviations-to-airportscities-codes/) into yaml and filter queries in perl, as per the case @jagtalon mentioned in #1359 (`weather nyc`). If there are other cases, well, that goes internal then, i believe?

**Comment by MrChrisW** [comment]
@killerfish A similar thing was done for the Time IA! I believe #1596 will resolve this issue with some internal changes being made.

**Comment by killerfish** [comment]
Oh, didnt know it was there :/ Need to know somehow when people pick up an issue to fix (to avoid multiple people working on the same thing)

**Comment by moollaza** [comment]
> Need to know somehow when people pick up an issue to fix (to avoid multiple people working on the same thing)

Commleaders should assign tasks to themselves that they intend to fix. A comment on the issue about an incoming fix would also certainly help :)

**Comment by moollaza** [comment]
Regarding this particular issue though, with the weather IA, we're going to remove most of the triggers and let our internal triggering (based on organic links) do the work to see if this helps ensure we only trigger and show the IA when needed.

**Comment by killerfish** [comment]
@moollaza Yup, i meant for the regular contributors ^^

**Comment by tommytommytommy** [comment]
@MrChrisW @killerfish @moollaza We just merged the changes that remove all words from the trigger list for Forecast except "weather". But, it is true that "weather network" still triggers when it shouldn't. I didn't want to remove "weather" yet because there are some cities that don't always show up in our search results (and therefore we can't infer them and internally trigger Forecast), but these are becoming fewer and farther between. If you are comfortable removing "weather" from the list of triggers and relying only on our internal trigger for this IA, I support it! We can always revert if we feel that it is under-triggering...

**Comment by tommytommytommy** [comment]
OH. Except, this will break "weather", which tries to return the weather for the user's current location :-(

**Comment by moollaza** [comment]
> OH. Except, this will break "weather", which tries to return the weather for the user's current location :-(

@tommytommytommy I think for that^ reason we should leave the weather trigger and just make sure that "weather network", "weather alert", etc don't show a result.

With the coming "place detection" function, we should be able to check if the candidate location is in fact, a location (rather than a dictionary word) which should help with relevancy.

**Comment by ponychicken** [comment]
Has this been fixed in the meantime?
All the example urls work correctly for me now:
https://duckduckgo.com/?q=weather+network&t=ffab&ia=weather 
https://duckduckgo.com/?q=weather+quantum+physics
https://duckduckgo.com/?q=weather+supercalifragilisticexpialidocious+test

**Comment by moollaza** [comment]
@ponychicken looks like it has :+1:
