### ISSUE TITLE
Steam Specials: API call changed so no longer works.

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/zeroclickinfo-spice#1372]
steam specials

**Comment by killerfish** [comment]
duplicate #1349

**Comment by jagtalon** [comment]
@MrChrisW mentioned that the API call changed https://github.com/duckduckgo/zeroclickinfo-spice/pull/1376#issuecomment-68428134. Changing the issue.

**Comment by killerfish** [comment]
Yup, i mailed a valve contact, 2-3 weeks back to make an exception for ddg, haven’t heard from him yet (probably busy with holidays). I would be at one of their events on 5-6 Jan, so ill try to check with someone directly, and update, otherwise.

**Comment by jagtalon** [comment]
Thank you @killerfish!

**Comment by MrChrisW** [comment]
@killerfish Any luck with this? 

Unfortunately I doubt they're going to fix their API as this issue has gone on for quite sometime. We may need to change to enumerating through each APPID although that would be slow!

**Comment by killerfish** [comment]
Yea, we cant have that, im still waiting for feedback on this, but for the time being, lets power off the steam instant answer, hopefully, we'd be able to get something on this in the future.

**Comment by moollaza** [comment]
Steam Spice removed in #1403
