### ISSUE TITLE
Flights - RouterHelper: Not working in Production

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1377]
https://duckduckgo.com/?q=delta+Toronto+to+Amsterdam

Looking in the dev panel, the request to `/js/spice/route_helper` returns no results in production, but works correctly in DuckPAN. 

https://duckduckgo.com/js/spice/flights/route_helper/YYZ/AMS/arr/2014/12/26?hourOfDay=10

@tommytommytommy I noticed that RouteHelper.pm is only expecting 1 param to be passed along because there is no `spice from` and only `$1` is being used, but the `router_helper.js` builds a much larger query with several params: https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/flights/route/flights_route.js#L59-63

Can you double check if everything is correct?

**Comment by tommytommytommy** [comment]
@moollaza Thanks for the heads-up on this bug (sorry for the delay!). Will get back to you as soon as I can track this down.
