### ISSUE TITLE
xkcd: Buttons aren't positioned properly on IE 8

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1384]
Other browsers:
![screen shot 2014-12-31 at 11 07 43 am](https://cloud.githubusercontent.com/assets/81969/5588730/7f5c69ac-90dd-11e4-9cb6-d4ace78e6e32.png)

IE 8:
![screen shot 2014-12-31 at 11 08 14 am](https://cloud.githubusercontent.com/assets/81969/5588731/7f6a498c-90dd-11e4-84e5-9036d923f922.png)

**Comment by andrey-p** [comment]
This one looks fairly straightforward. Looks like a problem with `:first-of-type` and `:last-of-type` selectors, which IE8 [doesn't seem to support](http://caniuse.com/#feat=css-sel3). Mind if I take it?

**Comment by MariagraziaAlastra** [comment]
@andrey-p Sure, go ahead :)
