### ISSUE TITLE
DNS: Tab name should probably be DNS instead of the domain name

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1395]
If you look at the tab, it says "Asana.Com". It should probably be just "DNS" or maybe "Domain Information" to be more descriptive

![screen shot 2015-01-05 at 10 27 21 am](https://cloud.githubusercontent.com/assets/81969/5615064/8fcf7356-94c5-11e4-9934-74bef27e073b.png)

**Comment by MrChrisW** [comment]
This change was introduced in #1128 the previous value was "Answer"

**Comment by jagtalon** [comment]
@MrChrisW Oh I see--I think it might be better for it to be "Answers" mostly because the way the letters are cased in "Asana.Com" and "Duckduckgo.Com" are bothering me haha

**Comment by MrChrisW** [comment]
Fixed in #1401
