### ISSUE TITLE
People in space images

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/zeroclickinfo-spice#1405]
Looks like there are images and a short bio available now. 
![selection_316](https://cloud.githubusercontent.com/assets/1882892/5682182/20c1d916-97ec-11e4-87f8-e15db3bd442c.png)
Any interest in using them @elebow @chrismorast @abeyang?

**Comment by chrismorast** [comment]
Yes @jdorweiler , there's already a PR for this: https://github.com/duckduckgo/zeroclickinfo-spice/pull/1296

**Comment by jdorweiler** [comment]
@chrismorast closing, thanks!
