### ISSUE TITLE
Improve wikipedia goodie

### ISSUE THREAD

**Issue by asantos3** [duckduckgo/zeroclickinfo-spice#1413]
Hopefully this is the right place - I would like to say a couple of things that could improve the infobox (the right side) in the "About" section.

* Add the age when available - Sometimes is quite useful to see how many years someone or a thing has. E.g. [Linus Torvals](https://duckduckgo.com/?q=Linus+Torvalds&ia=about) ([screenshot](https://cloud.githubusercontent.com/assets/1958425/5729713/5e5fa090-9b6c-11e4-98fa-ed1bff0443ac.png)) should have his age in the "Born" thing (and the Spouse's) and [Linux](https://duckduckgo.com/Linux?ia=about) ([screenshot](https://cloud.githubusercontent.com/assets/1958425/5729806/1e532098-9b6d-11e4-84eb-614bf186db43.png)) should display how many years as passed right next to the date (and the "Latest release" thing). Both of this examples have the missing bits in the screenshots in red in the wikipedia infobox.

* Some famous personalities have "Related Topics" in the infobox, while I dig that I would also like to check some information about said personality. Maybe you could implement a way to check both - maybe tabs like "Information | Related Topics" where one is opened by default? Examples of this issues are "Cristiano Ronaldo" and "Barack Obama".

**Comment by jagtalon** [comment]
@asantos3 thank you for this! Unfortunately Wikipedia is an internal project. I'll transfer it to our internal bug list.
