### ISSUE TITLE
Currency: Should accept plural forms of currency names

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1419]
Some discussion on the CP here: https://duck.co/ideas/idea/4827/british-pounds-in-currency-conversions

A query like "100usd to british pounds" doesn't currently work, however removing the plural, causes it to trigger successfully: https://duckduckgo.com/?q=100usd+to+british+pound&ia=currency

This problem seems to exist for other (all?) currencies:
- https://duckduckgo.com/?q=100usd+to+canadian+dollars
- https://duckduckgo.com/?q=100usd+to+south+african+rands

We should definitely allow for pluralized currencies!

https://duck.co/ia/view/currency

**Comment by laouji** [comment]
Added a quick fix in pull request #1450. Check it out when you get a chance.

**Comment by jagtalon** [comment]
Fixed by @laouji in #1450
