### ISSUE TITLE
Currency: Better triggers for precious metals

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1421]
https://duck.co/ideas/idea/4797/add-commodities-to-valuta-ratios

Right now you must use the [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) codes to indicated Gold, Silver, Platinum and Palladium. We should add some logic to except those names and related terms like "ounce", "ounces", "oz", so we can handle queries like "1oz Gold in USD"

------ 

IA Page:  https://duck.co/ia/view/currency

**Comment by W25** [comment]
"Gold price" and "gold price per gram" sounds more natural and that's what people usually search for (according to search suggestions).

**Comment by moollaza** [comment]
@W25 I agree! all of those are excellent triggers that this IA should be able to detect

**Comment by gabhi** [comment]
@moollaza I would like to work on this issue.

**Comment by gabhi** [comment]
@moollaza do you which API can i use to get the results?

**Comment by MrChrisW** [comment]
@gabhi You will be able to use the existing XE.com API which is included in the currency IA. See https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Currency.pm#L38

**Comment by gabhi** [comment]
Thanks @mrchrisw

**Comment by gabhi** [comment]
@moollaza @MrChrisW I created a pull request https://github.com/duckduckgo/zeroclickinfo-spice/pull/2564. Can you please have a look at it?
