### ISSUE TITLE
Bitcoin price ticker no results

### ISSUE THREAD

**Issue by MrChrisW** [duckduckgo/zeroclickinfo-spice#1432]
IA: https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Bitcoin.pm
Issue: Not returning results. 

**Expected:**
Show results for the query [bitcoin exchange rate](https://duckduckgo.com/?q=bitcoin+exchange+rate)

**Actual:**
No results returned. 
![selection_088](https://cloud.githubusercontent.com/assets/5282264/5833561/8fce41f8-a18f-11e4-84f4-f16af41e38ec.png)

Endpoint not returning data: https://duckduckgo.com/js/spice/bitcoin/
`ddg_spice_bitcoin();`

_____

This works locally (duckpan): 
![selection_089](https://cloud.githubusercontent.com/assets/5282264/5833588/cbc35644-a18f-11e4-8d0d-66770d66c7e7.png)

**Comment by MrChrisW** [comment]
Related: #1367

**Comment by jagtalon** [comment]
Thanks @MrChrisW. Looks like this on our end because Q/A has a higher priority. Closing and moving to our internal bug list.
