### ISSUE TITLE
Flights: Needs some CSS love

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1436]
This has regressed from it's original state. Mainly the title size and padding but also need to make sure the larger text (title and times) should have the class `tx-clr--dk` (so that it has the color `#333`). 

Should be:
![vx 143 at duckduckgo](https://cloud.githubusercontent.com/assets/81969/5839802/b9a7347a-a15e-11e4-9638-fea0ed8351f3.jpg)

Instead we have:
![screen shot 2015-01-21 at 11 14 38 am](https://cloud.githubusercontent.com/assets/81969/5839805/bfb4337c-a15e-11e4-9df9-1e05d84e2980.png)

CC @abeyang @chrismorast

**Comment by jagtalon** [comment]
Actually, if it had Route's CSS it would be fine:

![screen shot 2015-01-23 at 8 30 02 am](https://cloud.githubusercontent.com/assets/81969/5875352/1de62fd2-a2da-11e4-962b-3307c9927cd2.png)

https://duckduckgo.com/?q=Jetblue+Boston+to+Los+Angeles&ia=route

**Comment by MrChrisW** [comment]
Fixed by @tommytommytommy in #1449
