### ISSUE TITLE
Don't trigger twitter IA for [dictionary match single words]

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/zeroclickinfo-spice#1454]
e.g. 

https://duckduckgo.com/?q=twitter+analytics&t=ffab&ia=social

https://duck.co/ia/view/twitter

**Comment by puskin94** [comment]
I noticed that it doesn't works if the username contains numbers! 
e.g. https://duckduckgo.com/?q=twitter+puskin94
or https://duckduckgo.com/?q=%40puskin94

**Comment by zekiel** [comment]
@puskin94  looks like some work is going on over at #1455
