### ISSUE TITLE
Trigger GithubStatus and TravisStatus with just "github" and "travisci"?

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1457]
I was thinking that maybe simple queries like "github" or "travisci" should trigger GitHubStatus and TravisStatus. I think it would be a pleasant surprise for people when they put in those queries and see the status of the website. 

https://duckduckgo.com/?q=travis+ci+status&t=ffab&ia=status
https://duckduckgo.com/?q=github+status&t=ffab&ia=status

What do you think? @MariagraziaAlastra @jdorweiler @moollaza

**Comment by moollaza** [comment]
@jagtalon ya I think that would be fine :)

**Comment by jdorweiler** [comment]
Sounds like a good idea to me :cactus:

**Comment by jagtalon** [comment]
Sweet thanks!

**Comment by MrChrisW** [comment]
@jagtalon @moollaza @jdorweiler Currently these queries are served by the wiki IA which is probably the most appropriate. Optionally the status IA can be included with a low signal? 

![selection_143](https://cloud.githubusercontent.com/assets/5282264/5991421/8296f79e-aa29-11e4-96cd-76d83f016083.png)

![selection_142](https://cloud.githubusercontent.com/assets/5282264/5991422/8298a97c-aa29-11e4-9ca0-211410a14200.png)

Keyword `travisci` should probably trigger the wiki IA also.

**Comment by jagtalon** [comment]
Fixed by @MrChrisW in #1472 and #1485
