### ISSUE TITLE
GitHub: Showing results when the query is just "GitHub"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1458]
A search for "GitHub" shows a list of GitHub repos. We shouldn't be popping this IA unless there's more to the query than just the trigger.

https://duckduckgo.com/?q=GitHub&ia=software

**Comment by puskin94** [comment]
Hei @moollaza , I will fix this soon ;)

**Comment by MrChrisW** [comment]
Fixed by @puskin94 in #1467
