### ISSUE TITLE
Switch to TravisYML instead of TravisCI in dist.ini

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1460]
Check out the conversation in https://github.com/duckduckgo/zeroclickinfo-spice/pull/1456#issuecomment-72117156. TravisYML might be better maintained, but we could be wrong and there could be downsides to switching.

**Comment by kentfredric** [comment]
I would personally recommend against this.

TravisYML is way more complex than you're likely to need, and I've had a bit of a hard time getting fixes shipped so far.

TravisCI however, I have no problem with, and its getting patches.

So with regards to "better maintained", one should state specific issues that you need fixing, not simply "Um, no updates this week, must be out of date"

**Comment by kentfredric** [comment]
Just to clear what is happening up: What you are currently using is this: 

https://metacpan.org/release/GETTY/Dist-Zilla-Plugin-TravisCI-0.008

Its recent releases were: 

- 0.008 - 2015-02-05 ( Today )
- 0.007 - 2015-01-01 ( 1 Month ago ) 
- 0.006 - 2015-01-01 ( Minutes earlier )
- 0.005 - 2014-11-27 ( 2 Months ago )

And this proposal is to replace it with 

- https://metacpan.org/pod/Dist::Zilla::Plugin::TravisYML

Which is shipped in

- https://metacpan.org/release/BBYRD/Dist-Zilla-TravisCI-1.12 

Important to note that this second one lacks the word "Plugin" in the release name.

Its last release was : 2014-08-02 ( 6 Months ago ).

And this proposal is thus to switch to the *lesser* maintained one which is also more complicated. 

I'm pretty sure that's not what you want.

**Comment by jagtalon** [comment]
@kentfredric alright then, thanks for the info! Appreciate it.
