### ISSUE TITLE
CodeSearch: Move to `text` template, add Header and Subheader to give more info

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1461]
https://duckduckgo.com/?q=c%2B%2B+calculator+code&ia=software

Currently the CodeSearch Spice uses the `base` template group, and dumps the code snippet result into a custom template. It doesn't provide any context though, like the name of the file or what exactly you're looking at.

It should be switched to the `text` template group, and more context should be given!

Also, because we're getting multiple results, we should probably show them in a tile view, and show the code in a detail view.

https://duck.co/ia/view/code_search

**Comment by iambibhas** [comment]
The query in given example should search code for `C++`. It's searching code for `C` instead, by adding a space after C. `lang:c ++ calculator`

**Comment by moollaza** [comment]
Ping! Anyone wanna tackle this -- this IA looks kinda broken right now :(

https://duckduckgo.com/?q=javascript+console.log+example&ia=software

**Comment by iambibhas** [comment]
I tried working on it but the CSS seemed broken. Let me give it another shot and get back.

**Comment by iambibhas** [comment]
Something like this would work? 

![](http://imgur.com/flVTmcX.png)
