### ISSUE TITLE
Transit/SEPTA: On time should be color #5B9E4D (Green)

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1462]
![screen shot 2015-01-30 at 3 17 32 pm](https://cloud.githubusercontent.com/assets/81969/5982652/3053c53a-a893-11e4-9478-94a7a71a5d2a.png)

**Comment by jagtalon** [comment]
Similar to https://duckduckgo.com/?q=next+train+from+Metropark+to+New+York+Penn&ia=njtransit

**Comment by javathunderman** [comment]
@jagtalon I'll give it my best shot.

**Comment by javathunderman** [comment]
@jagtalon Not completely sure that this is a universal fix (it seems a bit too easy to change a CSS color value and be done with it), so let me know if I missed something!

**Comment by jagtalon** [comment]
@javathunderman it looks good!

**Comment by jagtalon** [comment]
Fixed by @javathunderman in #1464
