### ISSUE TITLE
Currency: bitcoin decimal issue

### ISSUE THREAD

**Issue by javathunderman** [duckduckgo/zeroclickinfo-spice#1465]
According to https://duck.co/forum/thread/12013/btc-conversion-bug

I haven't tested it myself, but I wanted to call attention to this. 

------ 

IA Page: https://duck.co/ia/view/currency

**Comment by MrChrisW** [comment]
@javathunderman Confirmed! Thanks for reporting.

![selection_139](https://cloud.githubusercontent.com/assets/5282264/5987884/7e16712c-a97f-11e4-8593-f8f430b2e164.png)

Looks like this [function](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/currency/currency.js#L98-L106) is the cause. We may need to add an exception for BTC to allow more decimal places, however that could cause UI issues. 

//CC @jagtalon

**Comment by jagtalon** [comment]
@MrChrisW yeah it was because of UI issues because it might break. Maybe we can have scientific notation but we have to talk about it first

**Comment by MrChrisW** [comment]
@jagtalon Sure let's talk about it! :wink: Currently it looks like it switches to sientific notation with decimal places 7> this needs fixing.

![selection_159](https://cloud.githubusercontent.com/assets/5282264/6053964/c416d752-ad21-11e4-8ab2-eef7d51266b6.png)


bitcoin as a currency is usually represented with at least 8 decimal places, we can work on rounding this up depending on the input. 
![selection_161](https://cloud.githubusercontent.com/assets/5282264/6053965/c41a0bc0-ad21-11e4-918e-838a4913613f.png)
![selection_160](https://cloud.githubusercontent.com/assets/5282264/6053963/c41259fc-ad21-11e4-9960-076ecd0cfcc3.png)

**Comment by jagtalon** [comment]
Ah, yeah if it doesn't break with 8 decimal places, then I think we should go with that. @chrismorast do you agree?
