### ISSUE TITLE
Timer: Improve triggers

### ISSUE THREAD

**Issue by BigxMac** [duckduckgo/zeroclickinfo-spice#1466]
The countdown instant answer should not trigger if whats typed before it doesn't pertain to a time to countdown. 

![img_0667](https://cloud.githubusercontent.com/assets/7342882/5986423/e63cf2d2-a8c4-11e4-98e2-ee302fc76d1e.PNG)

**Comment by NeoSilky** [comment]
The triggers for this IA currently stand at `triggers startend => ['timer', 'countdown'];` . 

What would be a good change? Maybe change it to `end`?

**Comment by MrChrisW** [comment]
@NeoSilky No need to modify the triggers. We need to modify the regexp guard inside the handle function, the expression is matching this query because 2015 could be a minute or hour. {\d}

**Comment by jagtalon** [comment]
Fixed by @mattr555 in #1482
