### ISSUE TITLE
Guidebox paid content message

### ISSUE THREAD

**Issue by yegg** [duckduckgo/zeroclickinfo-spice#1476]
It's a little weird to say 'paid content' next to everything here. It implies like the instant answer was a sponsored placement, which it is of course not.

![guidebox null](https://cloud.githubusercontent.com/assets/127263/6006088/ba521c22-aadd-11e4-88fc-3e035a9ab23d.png)

**Comment by moollaza** [comment]
@yegg perhaps the wording needs to be adjusted? It's meant to indicate that you're going to hit a paywall, e.g. if the episode is avail on Hulu/HBO and requires a subscription to view the episode

**Comment by yegg** [comment]
Yes, I'd maybe put it in the button: Watch Now (Paid)

**Comment by jagtalon** [comment]
Fixed by @MrChrisW in #1479
