### ISSUE TITLE
Books: Cloud icon not aligning with percentage

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1486]
![screen shot 2015-02-06 at 3 21 23 am](https://cloud.githubusercontent.com/assets/81969/6076278/56c2d4d8-adaf-11e4-931d-ffd6e0640fb3.png)

Using Chrome on a Mac

**Comment by samph** [comment]
Before:

![screen shot 2015-02-07 at 10 56 16](https://cloud.githubusercontent.com/assets/468118/6091862/12d7ebdc-aeb8-11e4-8038-febb72ff1230.png)

After:
![screen shot 2015-02-07 at 10 56 06](https://cloud.githubusercontent.com/assets/468118/6091861/08f621f6-aeb8-11e4-87dc-b38a27e8575b.png)

**Comment by jagtalon** [comment]
Fixed by @samph in #1494
