### ISSUE TITLE
Remove BitcoinBalance IA

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1487]
Since BitcoinBalance has been replaced by BitcoinBlock, should it be removed? CC @moollaza

**Comment by MrChrisW** [comment]
@jagtalon BitcoinBlock shows information about recent or previous blocks on the blockchain. 

I don't believe it shows information about a bitcoin address.

**Comment by jagtalon** [comment]
I got confused--thanks @MrChrisW
