### ISSUE TITLE
Remove IE 7 in the PR template?

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1488]
Running DuckPAN server and viewing it on IE 8 doesn't even work because we have console.log in there. Should we even list it? 

I don't think we should because people won't be able to test it on IE 8 and below at all. What do you think, @moollaza?

**Comment by MrChrisW** [comment]
@jagtalon It does work, it just looks bad ____
![selection_173](https://cloud.githubusercontent.com/assets/5282264/6081525/20461b94-ae55-11e4-88ee-76844a05e8d3.png)

**Comment by jagtalon** [comment]
@MrChrisW oh it does! Well, I guess just IE 7 then since we don't even support it in production (well, we do, but it goes to the lite site):

![screen shot 2015-02-06 at 10 16 34 am](https://cloud.githubusercontent.com/assets/81969/6081648/4a988e48-ade9-11e4-907a-c14f0b4d02d8.png)

**Comment by MrChrisW** [comment]
@jagtalon :+1: down with IE 7!

**Comment by moollaza** [comment]
Makes sense to me!

**Comment by javathunderman** [comment]
Made a PR. Feel free to take a look.

**Comment by jagtalon** [comment]
Fixed by @javathunderman in #1526

**Comment by javathunderman** [comment]
@jagtalon :+1:

**Comment by javathunderman** [comment]
@jagtalon Should we remove the test requirement in the pull request template for the other repositories (goodies, fathead, etc.)?
