### ISSUE TITLE
Calculator: Exponents getting cut off

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1492]
Half of the exponent is hidden

![screen shot 2015-02-06 at 1 45 52 pm](https://cloud.githubusercontent.com/assets/81969/6085319/afd40180-ae06-11e4-8b89-b8cd0670e4fd.png)

**Comment by jagtalon** [comment]
Fixed internally by @sdougbrown

**Comment by jagtalon** [comment]
He decreased the size of the text in the `<sup>` tags

**Comment by sdougbrown** [comment]
:dart:
