### ISSUE TITLE
Drinks IA vs Recipes IA

### ISSUE THREAD

**Issue by MrChrisW** [duckduckgo/zeroclickinfo-spice#1493]
**Reproduce Issue:** 
Example: https://duckduckgo.com/?q=how+to+mix+a+tom+collins&ia=recipes

Using the primary query "[how to mix a tom collins](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Drinks.pm#L5)" for the [Drinks IA](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Drinks.pm) results in the [Recipe IA](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Recipes.pm) triggering.

Demo:
![out](https://cloud.githubusercontent.com/assets/5282264/6090929/d14d45a4-aecb-11e4-968c-b4da3bb0ee3a.gif)

**Expected result:** 
Drinks IA is triggered and shown.

**Actual result**
Recipe IA overtakes Drink IA and is shown, displaying two "Recipes" in the answer bar.
![selection_178](https://cloud.githubusercontent.com/assets/5282264/6090936/4efba9aa-aecc-11e4-9373-f5888d321f79.png)

**Comment by moollaza** [comment]
Thanks for reporting this @MrChrisW !

@russellholt I'm not sure how you'd like to resolve issues like this?

**Comment by jagtalon** [comment]
A change from "Recipes" to "Drinks" in the Drinks IA should be ideal. We can't change recipes because we:

1. Have screenshots of it in places like http://duckduckhack.com
2. I think the recipes IA "deserves" the recipes tab more than the Drinks IA, but that's just me :)
