### ISSUE TITLE
Finish Up the Colour Picker IA

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1495]
The PR has been abandoned by the original contributor, but our design team has posted an amazing mockup of how it should look.

https://github.com/duckduckgo/zeroclickinfo-spice/pull/1351

Any takers?

/cc @mattr555 -- I thought you might be interested

**Comment by mattr555** [comment]
Hi @moollaza, I pulled the code to take a look and the image assets didn't load on duckpan. Instead I got a 500: http://sprunge.us/fFVB

Known bug?

**Comment by MrChrisW** [comment]
@mattr555 Just as a reference there's an issue lodged on p5-app-duckpan
 [#136](https://github.com/duckduckgo/p5-app-duckpan/issues/136).

**Comment by moollaza** [comment]
> Edit: I fixed this by moving the image files out of assets/, I guess DuckPAN can't handle subdirectories?

Glad you were able to find a workaround! Yes it's a known bug as of a couple weeks ago. When I get a chance I'll take a look but for now I guess we should just avoid using sub-directories.

**Comment by moollaza** [comment]
@mattr555 fixed this in a duckpan PR, feel free to test out the updated duckpan code :)
