### ISSUE TITLE
Update Design for IA's that return facts

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1496]
In an effort to further standardize our IA displays, we'd like to update IA's that return factual data like numbers, to display the number prominently at the top, with a short subtitle to provide context.

For example the Sales Tax IA should show:

------
**6%**

Pennsylvania - State Tax

------

### The following IA's should be updated:

- [x] Sales Tax (@MrChrisW, @javathunderman would you be interested in tackling this one?) - #1497
- [x] Expatisan - #1501 
- [x] Annual Rainfall - #1501 
- [x] URL Shorten - #1501 
- Any others?

------

/cc @abeyang @jagtalon

**Comment by javathunderman** [comment]
I’ll see what I can do…

**Comment by MrChrisW** [comment]
Seems reasonable. Can you approve the suggestion text below for the rainfall IA.
__________
**Title: 534mm**
Subtitle: Australia - Average annual rainfall in millimeters

**Comment by MrChrisW** [comment]
Expatisan suggestion

________
Current
**Title: Sydney cost of living index = 222**
Subtitle: in Expatistan's scale (100 = Prague, Czech Republic)

________
Suggestion
**Title: 222**
Subtitle: Cost of living index - Expatistan's scale (100 = Prague, Czech Republic

**Comment by MrChrisW** [comment]
The URL shorten IA uses a custom template currently to display the editable input box. Guessing you'd just like the "Shortened URL" appended below the input box? Please clarify.

**Comment by moollaza** [comment]
@MrChrisW these look pretty good to me, I see you made a PR so I'll comment over there. Thanks!

**Comment by javathunderman** [comment]
@moollaza @MrChrisW Anything else to do here?

**Comment by moollaza** [comment]
@javathunderman I don't think so, it looks like @MrChrisW managed to get to everything already!

**Comment by moollaza** [comment]
@javathunderman hehe if you're looking for work I made a few new issues today about reviving some old Spice IAs. I'd love to see Forvo up and running again.

**Comment by javathunderman** [comment]
Right, looking into that!

**Comment by moollaza** [comment]
>The URL shorten IA uses a custom template currently to display the editable input box. Guessing you'd just like the "Shortened URL" appended below the input box? Please clarify.

@MrChrisW yup that sounds perfect!

**Comment by MrChrisW** [comment]
@moollaza Ok, I've had a play around with the shorten link design. I don't think we really need to display "Shortened URL" under the link as it's on the answer bar, it feels repetitive. Maybe if the answer bar, was just "Answer" then we could provide a subtitle. Anyway see some examples below.

**Current**
![selection_201](https://cloud.githubusercontent.com/assets/5282264/6143889/182945e4-b20b-11e4-93de-417b5a842d33.png)
_____________________
**Suggested**
![selection_202](https://cloud.githubusercontent.com/assets/5282264/6143890/1829d86a-b20b-11e4-85b9-5fc99250e6f5.png)
_____________________
**Improved**
![selection_200](https://cloud.githubusercontent.com/assets/5282264/6143888/18282a7e-b20b-11e4-9a4b-510ee1394c45.png)
**Improved + Suggested**
![selection_199](https://cloud.githubusercontent.com/assets/5282264/6143891/182a14b0-b20b-11e4-9b16-9c08f568a57e.png)

**Comment by moollaza** [comment]
@MrChrisW looking good! Maybe we should switch URL with the actual URL that we shortened? Then it's less redundant.

@abeyang any thoughts on how the "URL Shorten" IA should look?

**Comment by abeyang** [comment]
@MrChrisW let's go with the standard title / subtitle, but with the input field included:

![shortened-link-v1 1](https://cloud.githubusercontent.com/assets/794084/6157493/a84dc894-b1f6-11e4-9470-88a49d07fbb1.jpg)

Couple of things to note:
- input field is sticking out to the left, so that the text inside is lined up with everything else
- I kept the "shortened link" in the subtitle. A bit redundant, I know, but I think it's ok b/c the url itself is first.

LMK if you have any thoughts / questions!

**Comment by MrChrisW** [comment]
@abeyang Updated as per your recommendations :+1: - [View online](http://duckpan.mrchris.me/?q=shorten+google.com&ia=shortenedlink)
![selection_206](https://cloud.githubusercontent.com/assets/5282264/6167278/90e005f6-b2f4-11e4-8ad1-ed3ac96cf3ef.png)

**Comment by abeyang** [comment]
Sweet @MrChrisW -- almost there! Just need a few more css tweaks:

``` css
.zci--shorten input.tag {
  font-size: 1.2em;
}

.zci__subheader, .zci__header__sub {
  margin-top: 2px;
  color: #999;
}
```

**Comment by MrChrisW** [comment]
@abeyang Updated as per your request.
+ [View CSS](https://github.com/MrChrisW/zeroclickinfo-spice/blob/standardise-fact-spices/share/spice/shorten/shorten.css)
+ [View online](http://duckpan.mrchris.me/?q=shorten+google.com&ia=shortenedlink)

![selection_208](https://cloud.githubusercontent.com/assets/5282264/6180421/8b6649c6-b35f-11e4-870f-3579d32099a1.png)

One question, why are we changing these default values? You can just say "for design purposes" and I'll shut up :laughing: 
````css
.zci__header {
    font-size: 1.38em
}
.zci__subheader, .zci__header__sub {
    color: #888;
}
````

**Comment by abeyang** [comment]
Looks good! :+1: 

That's a good question. We're still in the process of standardizing things, including going back and revisiting existing templates. Until we actually make those changes in the templates, it's going to require some hand-tweaking here and there...

But with that said, for the subheader, I think #888 would've been okay -- but yeah, looks good!

**Comment by MrChrisW** [comment]
Thanks for the explanation @abeyang  Looking forward to seeing styles standardised :smiley: 

@moollaza This should be good to close, provide there are no other fact IA's? Will have to remember if any new fact Spices appear to stick to these guidelines! Thanks

**Comment by moollaza** [comment]
@MrChrisW apologies for the delay, will tackle this ASAP.

**Comment by moollaza** [comment]
Haha whoops, thought this was a PR last night. We can close, the IA's have all been updated :+1:

**Comment by moollaza** [comment]
>Will have to remember if any new fact Spices appear to stick to these guidelines! Thanks
@MrChrisW we're also updating our templates and adding some new ones. I expect these kinds of IA's will be covered under a new template :)
