### ISSUE TITLE
Betterific IA - Disabled

### ISSUE THREAD

**Issue by MrChrisW** [duckduckgo/zeroclickinfo-spice#1499]
Looks like the [Betterific IA](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Betterific.pm) https://duckduckgo.com/?q=betterific+duck has been disabled internally, guessing due to design issues.

**Options**
+ Remove Betterific from repository 
+ Update design and re-enable

**Running on DuckPAN**
![selection_185](https://cloud.githubusercontent.com/assets/5282264/6094819/78eb9850-af77-11e4-9286-24c128d3b3f6.png)

**Comment by moollaza** [comment]
@MrChrisW whoops I didn't see this issue! I just made a new task to revive Betterific today: #1507 

Will close this one.

**Comment by MrChrisW** [comment]
@moollaza No problem :+1:
