### ISSUE TITLE
URL Shorten IA: API Down

### ISSUE THREAD

**Issue by MrChrisW** [duckduckgo/zeroclickinfo-spice#1502]
May be a temporary issue, the is.gd site seems unavailable at this time. This effects the Shorten IA.

http://tools.pingdom.com/fpt/#!/euPJhT/is.gd

![selection_189](https://cloud.githubusercontent.com/assets/5282264/6095000/05472c66-af81-11e4-9486-8949a5b898e2.png)

**Comment by mintsoft** [comment]
@MrChrisW This is fixed now; did you notice it because an error appeared on the main site or because the IA didn't work?

**Comment by MrChrisW** [comment]
@mintsoft The site is still down for me, returning 502. Maybe you're seeing the cloudflare page? 

Both, testing the IA in duckPAN didn't work, so I checked out the main site.

**Comment by mintsoft** [comment]
@MrChrisW Interesting, it's broken for me now but was definitely working earlier (both site and IA)!

**Comment by moollaza** [comment]
Interesting, it's working for me now and was previously, I haven't experienced the downtime yet

**Comment by javathunderman** [comment]
Site seems to work for me..

**Comment by MrChrisW** [comment]
@moollaza @javathunderman Looks like you missed the fun then :laughing: Only went down for one day :+1: Closing.


![isgd](https://cloud.githubusercontent.com/assets/5282264/6123134/53c99b26-b139-11e4-9723-39c0310974fb.png)
