### ISSUE TITLE
Betterific: Convert to Tile view

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1507]
I just realized this one hasn't been live for some time!

It needs to be updated to use a Tile view. I think the Reddit/HackerNews style approach would work. We can ditch the Users and Tags results, or only perform them when a keyword is present.

/cc @bradcater not sure if you're interested in updating this?

**Comment by altern8tif** [comment]
Time to close this as well?  Since the IA has been removed.
