### ISSUE TITLE
GoWatchIt: Netflix should say "Available for Streaming"

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1514]
This piece of code should do it, but it doesn't seem to be working: https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/go_watch_it/go_watch_it.js#L36

![screen shot 2015-02-10 at 11 24 05 am](https://cloud.githubusercontent.com/assets/81969/6131278/bef0e98e-b118-11e4-82cc-584f659da296.png)

**Update:**
It looks like it's netflix that's broken now: https://github.com/duckduckgo/zeroclickinfo-spice/issues/1514#issuecomment-74338822

https://duck.co/ia/view/go_watch_it

**Comment by samph** [comment]
My instinct is that there is some weirdness around what gets returned by the API for the item.buy_line and item.rent_line values for some YouTube videos. Unfortunately I don't have an API key for GoWatchIt to experiment more - I've requested one but I don't know whether they will provide me with one and in what timescale.

Interestingly it does work as expected for some requests.

![screen shot 2015-02-10 at 19 27 41](https://cloud.githubusercontent.com/assets/468118/6134691/01805acc-b15b-11e4-9b23-fab5428a5030.png)

**Comment by samph** [comment]
Specifically I think this issue occurs for media which GoWatchIt lists a rental price on YouTube.

Media which GWI lists no rental or purchase price display "Available for Streaming" correctly, those with a purchase price display the purchase price correctly. 

![screen shot 2015-02-10 at 21 15 17](https://cloud.githubusercontent.com/assets/468118/6136616/11418c9c-b16a-11e4-8830-b3ec3bd038c9.png)

At a glance I've been unable to find any media on GWI which lists both a rental and purchase price on YouTube to test the IA with.

**Comment by jagtalon** [comment]
Hmm looks like it's fixed now but Netflix is the one that's broken this time:

![screen shot 2015-02-13 at 5 30 44 pm](https://cloud.githubusercontent.com/assets/81969/6196439/1b671640-b3a6-11e4-980d-ba2c1abeb644.png)
