### ISSUE TITLE
Regex guard and prepositions between "time" and [location]

### ISSUE THREAD

**Issue by tommytommytommy** [duckduckgo/zeroclickinfo-spice#1522]
Would it be possible to remove the preposition check in the regex guard for this IA, so that queries such as "time new york" and "time in new york" both trigger the IA? I know that there are concerns about queries that contain "time" but do not end in a location, but are we able to rely on the upstream provider to return nothing and use Spice.failed() to quit those queries? If this is possible, it would help us more consistently show the time IA when there are competing answers from other IAs (e.g., news and lyrics in the case of "time new york").

Thanks!

-- http://duck.co/ia/view/time

**Comment by killerfish** [comment]
It already does that, try [this] (https://duckduckgo.com/?q=time+newyork), it should however work even with 'time new york', so thats an issue.

**Comment by tommytommytommy** [comment]
Hi @killerfish,

"Time new york" brings up the IA because the first link is to timeanddate.com, and DuckDuckGo is issuing an internal trigger. But, if you try <code>duckpan query Time</code> inside the spice repository, and then query for <code>time newyork</code>, you'll see that the Spice does not trigger. Maybe the regexp has a bug?

Thanks for looking into this!

**Comment by killerfish** [comment]
Oh i thought that it was triggering, anyhow, yes i believe the regex should handle it this case.
//cc @MrChrisW

**Comment by MrChrisW** [comment]
@killerfish @tommytommytommy Checking [Time.pm](https://github.com/duckduckgo/zeroclickinfo-spice/commit/d7924795914f2224d98454372cc7480bcf5128f3) commits, you can see that the anchor words `(in of for at)` are added to avoid over triggering. This behaviour was added by @moollaza in #1253 

So a query `time in new york` will trigger just not `time new york` 

It's possible to just call `Spice.failed()` as the API will return [no matches](https://ddh1.duckduckgo.com/js/spice/time/titantic) for an incorrect search (I'm sure there's edge cases) Although I think there was a reason behind limiting triggering... :grimacing:

**Comment by tommytommytommy** [comment]
@mrchrisw This makes sense to me now. Thanks for the information!

**Comment by MrChrisW** [comment]
@tommytommytommy No problem, I still think there may be a relevance/triggering issue with the query.

https://duckduckgo.com/?q=time+new+york

What IA triggers by default for you? I'm seeing the Lyrics IA...

**Comment by tommytommytommy** [comment]
@MrChrisW I sometimes get news, sometimes lyrics. What's happening is that we're getting results for those IAs first before the internally triggered time IA, and those other IA results look like a good match to the query because of the number of shared words. Consequently, we auto-open those tabs instead of waiting for Time. This may be a larger issue for us to internally address with respect to prioritizing IAs if their names show up in the query. I must admit that I know very little about this part of the code, so I need to do some more exploration before I am able to say something meaningful :)

Just as some background, in case "internally triggered" is a new idea for you, what we're doing is we're looking at the search results and then making our own (independent) upstream request with Time's Javascript callback function. If the upstream request succeeds, then we're able to use your great work on the front end to display the results, even if the user didn't directly trigger Time. But, the timing is a little different for these internally triggered IAs, and the priority of what shows can also be different, so that's why we're running into relevancy problems for this specific query.

**Comment by MrChrisW** [comment]
@tommytommytommy Sounds like a race condition! I'd be very interested see prioritisation improved and learn a little more about how it is currently handled in the backend :wink: 

I'm partially aware of how "internal triggers" work from some discussions here, however wasn't aware these may have different priorities/timing to standard triggers.

Thanks for taking the time to explain! :+1:

**Comment by tommytommytommy** [comment]
@MrChrisW Will keep you in the loop as I learn more! Thanks for your time and effort!
