### ISSUE TITLE
Stocks: Set low signal for dictionary word tickers

### ISSUE THREAD

**Issue by masochist** [duckduckgo/zeroclickinfo-spice#1529]
For example, if you search for `guid` or `IRC`, you'll get stock quotes--not the obvious things that you would expect that come from other IAs. This is because the Stocks spice triggers if the query is a stock symbol, regardless of whether it's actually a trigger keyword for another spice or other kind of IA.

One way to possibly address this is to consider the list of IA triggers and, if one of them matches, prioritize that IA above the Stocks IA.

------ 

IA Page: https://duck.co/ia/view/stocks

**Comment by killerfish** [comment]
@bsstoner should we set a signal for this or would you prefer to tweak this internally?

**Comment by gvanwaelvelde** [comment]
I've submitted a fix.
https://github.com/duckduckgo/zeroclickinfo-spice/pull/2561

**Comment by bsstoner** [comment]
Sorry, my fault for missing this comment thread initially. We're going to fix the triggering issues here internally. Thanks everyone for raising the issue and pushing the discussion forward.
