### ISSUE TITLE
NPM: Show more important information about the package!

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1530]
When I search something like `npm phantomjs` I get this

![screen shot 2015-02-13 at 4 50 00 pm](https://cloud.githubusercontent.com/assets/81969/6195865/684fe780-b3a0-11e4-9a4b-d8462cd0baa5.png)

But I'm not sure if that's the best one partly because I can't see how popular it is. So I end up clicking on the link anyway.

**Comment by moollaza** [comment]
Looks like there's tons of data from the API that we're not using: http://registry.npmjs.org/phantomjs/latest

I think that for package search Spice's we should probably aim for a tile view that shows multiple results when possible. I'm not sure if there's a proper search endpoint for NPM, but would probably be an improvement. We can always boost an exact matching result to the top of the list.

**Comment by puskin94** [comment]
I think that an Infobox can be very useful!
