### ISSUE TITLE
Currency: Doesn't trigger when "$" in query?

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1532]
https://duckduckgo.com/?q=%24118+USD+to+CAD

This should definitely be triggering the Currency Spice and showing a result

**Comment by MrChrisW** [comment]
@moollaza This is a duplicate of #1175 I'll happly take this one on!

**Comment by moollaza** [comment]
@MrChrisW thanks for pointing that out!
