### ISSUE TITLE
Revive Old IA Branches

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1535]
https://github.com/duckduckgo/zeroclickinfo-spice/branches/stale

Previously we have pushed the "abandoned" PRs to a branch for others to work off of and they've been sitting there for a while now untouched.

Most of the branchs [here](https://github.com/duckduckgo/zeroclickinfo-spice/branches/stale) have Spice IAs that are nearly complete, but in many cases need to be updated to meet the current Spcie practices (using built-in Templates and the new Spice API)

If you're interested in picking up some of these IA's feel free to let us know and submit a PR :smile:

**Comment by tagawa** [comment]
Re. the exoplanets IA, the original API (exoapi.com) seems dead but NASA have a public API that could probably be used: http://exoplanetarchive.ipac.caltech.edu/docs/program_interfaces.html

**Comment by iambibhas** [comment]
I looked at the [ideas/firefox-plugins](https://github.com/duckduckgo/zeroclickinfo-spice/tree/ideas/firefox-plugins) branch. addons.mozilla.org API now returns XML as mentioned [here](https://developer.mozilla.org/en-US/docs/addons.mozilla.org_%28AMO%29_API_Developers%27_Guide). They probably changed it since the last time that branch was used.

**Comment by moollaza** [comment]
@iambibhas it looks like that branch was going to use XML (which isn't allowed), but I just tried adding `?format=json` to an example URL in their docs and it worked! :smiley: 

https://services.addons.mozilla.org/en-US/firefox/api/1.5/addon/1865?format=json

**Comment by iambibhas** [comment]
Cool! Not sure why it isn't documented. So I Can work on it. Lemme give it a try.

**Comment by iambibhas** [comment]
Looks like JSON response isn't available for the search endpoint.
```
{
    "msg": "Not implemented yet."
}
```

https://services.addons.mozilla.org/en-US/firefox/api/1.5/search/memory/all/1?format=json

**Comment by iambibhas** [comment]
This old IA(stale branch `upc`) specifies the API Key in plain text. That should be removed, right? https://github.com/duckduckgo/zeroclickinfo-spice/blob/upc/lib/DDG/Spice/Upc.pm#L10

**Comment by moollaza** [comment]
@iambibhas that's not one of DDG's keys, it's the contributor's, but yes if you plan to bring back that IA, you should get a new key. 

The contributor isn't using that key though for anything else. He was a DDG intern :)

**Comment by iambibhas** [comment]
Just maintaining a checklist - 

* [ ] [campaign-finance](https://github.com/duckduckgo/zeroclickinfo-spice/tree/campaign-finance)
* [ ] [upc](https://github.com/duckduckgo/zeroclickinfo-spice/tree/upc)
* [ ] [exoplanets](https://github.com/duckduckgo/zeroclickinfo-spice/tree/exoplanets)
* [ ] [4chan](https://github.com/duckduckgo/zeroclickinfo-spice/tree/4chan)
* [ ] [mta](https://github.com/duckduckgo/zeroclickinfo-spice/tree/mta)
* [ ] [ideas/doi](https://github.com/duckduckgo/zeroclickinfo-spice/tree/ideas/doi)
* [x] [ideas/deb](https://github.com/duckduckgo/zeroclickinfo-spice/tree/ideas/deb) - #1697 
* [ ] [ideas/wikinews](https://github.com/duckduckgo/zeroclickinfo-spice/tree/ideas/wikinews)
* [ ] [jd/lobbying](https://github.com/duckduckgo/zeroclickinfo-spice/tree/jd/lobbying)
* [ ] [zaahir/example-ia-comments](https://github.com/duckduckgo/zeroclickinfo-spice/tree/zaahir/example-ia-comments)
* [ ] [kngine](https://github.com/duckduckgo/zeroclickinfo-spice/tree/kngine)

**Comment by javathunderman** [comment]
@moollaza I'll make a PR for lobbying (with unchanged code) and I think we can go from there.

**Comment by mariano-simone-zocdoc** [comment]
@moollaza @iambibhas the [UPC](https://github.com/duckduckgo/zeroclickinfo-spice/tree/upc) branch seems pretty poor to me. The upcdatabase.org API doesn't return images, does not have price info for most products.

I like the idea of a UPC IA, but it might be better to ditch that implementation and find a better API altogether

**Comment by iambibhas** [comment]
@mariano-simone-zocdoc I agree that it's really poor. I tried finding a better source, but couldn't find anything. Might need a vote to decide what to do with it.

**Comment by altern8tif** [comment]
@mariano-simone-zocdoc @iambibhas Found [this](https://www.digit-eyes.com/cgi-bin/digiteyes/apiDemo.cgi) from Digit-Eyes.  It has thumbnails and a link to the product page.  Unfortunately it's not free.

Not sure what DDG's policy on APIs which require paid access though.  Couldn't find it in the documentation.
