### ISSUE TITLE
If Search is too long, Webpage Reverts to old styling it appears.

### ISSUE THREAD

**Issue by redwavestudios** [duckduckgo/zeroclickinfo-spice#1539]
Search at length and this will appear (mac OS X yosemite)

**Comment by redwavestudios** [comment]
![screenshot 2015-02-16 17 07 20](https://cloud.githubusercontent.com/assets/10037293/6219974/6a9725ca-b5fe-11e4-860e-b91ff2f272e7.png)

**Comment by MrChrisW** [comment]
This page (https://duckduckgo.com/50x.html?e=3) is displayed in response to error [414 Request-URI Too Long](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.15)

It may be kept simple on purpose to avoid loading anything that could be causing the error, however I'm just guessing.

**Comment by MrChrisW** [comment]
@redwavestudios You can report this issue here https://duck.co/feedback/bug/-

As this issue is unrelated to zeroclickinfo-spice, closing.

**Comment by moollaza** [comment]
@redwavestudios thanks for reporting this!

It's a known issue and we're working on updating the error pages right now. Should have them out soon!
