### ISSUE TITLE
RXInfo: Relevancy

### ISSUE THREAD

**Issue by yegg** [duckduckgo/zeroclickinfo-spice#1542]
Bad relevancy here -- is this going through the is_relevant function?

https://duckduckgo.com/?q=tablet+of+ahkmenrah&t=iphone&iax=1&ia=rxinfo

https://duck.co/ia/view/rx_info

**Comment by MrChrisW** [comment]
@yegg [rx_info.js] (https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/rx_info/rx_info.js) isn't using `DDG.isRelevant` I'll see if it can be improved.

**Comment by moollaza** [comment]
Fixed in #1550
