### ISSUE TITLE
GoWatchIt: Tile doesn't look right

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1544]
Investigate why this is happening:
![screen shot 2015-02-17 at 1 38 39 pm](https://cloud.githubusercontent.com/assets/81969/6234634/62c39f66-b6aa-11e4-82eb-745485e168d0.png)

It should be consistent with this look:
![screen shot 2015-02-17 at 1 39 49 pm](https://cloud.githubusercontent.com/assets/81969/6234640/7c1e00e6-b6aa-11e4-89a9-713bb7039bdb.png)

https://duck.co/ia/view/go_watch_it

**Comment by moollaza** [comment]
@jagtalon was this fixed in your recent GWI PR? (the CSS fix)

**Comment by jagtalon** [comment]
@moollaza no it wasn't
