### ISSUE TITLE
Forecast: Can mistake the sunrays as the negative sign

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1546]
![screen shot 2015-02-17 at 1 07 06 pm](https://cloud.githubusercontent.com/assets/81969/6236885/4b5ec5c8-b6bc-11e4-910c-bc77490c9999.png)

I sometimes read the above as "-16". Switching the temperature and the icon should fix the issue as recommended by @sdougbrown and @thm 

![fix](https://cloud.githubusercontent.com/assets/81969/6236909/75620a6a-b6bc-11e4-9d4d-542196e2e847.png)

**Comment by NeoSilky** [comment]
Fixing :)

**Comment by jagtalon** [comment]
Fixed by @NeoSilky in #1547
