### ISSUE TITLE
Replacing https to http should just use DDG.toHTTP

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1552]
Lines such as https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/sound_cloud/sound_cloud.js#L55 should be replaced with `DDG.toHTTP`. Might exist in other spices as well.

**Comment by moollaza** [comment]
Likewise, for the reverse we have `DDG.toHTTPS()`
