### ISSUE TITLE
Weather: Triggers on "uv index", gives weather for Alice Springs, NT

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1553]
https://duckduckgo.com/?q=uv+index&ia=weather

I'm OK with it triggering for this query, but it should be using the user's location. I'm seeing a forecast 
for Alice Springs, NT which is wrong.

**Comment by jagtalon** [comment]
@moollaza this looks like it's on our end:

![screen shot 2015-02-20 at 2 39 27 pm](https://cloud.githubusercontent.com/assets/81969/6307979/574914d4-b90e-11e4-848d-f8b2e67bc30e.png)

I think it's getting its info from Wunderground.

**Comment by jagtalon** [comment]
Moving to internal bug list.
