### ISSUE TITLE
Switch custom date formatting to moment.js

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1554]
We recently added support for http://momentjs.com/, and it would be cool if we move things like https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/hacker_news/hacker_news.js#L63.

![screen shot 2015-02-19 at 1 31 09 pm](https://cloud.githubusercontent.com/assets/81969/6273242/b514424c-b83b-11e4-8485-d0f4baa9c2c1.png)

If possible, of course. This might be a huge task that needs a bunch of testing so it's best to do one PR for each IA so that it's easier to review.

Usage of moment.js in DuckDuckGo is as follows:

``` javascript
DDG.require("moment.js", function() {
    console.log(moment("9/23/2015").format("dddd, MMMM Do YYYY")); // Wednesday, September 23rd 2015
});
```

**Comment by mattr555** [comment]
YES!
![gif](http://www.reactiongifs.com/wp-content/gallery/yes/dwight_yes.gif)

There are many "fuzzy date" functions in the codebase that should be replaced. Some more that I found (in no particular order):

+ [airlines](https://github.com/duckduckgo/zeroclickinfo-spice/blob/73b4091f04695ce104b94c0bfe38e0e47ee86dc9/share/spice/airlines/airlines.js#L145)
+ [flights](https://github.com/duckduckgo/zeroclickinfo-spice/blob/73b4091f04695ce104b94c0bfe38e0e47ee86dc9/share/spice/flights/route/flights_route.js#L309)
+ [tvmaze](https://github.com/duckduckgo/zeroclickinfo-spice/blob/dc7bddb4f42b0d52cafcfa6e2cb8b176decd5ad0/share/spice/tvmaze/nextepisode/tvmaze_nextepisode.js#L96)
+ [launchbug](https://github.com/duckduckgo/zeroclickinfo-spice/blob/4e83783722e32b27adeb66072c1780f59d3610ed/share/spice/launchbug/launchbug.js#L9)
+ [time](https://github.com/duckduckgo/zeroclickinfo-spice/blob/837c18804528b96784fb2d7397d781a2749ded0e/share/spice/time/time.js#L33)
+ [github_jobs](https://github.com/duckduckgo/zeroclickinfo-spice/blob/6502229e8f2126df93168104650c9cf81cc7968b/share/spice/github_jobs/github_jobs.js#L40)
+ [reddit_search](https://github.com/duckduckgo/zeroclickinfo-spice/blob/73b4091f04695ce104b94c0bfe38e0e47ee86dc9/share/spice/reddit_search/reddit_search.js#L52)
+ [game_info](https://github.com/duckduckgo/zeroclickinfo-spice/blob/ee1aa6f36f1fa26aa588a72999e01b0b7ef117b6/share/spice/game_info/game_info.js#L55)
+ [whois](https://github.com/duckduckgo/zeroclickinfo-spice/blob/48967d8d225c50457123ebfdbd08c6b150a06688/share/spice/whois/whois.js#L117)
+ [bitcoin_{transaction,block}](https://github.com/duckduckgo/zeroclickinfo-spice/blob/89fefb2c9bc92099576e95e1caa4be5282caaf45/share/spice/bitcoin_transaction/bitcoin_transaction.js#L4)
+ [guidebox](https://github.com/duckduckgo/zeroclickinfo-spice/blob/73b4091f04695ce104b94c0bfe38e0e47ee86dc9/share/spice/guidebox/getid/guidebox_getid.js#L116)
+ [newint](https://github.com/duckduckgo/zeroclickinfo-spice/blob/ee1aa6f36f1fa26aa588a72999e01b0b7ef117b6/share/spice/newint/newint.js#L25)
+ [github](https://github.com/duckduckgo/zeroclickinfo-spice/blob/73b4091f04695ce104b94c0bfe38e0e47ee86dc9/share/spice/github/github.js#L68)
+ And perhaps the transit IAs.

**Comment by MrChrisW** [comment]
OMG FINALLY! I'll help remove the existing functions!

**Comment by russellholt** [comment]
Thanks for looking into that, @mattr555

**Comment by jagtalon** [comment]
Could also help [seatgeek](https://github.com/duckduckgo/zeroclickinfo-spice/blob/b79c0b3a3eff33d2363dd4bb228d80430d47c51a/share/spice/seat_geek/events_by_artist/seat_geek_events_by_artist.js#L71)

**Comment by iambibhas** [comment]
Looks like tvmaze [has been moved](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/tvmaze/nextepisode/tvmaze_nextepisode.js#L9) to moment.js. Should probably update that checklist above.

**Comment by marianosimone** [comment]
Would be nice to have an updated list of pending IAs that need migration (or close this issue if there are no more ;))

From the current list, both `game_info` and [guidebox](https://github.com/duckduckgo/zeroclickinfo-spice/pull/2030) seem to have been deleted

**Comment by MrChrisW** [comment]
@marianosimone Updated the list.

Quick search of the repository https://github.com/duckduckgo/zeroclickinfo-spice/search?utf8=%E2%9C%93&q=getDay the following IA's probably need updating.

**Comment by moollaza** [comment]
@marianosimone thanks for pointing that out! I've removed GameInfo

@MrChrisW thanks for cleaning up as well!

**Comment by sekhavati** [comment]
I was going to take a look at the SeatGeek IAs that were highlighted in the search MrChrisW posted above but none of them seem to be working for me. Do they work for anyone else?

I've done a little debugging of the [SeatGeek Nearby Concerts](https://duck.co/ia/view/seat_geek_events_near_me) IA and it looks to me as though the triggers on the back-end are firing but the JavaScript callback isn't receiving any data.

**Comment by moollaza** [comment]
@sekhavati thanks for reporting this! It looks like they've switched their API to always redirect to HTTPS and so we need to update the Perl to reflect that, for each of the SeatGeek IAs. Would you like to do that?

**Comment by sekhavati** [comment]
@moollaza Sure, I can take a look. What's the normal protocol, would you like to file an issue first?

**Comment by moollaza** [comment]
@sekhavati I wouldn't say it's required but if you'd like to, that's perfectly fine.

**Comment by edgesince84** [comment]
@jagtalon is this issue still relevant?
