### ISSUE TITLE
Book Reviews: Broken in mobile layouts

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1556]
![screen shot 2015-02-19 at 3 59 14 pm](https://cloud.githubusercontent.com/assets/81969/6275843/75fa62f2-b850-11e4-8463-e38da3753387.png)

https://duck.co/ia/view/book

**Comment by altern8tif** [comment]
@jagtalon @moollaza This looks like it's fixed.  Time to close issue?

**Comment by moollaza** [comment]
@altern8tif LGTM :+1:
