### ISSUE TITLE
Currency: Numbers with spaces don't work

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1564]
"10 000 000 usd to php" don't work but "10,000,000 usd to php" does.

------ 

IA Page: https://duck.co/ia/view/currency

**Comment by pjhampton** [comment]
Through the passage of time, this has been fixed! 🤘 

![screen shot 2017-07-25 at 10 43 04 am](https://user-images.githubusercontent.com/8960296/28566110-19f0445e-7126-11e7-8ff8-6418abdafe04.png)
