### ISSUE TITLE
Kwixer: Should trigger on "movies"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1573]
Example:
https://duckduckgo.com/?q=adam+sandler+movies
vs
https://duckduckgo.com/?q=movies+with+adam+sandler&ia=movies

We should add "movies" to the triggers.txt file and it looks like we should probably be checking the relevancy of the query against the actor/director returned by the API.

A [relevancy block](https://duck.co/duckduckhack/spice_displaying#relevancy-blocks) would be good.

------
IA Page: https://duck.co/ia/view/kwixer

**Comment by gokul1794** [comment]
@moollaza, No one doing this?

**Comment by moollaza** [comment]
Nope!

**Comment by gokul1794** [comment]
@moollaza Should I add a relevancy block too or just add movies to the txt?

**Comment by Sayanc93** [comment]
hey i think movies trigger the InTheatres spice..adding movies to the trigger text might conflict with that spice

**Comment by moollaza** [comment]
@Sayanc93 triggers are allowed to overlap. These are two different IAs that don't provide the same kinds of answers so it should be OK.

**Comment by moollaza** [comment]
Closing. Kwixer is being shut down. If anyone knows of an alternative data source perhaps we can create a new Instant Answer for this query space.
