### ISSUE TITLE
Add "is it raining?" back!

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1577]
We used to have an answer to "is it raining?" like https://duckduckgo.com/?q=is+it+snowing, but we no longer do. It would be cool if we can have that back again. It could probably use our existing Forecast IA as the source.

**Comment by iambibhas** [comment]
I can work on it. But need the forecast api key.

**Comment by moollaza** [comment]
@iambibhas I think you can use the same API call as the current Forecast spice? If so then copying the Spice to will force a call to `ddh1.duckduckgo.com/js/spice/forecast/<location>` which should be all you need?

**Comment by iambibhas** [comment]
@moollaza already tried that. Then the response comes wrapped inside `ddg_spice_forecast()` callback. Can't override that, can I?

**Comment by moollaza** [comment]
@iambibhas ah right -- I think you'll need to signup for a key then, because we can't create create additional keys: https://developer.forecast.io/register

**Comment by iambibhas** [comment]
@moollaza I have created a key. But the regular API endpoint only takes longitude and latitude as input - https://developer.forecast.io/docs/v2 . The endpoint made for ddg takes location name as input I think.

**Comment by moollaza** [comment]
@iambibhas Right. I assume your API key doesn't work for the custom endpoint? We're gonna reach out to them for a dev key.

**Comment by iambibhas** [comment]
@moollaza no, My key doesn't work. :(

**Comment by jagtalon** [comment]
@iambibhas Hmm, well, we haven't quite figured out how to share keys with developers, but I think for the moment you can copy over whatever https://duckduckgo.com/js/spice/forecast/19104/current is returning, and you can use http://www.json-generator.com/ for now (example endpoint: http://www.json-generator.com/api/json/get/cqarcjqZbC?indent=2&callback=hello)

We'll just switch when it's ready to merge.

@moollaza what do you think?

**Comment by moollaza** [comment]
Sure that'll work for now. We're asking them for a key we can give to developers

**Comment by jagtalon** [comment]
Cool. Seems like the best approach that we have right now.

**Comment by iambibhas** [comment]
@moollaza did you get the keys?

**Comment by moollaza** [comment]
Sorry not yet, will ping you when I get it.
