### ISSUE TITLE
Snow: Hard to tell if the API is returning good results

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1578]
When we look at the endpoint of Snow in, say, https://duckduckgo.com/js/spice/snow/new%20york, we can't really tell if it's giving us the right location or not because the location is not in the API so we can't verify.

Is isitsnowingyet.org a good endpoint? Would using forecast.io (such as in the Forecast.pm IA) be better?

https://duck.co/ia/view/snow

**Comment by moollaza** [comment]
Closing. IA has been removed.
