### ISSUE TITLE
Songkick: Would it be better to revive this or to use SeatGeek instead?

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1579]
We can answer questions like https://duckduckgo.com/?q=concerts+near+me&ia=concerts, so maybe Songkick is no longer needed--unless it can answer questions that SeatGeek can't.

**Comment by moollaza** [comment]
@jagtalon I think we should reduce the trigger to just "songkick" -- it doesn't look like this IA is live though?

**Comment by moollaza** [comment]
One benefit of Songkick::Artists is that it shows similar/related artists, but I suppose this functionality will also exist in LastFM

**Comment by jagtalon** [comment]
Yeah the IA isn't live, unfortunately.
