### ISSUE TITLE
Keybase: Should provide info when no hit is found.

### ISSUE THREAD

**Issue by ScreapDK** [duckduckgo/zeroclickinfo-spice#1581]
~~The [Keybase IA](https://duck.co/ia/view/keybase) when trying to get key based on GitHub username.~~
~~E.g. a search for [keybase github:mwolny](https://duckduckgo.com/?q=keybase+github%3Amwolny&ia=keybase) doesn't trigger the Instant Answers.~~

~~At the same [keybase github:jeresig](https://duckduckgo.com/?q=keybase+github%3Ajeresig&ia=keybase).~~

~~Switching between space and colon doesn't make any difference.~~

~~Instant Answer details:~~
~~[Keybase IA](http://duck.co/ia/view/keybase)~~

...the above is what I've been write for the last 5 minutes... but, I have discovered that what I thought was a bug, is actually just an example of not giving useful feedback upon error.

The reason "keybase github:mwolny" doesn't work, while "keybase github:jeresig" does is that the GitHub user `mwolny` is not connected to any Keybase.io user. The DDG SERP just doesn't tell me.

E.g. if the search [keybase github:ScreapDK](https://duckduckgo.com/?q=keybase+github%3AScreapDK&ia=keybase) doesn't work because GitHub user ScreapDK is not on Keybase, then the Instant Answer should report something like:
"Sorry, @ScreapDK on **GitHub** does not appear to be on Keybase."

**Comment by MrChrisW** [comment]
@ScreapDK Usually if the answer doesn't return a result the default is to not display the IA.

Although this is a great case to update the [example queries](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Keybase.pm#L19-L20), we shouldn't include queries in `
secondary_example_queries` that don't trigger. 

I'd also like to update the `primary_example_queries` to include a better result for the first query, as currently the primary query doesn't really show off the IA as it excludes the *description, location and a nice profile image*! I think a better query would make this look nicer https://duck.co/ia/view/keybase

**Comment by moollaza** [comment]
@ScreapDK as @MrChrisW said, generally if we don't have something good to show, we don't show anything at all. It's arguable that given how specific the query and triggers are for this IA that we could, but then you get into difficult territory when people search things that aren't meant to be a keybase user search. E.g. "keybase website", "keybase faq", "keybase financial"

**Comment by ScreapDK** [comment]
Sorry for this late reply! 

@MrChrisW Looking forward to seeing the full potential of this IA with some new queries! :)
@moollaza I see what you mean! We shouldn't annoy people with unnecessary error-messages!

**Comment by MrChrisW** [comment]
@ScreapDK The queries have been updated in #1597 :smile: Thanks for lodging an issue. Closing as fixed.

**Comment by jagtalon** [comment]
:heart:

**Comment by ScreapDK** [comment]
@MrChrisW Great! Looking forward to see the IA-page being updated. BTW, how often is it being updated?

**Comment by MrChrisW** [comment]
@ScreapDK I have no idea! I think @jdorweiler or @MariagraziaAlastra may know.

**Comment by jdorweiler** [comment]
Just updated it :smile:

**Comment by MrChrisW** [comment]
@jdorweiler :smile: can you also reprocess the screenshot? or maybe I have to wait for the server side cache to clear :+1:

**Comment by jdorweiler** [comment]
@MrChrisW I think it's automated now otherwise @jagtalon will have to update it.

**Comment by MrChrisW** [comment]
@jdorweiler Yup I believe you're using PhantomJS in the backend to capture the screenshots.
