### ISSUE TITLE
TVMaze: Conversion of Airdate to local date incorrect

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1583]
The airdate of tonight's (March 1st) episode of "Madame Secretary" shows it aired on "February 28" in the info box. But the API returned `2015-03-01` which is correct.

![2015-03-01_21h11_00](https://cloud.githubusercontent.com/assets/873785/6434489/30fa34e2-c058-11e4-82ed-07729d7dd907.png)

It seems like the simplest solution is to switch this Spice to use the recently added Moment.js. The `Spice.add()` will need to me wrapped in a `DDG.require('moment.js', function() { ... });`

Example: https://github.com/duckduckgo/zeroclickinfo-spice/pull/1335/files#diff-af2edb09dbcc64af8c4652306ff86876R33

/cc @tvdavid -- feel free to fix this if you'd like, otherwise I'm sure someone from the community will :)

------

Also, I think the phrase "most recent episode" and "recent episode" should be added as triggers for the TVMaze Previous Episode IA

https://duck.co/ia/view/tvmaze_nextepisode

**Comment by moollaza** [comment]
After a quick inspection, we should either be using the `airstamp` property to get the airdate as it specifies the timezone offset, unlike the `airdate` property.

**Comment by tvdavid** [comment]
Ah, having moment.js available is great! I rewrote all three IA's to make use of it, making the code a lot cleaner.

I also added the "recent episode" trigger, this makes sense indeed.

**Comment by moollaza** [comment]
Fixed in #1646
