### ISSUE TITLE
SeatGeek: Maybe "amanda palmer tickets" should be the same as "amanda palmer concerts"

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1585]
Not sure how hard this is to do especially since "tickets" could either mean concerts or sports or actually any event.

https://duck.co/ia/view/seat_geek_events_by_artist

**Comment by marianosimone** [comment]
I made a small change in #1975 that takes care of this.

However, there's an alternative for this solution, that would involve merging [EventsByArtist](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/SeatGeek/EventsByArtist.pm) with [Sports](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/SeatGeek/Sports.pm), and deciding if the `taxonomies.name`(as documented [here](http://platform.seatgeek.com/#events)) should be included or not, depending on some keywords to be present (e.g. "game", "match" vs "concert", "gig")

**Comment by russellholt** [comment]
'tour' and 'tour dates' would improve this, also.

**Comment by moollaza** [comment]
@marianosimone I believe we attempted to have a unified Instant Answer that looked through the taxonomies but we didn't end up going down that route.

@jagtalon do you remember why?
