### ISSUE TITLE
Population: "canada population" not working but "population of canada" is

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1586]
https://duckduckgo.com/?q=population+of+canada&ia=population

**Comment by killerfish** [comment]
![population canada](https://cloud.githubusercontent.com/assets/1424236/6550843/8744e07e-c650-11e4-81c9-7fa0da6b458f.png)
Working for me, perhaps you meant another trigger?

**Comment by moollaza** [comment]
"canada population" doesn't seem to work:

![2015-03-09_22h38_18](https://cloud.githubusercontent.com/assets/873785/6568390/0fa8d28e-c6ad-11e4-97c8-96a411f03f5a.png)

**Comment by killerfish** [comment]
damn :/ i overlooked that completely, so population is using regex to trigger, @moollaza i think we should trigger on words, unless the trigger range becomes to broad, what do you suggest?

**Comment by moollaza** [comment]
>so population is using regex to trigger, @moollaza i think we should trigger on words

@killerfish absolutely! There's no need for a regex trigger.
