### ISSUE TITLE
Octopart: Migrate to API v3 -- API v2 deprecating March 20!

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1595]
Octopart will be officially turning off Octopart API v2 on **March 20, 2015** and **will not be functional** after March 20. 

Let's update it fast!

Here's the documentation for v3: https://octopart.com/api/docs/v3/overview

Code: https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Octopart.pm#L18

https://duck.co/ia/view/octopart

**Comment by killerfish** [comment]
relax i got this :>

**Comment by killerfish** [comment]
Hmm, i wasnt able to find how to get average price and market status (in v3), so mailed the guys, ill update when i get a response from them.

**Comment by moollaza** [comment]
> so mailed the guys, ill update when i get a response from them.

Great, thanks. If they don't respond soon, let me know :)

**Comment by jagtalon** [comment]
Fixed by @killerfish and @moollaza
