### ISSUE TITLE
Transit: Use text--primary on the times for dark mode

### ISSUE THREAD

**Issue by mattr555** [duckduckgo/zeroclickinfo-spice#1600]
![screenshot - 03062015 - 05 00 08 pm](https://cloud.githubusercontent.com/assets/4411471/6537187/426e7346-c422-11e4-8c6b-36a58ad06a02.png)
The status text also looks too dark, we could add `.text--secondary` to that.
cc @tagawa

**Comment by jagtalon** [comment]
@mattr555 good catch!

**Comment by tagawa** [comment]
PR #1603 should fix this but the tile design for cancelled trains could also use some love (affects NJT and SEPTA IAs).

Using preset classes is good for handling dark mode but there are no classes for backgrounds in the [style guide](https://duckduckgo.com/styleguide#txt-n-color). Any plans to create some?

![ddg_spice_transit_switzerland_dark_cancelled](https://cloud.githubusercontent.com/assets/94173/6539824/54ecbcca-c4c3-11e4-9e58-ab39ba74dbed.png)
