### ISSUE TITLE
Timer: Improve triggering, "timer for x minutes" should trigger

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1607]
https://duck.co/ideas/idea/5050/timer-for-n-minutes

As the issue explains, queries like "timer for x minutes" should trigger the timer.

https://duck.co/ia/view/timer

**Comment by mattr555** [comment]
There is also https://duck.co/ideas/idea/5032/timer-extension, which also seems pretty useful.
