### ISSUE TITLE
Bad nutrition relevancy

### ISSUE THREAD

**Issue by yegg** [duckduckgo/zeroclickinfo-spice#1621]
https://duckduckgo.com/?t=palemoon&q=carbon+fiber+wrap&ia=nutrition

Is this going through relevancy appropriately?

![screen shot 2015-03-10 at 8 57 33 am](https://cloud.githubusercontent.com/assets/127263/6575253/82d178be-c703-11e4-97c9-1f7ee0ad611c.png)

https://duck.co/ia/view/nutrition

**Comment by moollaza** [comment]
@yegg I noticed this as well and made a task for it #1616 -- There's a bug in our regex that checks the query format. I don't believe it's using a relevancy block either, which I mentioned should be added.

**Comment by yegg** [comment]
I think high relevancy bugs we should do internally ASAP. cc @nilnilnil @russellholt

**Comment by nilnilnil** [comment]
@russellholt @moollaza @yegg was this really resolved?

**Comment by moollaza** [comment]
@nilnilnil not yet AFAIK, I closed because it's a duplicate of #1616

**Comment by nilnilnil** [comment]
ok, so it was assigned. thanks.
