### ISSUE TITLE
ColorPicker: Set signal: high

### ISSUE THREAD

**Issue by mattr555** [duckduckgo/zeroclickinfo-spice#1626]
It currently doesn't open up automatically when you just search [color picker](https://duckduckgo.com/?q=color+picker) (though searching for a [specific color](https://duckduckgo.com/?q=color+picker+%23123) is ok)

https://duck.co/ia/view/color_picker

**Comment by chrismorast** [comment]
Thanks for creating an issue for this @mattr555 , I was about to do the same :)
