### ISSUE TITLE
Expanded triggers for flight search?

### ISSUE THREAD

**Issue by yegg** [duckduckgo/zeroclickinfo-spice#1629]
us air 581

works

but these dont't

us airways flight 581
usairways 581
usairways flight 581

https://duck.co/ia/view/flights_route

**Comment by moollaza** [comment]
@yegg "us airways flight 581" works for me?

![2015-03-12_15h13_10](https://cloud.githubusercontent.com/assets/873785/6626033/58bb02c0-c8ca-11e4-960d-1c1685798406.png)

The others should definitely be made to work though.

**Comment by javathunderman** [comment]
@moollaza Seems like these are all working now?
