### ISSUE TITLE
Flights: Implement new design

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1636]
We've recently re-designed our Flights Tiles as you can see below:

![screen shot 2015-02-27 at 10 43 02 am](https://cloud.githubusercontent.com/assets/873785/6648016/176a08ca-c9ab-11e4-8d8f-5472f2ea726b.png)

This new design now needs to be implemented. Any takers?!

https://duck.co/ia/view/flights_route

**Comment by moollaza** [comment]
Here's a spec outlining the design.

It specifies the CSS classes which should be given and the font sizes which will need to be specified in a CSS file. 

![2015-03-16_20h31_19](https://cloud.githubusercontent.com/assets/873785/6679230/6cab42d2-cc1b-11e4-99ca-ffc0bf7886f4.png)

**Comment by iambibhas** [comment]
Is anyone working on this?

**Comment by iambibhas** [comment]
```
    STATUS: {
        "S": "Scheduled",  // this comes under Landed
        "A": "In the air",  // this comes under Landed
        "U": "Unknown status",
        "R": "Redirected flight",
        "L": "Landed",
        "D": "Diverted",
        "C": "Cancelled",
        "NO": "Not Operational",
        "DN": "Data Needed"
    },
```
These are the possible statuses. What should be the subtitle for the ones other than `Landed` or `On Time`. In current implementation, `Scheduled` comes under `Landed`. Have to check the date calculation for the `Delayed` status.

**Comment by moollaza** [comment]
@iambibhas so sorry for the delay here!

- I don't think we should show results for flights with a status of `Data Needed`, `Not Operational` and `Unknown`.
- For **Diverted** and **Redirected flight**,  I imagine that means it *will be* late?
- For **Cancelled** we can set the subtitle to `cancelled` or perhaps set the body to that so it's more apparent
- For **Scheduled** I image we can set something like `waiting to depart`

/cc @abeyang @chrismorast -- any thoughts on what we should say for these statuses?

@iambibhas do we have any examples of results with these statuses?

**Comment by iambibhas** [comment]
@moollaza I dont have examples with these statuses. Most results are `on time`. Updating the PR with current UI. Let's continue there.

**Comment by chrismorast** [comment]
"S": "Scheduled" = On Time or Delayed
"A": "In the air" = This is represented by either 'on time' in green or 'delayed' in red with the flight timeline indicating that it;'s in the air:
![delayed](https://cloud.githubusercontent.com/assets/7061920/7965425/42a590ec-09d2-11e5-960c-13fb53a996b7.png)

"U": "Unknown status" = Unknown (hopefully this is extremely rare)
"R": "Redirected flight" = Redirected to [Airport code] [with new time show in red if it's delayed]
"L": "Landed" = Landed (green if it was on time and red if it was late)
"D": "Diverted" = Diverted to [Airport Code]
"C": "Cancelled" = Cancelled (Red subtitle - #de5833 font-weight 600 is fine - no need to set the body to it)
"NO": "Not Operational" = remove tile
"DN": "Data Needed" = remove tile

**Comment by chrismorast** [comment]
@moollaza , ping

**Comment by tagawa** [comment]
Looks good to me now.
