### ISSUE TITLE
Switch "String::Trim" to "Text::Trim"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1638]
We're currently using both `Text::Trim` and `String::Trim` in various Spices. This seems unnecessary and I believe we might as well choose one lib and just use that one. I vote for `Text::Trim`, but I don't think one is much better than the other - any opinions on which to choose?

Once we decide, let's updated the Goodies so that they're all using the same package.

Also, some other Goodies define a `trim` sub or use a regex to trim leading/trailing spaces. We should probably update those to use a more robust `trim` sub provided by the package we choose.

**Comment by MrChrisW** [comment]
@moollaza Did you mean to lodge this over here [zeroclickinfo-goodies](https://github.com/duckduckgo/zeroclickinfo-goodies/issues) ?

**Comment by moollaza** [comment]
Whoops, meant to say "Spices" -- we're not actually using either lib in the Goodie, but I think we should be!

**Comment by moollaza** [comment]
```shell
[03:43 PM codio@pizza-emerald zeroclickinfo-spice {master}]$ ack -l String::Trim
lib/DDG/Spice/Images.pm
lib/DDG/Spice/Quixey.pm
[03:43 PM codio@pizza-emerald zeroclickinfo-spice {master}]$ ack -l Text::Trim
lib/DDG/Spice/Currency.pm
lib/DDG/Spice/SeatGeek/EventsByArtist.pm
lib/DDG/Spice/TravisStatus.pm
lib/DDG/Spice/Whois.pm
lib/DDG/Spice/Forecast.pm
lib/DDG/Spice/Quandl/Fundamentals.pm
lib/DDG/Spice/Quandl/HomeValues.pm
lib/DDG/Spice/Coursebuffet.pm
lib/DDG/Spice/RandPOS.pm
lib/DDG/Spice/Recipes.pm
lib/DDG/Spice/Parking.pm
lib/DDG/Spice/GithubStatus.pm
lib/DDG/Spice/GoWatchIt.pm
```

**Comment by MrChrisW** [comment]
[Text::Trim](https://metacpan.org/pod/Text::Trim) looks good to me! After a little research there's no performance difference between the above mentioned packages however I believe `String::Strip` can be faster as its implemented in XS however unmaintained.

**Comment by moollaza** [comment]
@MrChrisW Let's go with `Text::Trim` then. Means less work anyways :)

**Comment by mintsoft** [comment]
@MrChrisW @moollaza I've recently switched the Goodies repo to harmonise trimming on `Text::Trim` too

**Comment by moollaza** [comment]
Fixed ^
