### ISSUE TITLE
Time: "time", "local time", "current local time", etc should show user's time

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1641]
This IA could definitely be improved to show the user's local time for certain queries, such as:

- "time"
- "local time"
- "current local time"
- "current time"
- "what's the time"
- etc.

https://duck.co/ia/view/time

**Comment by iambibhas** [comment]
Just curious, now that we have moment.js support, can't we show the datetime without an api call?

**Comment by moollaza** [comment]
@iambibhas I don't believe so because the TimeandDate API allows us to search for a specific location, and then they do the work of determining the timezone for that place. I don't believe Moment is capable of doing the `location -> timezone` piece unless it had a DB of all the world's cities?

**Comment by iambibhas** [comment]
@moollaza right. I just meant for the local time. But seems like the api takes care of it. never mind.

**Comment by moollaza** [comment]
Updating this one to important -- we'd love for someone to tackle this ASAP :rocket:

**Comment by iambibhas** [comment]
Couple of issues - 
 - `time` is being handled by `Timer` spice
 - `local time` triggers the `Maps::Places` spice

Anyway to prioritize the `Time` spice instead of them?

**Comment by moollaza** [comment]
>time is being handled by Timer spice

IA's can share triggers, there should be no problems

> local time triggers the Maps::Places spice

That's an internal bug. I'll make an issue for them to fix it. While testing you can set `signal: high` but I'd like to avoid setting that permanently unless we really need to.

**Comment by iambibhas** [comment]
Just changed the regex handling and it's working on my duckpan. There are cases when the query can return multiple locations and their times, do we need to show all of them in tiles? Or just the first one as `text`?

**Comment by moollaza** [comment]
>There are cases when the query can return multiple locations and their times, do we need to show all of them in tiles? Or just the first one as text?

Not quite sure what you mean -- can you give an example?

I think we currently operate under the assumption that the first place is the closest. If we can compare the user's city/country to the result and they match it would be ideal.
