### ISSUE TITLE
Movie + InTheaters: Images are slowly being deprecated in the API

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1647]
We've been modifying the API results to deal with the constantly changing URL for the images (see https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/in_theaters/in_theaters.js#L6...L16), and it's been a mess especially since the images in the API will be deprecated. 

A good way is to use another API for the images such as http://docs.themoviedb.apiary.io/#introduction/useful-links. It's worth investigating a way of accessing their images through Movie and InTheaters because we're starting to see broken images again.

@moollaza mentioned that we could:
- Use the IMDB ID in the RT results and match it with [MovieDB](https://www.themoviedb.org/)
- ~~Maybe some JS magic to access the MovieDB images without calling the API~~
  - Not possible, image URLs are all unique 

![screen shot 2015-03-17 at 11 39 44 am](https://cloud.githubusercontent.com/assets/81969/6691019/59ee1ec4-cc9a-11e4-9153-34fbdef92b19.png)

https://duck.co/ia/view/movie
https://duck.co/ia/view/in_theaters

**Comment by jagtalon** [comment]
Maybe we could also use the GoWatchIt API for it

**Comment by MrChrisW** [comment]
Source: http://developer.rottentomatoes.com/forum/read/184496 (posted 9 months ago) *high-resolution poster images are no longer available via the APIs and will need to be sourced elsewhere.*

**Comment by moollaza** [comment]
@MrChrisW good find! I hadn't thought to check there.

**Comment by iambibhas** [comment]
What to do about this one? Find a new source?

**Comment by jagtalon** [comment]
@iambibhas docs.themoviedb.apiary.io/#introduction/useful-links might work if you're interested!

**Comment by jagtalon** [comment]
@iambibhas I haven't looked at the API results but this is probably going to make one request per item. We need to find the best way to do this or else the IA will be slow.

**Comment by iambibhas** [comment]
I dont think using 2 different APIs is a good solution. Isn't there a single source for results with images? Nothing better than RT?

**Comment by jagtalon** [comment]
@iambibhas you're right--maybe we can just use themoviedb instead of RT. I'll consult the BD team and get back to you.

**Comment by MrChrisW** [comment]
@jagtalon @iambibhas I've tested out using [TheMovieDB](https://www.themoviedb.org/) API endpoint you can see an [example here](http://duckpan3.mrchris.me/?q=movie+australia&ia=movies)

[Movie.pm](https://github.com/MrChrisW/zeroclickinfo-spice/blob/movies-new/lib/DDG/Spice/Movie.pm)
[movie.js](https://github.com/MrChrisW/zeroclickinfo-spice/blob/movies-new/share/spice/movie/movie.js)

The only problem I can see with using this endpoint is it only offers move descriptions via a second endpoint `/movie/{id}` meaning if we wanted to display extra details in the `details_pane` we'd need to make an extra call :cry:

**Comment by iambibhas** [comment]
Do we really want to show movie descriptions? If the images are alright, I think we can just show the list of movies and skip the details view.

**Comment by MrChrisW** [comment]
@iambibhas I agree, although I think the idea is to provide as much information as possible without needing too clicks through to the site. @jagtalon @moollaza opinions?

**Comment by moollaza** [comment]
@MrChrisW @iambibhas I love seeing the descriptions and move ratings. @MrChrisW to clarify we don't want to get rid of the RT ratings -- those should still be there and we can request them as the tiles load. RT is moving towards an API that only provides their ratings, but no longer provides movie metadata.

Let's keep the detail view for now, I'm pretty sure the design team still wants it :)
