### ISSUE TITLE
WGHA: Subtitle is getting cut off

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1649]
![screen shot 2015-03-17 at 2 08 24 pm](https://cloud.githubusercontent.com/assets/81969/6694228/28fc3188-ccaf-11e4-9ea5-b5b483493998.png)

https://duck.co/ia/view/wgha

**Comment by moollaza** [comment]
Looks like it needs the `title` and `footer` variations to be set. Something like:

```js
options: {
    variations: {
        title: '4line',
        footer: '3line'
    }
}
```

/ccc @sdougbrown

**Comment by iambibhas** [comment]
I think `variants` should be outside `options`. Adding the variants and removing the css file, this is how it looks - 

![](http://imgur.com/HcTxjaS.png)

Removed the css file because the spacing between the title and the footer seemed a bit too much. Does this look fine?

**Comment by moollaza** [comment]
>I think variants should be outside options 

Whoops, my mistake. You're correct.

>Does this look fine?

Looks great!

**Comment by iambibhas** [comment]
@moollaza when are these changes deployed?

**Comment by moollaza** [comment]
We need to do a release of the Spice repo (you'll see the git tag increase) and then we need to wait for the site to be redeployed. Usually takes a few days to a week.
