### ISSUE TITLE
Timer: Tighter triggering needed perhaps

### ISSUE THREAD

**Issue by killerfish** [duckduckgo/zeroclickinfo-spice#1655]
Queries such as [this] (https://duckduckgo.com/?q=Time%3A%3Apiece) is triggering the timer, should be addressed perhaps.
//cc @mattr555 

https://duck.co/ia/view/timer

**Comment by moollaza** [comment]
hahaha @killerfish I totally didn't notice you made an issue for this! I made the exact same issue this morning https://github.com/duckduckgo/zeroclickinfo-spice/issues/1656

**Comment by moollaza** [comment]
there's some discussion there so I'll close this one. Thanks for noticing and making an issue!
