### ISSUE TITLE
Timer: Triggers on "Time::Piece"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1656]
It shouldn't :)

Looks like the triggers and regex need some more testing and review.

https://duck.co/ia/view/timer

**Comment by iambibhas** [comment]
Just testing, this seems to work as expected - 

```
diff --git a/lib/DDG/Spice/Timer.pm b/lib/DDG/Spice/Timer.pm
index c12a1d7..66a28f5 100644
--- a/lib/DDG/Spice/Timer.pm
+++ b/lib/DDG/Spice/Timer.pm
@@ -13,12 +13,11 @@ attribution twitter => 'mattr555',
             github => ['https://github.com/mattr555/', 'Matt Ramina'];
 
 triggers startend => ['timer', 'countdown', 'alarm'];
-triggers start => ['time'];
 
 spice call_type => 'self';
 
 handle remainder => sub {
-    return unless /^( ?([\d.]+ ?(m(in((ute)?s?)?)?|s(ec((ond)?s?)?)?|h(ours?)?|hr)|online) ?)+$/ || $_ eq '';
+    return unless $_ =~ /^( ?([\d.]+ ?(m(in((ute)?s?)?)?|s(ec((ond)?s?)?)?|h(ours?)?|hr)|online) ?)*$/i;
     return '';
 };
 ```

Not sure why `time` was set to `triggers start`. Replacing `+` with `*` so this is triggered if someone just searches with `timer`, hence removing the `$_ eq ''` part.

This is kind of my first time messing with perl. If something is broken, please humor me. :)

**Comment by moollaza** [comment]
@iambibhas it's intended to trigger on the query "timer" and also queries like "time 4 minutes", "timer 20 mins 3 seconds", etc.

I think your changes would break that?

**Comment by moollaza** [comment]
Best way to verify is to run the test ;) `prove -Ilib t/Timer.t`

**Comment by iambibhas** [comment]
@moollaza yeah, then my changes would break that. But the way it's now, querying for `time` returns a timer instead of triggering the Time spice. Is that intended?

**Comment by moollaza** [comment]
"time" definitely should't return the Timer IA. -- There's a slight problem in the duckduckgo code that also needs to be addresses. For the query `Time::Piece` because we break the query on symbols like `:` it sees "time" and "piece" as two separate words, but it's not correctly setting the `remainder` to `::piece` -- instead it's setting the remainder to `""` which is why this falls through...

**Comment by iambibhas** [comment]
Ah. That explains things. So if querying *only* `time`, it should trigger Time.pm. If `time` is followed by any of the stuff that's supposed to follow `timer`, it should trigger Timer.pm. Right?

But TBH, I can't imagine someone would want a timer by querying `time 5 hours`. sounds more like they'd want to know the time after 5 hours. That might just be me.

**Comment by moollaza** [comment]
>So if querying only time, it should trigger Time.pm

Yes, there's actually an issue to make "time" show the user's local time -- it currently does not.

> But TBH, I can't imagine someone would want a timer by querying time 5 hours. sounds more like they'd want to know the time after 5 hours, which also doesn't make much sense. That might just be me.

A user actually made an issue for that because they were expecting a timer for that kind of query

**Comment by moollaza** [comment]
Now that "time" triggers the Time IA, we need to update the Timer Spice to stop triggering on "time":

https://duckduckgo.com/?q=time

**Comment by mattr555** [comment]
@moollaza It might be useful in cases like this (if it doesn't exist already) to add the ability to find which trigger word the query triggered on. Therefore if we trigger on "time" and nothing else we can decide not to return a spice. I guess alternatively we could change it to `handle query_lc` and do all the parsing ourselves.

Barring either of those, we could do it on the JS:

```js
if (DDG.get_query().toLowerCase() === "time") {
    return Spice.failed('timer');
}
```

**Comment by moollaza** [comment]
>It might be useful in cases like this (if it doesn't exist already) to add the ability to find which trigger word the query triggered on.

Agreed, I have an internal task for the team to add this functionality, I've seen a few cases now where this would be useful.

FWIW, there is a `$req` object that's accessible in the `handle` func. Ideally this is where we'd expose the matched trigger, but the object contains other useful stuff like the original query.
