### ISSUE TITLE
SoundCloud: volume control?

### ISSUE THREAD

**Issue by malbin** [duckduckgo/zeroclickinfo-spice#1660]
Just wondering if there is a plan to implement volume control in the SoundCloud IA. I think it would be useful

------ 

IA Page:   http://duck.co/ia/view/sound_cloud

**Comment by gokul1794** [comment]
:+1: for volume control

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are only accepting issues for essential bugs/fixes.
