### ISSUE TITLE
Some issues with ExpandUrl

### ISSUE THREAD

**Issue by arroway** [duckduckgo/zeroclickinfo-spice#168]
Hi, 
I've been using the ExpandUrl functionnality for a couple of weeks. I don't know what is the official state of the functionnality, but here are some issues I faced when using it: 

1) For some queries, the result box doesn't display the expanded url in the target field "Expanded url:". Instead, it prints the shortened url.

https://duckduckgo.com/?q=expand+http%3A%2F%2Fbit.ly%2F1avAYhr&t=canonical 
https://duckduckgo.com/?q=expand+http%3A%2F%2Ft.co%2F3BjGmvnowY&t=canonical

But if I click on the longurl.org link, I can read the expected result. I think it is mostly related with bit.ly and t.co shortened urls.

2) Some short urls don't trigger anything if there isn't "http://" prefixing them:

https://duckduckgo.com/?q=yhoo.it%2F1b9ro1o&t=canonica
https://duckduckgo.com/?q=bit.ly%2F1avAYhr&t=canonical

(As I often copy/paste links from Twitter, I sometimes get such urls.)

**Comment by eladkarako** [comment]
this is really old, but happen to came across in Google, 
not sure if longurl is still used in the background, 
here are two alternatives:
<code>http&#x003A;//9inchurl.com/api.php?url=</code>
<code>https&#x003A;//unshorten.me/s/</code>

( used in https://github.com/eladkarako/chrome_extensions/tree/store/Remove-Redirects-Plus )

**Comment by moollaza** [comment]
@eladkarako thanks, we're currently using https://is.gd which seems to be working well for us.

https://duckduckgo.com/?q=shorten+duckduckgo.com&ia=shortenedlink

**Comment by Adman** [comment]
@moollaza `is.gd` if for shortening the link, this issue discusses expanding urls :)

**Comment by moollaza** [comment]
@Adman whoops, my bad. 

@eladkarako it looks like we're already using unshorten.me actually: 
https://duckduckgo.com/?q=expand+http%3A%2F%2Fbit.ly%2F1avAYhr&t=canonical&ia=answer

**Comment by eladkarako** [comment]
<em>Ah yes,</em> 
https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/expand_url/expand_url.js#L24
