### ISSUE TITLE
Seasons: Improve triggering

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1683]
Would like it to work for these queries too:
- when is spring?
- when is summer?
- when does spring start?
- spring in the us
- spring in the ph

------ 

IA Page: https://duck.co/ia/view/seasons

**Comment by GuiltyDolphin** [comment]
@moollaza Why is this still open? It looks like [This PR](https://github.com/duckduckgo/zeroclickinfo-spice/pull/1678) fixes it.

**Comment by moollaza** [comment]
@GuiltyDolphin there's another issue somewhere...we had to take this IA offline because we can't determine the user's hemisphere very easily, which affects the results. We were basically showing wrong info for everyone in the southern hemisphere

**Comment by moollaza** [comment]
IA is no longer online.
