### ISSUE TITLE
SimilarSites: Move away from using IDs

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1691]
We often use classes in IAs and rarely IDs. Reference DOM using classes instead. 

https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/similar_sites/content.handlebars#L10

**Comment by tagawa** [comment]
Sent PR with a couple of other small edits: https://github.com/duckduckgo/zeroclickinfo-spice/pull/1716
