### ISSUE TITLE
Soundcloud: Add AutoPlay and AutoRepeat buttons

### ISSUE THREAD

**Issue by killerfish** [duckduckgo/zeroclickinfo-spice#1692]
Would be nice to have such controls. Could be made part of the audio view (internal change needed).
//cc @jagtalon @moollaza 

------ 

IA Page: https://duck.co/ia/view/sound_cloud

**Comment by jagtalon** [comment]
![7qsghgl](https://cloud.githubusercontent.com/assets/81969/6855192/833dac3e-d3cc-11e4-94d2-05e403bb9fd3.gif)

**Comment by iambibhas** [comment]
Soundcloud IA doesn't seem to be working for me.

**Comment by killerfish** [comment]
@iambibhas please elaborate, and open an issue with the details. Is it not working on duckpan? or live? Is the audio not playing?

**Comment by iambibhas** [comment]
@killerfish it's not working on either duckpan or live. I'm getting some JSON parsing error for this request https://duckduckgo.com/js/spice/sound_cloud/soundcloud%20ray%20bradbury

![](http://imgur.com/TuvHI8c.png)

**Comment by iambibhas** [comment]
Seems to be working on Firefox Android. Not sure why not on Firefox Desktop 35.0.1 on linux, not even on Chrome 40.

**Comment by moollaza** [comment]
Seems to be working fine for me. @iambibhas if it's still not working for you, please open a separate issue and provide as many details as you can about your environment so we can figure it out -- this issue isn't the best place to discuss if the IA is/isn't working though :)

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
