### ISSUE TITLE
Github: Use moment.js

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1694]
Seeing `NaN`s like it's a Batman show in IE 8.

![screen shot 2015-03-26 at 3 14 39 pm](https://cloud.githubusercontent.com/assets/81969/6854951/e55e5abe-d3ca-11e4-8ad2-a51a08c15f5f.png)

**Comment by jagtalon** [comment]
Maybe moment.js won't fix it, but code would look cleaner.

**Comment by iambibhas** [comment]
@jagtalon Try now. Batman should be gone. :P That `NaN` was being thrown by the helper function I think.
