### ISSUE TITLE
SoundCloud IA not working, badly formatted JSON

### ISSUE THREAD

**Issue by iambibhas** [duckduckgo/zeroclickinfo-spice#1707]
Here is what's happening when I search for `soundcloud ray bradbury` - 

![screenshot from 2015-03-31 19 50 57](https://cloud.githubusercontent.com/assets/357253/6921041/d314cfc8-d7df-11e4-9f0f-0dc3e7b48dad.png)
![selection_002](https://cloud.githubusercontent.com/assets/357253/6921043/d87ae4ac-d7df-11e4-96ad-b0dd99a6c6ba.jpg)
![selection_001](https://cloud.githubusercontent.com/assets/357253/6921045/d8e06aac-d7df-11e4-9dbb-782b9a15a1df.jpg)

Using Ubuntu 14.04, Firefox 35.0.1. Same thing happening with Chrome 40.

![selection_003](https://cloud.githubusercontent.com/assets/357253/6921072/1157bf20-d7e0-11e4-8589-32eadaa38a1d.jpg)

There seems to be a `/**/` before the json which is causing trouble. Although the whole thing works on my Firefox Android.

**Comment by moollaza** [comment]
@iambibhas the malformed JSON is a known-problem. It causes problems for your browser, but the javascript returned is still valid and so the IA still works. I see the same error page if I open my browser to the API response, but the Spice still works.

This specific query has a known problem though and the SoundCloud team is currently working to fix it. For now we can leave this open, but there isn't much we can do on our side as it's a bug in the SC API.

**Comment by iambibhas** [comment]
@moollaza If they know about and working on it, then all good. I wonder why my desktop browser is not tolerating it but my mobile browser is?

**Comment by jagtalon** [comment]
Should be fixed!
