### ISSUE TITLE
Time: Relevancy block prevents "time in london england", "time in london uk" from showing

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1710]
This IA should be returning a result for "time in London, England" and "time in London, UK" but the relevancy block throws the result away.

We may need a special check if it's UK because United Kinhdom will never pass a relevancy test against "england" or "uk"

**Comment by MrChrisW** [comment]
@moollaza Looks like this has been resolved internally as these queries now work.

+ https://duckduckgo.com/?q=time+in+united+kingdom&ia=time
+ https://duckduckgo.com/?q=time+in+london+uk&ia=time
+ https://duckduckgo.com/?q=time+in+london+england&ia=time

Unfortunately there's still some broken queries noted in #1730
