### ISSUE TITLE
Gravatar - should show the whole avatar 

### ISSUE THREAD

**Issue by iambibhas** [duckduckgo/zeroclickinfo-spice#1722]
The only reason anyone would use this IA is to see the avatar, but yet the current view hides about 20% of it - 

![](https://i.imgur.com/MHEWbba.png)

We should remove the circle - 

![](https://i.imgur.com/eRTJJbW.png)

**Comment by moollaza** [comment]
@abeyang any thoughts?

**Comment by abeyang** [comment]
@iambibhas , we're currently using circles as a design pattern for avatars (people in space, G+, twitter profiles, etc) as well as for flags. So we'd like this to be consistent as well.

I don't think losing the corners is that big of a deal... unless your profile isn't centered or something. :smile:

**Comment by iambibhas** [comment]
I just like the full picture, that's all. Never liked the circle thingy on G+. I've seen too many images where faces are not really at the center. Hence they are always cropped by this circle.

Anyway, if this is being implemented everywhere, then let's keep it.

**Comment by MrChrisW** [comment]
Closing as a decision was made to keep circles as design pattern. See [comment](https://github.com/duckduckgo/zeroclickinfo-spice/issues/1722#issuecomment-89427420)
