### ISSUE TITLE
SteamDB - API endpoint is throwing 404

### ISSUE THREAD

**Issue by iambibhas** [duckduckgo/zeroclickinfo-spice#1723]
The API endpoint being used seems to throw 404 now.

https://steamdb.info/api/GetMetadata/?search=team%20fortress&jsonp=ddg_spice_steam_db

Can't find any API doc on the site.

**Comment by MrChrisW** [comment]
Ping @xPaw has the API been depreciated? Thanks!

**Comment by xPaw** [comment]
That API has been disabled because there were zero requires from DDG to that endpoint, and trying to search myself wouldn't call it either.

**Comment by MrChrisW** [comment]
Wow, thanks for the quick update @xPaw :+1: 

>trying to search myself wouldn't call it either.

That's strange, it's possible the IA could have been disabled internally :confused: . Would you be interested in getting it running again or should it be removed?

**Comment by xPaw** [comment]
I think we're better off removing it.

**Comment by MrChrisW** [comment]
@xPaw Sure no problem! Thanks :wink:

**Comment by MrChrisW** [comment]
@iambibhas Do you mind lodging a PR to remove the SteamDB IA? :cry:

**Comment by iambibhas** [comment]
@MrChrisW we could use this endpoint from steam to cache a list of all games and their ids http://api.steampowered.com/ISteamApps/GetAppList/v2/?format=json  - [doc](https://wiki.teamfortress.com/wiki/WebAPI/GetAppList)

And then search that list for given game and return details using this endpoint http://store.steampowered.com/api/appdetails/?appids=32330 - [doc](https://wiki.teamfortress.com/wiki/User:RJackson/StorefrontAPI#appdetails)

Or we can just remove it.

**Comment by MrChrisW** [comment]
@iambibhas Good idea :smile: although I'm not sure about caching that json data locally (copyright issues) also the size is quite large (1.2MB) this may impact performance when slurping the list. 

>And then search that list for given game and return details using this endpoint 

One problem with this endpoint, [mentioned here](https://github.com/duckduckgo/zeroclickinfo-spice/pull/1376#issuecomment-68428134) was we cannot request multiple game ID's meaning we'd need to call the API multiple times if more then one match is found. Another performance issue. :frowning: 

Either way we should remove the *SteamDB IA* and post a suggestion/issue regarding implementation of a new Steam IA. :+1:

**Comment by iambibhas** [comment]
Hmm. Sounds good. I'll send a PR removing SteamDB IA.

**Comment by moollaza** [comment]
:+1:

**Comment by iambibhas** [comment]
Removed the SteamDB IA and opened #1725 for tracking future progress. Closing this.
