### ISSUE TITLE
SteamDB - Suggestion for new implementation

### ISSUE THREAD

**Issue by iambibhas** [duckduckgo/zeroclickinfo-spice#1725]
Following #1723 up. The existing API has been deprecated. I sent a PR removing the existing spice. We can think about ways to bring it back. Here is a way to bring it back - 

> we could use this endpoint from steam to cache a list of all games and their ids http://api.steampowered.com/ISteamApps/GetAppList/v2/?format=json  - [doc](https://wiki.teamfortress.com/wiki/WebAPI/GetAppList)

> And then search that list for given game and return details using this endpoint http://store.steampowered.com/api/appdetails/?appids=32330 - [doc](https://wiki.teamfortress.com/wiki/User:RJackson/StorefrontAPI#appdetails)

@MrChrisW mentioned few problems with above approach - 

> although I'm not sure about caching that json data locally (copyright issues) also the size is quite large (1.2MB) this may impact performance when slurping the list.

>>    And then search that list for given game and return details using this endpoint

> One problem with this endpoint, [mentioned here](https://github.com/duckduckgo/zeroclickinfo-spice/pull/1376#issuecomment-68428134) was we cannot request multiple game ID's meaning we'd need to call the API multiple times if more then one match is found. Another performance issue. :frowning:

**Comment by MrChrisW** [comment]
CC// @killerfish you may be interested in this as I know you built the original SteamSpecials Spice!

**Comment by killerfish** [comment]
@MrChrisW the instant answer i worked on was using the same api from steam which steamdb is using (with the issues @iambibhas has mentioned plus others), its best to leave this for now, i've tried to contact Valve, but so far no response on this issue :cry:

**Comment by MrChrisW** [comment]
@killerfish Thought that might be the case! Its a shame, but there's not much we can do I guess!

**Comment by MrChrisW** [comment]
Closing for now. :wink:
