### ISSUE TITLE
Duplicated Markdown cheatsheet on IA index?

### ISSUE THREAD

**Issue by ngzhian** [duckduckgo/zeroclickinfo-spice#1732]
Duplicate on the index for Markdown cheatsheet?

![dup](https://cloud.githubusercontent.com/assets/1749303/6993650/56dfd488-dac9-11e4-9a17-690a79ffeb30.PNG)

https://duck.co/ia

**Comment by iambibhas** [comment]
Seems like they are same Goodie, just 2 pages for it. 

 - https://duck.co/ia/view/markdown_cheatsheet - this one has almost no metadata
 - https://duck.co/ia/view/markdown_cheat_sheet - this one seems like the one that should stay

This issue should go to the Goodie repo I think.

**Comment by ngzhian** [comment]
@iambibhas oops! great point, i'll file it on the goodie repo, thanks!
