### ISSUE TITLE
MetaCPAN Plugin should be switched to use auto-complete API Endpoint

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#174]
Currently the MetaCPAN plugin only works when a user enters a case-sensitive package name. This makes it very difficult to use and doesn't really "search" MetaCPAN. 

However, switching to the Autocomplete API should be a lot more helpful as it seems to mimic the autocomplete used for the site search.

Example: http://api.metacpan.org/v0/search/autocomplete?q=Moose

**Comment by killerfish** [comment]
Closing in favour of #898
