### ISSUE TITLE
LeakDB: Template group should be switched to 'list'

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1765]
Now that we have the `list` template group, this IA (and others!) can be switched over to use it.

https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/leak_db/leak_db.js#L27

- It's already setup to use the `record` template which is perfect. Switching to 'list' group is beneficial because it will automatically supress the output so it doesn't take up too much vertical space. The "Show more" button will allow users to expand the content to see it all.
- We should also remove the row-highlight option

It also wouldn't hurt to add a `title` and possible `subtitle` if we have something worth putting there :)

The end result will look almost identical to the Whois Spice: https://duckduckgo.com/?q=whois+duckduckgo.com&ia=whois

**Comment by gokul1794** [comment]
@moollaza This can be closed!

**Comment by moollaza** [comment]
@gokul1794 thanks!
