### ISSUE TITLE
InTheaters: "kids movies in theaters" should show g/pg movies

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1768]
Right now the query "kids movies in theaters" doesn't trigger the InTheater's IA. It should be considered an alias for "pg movies in theaters" or "g movies in theaters" (if "g" is supported).

- https://duckduckgo.com/?q=kids+movies+in+theaters
- https://duckduckgo.com/?q=pg+movies+in+theaters

**Comment by gokul1794** [comment]
@moollaza Looks like this can be closed too!

**Comment by moollaza** [comment]
@gokul1794 thanks!
