### ISSUE TITLE
Similar site search has an extra show more plus icon (+)

### ISSUE THREAD

**Issue by KK4OXJ** [duckduckgo/zeroclickinfo-spice#1770]
Searching for similar sites works pretty well, but there's an extra plus sign (+) by the show more link. See screenshot: 
![screenshot from 2015-04-15 12 24 16](https://cloud.githubusercontent.com/assets/7751418/7164018/62714bc4-e36b-11e4-8f2b-8751c8876fb2.png)

**Comment by MrChrisW** [comment]
@KK4OXJ Thanks for reporting, we'll investigate and fix :smile: 

@jagtalon @moollaza Iterestingly the CSS that's deployed on production for *similar sites* differs from the one contained in the repository. :confused: 

+ https://duckduckgo.com/share/spice/similar_sites/1109/similar_sites.css

+ https://raw.githubusercontent.com/duckduckgo/zeroclickinfo-spice/master/share/spice/similar_sites/similar_sites.css

**Comment by moollaza** [comment]
> @jagtalon @moollaza Iterestingly the CSS that's deployed on production for similar sites differs from the one contained in the repository. :confused: 

Hehe, that's because we fixed the code on master already. Fix should roll out shortly :+1: 

Checkout #1669

**Comment by MrChrisW** [comment]
@moollaza :+1:

**Comment by moollaza** [comment]
Sorry my PR hasn't been merged yet, but it will fix the issue.

**Comment by moollaza** [comment]
Alright merged my PR -- we'll be releasing the Goodies repo this week so a fix should be out within the next few days. Thanks again @KK4OXJ

**Comment by KK4OXJ** [comment]
@moollaza No problem, thanks for fixing it!
