### ISSUE TITLE
Transit::Switzerland: Should show AM / PM instead of military time.

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1781]
![nrphydx](https://cloud.githubusercontent.com/assets/81969/7206521/3823bb18-e500-11e4-9da0-79915ab63997.png)

**Comment by iambibhas** [comment]
Also, it doesn't show the platform. `Platform <foo>`.

Seems like the API doesn't provide the platform is some cases, should I omit the platform text altogether then?

![](http://imgur.com/eokjGUm.png)

**Comment by jagtalon** [comment]
@mattr555 mentioned that it should be in 24hr format. https://github.com/duckduckgo/zeroclickinfo-spice/pull/1784#issuecomment-101064344. Closing this.
