### ISSUE TITLE
ProductHunt: `tileTitle` variant should be '2line'

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1786]
https://github.com/duckduckgo/zeroclickinfo-spice/blob/9ffde54d9d666f1d3b0bb4e9338605c07390cfad/share/spice/product_hunt/product_hunt.js#L50

`2line--small` doesn't actually exist, it should be change to `2line`

**Comment by MrChrisW** [comment]
@moollaza This is being addressed in PR [1750](https://github.com/duckduckgo/zeroclickinfo-spice/pull/1750/files#diff-eddf2d198f0d510618c15f1c4dc1d017R61)

**Comment by moollaza** [comment]
@MrChrisW thanks :+1:

**Comment by altern8tif** [comment]
@moollaza good to close!
