### ISSUE TITLE
Quixey: Skip GoogleTV apps

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1793]
Unfortunately the API doesn't differentiate GoogleTV apps from standard Android apps, so it seems the only way is to check the name for "GoogleTV". If it matches, we should toss the result as it's not very relevant to most users.

Example: https://duckduckgo.com/?q=youtube+android+app&ia=apps&iai=0 -- the YouTube result has two Android links, one of which is for GoogleTV -- let's get rid of the GoogleTV result.

**Comment by moollaza** [comment]
It may also help to check the `package_name` which contains, "googletv": `package_name":"com.google.android.youtube.googletv`

**Comment by jagtalon** [comment]
Fixed in #1810
