### ISSUE TITLE
Update old meta text attributes

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#1794]
We have a shim internally to convert old attribute names to the new ones, but it would be nice if we could just migrate to using the new ones so we could deprecate the shim:

`meta.heading` => `meta.primaryText`
`meta.altMeta` => `meta.secondaryText`

Forecast is good example with both:
https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/forecast/forecast.js#L274

**Comment by MrChrisW** [comment]
@bsstoner Seems like Forecast is the only one using these old meta attributes?

**Comment by gokul1794** [comment]
@moollaza this can be closed?

**Comment by moollaza** [comment]
@gokul1794 looks like there's still some lurking:

- https://github.com/duckduckgo/zeroclickinfo-spice/blob/ed05efa4152f627dd3e54821bca2eb563d105192/share/spice/transit/path/transit_path.js#L14
- https://github.com/duckduckgo/zeroclickinfo-spice/blob/ed05efa4152f627dd3e54821bca2eb563d105192/share/spice/transit/switzerland/transit_switzerland.js#L17
- https://github.com/duckduckgo/zeroclickinfo-spice/blob/ed05efa4152f627dd3e54821bca2eb563d105192/share/spice/transit/njt/transit_njt.js#L16
- https://github.com/duckduckgo/zeroclickinfo-spice/blob/ed05efa4152f627dd3e54821bca2eb563d105192/share/spice/transit/septa/transit_septa.js#L26

That seems to be it. Just the Transit IAs;

**Comment by gokul1794** [comment]
Cool, will do this!
