### ISSUE TITLE
Missing movie images

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#1796]
https://duckduckgo.com/?q=movies&ia=movies&iai=5

![screen shot 2015-04-21 at 3 02 00 pm](https://cloud.githubusercontent.com/assets/126358/7260386/9ce45af0-e837-11e4-8615-6017d6c96e7e.png)
![screen shot 2015-04-21 at 3 02 07 pm](https://cloud.githubusercontent.com/assets/126358/7260385/9ce3d562-e837-11e4-8466-a6228d9adc73.png)

**Comment by iambibhas** [comment]
I think this is related to #1647.

**Comment by moollaza** [comment]
@bsstoner @iambibhas yup it is -- we really need to get images from a new source.

**Comment by iambibhas** [comment]
Can't we use this? 

http://www.imdbapi.com/?i=tt1375666
http://www.imdbapi.com/?i=&t=inception

**Comment by moollaza** [comment]
I believe this is fixed now. We can't use that API as its unofficial and seems to be faces legal issues given its name
