### ISSUE TITLE
Time: any query that ends with "time" triggers...

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1801]
Any query that ends with "time" seems to trigger a search for the user's local time.

Examples
- https://duckduckgo.com/?q=pdt+time&ia=time
- https://duckduckgo.com/?q=testing+time&ia=time
- https://duckduckgo.com/?q=foobar+time&ia=time
- https://duckduckgo.com/?q=adhjasdhjkd+hjkasdjasd+ashjkas+time&ia=time

---

Looks like we need to `return` if the query didn't match our regex, but still has a remainder.

**Comment by MrChrisW** [comment]
@moollaza This was introduced in #1714 - ping @iambibhas

It's strange that these queries aren't just discarded due to the [relevancy checking](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/time/time.js#L20-L23).

It's hard to test this in the development environment, due to the API limitations.

**Comment by iambibhas** [comment]
@moollaza @MrChrisW Sorry about this. I think my regex checking let pass these random queries. I've added tests for the above 4 queries right now so that we can be sure that doesn't happen.

**Comment by moollaza** [comment]
>It's strange that these queries aren't just discarded due to the relevancy checking.

@MrChrisW the reason they pass the relevancy is because for all those queries we were using the user's location as the search term. We then compared that against the result, and in almost every case it's relevant so the result shows. This happens because we're using `stringsRelevant` instead of `isRelevant` which automatically uses the query as the comparator.

**Comment by MrChrisW** [comment]
@moollaza Sure that makes sense, as I said before testing this locally is hard as the default location is always `Phoenixville` which doesn't actually return true using `stringsRelevant` for any of the results.
