### ISSUE TITLE
Time: Should support timezone lookups

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1802]
Searches like  "PDT time", "Time in ET", "Eastern Standard Time" should all show the time for the given timezone.

The TimeandDate API doesn't support searches for Timezones though, so we could use a hash that maps timezones to countries and use the time for a given country to show the time for the specified timezone.

---

Instant Answer Page: https://duck.co/ia/view/time

**Comment by iambibhas** [comment]
I have a CSV of all the most used timezones https://github.com/iambibhas/iambibhas.github.com/blob/master/csv/timezones.csv

There are some redundant timezones in real life. I only kept the most used ones and removed the others.

**Comment by iambibhas** [comment]
T&D API doesn't seem to have an option to get time by Tomezone. This might require a separate Spice or a Goodie maybe.

**Comment by moollaza** [comment]
@iambibhas yup, that's unfortunate, but that's why I suggested we build a hash of countries that map to timezones so we can do the lookup that way. Alternative a different API could work if one exists.

**Comment by iambibhas** [comment]
For queries like `time in IST`, we can just use the csv(turned to yml) I have above, fetch the UTC time and add the offset. But yeah, if we have a map of country -> timezone, then we could even process the `time in <country>` queries without calling any API.

**Comment by sekhavati** [comment]
@moollaza I've been giving this some thought and I think there’s a simpler way to approach this. 

We could request the current UTC time from the API, then in JavaScript using moment.js we apply an appropriate offset depending on the time zone requested. This would mean client side we'd have a mapping between `Time Zone => Offset from UTC`, similar to the information listed [here](http://www.timeanddate.com/time/zones/).

I'll knock something together to demonstrate...

One tricky aspect is that time zone abbreivations are not unique, for example IST could stand for:
- India Standard Time (UTC+5.30)
- Irish Standard Time (UTC+1)
- Israel Standard Time (UTC+2)

In these circumstances do we display all three and if so is this IA written in such a way that they could all be displayed?

**Comment by moollaza** [comment]
> In these circumstances do we display all three and if so is this IA written in such a way that they could all be displayed?

@sekhavati thanks a lot for looking into this! It sounds like your approach will work. I think disambiguating will be necessary but it seems like the ISO standard sets IST as the time zone for India?

**Comment by MrChrisW** [comment]
@moollaza Unfortunately not..
>Time zones are often represented by >abbreviations such as "EST, WST, CST" but >these are not part of the international time and >date standard ISO 8601 and their use as sole >designator for a time zone is not >recommended. Such designations can be >ambiguous. For example, "ECT", could be >interpreted as "Eastern Caribbean Time" >(UTC−4h), "Ecuador Time" (UTC−5h) or >"European Central Time" (UTC+1h).

https://en.m.wikipedia.org/wiki/Time_zone

**Comment by moollaza** [comment]
@MrChrisW @sekhavati it looks like Google does handle those ambiguous abbreviations -- I'm not sure how they've decided but they use Indian Standard Time for IST and Ecuador for ECT.

My first query for ECT was actually corrected to CET though, and I had to specify I wanted results for ECT.

I think if we display the results for all 3 in those ambiguous cases it would be fine.

![5pm_ist_to_est_-_google_search](https://cloud.githubusercontent.com/assets/873785/13724464/a949f64c-e854-11e5-8ee0-ea39e51c4743.png)
![5pm_ect_to_est_-_google_search_and_1____projects_zeroclickinfo-goodies__bash_](https://cloud.githubusercontent.com/assets/873785/13724468/b2f88fbe-e854-11e5-833d-8e0c706714b3.png)

**Comment by MrChrisW** [comment]
@moollaza Thanks for doing some research and clarifying the best way to proceed. I'll work on pushing up these improvements shortly. 

Do you have any suggestions (design wise) for displaying 3 separate times?

**Comment by moollaza** [comment]
> Do you have any suggestions (design wise) for displaying 3 separate times?

I think we can use our list template to show the timezones + times for each:

**IST**
 Timezones
<table>
<tr><td>India Standard Time</td><td>4:00PM</td></tr>
<tr><td>Irish Standard Time</td><td>5:00PM</td></tr>
<tr><td>Israel Standard Time</td><td>6:00PM</td></tr>
</table>

**Comment by moollaza** [comment]
Something like that^

**Comment by bsstoner** [comment]
Would it be easier to make progress here if we defer worrying about disambiguation for now? The complaints are all related to the fact that we don't show anything for: PST, CST, EST, UTC and GMT work. We could just show the first result for now and come back and do the disambiguation later?

**Comment by bsstoner** [comment]
More user feedback:

**gmt now time**
[https://duckduckgo.com/?q=gmt%20now%20time](https://duckduckgo.com/?q=gmt%20now%20time)
_Comment: Should show the time for GMT_

**Comment by bsstoner** [comment]
**time now est**
[https://duckduckgo.com/?q=time%20now%20est](https://duckduckgo.com/?q=time%20now%20est)
_Comment: Searching "time now ET" should display the time in the results_

**Comment by bsstoner** [comment]
**eastern time**
[https://duckduckgo.com/?q=eastern%20time](https://duckduckgo.com/?q=eastern%20time)
_Comment: When I search for eastern time, it could be useful if it displayed the current eastern time prominently._
