### ISSUE TITLE
ColorPicker: Mobile layout fixes, try to use DDG grid system

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1806]
There are some mobile layout bugs for this color picker which need to be addressed.

We currently use a bunch of CSS to control the design of this IA and I thought we may be able to reduce that by using the DDG Grid system. We don't typically use this for IA's (mostly because there hasn't been a need!) but this may be a great test case. I think the IA can be broken down to about an 8 or 10 grid layout.

Info on the grid system can be found here: https://duckduckgo.com/styleguide#grids -- note for the mobile section, we'll need to add additional classes to specify the sizing on mobile screen. More details here: https://duckduckgo.com/styleguide#responsive

---

The mobile layout should look like this:
![32414325331720 osu3ozgyqx5dcf9ksehd_height640](https://cloud.githubusercontent.com/assets/873785/7325783/cd41b914-ea8e-11e4-8e9f-02c979bf512f.png)
![32414325331722 gse1vd1ddaqc1nvatoma_height640](https://cloud.githubusercontent.com/assets/873785/7325784/cd430404-ea8e-11e4-920e-baeffb61ad2b.png)

---

https://duck.co/ia/view/color_picker

**Comment by mattr555** [comment]
Sounds good! We may want to explore using a grid on timer and stopwatch as well; I had to basically implement my own when I originally wrote those.

**Comment by chrismorast** [comment]
Yeah @mattr555 , I think that's a good call. I'll be out next week but can have a look into it when I return.
