### ISSUE TITLE
SearchCode: Revive this IA! Port it to the new Spice API for re-launch

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1814]
I just realized this IA has been down for a very long time, since the launch of the DuckDuckGo redesign. Let's get it live again! It needs to be ported to the newest Spice API (in the docs) and should be using an existing template.

**Comment by javathunderman** [comment]
@moollaza Is there any old code lying around?

**Comment by iambibhas** [comment]
@moollaza #1822 fixes this, right?

**Comment by moollaza** [comment]
@iambibhas nope, SearchCode and CodeSearch are two different IA's that use the same source, but for differrent types of searches.

**Comment by sahildua2305** [comment]
This may be my first contribution to this repo. Can I take this? @moollaza 
Docs to get started please?

**Comment by jbarrett** [comment]
I came across this IA when working on metacpan - overlapping trigger spaces! Noticed it was broken, cane looking for an issue :smile: 

Thanks @sahildua2305! Docs for getting started with spice are here : http://docs.duckduckhack.com/walkthroughs/forum-lookup.html

**Comment by sahildua2305** [comment]
If I understand it correctly, the javascript code needs an update right? I mean it needs to use closure, right? Does it need any other change? @jbarrett

**Comment by moollaza** [comment]
@sahildua2305 I've left some comments for other required changes on your PR 👍
