### ISSUE TITLE
Places: tile__title uses #dadada color on dark theme, text unreadable

### ISSUE THREAD

**Issue by MrChrisW** [duckduckgo/zeroclickinfo-spice#1818]
The h4 `tile__title` class has a color `#dadada` (standard link color for dark theme) on the place name, this looks a little washed out as it's on a white background. 

IA: https://duck.co/ia/view/maps_places
Example: https://duckduckgo.com/?q=City+Hall+Philadelphia&kae=t&ia=places

![selection_396](https://cloud.githubusercontent.com/assets/5282264/7430582/db350fee-f047-11e4-987a-1dccb2a1beae.png)

**Comment by moollaza** [comment]
I believe this requires and internal fix.

/cc @sdougbrown @chrismorast

**Comment by chrismorast** [comment]
@bsstoner , any reason we can't apply the dark theme to the tile in this case as well?

**Comment by bsstoner** [comment]
We can, I didn't do it because it looked a little funny on top of the light map.

**Comment by chrismorast** [comment]
Yeah, I guess I'd have to see it. Would we have an option to use a dark map if we were to create one through MapBox? That might be really cool - probably not quite as useable though.

**Comment by altern8tif** [comment]
This looks like it's been fixed.  Can the issue be closed?

![screen shot 2015-10-21 at 5 17 31 pm](https://cloud.githubusercontent.com/assets/5793364/10632534/a4917eac-7817-11e5-80c4-525cbb20b523.png)

**Comment by bsstoner** [comment]
This is still an issue. It's when the link is `:visited`. We need to fix it internally, will open a task.
