### ISSUE TITLE
Time vs Timer: Query "time"

### ISSUE THREAD

**Issue by MrChrisW** [duckduckgo/zeroclickinfo-spice#1819]
Using the query "time" shows the **Timer** IA first as it has [signal high](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/timer/timer.js#L58) set.

The first result should actually be the **Time** IA displaying the current time based on the users location. 

+ Example: https://duckduckgo.com/?q=time
+ Timer: https://duck.co/ia/view/timer
+ Time: https://duck.co/ia/view/time

![selection_395](https://cloud.githubusercontent.com/assets/5282264/7430680/f257b004-f048-11e4-8c69-4f1a3e7ba928.png)

**Comment by zekiel** [comment]
related to "time" triggerspace #1821

**Comment by MrChrisW** [comment]
Closing as duplicate of #1656
