### ISSUE TITLE
Geometry: Add variable to diagram

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/zeroclickinfo-spice#1825]
https://twitter.com/tubakerl/status/594982609165365248 

Per the feedback in the tweet---> we should label the variable being referenced in the diagram. 

------ 

IA Page: http://duck.co/ia/view/geometry

**Comment by moollaza** [comment]
The reason it's missing is because when you hover on the letters or color block, the image highlights what that refers to. This seems like a design problem.

/cc @abeyang -- any ideas on how we can suggest to users this IA is interactive? Perhaps we should simply tell them to hover?

**Comment by tagawa** [comment]
The UI shouldn't rely solely on colour or contrast because of users with colour-blindness, etc. not being able to distinguish it.
