### ISSUE TITLE
Currency: Change signal to high for better triggering

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1834]
The Currency Spice isn't always displaying when it has a tab - we need to set the `signal: 'high'` for this IA so that it works for queries like these:

https://duckduckgo.com/?q=25+USD+in+DKK

------

https://duck.co/ia/view/currency

**Comment by altern8tif** [comment]
@moollaza I'm not able to replicate the triggering issue for me.  The IA still displays upfront using the query you mentioned.  Does this still need to be worked on?

**Comment by gokul1794** [comment]
@moollaza Same as @altern8tif , looks good to me!

**Comment by moollaza** [comment]
> The IA still displays upfront using the query you mentioned. Does this still need to be worked on?

I believe so, one of our team members had raised the issue and wasn't getting the Currency IA when he expected it.
