### ISSUE TITLE
Transit Switzerland: API not always providing platform, leads to bad result

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1835]
https://duckduckgo.com/?q=next+train+to+geneva+from+paris&ia=swisstrains

The footer in the IA shows "Platform " with no number because the API response doesn't contain one. We should check to make sure we have a platform, or show that one has not been assigned yet (I'm assuming that's the case?)

https://duckduckgo.com/js/spice/transit/switzerland/paris/geneva

/cc @tagawa @mattr555

**Comment by tagawa** [comment]
Thanks for spotting @moollaza. https://github.com/duckduckgo/zeroclickinfo-spice/pull/1842 is a simple fix.
