### ISSUE TITLE
Flights + Airlines: Move to moment.js

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1837]
There are a lot of date-related functions in airlines.js and route.js. Maybe it could be simpler if we use moment.js. Here's an example on how to use it: https://github.com/duckduckgo/zeroclickinfo-spice/blob/84bff0bfb0b277c38c5268d511eb70a5d783b24b/share/spice/get_events/get_events.js#L10

**Comment by moollaza** [comment]
@jagtalon that's being take care of in https://github.com/duckduckgo/zeroclickinfo-spice/pull/1736/files
