### ISSUE TITLE
Flights - Routes: should allow for "flights" in query

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1838]
"air canada phl to yyz" works, but "air canada flights from phl to yyz" does not.

https://duckduckgo.com/?q=air+canada+phl+to+yyz&ia=route

**Comment by javathunderman** [comment]
#228 and #217 Also related to this IA.

**Comment by zekiel** [comment]
can we close or take action on this @amoraleda ?

**Comment by amoraleda** [comment]
I wasn't aware of this issue but could be fixed easily. I'm on it!
