### ISSUE TITLE
Currency: "500 $ to php" should work as well.

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1847]
See https://github.com/duckduckgo/zeroclickinfo-spice/pull/1823#issuecomment-102351566 for more information. 

https://duck.co/ia/view/currency

**Comment by marianosimone** [comment]
@jagtalon this query and all variants I tried worked without issues

- https://duckduckgo.com/?q=%24500+to+php
- https://duckduckgo.com/?q=500%24+to+php
- https://duckduckgo.com/?q=500+%24+to+php

maybe this ticket can be closed ;)

**Comment by GuiltyDolphin** [comment]
@marianosimone @jagtalon Yeah, I've tried this out and it seems to be working fine. Re-open if it is still an issue.
