### ISSUE TITLE
Timer Spice Triggering too eager

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/zeroclickinfo-spice#1850]
Lo,

I don't think it should trigger on `Time::HiRes` as a query:
![image](https://cloud.githubusercontent.com/assets/978048/7677347/20722eb8-fd43-11e4-96ec-70a8b38b9432.png)

**Comment by mattr555** [comment]
Hi @mintsoft, probable duplicate of #1656? Does #1849 fix it for you?

**Comment by moollaza** [comment]
@mintsoft I just merged @mattr555 PR which should reign in the triggers. I beleive it solves this...

**Comment by moollaza** [comment]
Yup!

![codio_-_duckduckhack](https://cloud.githubusercontent.com/assets/873785/7705652/8756b7cc-fe13-11e4-8965-ffdf4fe370ff.png)

**Comment by mintsoft** [comment]
Cool thanks!
