### ISSUE TITLE
Stocks: Check when market is closed and grey out IA

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1854]
We can check whether the market is open using another API call (which means we'll need another Perl package for this new endpoint):

http://globalexchanges.xignite.com/xGlobalExchanges.json/IsExchangeOpen?Exchange=XNAS

If the market is closed, we should indicate that on the IA. Specifically, we should update the subtitle like so:

![aapl_at_duckduckgo](https://cloud.githubusercontent.com/assets/873785/7708316/c7e2588c-fe22-11e4-8047-04393f3fcdea.png)

------

IA Page: http://duck.co/ia/view/stocks

**Comment by moollaza** [comment]
Tackling this one myself because it's important...

**Comment by dronov** [comment]
:+1:
