### ISSUE TITLE
Currency sets z-index for flags

### ISSUE THREAD

**Issue by russellholt** [duckduckgo/zeroclickinfo-spice#1856]
and shouldn't.

http://duck.co/ia/view/currency

**Comment by jagtalon** [comment]
@russellholt could you give more context on this? Why is it not a good to have z-index set?

**Comment by moollaza** [comment]
@jagtalon I believe we've now seen that it interferes with the credits link (if the z-index of the IA is higher than additional content, it'll take precedence, hiding the other content)

**Comment by russellholt** [comment]
I think this is already fixed. #2054

**Comment by moollaza** [comment]
Yup!
