### ISSUE TITLE
SimilarSites: Border should be re-added and set to transparent

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1857]
We're about to make some internal changes to the spacing of the list elements. In order to preserve the intended spacing we need to change the CSS so that it sets `border-color: transparent` instead of removing the border.

------

IA Page: http://duck.co/ia/view/similar_sites

**Comment by jagtalon** [comment]
Fixed in https://github.com/duckduckgo/zeroclickinfo-spice/pull/1951
