### ISSUE TITLE
Stocks: "More At" link (Nasdaq) leads to page country-specific pagea with broken chart links

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/zeroclickinfo-spice#1859]
https://duck.co/forum/comment/56257 

//cc @moollaza  not sure if the corrected link (in my comment on duck.co) is avail via the api or that general situation so hoping you can help here

**Comment by moollaza** [comment]
@mintsoft @MrChrisW I'm unable to get the More At here to redirect me to Xignite's country specific pages -- even when I use a VPN. Can you check if you get re-directed to `xignite.com/au/` or `/gb/`?

If not then I'm not sure there's much we can do here, other than ask Xignite to fix their site.

**Comment by MrChrisW** [comment]
@moollaza No redirect for me. 
+ **Search MSFT**: https://duckduckgo.com/?q=MSFT&t=ffcm&ia=stock
+ **Click More At**: http://www.nasdaq.com/symbol/msft/real-time

**Comment by moollaza** [comment]
@MrChrisW thanks a lot for confirming!

**Comment by mintsoft** [comment]
@moollaza @MrChrisW Same here; I end up with http://www.nasdaq.com/symbol/msft/real-time and $

**Comment by moollaza** [comment]
@mintsoft thanks a lot for confirming, too!

**Comment by altern8tif** [comment]
@zekiel I suppose this can be closed?
