### ISSUE TITLE
Gravatar, Keybase, Zodiac, Twitter : Switch to Icon template group

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1864]
To Be Converted:

- [x] Gravatar (assigned to @altern8tif)
- [x] Keybase
- [ ] Zodiac (images assets: http://cl.ly/19171G2D2H21)
- [x] Twitter

---

We now have the [Icon template group](https://duck.co/duckduckhack/templates_overview#icon-template-group), which allows us to easily re-create the looks of these IA's without the need for any custom templates.

The icon template can display 3 lines of text if you specify the `title`, `subtitle` and `altsubtitle` accordingly.

The `subtitle` and `altsubtitle` can be a single string, or an `array` of `string`'s or `objects`. If an array is provided, the template will automatically separate the elements. To create separated links, an array of objects can be provided like so:

```js
normalize: function(item){
    subtitle: [{
        href: "https://website.com"
        text: "My Website"
    }, {
        href: "https://other.site.com",
        text: "Other Site"
    }, {
        'This 3rd element is plain text!"
    }]
```

This would produce:

```html
<a href="https://websitecom">My Website</a>
<span class="sep"></span>
<a href="https://other.site.com">Other Site</a>
<span class="sep"></span>
This 3rd element is plain text!
```

All of this is covered in detail in the [documentation](https://duck.co/duckduckhack/templates_overview#icon-template-group)

**Comment by altern8tif** [comment]
If no one is working on this, I don't mind helping out for the Gravatar spice...

**Comment by moollaza** [comment]
@altern8tif awesome! Thanks a lot :+1:

**Comment by altern8tif** [comment]
@moollaza while we're on this, I'm presuming the Twitter spice needs to be converted too?

**Comment by altern8tif** [comment]
Just another thought: 

Since the above spices always return a single result, wouldn't it be better to use the `basic_icon_detail` template instead of using the Icon template group?  The Icon template group seems more suited for IAs which return multiple results.

Pardon the ignorance.  Still feeling my way around here.

**Comment by altern8tif** [comment]
@moollaza done for Gravatar.  Let me know if this works.

![screen shot 2015-06-14 at 12 41 38 pm](https://cloud.githubusercontent.com/assets/5793364/8147163/db11454c-1292-11e5-84b8-cc1fb289039b.png)

**Comment by moollaza** [comment]
> I'm presuming the Twitter spice needs to be converted too?
@altern8tif yes! I totally forgot :smile:  -- looks like it could be greatly simplified thanks to the templates :+1:

**Comment by altern8tif** [comment]
Will work on Twitter as well then..

**Comment by sekhavati** [comment]
The Zodiac IA has been converted by [this PR](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1821). Hence it appears there is no more work to be done for this issue.
