### ISSUE TITLE
GoWatchIt: Should support the trigger "movie"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1865]
Currently this IA only triggers on "watch", we should also add support for the trigger "movie", e.g., "Skyfall movie"

------
IA Page: http://duck.co/ia/view/go_watch_it

**Comment by altern8tif** [comment]
This still doesn't work for me... It seems like "movie" is still listed as one of the `killwords` – I suppose that's the problem?

![screen shot 2015-06-22 at 9 44 44 am](https://cloud.githubusercontent.com/assets/5793364/8274382/5d7fae3e-18c3-11e5-81dc-17b0b8c35eb9.png)
