### ISSUE TITLE
RubyGems: Design broken, needs fixing & update

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1866]
The current IA has an issue, causing the footer text to overlap the body text: https://duckduckgo.com/?q=gem+nokogiri&t=ffab&ia=software

This IA should be updated to look just like the [SublimePackages Spice](https://github.com/duckduckgo/zeroclickinfo-spice/pull/1731).

The footer should also use the new `ddgsi-download` icon

**Comment by altern8tif** [comment]
Ran `master` branch on DuckPan server and everything seems to be fine.

![screen shot 2015-06-06 at 4 56 58 pm](https://cloud.githubusercontent.com/assets/5793364/8019048/2daae41a-0c6d-11e5-8810-58012ef88722.png)

Did some digging using Chrome Devtools and it seems like production code still shows css & js files prior to #1715.  The css file is causing the footer to overlap the body.

![screen shot 2015-06-06 at 4 57 20 pm](https://cloud.githubusercontent.com/assets/5793364/8019049/306acc38-0c6d-11e5-8cc8-4327dc2d546b.png)

**Comment by moollaza** [comment]
@altern8tif thanks for looking into this!

I'm still seeing it broken in production: 
![gem_nokogiri_at_duckduckgo](https://cloud.githubusercontent.com/assets/873785/8050519/08727d0e-0e3c-11e5-9c35-2a82ea10d29e.png)

The problem seems to be that we're setting a height for the body of the tile, which is clearly too small:

```css
.tile--ruby_gems .tile__body {
    height: 150px;
}
```
We should be able to solve this by removing the CSS file altogether -- I don't believe it's necessary.

**Comment by altern8tif** [comment]
The css file is already removed on the Rubygems spice on the master branch. But it's still broken in production.

Or am I looking in the wrong place?

**Comment by moollaza** [comment]
@altern8tif you're totally right. Seems like an internal bug; I'll make a task for the team. Thanks!

**Comment by altern8tif** [comment]
@moollaza this looks like it's been fixed :+1: Time to close the issue?

![screen shot 2015-06-16 at 11 30 30 pm](https://cloud.githubusercontent.com/assets/5793364/8186944/b927e7f8-147f-11e5-9b7a-1dde6673989b.png)

**Comment by moollaza** [comment]
@altern8tif yup, we noticed there was a bug and fixed it :+1:
