### ISSUE TITLE
DogoNews: Switch to new media template group, implement new design

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1867]
This IA should now be switched to use the the `media` template group so it can also display a picture.

Along with displaying a picture, the body of the IA should be updated to meet the new design:

![dogo-news-v1 3](https://cloud.githubusercontent.com/assets/873785/7801981/9589ccac-02fb-11e5-9bf7-6c4a5871ecf0.jpg)

/cc @dogomedia

**Comment by moollaza** [comment]
We'd love to see this one get converted!

**Comment by joe1chen** [comment]
@moollaza We've switch to using the media template and can get the thumbnail and the description to show.  Any tips on getting the footer to look like the screenshot that you have (with the little icons)?

**Comment by gokul1794** [comment]
@moollaza this can be closed?

**Comment by gokul1794** [comment]
@moollaza This is good to close too!

**Comment by moollaza** [comment]
@gokul1794 thanks!
