### ISSUE TITLE
Indeed Jobs: Implement new footer design

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1873]
We now have an optional `datebadge`property that can be specified for each tile's `item` (should be specified using the `normalize` function.

We need to add a `datebadge` to the Jobs Spice to better display the posting date for each job.

Live examples can be seen in the SeatGeek Spice: https://duckduckgo.com/?q=concerts+in+toronto&ia=concerts

Code example: https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/seat_geek/events_by_city/seat_geek_events_by_city.js#L153

------
IA Page:  http://duck.co/ia/view/indeed_jobs

**Comment by jagtalon** [comment]
@moollaza with a date, we kinda lose some resolution, right? 4 hrs ago, 8 hrs ago could all have the same date so we lose some information there.

**Comment by moollaza** [comment]
Yes, but if the job was posted within the past day or two, I'd say it's still "fresh" and worth considering. 

@abeyang and I looked at a few job sites and some of them use relative times, while others used the posting date. I think I slightly prefer relative dates, but Abe and I decided to try this. 

One thing I did just realize is that we tend to show a lot of results that were posted within 24 hours, so it may look funny.

@abeyang any thoughts on that?

**Comment by abeyang** [comment]
@moollaza that's a good point.. I guess we're only looking into "new jobs"? By default, when I go to Indeed, it shows me results that span across days.

In any case, I'm open to using the tiles that have the clock icon that indicate the relative time ago, like this one:

![sublime-v1 1](https://cloud.githubusercontent.com/assets/794084/8071070/9a2d93bc-0ebb-11e5-93aa-9745d24f0e3e.jpg)

**Comment by altern8tif** [comment]
@jagtalon @abeyang @moollaza so the decision is to stick with relative dates?

**Comment by abeyang** [comment]
Yes, let's use relative time (1min ago, etc).

**Comment by altern8tif** [comment]
@abeyang the live Sublime Text IA doesn't seem to have the clock icon.  Is that an icon font?

<img width="778" alt="screen shot 2015-07-19 at 2 03 40 pm" src="https://cloud.githubusercontent.com/assets/5793364/8764749/ffd39cac-2e1e-11e5-9d77-cd182a4bdeb4.png">

**Comment by abeyang** [comment]
@altern8tif The Sublime Package IA is being worked on concurrently as well. :smile: 

But yes, it's an icon-font.. you can see it here (`.ddgsi-clock`):
https://duckduckgo.com/styleguide

**Comment by cinlloc** [comment]
Have a new status on this issue? Relative time is already implemented on this so it should be only a matter of adding `ddgsi-clock` class to the result?

**Comment by abeyang** [comment]
@cinlloc @altern8tif Adding the clock, floating the date to the right, and adding the download icon.

**Comment by cinlloc** [comment]
@abeyang Suggested design does not fit actual tile size:
![selection_001](https://cloud.githubusercontent.com/assets/8652709/10497522/9f5a9bc2-72c6-11e5-8389-d8c85f4b789c.png)
Should increase tile width or review data to display (maybe remove "Updated" text?).
