### ISSUE TITLE
Movies: Detail pane broken? -- Console error for movies.js

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1875]
For some reason we're not showing the thumbnail in the detail pane for single item results (likely the `item_detail` template...)

There appears to be a console error in these cases...

https://duckduckgo.com/?q=the+lord+of+the+rings+return+of+the+king+movie&t=ffab&ia=movies
https://duckduckgo.com/?q=down+periscope+movie&t=ffab&ia=movies

**Comment by moollaza** [comment]
Looks like this line is the problem: https://github.com/duckduckgo/zeroclickinfo-spice/issues/1875

We didn't consider the single-item view and this needs to be adjusted accordingly.

/cc @jagtalon

**Comment by iambibhas** [comment]
@moollaza where does the `item.$html` come from? And where is `onItemShown` event documented?

**Comment by moollaza** [comment]
@iambibhas `item.$html` comes from some internal code, it's simply a reference to `$item` which is `$(item)`.

onItemShown should be documented in the events section...

**Comment by moollaza** [comment]
@iambibhas looks like this has been fixed in https://github.com/duckduckgo/zeroclickinfo-spice/pull/1884
