### ISSUE TITLE
Currency: Adding a currency code NIS

### ISSUE THREAD

**Issue by bluzername** [duckduckgo/zeroclickinfo-spice#1878]
Hi,

The commonly used abbreviation for ILS (Israeli Shekel) is NIS (New Israeli Shekel) which is currently not recognised by the Instant Answer "Currency".
Can we add "NIS" to "currencyNames.txt", or whatever is needed to make it work?

Cheers!

------

IA Page: https://duck.co/ia/view/currency

**Comment by iambibhas** [comment]
NIS is not an ISO 4217 currency code. Hence xe.com doesn't support it I think.
```
headers: {
encoding: "utf-8",
language: "en",
legal-warning: "Use of this service is subject to the terms of use at http://www.xe.com/legal/",
help-notice: "For help using this service, please see: http://www.xe.com/tmi/help.php",
utc-timestamp: "2015-06-11 19:32:20",
status: "4",
output-format: "json",
description: "ERROR: Invalid from_currency_symbol."
},
```

**Comment by moollaza** [comment]
@iambibhas that shouldn't matter if we add NIS as an alias of ILS though?

**Comment by iambibhas** [comment]
@moollaza how to add it as an alias?
