### ISSUE TITLE
NPM: Make sure we have dependencies to show before adding to InfoBox

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1881]
Looks like this module doesn't have any dependencies? Or potentially there's something else going on?

![npm_getconfig_at_duckduckgo](https://cloud.githubusercontent.com/assets/873785/7920537/c0530de6-086d-11e5-94e7-5743d2f2c2a4.png)

---

IA Page: https://duck.co/ia/view/npm

**Comment by altern8tif** [comment]
@moollaza This module does indeed have no dependencies.  Doesn't look like there's anything wrong with the NPM spice.

**Comment by moollaza** [comment]
>This module does indeed have no dependencies. Doesn't look like there's anything wrong with the NPM spice.

Whoops just saw this. If there's no dependencies, we shouldn't show that row in the InfoBox. This has been addressed in #1922
