### ISSUE TITLE
Currency: Support "X pounds in dollars"

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/zeroclickinfo-spice#1883]
Moved from: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1170

> Got a note on twitter that we're not converting in the form
> X pounds in dollars
> https://twitter.com/vectorvitale/status/605771245599064064/photo/1

https://duck.co/ia/view/currency

**Comment by jagtalon** [comment]
Maybe we can add it as an alias to GBP

**Comment by domjacko** [comment]
The issue with this is that not only the United Kingdom uses the term 'pound'. There's the Egyptian pound, Syrian pound etc. 
http://en.m.wikipedia.org/wiki/Pound_(currency)#Countries_currently_using_the_pound_or_similar

Hence why the aliases in the `currency/currencyNames.txt` file that include 'pound' have the nation in front of them.

**Comment by moollaza** [comment]
I think it's OK to assume "pound" means GBP, given that it's the most popular "pound". We handle "dollars" similarly and use USD.

**Comment by domjacko** [comment]
I've created a PR which just adds 'pounds' as an alias here:

https://github.com/duckduckgo/zeroclickinfo-spice/pull/1907

**Comment by moollaza** [comment]
@domjacko thanks!
