### ISSUE TITLE
Nutrition: Improve relevancy checking (too strict?)

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1885]
"protein in turkey bacon" and all other "protein in <food>" queries trigger the Nutrition IA, but we're not showing any results.

It looks like we're failing the relevancy check that we have in place and so they need to be revised to let these results through!

https://duckduckgo.com/?q=protein+in+turkey+bacon

------
IA Page: https://duck.co/ia/view/nutrition

**Comment by javathunderman** [comment]
Definitely noticed that sometimes the Nutrition IA is lacking sometimes...

**Comment by iambibhas** [comment]
The nutrition IA seems to have only one trigger - calories. Are the other triggers work because of deep triggering?

**Comment by iambibhas** [comment]
If I add protein to the triggers, above mentioned queries work locally 
![selection_044](https://cloud.githubusercontent.com/assets/357253/8144776/c6b402f2-120a-11e5-89af-cda7afeb521a.jpg)

**Comment by moollaza** [comment]
@jdorweiler did the Nutrition IA ever get a deep trigger? It seems like we could bring back some of the original, less ambiguous triggers and only allow them as `startend`

**Comment by jdorweiler** [comment]
@moollaza it does have a deep trigger.  You can try adding a few more trigger words but watch out for weird results.  The api was returning results for pretty much any query so things like "fiber glass" would return a result.

**Comment by moollaza** [comment]
@jdorweiler ah right, then it's just our relevancy checking that needs adjusting.

@iambibhas looks like the best way to fix is to revise the relevancy checking code.

**Comment by iambibhas** [comment]
@moollaza how to test this then? Because the mentioned queries work perfectly in local duckpan if I add `protein` to triggers.

**Comment by jdorweiler** [comment]
@iambibhas try typing protein and any other trigger words in the ddg search box.  See what autocomplete suggestions come up and try some of the ones that shouldn't show nutrition.  That was my method for finding weird queries :smile:

**Comment by MrChrisW** [comment]
@moollaza Do you still see relevancy issues with the Nutrition IA, if so can you provide some examples, I've attempted to replicate but am unable to.

**Comment by moollaza** [comment]
@MrChrisW I think we're OK for now. If more are found we can deal with them then.
