### ISSUE TITLE
BaconIpsum: not showing

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/zeroclickinfo-spice#1898]
------
IA Page:  http://duck.co/ia/view/bacon_ipsum

**Comment by moollaza** [comment]
Argh. Looks like the API is completely broken. It's returning tons of HTML along with the api response:

https://duckduckgo.com/js/spice/bacon_ipsum/4

**Comment by iambibhas** [comment]
@moollaza maybe it was a temporary bug on their side because it's working now.

**Comment by moollaza** [comment]
:+1:
