### ISSUE TITLE
SoundCloud: wrong id

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/zeroclickinfo-spice#1899]
https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/sound_cloud/sound_cloud.js#L24

`soundcloud` should be `sound_cloud`

------
IA Page:  http://duck.co/ia/view/sound_cloud

**Comment by jdorweiler** [comment]
This also needs to be fixed in the deep trigger and tests.

**Comment by tagawa** [comment]
Changed in the .js file but I can't see where it should be changed in the .pm file or test. Isn't this all that's needed?
