### ISSUE TITLE
TravisStatus: Change `spice to` endpoint to HTTPS

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#1905]
In the duck.co list this is listed as live but is currently not triggered with [travis status](https://duckduckgo.com/?q=travis+status)

**Comment by moollaza** [comment]
The IA is live and triggering, it seems that we're not getting a response from our internal API call though:

However, the API does seem to be live: https://www.traviscistatus.com/index.json and the IA is working for me in DuckPAN.

Possibly an internal bug/fix...

**Comment by tagawa** [comment]
Strange. Thanks for the explanation @moollaza.

**Comment by jagtalon** [comment]
@tagawa @moollaza problem here is that we have http://www.traviscistatus.com/index.json, but it's redirecting to https--our nginx config doesn't handle redirects so simply changing `spice to` to HTTPS should fix it.
