### ISSUE TITLE
Sunrise: Doesn't seem to work currently.

### ISSUE THREAD

**Issue by jkanarek** [duckduckgo/zeroclickinfo-spice#1924]
http://duck.co/ia/view/sun_rise_set

**Comment by altern8tif** [comment]
My mileage varies too.  I suppose it depends on what city/country you have entered in the search.

@jkanarek Perhaps you could share what your search input is, so that someone can cross check?

**Comment by moollaza** [comment]
Currently it only triggers for capital cities. We're going to increase the triggering internally.

**Comment by jkanarek** [comment]
Hmm yeah not even working for big cities.

**Comment by Gusgus01** [comment]
I would love to work making this better. I regularly need to add the city to my search in order to provide my actual city.

 Is there a preferred method of making this more compatible?
