### ISSUE TITLE
Seasons: Wrong dates for Southern Hemisphere!

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1927]
A user pointed out that our results for Australia (and the rest of the Southern Hemisphere are incorrect!)

https://twitter.com/nauzilus/status/609086192814923777

We incorrectly assumed that "summer" implies June, but the seasons depend on the hemisphere of the country. We need to be able to determine the hemisphere of the country we're working with in order to choose the correct solstice (June vs December).

/cc @mayo 

---

IA Page: https://duck.co/ia/view/seasons

**Comment by moollaza** [comment]
An interim fix for this would be to make a 2nd API call to Time&Date for the given country in order to get the Lat/Lon of it. Using that, we can determine the hemisphere and choose the right date.

**Comment by mayo** [comment]
@moollaza I've been pondering about this, but didn't have a chance to dig in. I think the DDG location API already gives lon/lat, so it shouldn't need a second request. We already use that to get the country name if none is specified.

I'll try to get a patch tonight.

**Comment by mayo** [comment]
Pull request https://github.com/duckduckgo/zeroclickinfo-spice/pull/1989

**Comment by moollaza** [comment]
IA is no longer live
