### ISSUE TITLE
GooglePlus: Content height causing border to overflow

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1928]
Looks like the CSS for this IA needs adjusting. The combination of set heights and padding is causing the border to overflow on highlight.

This needs to be fixed!

![google_plus_doug_at_duckduckgo_and_1____projects_zeroclickinfo-spice__ssh_](https://cloud.githubusercontent.com/assets/873785/8169733/7dfdd75c-1379-11e5-8548-a7bd62b0775c.png)

------
https://duck.co/ia/view/googleplus

**Comment by altern8tif** [comment]
Looks fine for me though.  [Mac OS X Yosemite 10.10.3, Chrome 43.0.2357.124]

![screen shot 2015-06-16 at 4 19 23 am](https://cloud.githubusercontent.com/assets/5793364/8169872/fa7eb61a-13de-11e5-92aa-0eceaaf845b9.png)

Only problem for me is that the "Showing x items" bar is overlapping the tiles.  Don't remember it being that way.  And it seems to be the same for other IAs when the tiles are expanded into a grid.

![screen shot 2015-06-16 at 4 22 09 am](https://cloud.githubusercontent.com/assets/5793364/8169910/50dcb19c-13df-11e5-91ff-acf53aa16b9b.png)

![screen shot 2015-06-16 at 4 27 09 am](https://cloud.githubusercontent.com/assets/5793364/8169993/0269e8da-13e0-11e5-949f-86163d888689.png)

**Comment by moollaza** [comment]
Hmm I'm using FF on Yosemite. Let's check Safari...

**Comment by moollaza** [comment]
Looks like it's only happening in FF, but in all cases the footer *is* overflowing and so addressing that should fix it for Firefox:

![g__doug_at_duckduckgo_and_googleplus__content_height_causing_border_to_overflow_ _issue__1928_ _duckduckgo_zeroclickinfo-spice](https://cloud.githubusercontent.com/assets/873785/8172681/2c9fa9d6-1391-11e5-8ad4-b79353006591.png)

![google__doug_at_duckduckgo_and_googleplus__content_height_causing_border_to_overflow_ _issue__1928_ _duckduckgo_zeroclickinfo-spice](https://cloud.githubusercontent.com/assets/873785/8172683/32af2eb4-1391-11e5-9999-c3ddf480ae4e.png)

![g__doug_at_duckduckgo](https://cloud.githubusercontent.com/assets/873785/8172693/50612840-1391-11e5-8d83-b85cae87aec4.png)

**Comment by altern8tif** [comment]
@moollaza is the `products_simple` template group deprecated?  I can't seem to find it on your DuckDuckHack documentation...

**Comment by moollaza** [comment]
@altern8tif it was previously deprecated, and we've temporarily brought it back. It will be replaced by the `Media` group.

**Comment by moollaza** [comment]
Spoke to the team and the Media group is ready to be used. If you wouldn't mind switching this one to the Media template it would be great. Otherwise I can merge this for now and make a new task.

There's a few others that need to be switched over to use Media (or at least not use products_simple anymore)
