### ISSUE TITLE
Currency: Should be triggered by symbol suffix

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#1930]
Currently the IA is triggered with ```₫1000000 to €``` but not ```1000000₫ to €``` (Vietnamese dong).

There are other currencies where the symbol can be used as a suffix rather than prefix, e.g. Japanese yen: 100円 (as well as ￥100).

**Comment by MrChrisW** [comment]
@tagawa To support the currency symbol triggering before the amount the regex `guard` will need to be updated on [line 46 Currency.pm](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Currency.pm#L46) to include `\p{Currency_Symbol}` after `$number_re`.

It doesn't look like the symbol 円 or 圓 are included [currencySymbols.yml](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/currency/currencySymbols.yml)

The UTF-16BE decimal values for the symbols will need to be added:
+ `20870: "jpy"`
+ `22291: "jpy"`

**Comment by kbhat95** [comment]
If no one's working on this, I'll take it up.

**Comment by MrChrisW** [comment]
@kbhat95 Go for it! :+1: Feel free to ping me when you've created a PR.

**Comment by kbhat95** [comment]
@MrChrisW what do I set the API key to?

**Comment by MrChrisW** [comment]
@kbhat95 DuckPan should failback to using the DuckDuckGo.com endpoint for the API if no API keys are found locally, so try just running it first. 

If you have troubles with that you can *temporarily* change the `spice to =>` value to
`https://duckduckgo.com/js/spice/currency/$1/$2/$2`

**Comment by kbhat95** [comment]
Okay, so it's using the DDG endpoint, but now I get this: ```500 Can't connect to ddh1.duckduckgo.com:443 (Connection refused)```.

**Comment by MrChrisW** [comment]
@kbhat95 Yes that's a known issue, I've just lodged a [issue](https://github.com/duckduckgo/p5-app-duckpan/issues/263) for that.

The current workaround is to modify [line 51 Currency.pm](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Currency.pm#L51)
>temporarily change the spice to => value to `https://duckduckgo.com/js/spice/currency/$1/$2/$2`

**Comment by kbhat95** [comment]
@MrChrisW okay, thanks.

**Comment by MrChrisW** [comment]
@kbhat95 Feel free to ping me if you have any further questions! Good luck :smile:

**Comment by MrChrisW** [comment]
@kbhat95 Thanks for the quick turnaround on these changes. Looking forward to any further contributions, as always feel free to ping me or any of the other DDG community members should you have any questions :+1:

Fixed by @kbhat95 in #1942
