### ISSUE TITLE
Twitter – Tidying up Spice code (template, trigger fails, latest tweet functionality)

### ISSUE THREAD

**Issue by altern8tif** [duckduckgo/zeroclickinfo-spice#1931]
The Twitter spice code looks rather messy.  Don't mind working on this, but thought I should consolidate some of the outstanding issues here for ease of reference.

- Switch to Icon Template Group – #1864
- Switch to latest Spice API – not in #1896 but should be referenced as well
- Results not showing latest tweet – Is it supposed to?  It only seems to be showing the account description and not the tweet.  If so, then description on IA page should be changed too.

Anything else to add?

Can someone also explain what `https://duckduckgo.com/tw.js` is?

***
IA Page: https://duck.co/ia/view/twitter

**Comment by MrChrisW** [comment]
@altern8tif Hey!

>Results not showing latest tweet – Is it supposed to? It only seems to be showing the account description and not the tweet. If so, then description on IA page should be changed too.

I don't believe the Twitter API is currently meant to show the users latest Tweet, just to show the users profile description. 

Regarding the changing of the [IA page](https://duck.co/ia/view/twitter) you can update the meta data for the IA on [line 9 Twitter.pm](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Twitter.pm#L9), then the metadata can be regenerated :+1: 

>Can someone also explain what https://duckduckgo.com/tw.js is?

As the [twitter api](https://dev.twitter.com/rest/public) requires the use of OAuth, which the Spice IA's do not support yet. DDG have created an internal proxy endpoint for the Twitter API at https://duckduckgo.com/tw.js

https://duckduckgo.com/js/spice/twitter/duckduckgo
