### ISSUE TITLE
RedditSearch: Unable to open new tab from SERP

### ISSUE THREAD

**Issue by mrzod** [duckduckgo/zeroclickinfo-spice#1936]
http://duck.co/ia/view/reddit_search

When I click a new result, it doesn't open. I am using CTRL + left mouse click.

Would be better if users are able to open multiple tabs from the results page. Thank you.

**Comment by moollaza** [comment]
@mrzod thanks for making this issue!

To clarify, are you saying that when you Ctrl+Click the Reddit tiles, it's not opening the site in a new tab?

If so, what browser and OS are you using? Right now that's working, as expected for me on Firefox 38 on OSX.

**Comment by mrzod** [comment]
Thank for making this add on and also thank you for getting back to me.
Using Win 8 and Chrome doesn't seem to work for me. Odd.

**Comment by mrzod** [comment]
It appears to work. I just tried it out today, please disregard / close my
ticket.

On Fri, Jun 19, 2015 at 12:15 PM, Jay Wong <jywong@tepper.cmu.edu> wrote:

> Thank for making this add on and also thank you for getting back to me.
> Using Win 8 and Chrome doesn't seem to work for me. Odd.
> On Jun 19, 2015 10:50 AM, "Zaahir Moolla" <notifications@github.com>
> wrote:
>
>> @mrzod <https://github.com/mrzod> thanks for making this issue!
>>
>> To clarify, are you saying that when you Ctrl+Click the Reddit tiles,
>> it's not opening the site in a new tab?
>>
>> If so, what browser and OS are you using? Right now that's working, as
>> expected for me on Firefox 38 on OSX.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/duckduckgo/zeroclickinfo-spice/issues/1936#issuecomment-113536392>
>> .
>>
>


-- 
LinkedIn: www.linkedin.com/in/heyjay
Email: jywong@tepper.cmu.edu

**Comment by moollaza** [comment]
>It appears to work. I just tried it out today, please disregard / close my ticket.

@mrzod glad to hear it's working! Thanks again
