### ISSUE TITLE
Timer shouldn't trigger on "five-alarm" query

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/zeroclickinfo-spice#1937]
https://duckduckgo.com/?q=five-alarm&ia=timer seems out of place!

**Comment by gokul1794** [comment]
should this IA be triggered only with "alarm"?

**Comment by moollaza** [comment]
@gokul1794 nope. Take a look at the code and tests. There's a bunch of queries we want it to work for. this just isn't one of them ;)

**Comment by gokul1794** [comment]
@moollaza `/^time($|[^r ][\S]+$)|five-/i` should do the trick right?
