### ISSUE TITLE
SublimePackages: should strip "for" from query

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1944]
This IA is not yet, live, but will be soon!

During some final testing I noticed that the query "sublime text packages for json" triggers and returns decent results, but the API call we make sends "for json" as the search term, when it should really be "json".

Let's strip any potential filler words from the query.

------
IA Page: https://duck.co/ia/view/sublime_packages

**Comment by MrChrisW** [comment]
@moollaza Any other words that need to be filtered? 7e1d2e7

**Comment by moollaza** [comment]
@MrChrisW none that I can think of right now. Actually, I see some queries come up through auto-complete that mention the version of sublime text. That might be a separate problem because I don't think we can specify that to the API?

**Comment by MrChrisW** [comment]
@moollaza It looks like we can specify the version using the search term :`st2` or `:st3` also operating system `:win` `:osx` `:linux`

I'll add this functionally :+1:

**Comment by jagtalon** [comment]
Fixed in #1953
