### ISSUE TITLE
Stocks: Convert to use new moreAtText property

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1946]
We now have a "moreText" property which can be defined in `meta.option`. We should use is here so the template doesn't have to manually create the More at link anymore:

Example
```js
id: ...,
name: ...,
meta: {
   ...
   options: {
      moreText: {
        url: "https://website.com",
        text: "Link text"
      }
   }
}
```

------

Documentation will be live shortly. PR here: https://github.com/duckduckgo/duckduckgo-documentation/pull/269

**Comment by jagtalon** [comment]
Fixed by #1949
