### ISSUE TITLE
HackagePackages: Find new data source, re-implement IA with templates

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1950]
This IA was using a JSON file hosted on GitHub as it's source. The file has since been removed so I've taken the IA offline as it is now throwing a console error.

This IA should be revamped entirely. Let's use a more official data source that allows for actual package search so we don't have to dig through a large JSON file each time the IA triggers.

Once we have the API figured out, this IA should be re-implemented using our built-in templates. There no reason this one should need a custom template anymore :+1: 

------

IA Page: https://duck.co/ia/view/hackage

**Comment by altern8tif** [comment]
@moollaza I'm not too familiar with Haskell but [this](https://hackage.haskell.org/api) looks like the official API from Hackage/Haskell.  Reckon we can use it?

**Comment by cskksc** [comment]
[Hayoo](http://hayoo.fh-wedel.de/) looks better. It supports json responses whereas hackage responses mostly are html.

**Comment by cskksc** [comment]
I've created a IA which uses the [Hoogle](https://www.haskell.org/hoogle/) as its data source. It is running on [codeio](http://twist-joker.codio.io:5000/). A couple of things are still to be done, like writing tests, improving sort order by correct version comparisions etc. This is my first contribution to any IA so please let me know if I'm on the correct path. Here's a [diff](https://github.com/duckduckgo/zeroclickinfo-spice/compare/master...cskksc:bugfix_hackage?expand=1) of the code I've written so far. I'll raise a PR once all the todo's are done.

**Comment by jagtalon** [comment]
Fixed by @cskksc in #1977
