### ISSUE TITLE
BrainyQuote: Don't trigger on queries containing "stock quote"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1952]
In testing the Stock IA, I noticed that brainy quote triggers for any query that has "quote" and so it triggers on queries containing "stock quote" as well.

We should detect this in the `handle` function and bail early to prevent redundant API calls.

------
https://duck.co/ia/view/brainy_quote

**Comment by iambibhas** [comment]
What if someone is looking for stock related quotes? There are plenty of them http://www.brainyquote.com/search_results.html?q=stock

**Comment by altern8tif** [comment]
In my opinion, we could leave both Stocks and Quotes IAs as possible answers.

Maybe we could give a higher priority if the query remainder matches a particular stock ticker? Otherwise it returns the Quotes IA as higher priority.

Then at least the user can select which IA he is interested in if the IA returned is not what he is looking for.

I hope this makes sense.

**Comment by moollaza** [comment]
I really don't think anyone would use the term "stock quotes" when searching for "quotes about stocks"

We could be a little more granular when checking the query, but pretty much anything that matches `/\w+ stock quotes?/` is almost surely a check for a company's stock price.

>Maybe we could give a higher priority if the query remainder matches a particular stock ticker? Otherwise it returns the Quotes IA as higher priority.

@altern8tif the only problem with that is we'd need a list of all stock symbols in the Perl, which is possible but IMO overkill. I'm confident we can rely on heuristics. 

If we get feedback from users complaining they're not getting the right results we can revisit, but this should save us from making a ton of useless API calls. Stocks are a much more popular topic.

Separately, the triggering for the BrainyQuotes IA could use some improving. Queries like "quotes on/about" or "quotes by" should be better handled. I would search "quotes about stocks" personally because I know the term "stock quotes" is probably going to give me results for stock prices. Looking at the organic results, they're all about stock prices.

Similarly, https://duckduckgo.com/?q=quotes+about+stocks has an organic result from Brainy Quote
