### ISSUE TITLE
Pokedex - need better "more at" url

### ISSUE THREAD

**Issue by iambibhas** [duckduckgo/zeroclickinfo-spice#1969]
Right now the "more at pokeapi.co" links pokeapi.co, without any permanent url for the specific pokemon. That page just shows how to call the api. It's kind of useless. We could probably link it to bulbapedia.

Also, the name of the pokemon being searched is linked to that search page itself. E.g. searching for Machop hyperlinks the name Machop to https://duckduckgo.com/?q=pokemon+machop&t=canonical&ia=pokedex&iax=1. We could avoid doing that. It's no help at all. Linking the pokemon they evolve to, to the duckduckgo search page is fine.

/cc @AkA84

**Comment by moollaza** [comment]
@iambibhas I agree on a better "More at" link. We should use the new `moreText` property to give credit to the data source as well, like we do for the Stocks IA: https://duckduckgo.com/?q=appl+stock&ia=stock

**Comment by gokul1794** [comment]
We can use the official link http://www.pokemon.com/us/pokedex/
Is anyone working on it yet?

**Comment by MrChrisW** [comment]
@gokul1794 No one has taken this up yet.

Looks like we could easily do 
`sourceUrl: 'http://www.pokemon.com/us/pokedex/<pokemon name>'`

However we'd need to check if this is allowed? @moollaza

**Comment by iambibhas** [comment]
Bulbapedia has more data than the official pokemon site and less resource hungry, it's also the go-to website for any kind of info on pokemons. We could probably mention both. I think if it's helping the user who's searching, it should be allowed.

**Comment by AkA84** [comment]
@iambibhas sorry for not having been able to look at this!
@moollaza I noticed that I'm not credited on the IA info, how can I change that? Thanks!

**Comment by moollaza** [comment]
>I noticed that I'm not credited on the IA info, how can I change that? Thanks!

@AkA84 apologies! I will fix that right now. Do you have a duck.co account?
