### ISSUE TITLE
AA 102 not triggering IA

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/zeroclickinfo-spice#1974]
AA 102 doesn't trigger flights IA (yet that's the test query on the IA page)

http://duck.co/ia/view/airlines

**Comment by MrChrisW** [comment]
@chrismorast I think we can blame @tommytommytommy for this one :stuck_out_tongue_winking_eye: he disabled triggers in #1843 in favor of internal triggers. 

It looks like the reason [`AA 10`](
https://duckduckgo.com/?q=AA+102&ia=airlines) does not trigger is there's no flight tracking site contained in the SERP, where as with the query [`AA102`](
https://duckduckgo.com/?q=AA102&ia=airlines) there is.

**Comment by tommytommytommy** [comment]
Yeah! That's right. And sad. :-(

@MrChrisW Any thoughts on writing a keyword-based trigger for airlines using the airline codes for the Flights::Route Spice? We turned it off because of overtriggering, but at that point I THINK we were doing a reg-ex based trigger...

**Comment by MrChrisW** [comment]
Hey @tommytommytommy ! It looks like Airlines was using a regex trigger with the airlines codes as a sort of trigger guard. 

Do you have any example triggers (queries) that were over triggering this IA?

**Comment by tommytommytommy** [comment]
I don't have examples for this, but if I remember correctly, we were using a regex trigger, guarding against names on the periodic table, and making an upstream request with everything else.

**Comment by moollaza** [comment]
This looks to be fixed. "AA 102" and "flight aa102" both trigger for me. The example queries have also been updated.
