### ISSUE TITLE
IA for INDIA is showing an music album name

### ISSUE THREAD

**Issue by abhijainn27** [duckduckgo/zeroclickinfo-spice#1997]
The IA for India shows an answer for an album named INDIA instead f the country INDIA which is on the top of the wikipedia search.

**Comment by MariagraziaAlastra** [comment]
Hey @abhijainn27, thanks for spotting that! However, could you open an issue in the [zeroclickinfo-longtail repo](https://github.com/duckduckgo/zeroclickinfo-longtail/issues) instead?
The Wikipedia IA you're talking about is, in fact, not a Spice, but a Longtail. Thanks!

**Comment by abhijainn27** [comment]
Oh ok. Thanks! for the information @MariagraziaAlastra . I have opened an issue there.

**Comment by MariagraziaAlastra** [comment]
No problem @abhijainn27! Thank you, closing this :)
