### ISSUE TITLE
Developer's name is missing

### ISSUE THREAD

**Issue by sagarhani** [duckduckgo/zeroclickinfo-spice#2004]
Developer's name for the IA [Playing Cards](https://duckduckgo.com/?q=deal+5+cards&ia=answer) :black_joker:  is missing. It should have been @kbhat95's name.

-----
IA Page: https://duck.co/ia/view/playing_cards

**Comment by moollaza** [comment]
@jdorweiler the correct metadata exists on the IA page, but it was added after this IA went live (by me, once the dev noticed). I assume after another release of the metadata, this will fix itself?

**Comment by jdorweiler** [comment]
@moollaza that's right.

**Comment by moollaza** [comment]
Fixed :+1:
