### ISSUE TITLE
Whois: Omits digits from domain name

### ISSUE THREAD

**Issue by altern8tif** [duckduckgo/zeroclickinfo-spice#2005]
Noticed that searches for domain names with digits in them always omit the digits in their query to the api endpoint.

Also, the `whois refinery29.com` query returns the Images IA over the Whois IA.  How does the DDG backend determine which IA takes priority?

![screen shot 2015-07-07 at 5 42 29 pm](https://cloud.githubusercontent.com/assets/5793364/8543482/920ff0a6-24cf-11e5-9170-6ae847b268cc.png)

![screen shot 2015-07-07 at 5 40 31 pm](https://cloud.githubusercontent.com/assets/5793364/8543441/4d47a554-24cf-11e5-90af-edec63c3d216.png)

------
IA Page:  http://duck.co/ia/view/whois

**Comment by moollaza** [comment]
>Also, the whois refinery29.com query returns the Images IA over the Whois IA. How does the DDG backend determine which IA takes priority?

There's a few different signals, we have backend priority/ordering, frontend priority, (e.g. `signal: 'high'`) and also based on who returns faster (so Spice's are at a slight disadvantage as we need to wait for API responses + JS execution)
