### ISSUE TITLE
"apps like branch.io" should not trigger the weather IA

### ISSUE THREAD

**Issue by gokul1794** [duckduckgo/zeroclickinfo-spice#2006]
This should definitely not trigger the forecast IA 
![wrongtrigger](https://cloud.githubusercontent.com/assets/6311809/8543731/a32bfe92-24bc-11e5-947c-5ab08d93a2fe.png)

**Comment by altern8tif** [comment]
@gokul1794 Looks fine to me. Although IMO a search like this should trigger the [Quixey IA](https://duck.co/ia/view/apps).

![screen shot 2015-07-07 at 6 09 13 pm](https://cloud.githubusercontent.com/assets/5793364/8543915/517d4c60-24d3-11e5-8cb4-192f24fd3be7.png)

**Comment by gokul1794** [comment]
@altern8tif Yes, this does not happen to me on Incognito(Chrome) but not the normal one. How weird o.O

**Comment by altern8tif** [comment]
@gokul1794 Chrome extensions (by default) don't run in incognito mode.  So if you see the bug in normal mode but not incognito mode, it probably means that one of your extensions is causing the problem.

Might be worth trying on Firefox/Safari/IE to see if it's a browser issue as well...

**Comment by gokul1794** [comment]
@altern8tif Ahh doesn't happen so on firefox, might be a browser issue! I probably should have tried it on all before opening an issue..

**Comment by moollaza** [comment]
@gokul1794 thanks for reporting, do you have a region setting set?

>@gokul1794 Looks fine to me. Although IMO a search like this should trigger the Quixey IA.

Quixey is actually down right now (they had API problems), but it's slated to come back online soon, so I expect it will trigger for this query.

>@altern8tif Ahh doesn't happen so on firefox, might be a browser issue! I probably should have tried it on all before opening an issue..

That's very odd. This IA in this case should be triggering based on the organic links -- can you send me a pic that includes the fist few?

**Comment by moollaza** [comment]
Looks like Quixey is back already :)

![apps_like_branch_io_at_duckduckgo](https://cloud.githubusercontent.com/assets/873785/8558140/43fce990-24d0-11e5-9755-6aa104d79de0.png)

https://duckduckgo.com/?q=apps+like+branch.io&ia=apps

**Comment by moollaza** [comment]
With my region set to India i'm seeing the weather tab, but Quixey is taking precedence as it should.  I'll let the team know
