### ISSUE TITLE
Similar Websites: 'Similar Site' to... (singular) doesn't trigger the IA

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/zeroclickinfo-spice#2024]
Can we add 'similar site' as a trigger?

------
IA Page:  http://duck.co/ia/view/similar_sites

**Comment by moollaza** [comment]
I think we should also allow "alternative(s) to" as a trigger:

E.g. [alternatives to craigslist.com](https://duckduckgo.com/?q=alternatives+to+craigslist.com)

**Comment by gokul1794** [comment]
@moollaza should i add "alternative(s) to"?

**Comment by moollaza** [comment]
@gokul1794 sure!
