### ISSUE TITLE
Similar Websites: Change line height to 1.2

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/zeroclickinfo-spice#2025]
I'm still seeing content getting clipped (see Bebo in the list) - can we override the template line height and adjust it to 1.2 (for this IA only)? That value fixes the issue.

![screen shot 2015-07-10 at 9 19 17 am](https://cloud.githubusercontent.com/assets/7061920/8623206/003d6b46-26e5-11e5-90f4-2094138c2d1b.png)

------
IA Page:  http://duck.co/ia/view/similar_sites

**Comment by altern8tif** [comment]
@moollaza Should be good to close this issue.

**Comment by moollaza** [comment]
@altern8tif yup, thanks :+1:
