### ISSUE TITLE
Snow: "More info" links not clickable when snowing, source needs to be updated

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#2036]
Steps to reproduce:
1. Go to https://duckduckgo.com/?q=is+it+snowing+in+ushuaia&ia=answer (or somewhere else where it's likely to be snowing now)
2. Try to click on the information icon or "More at ..." link.

What should happen:
The links should be clickable

What actually happens:
The animated snow layer is on top of the content box, making it not possible to interact with it.

------
IA Page:  http://duck.co/ia/view/snow

**Comment by moollaza** [comment]
@tagawa thanks for reporting! We've set the IA to be taken down for now.

**Comment by moollaza** [comment]
IA has been removed
