### ISSUE TITLE
Rhymes spice down/throwing console error

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#2037]
https://duckduckgo.com/?q=rhymes+with+duck
<img width="1035" alt="screen shot 2015-07-15 at 9 12 05 am" src="https://cloud.githubusercontent.com/assets/126358/8699289/82e50630-2ad2-11e5-99b2-884ec3f9850b.png">

**Comment by moollaza** [comment]
Fixed in #2038
