### ISSUE TITLE
Air Quality Index: Wrong location / zip code match

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/zeroclickinfo-spice#2042]
The zip code '96161' is Truckee, CA but it's being shown as Tahoe City (which is 96146)
![screen shot 2015-07-16 at 2 34 05 pm](https://cloud.githubusercontent.com/assets/7061920/8735702/bbfc72a0-2bc7-11e5-8684-d89078bac472.png)

**Comment by altern8tif** [comment]
@chrismorast Can't really tell the real reason without looking at the JSON file but I suspect that the agency responsible doesn't have data specific to that zip code so it returns the general area instead.

>**What is the relationship between reporting areas and zip codes?**
>The air quality agency responsible for a reporting area assigns one or more zip codes to be associated with that area.

Source: [Air Now API](http://airnowapi.org/faq#reportingAreaZipCodes)

Perhaps there is a way we can show the zip code queried, but indicate that the closest data is from so-and-so area.  Then again, this depends on what is returned via the JSON.

**Comment by chrismorast** [comment]
Thanks for looking into it @altern8tif - I'll circle up with @moollaza to see about the JSON file.

**Comment by moollaza** [comment]
@chrismorast @altern8tif 

Unfortunately, the API and data it returns is pretty rudimentary:

```json
[
    {
        "DateObserved": "2015-07-31 ",
        "HourObserved": 21,
        "LocalTimeZone": "PST",
        "ReportingArea": "Truckee",
        "StateCode": "CA",
        "Latitude": 39.3386,
        "Longitude": -120.1703,
        "ParameterName": "PM2.5",
        "AQI": 48,
        "Category": {
            "Number": 1,
            "Name": "Good"
        }
    }
]
```

We're basically at the will of the API, and trust that it provides relatively accurate info.

**Comment by moollaza** [comment]
Wait a sec, that response looks correct! I'm seeing "Truckee" on the site right now @chrismorast https://duckduckgo.com/?q=aqi+96161&t=ffab&ia=airqualityindex

Are you?

**Comment by altern8tif** [comment]
@moollaza @chrismorast it looks alright for me too now... Weird

**Comment by chrismorast** [comment]
strange, I don't see anything now.

![screen shot 2015-09-01 at 1 38 31 pm](https://cloud.githubusercontent.com/assets/7061920/9615705/c901be40-50ae-11e5-88fa-caa273e62036.png)

**Comment by moollaza** [comment]
@chrismorast still happening? Seems to be working for me today

**Comment by chrismorast** [comment]
Yup! Looks like it's working now
