### ISSUE TITLE
PeopleInSpace: decrease or eliminate z-index

### ISSUE THREAD

**Issue by russellholt** [duckduckgo/zeroclickinfo-spice#2053]
setting the z-index so high conflicts with other answerbar elements.
set it low, like 2, or find a better way to line up the flags without using z-index.

------
http://duck.co/ia/view/people_in_space

**Comment by jagtalon** [comment]
![screen shot 2015-07-24 at 12 20 15 pm](https://cloud.githubusercontent.com/assets/81969/8879267/635483e4-31fe-11e5-9b1f-7f263b2ecad1.png)

**Comment by mattr555** [comment]
Is this fixed with af3769f?

**Comment by russellholt** [comment]
Looks like it, @mattr555
