### ISSUE TITLE
Bible: HTML encoding in API response

### ISSUE THREAD

**Issue by cotto** [duckduckgo/zeroclickinfo-spice#2055]
The instant answer for hosea 11:9 shows some mojobake:

I cannot carry out my fierce anger! I cannot totally destroy Ephraim! Because I am God, and not man &#8211; the Holy One among you &#8211; I will not come in wrath! 

------
IA Page:  http://duck.co/ia/view/bible

**Comment by jagtalon** [comment]
Thanks! We get those entities rendering properly.

**Comment by cotto** [comment]
Yeah.  That was github being helpful.  Here's a screenshot in Chrome 43.0.2357.134 on Windows.  I saw the same thing in Firefox nightly on Linux.
![untitled](https://cloud.githubusercontent.com/assets/57991/8880001/3b5d48ee-31ea-11e5-8f40-18a4d4f8ce41.png)

**Comment by MrChrisW** [comment]
@cotto Thanks for reporting this.

** Issue**
The API is returning [HTML entities](https://duckduckgo.com/?q=html+entities) 

See: https://duckduckgo.com/js/spice/bible/hosea%2011%3A9

**Fix:**
Use [`stripHTML`](https://duck.co/duckduckhack/handlebars_helpers#codestriphtmlcode) in [handlebars template](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/bible/content.handlebars)

**Notes** This API should moved away from the `base` template group: https://github.com/duckduckgo/zeroclickinfo-spice/blob/ed05efa4152f627dd3e54821bca2eb563d105192/share/spice/bible/bible.js#L22

**Comment by iambibhas** [comment]
@MrChrisW `#stripHTML` doesn't work. Handlebars can't decode HTML entities. Have to do it in JS, something like this - 

    var text = $('<textarea />').html(data.text).text();

**Comment by MrChrisW** [comment]
@iambibhas That's correct :+1: Thanks for the clarification. In reality the API shouldn't be passing HTML entities.
