### ISSUE TITLE
RandWord: Allow "random words", use `randomWords` API endpoint

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2062]
Right now the Rand Word Spice only returns a single, random word. We don't show anything for queries like "random words" or "5 random words", etc.

We can easily extend this IA to provide more than one word when requested. We should switch to the `/randomWords` endpoint to allow for this. http://developer.wordnik.com/docs.html#!/words/getRandomWords_get_3

------
IA Page:  http://duck.co/ia/view/rand_word

**Comment by iambibhas** [comment]
@moollaza do we have any test api key for wordnik?

**Comment by moollaza** [comment]
> @moollaza do we have any test api key for wordnik?
Sorry just saw this -- we don't have test keys for any of the API's. We just have the one we use in production.
