### ISSUE TITLE
Currency: Infer local currency from Region when set, otherwise show tile view

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2069]
Should fix #2074 and #2045

Currently we show a special tile view when only the name of a currency is search, or when the amount is `1`. E.g. "usd" or "1 cad".

We should update the IA to use the currency for the user's selected region (when a region is selected) and default to show the tile view whenever the "TO" currency is not specified. So "$12 USD" should also produce a conversion to $CAD if my region is set to Canada, and a tile view when no region is set.

For the tile view, we may need to widen the tiles for very large numbers, but we can deal with that once we have a PR.

---

IA Page:  http://duck.co/ia/view/currency

**Comment by MrChrisW** [comment]
@moollaza The users region setting is provided by the js object `DDG.settings.region` right? 

So a second request would need to be made in order to query the API with the users `region` setting?

We can't use the `$loc` function as this gets the users location based on IP, not region setting.

**Comment by moollaza** [comment]
@MrChrisW whoops, you're totally right, I overlooked that :frowning: 

Let me see if we can expose the region setting to the Perl...

**Comment by moollaza** [comment]
I've made a task to see if we can expose this to the Perl. For now this task will have to wait.

**Comment by MrChrisW** [comment]
@moollaza Any update on exposing the `DDG.settings.region` setting?

**Comment by moollaza** [comment]
> @moollaza Any update on exposing the DDG.settings.region setting?

Nothing yet. Will post here when I have something :+1:

**Comment by moollaza** [comment]
The IA now does this.
