### ISSUE TITLE
GoWatchIt: Should ignore the query "pocket watch"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2070]
Unfortunately the query "pocket watch" triggers this IA and get's past our relevancy checking. 

https://duckduckgo.com/?q=pocket+watch&t=ffab&ia=watch

We may need to adjust the relevancy checking threshold to consider all words with 3+ characters, but it may be best to simply check if the query matches this term and if so, `return;`

------
IA Page:  http://duck.co/ia/view/go_watch_it

**Comment by iambibhas** [comment]
I wonder why it doesn't trigger for `apple watch`?

**Comment by moollaza** [comment]
> We should probably add these words to a stopwards list in backend.
@iambibhas yup that's what I meant for us to do :+1:  We can make a hash in the Perl and verify the query doesn't match it.
