### ISSUE TITLE
Dogo News: Minor CSS adjustments

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2072]
The design team would like some changes to be made: 

1. Adjust the bottom-margin to `0.8em` (or remove the rule altogther if it's the same)
2. Reduce the height of the snippet to 6.2em
3. Reduce the title margin-bottom to .5em

Should look like:
<img width="814" alt="download_asset" src="https://cloud.githubusercontent.com/assets/873785/9076666/632f1138-3af3-11e5-9d94-db4a14e4e53a.png">

------
IA Page:  http://duck.co/ia/view/dogo_news

**Comment by pecey** [comment]
@moollaza Is this still open?

**Comment by moollaza** [comment]
@pecey yes! It was never fixed
