### ISSUE TITLE
Currency: should use selected region for unspecified To-currency

### ISSUE THREAD

**Issue by unhammer** [duckduckgo/zeroclickinfo-spice#2074]
To reproduce, select region:Norway and search for "£42"

Actual output: $something

Expected output: NOK something

------
IA Page:  http://duck.co/ia/view/currency

**Comment by moollaza** [comment]
@unhammer thanks a lot for the input. I'll pass this to the team for consideration!

**Comment by MrChrisW** [comment]
@unhammer Thanks you for the suggestion! this is currently being addressed in #2069 - although there's not much process at this stage. I'll close this as a duplicate.Thanks!
