### ISSUE TITLE
Timer: visual modifications

### ISSUE THREAD

**Issue by abeyang** [duckduckgo/zeroclickinfo-spice#2077]
@andrey-p , timer is almost there! Here are several comments to improve it visually and experientially. /cc @chrismorast 

First, by default, I think we should set it at 1:00, like so (also note that the outer ring, `.progress`, is a lighter gray, `#eee`):

![image](https://cloud.githubusercontent.com/assets/794084/9143545/f993deb0-3cfb-11e5-9b01-89ea3c71abce.png)

Second, as the timer is going, the Title should **not** have the input field behind it, like so:
![image](https://cloud.githubusercontent.com/assets/794084/9143594/382719e4-3cfc-11e5-94c1-30a10396662e.png)

However, **on hover** we should be able to see the input field behind the title, and it should be **editable**.

 Moreover, we need to align the fields a bit:

```css
.zci--timer .time_display {
  margin-top: -1.6em;
  margin-left: .3em;
}
```

Third, the +1 should look more like Chris' design -- LMK if you want css help with this:
![image](https://cloud.githubusercontent.com/assets/794084/9143916/1eda3154-3cfe-11e5-85fd-605f398b59af.png)

Fourth, the progress ring inside seems a bit off... like a couple of pixels to the top, and a couple of pixels to the left. We'll need to fix that... this is what it looks like at 800%..
![image](https://cloud.githubusercontent.com/assets/794084/9143977/95099afe-3cfe-11e5-8c4e-70a3d8f54e17.png)

A few more soon to come..

**Comment by mattr555** [comment]
Woah, this looks really cool (commenting to follow, lmk if you need my help with the old code)

**Comment by andrey-p** [comment]
Hey @abeyang, I'm moving the discussion to a PR so we can comment on this as I add new bits to it. I'll implement this round of changes shortly.

@mattr555 I've cc'd you there :)
