### ISSUE TITLE
Forecast: FR - not working with every city

### ISSUE THREAD

**Issue by arochedy** [duckduckgo/zeroclickinfo-spice#2086]
Hi, 

The weather instant answer is great but for french people it does'nt work every time. 

For example : 

"meteo paris" works
but "meteo lyon" doesn't work !
("weather lyon works fine !" 

---

IA Page:  http://duck.co/ia/view/forecast

**Comment by moollaza** [comment]
@arochedy thanks for reporting!

It looks like it's working for me right now... Do you have a region set?
<img width="1437" alt="meteo_lyon_at_duckduckgo" src="https://cloud.githubusercontent.com/assets/873785/9211203/8ece9d94-404e-11e5-86b7-0d9452ad8c6b.png">

**Comment by arochedy** [comment]
I try again today : with a region (france ) it doesn't work with paris too ! 

![image](https://cloud.githubusercontent.com/assets/2261478/9221117/1656f420-40e8-11e5-94c2-3a3e10b9ac9f.png)

without region it doesn't work with "meteo lyon" but work fine for "meteo paris" 

![image](https://cloud.githubusercontent.com/assets/2261478/9221107/fabaa8c4-40e7-11e5-9990-6a44a078b245.png)

**Comment by arochedy** [comment]
with canada in region it works fine for paris, lyon and marseille (but not with lille or strabourg for example)

**Comment by moollaza** [comment]
@arochedy for now I think this will be considered a tolerated bug as we don't really have non-english triggering for Instant Answers yet. If you search "weather lyon" you should get the correct result.

We do plan to internationalize Instant Answers and will make an issue for the team to investigate this further.

![weather_lyon_at_duckduckgo](https://cloud.githubusercontent.com/assets/873785/9316594/ffd2b912-4503-11e5-826c-567c3c15534c.png)
