### ISSUE TITLE
Quandl HomeValues: doesn't work when query is in the form "home values in [state|zip code]"

### ISSUE THREAD

**Issue by PalmerAL** [duckduckgo/zeroclickinfo-spice#2090]
If the search term is in the form "home values in [state]", the result shown is for Indiana no matter what state is entered.
Examples:
https://duckduckgo.com/?q=home+values+in+california&ia=homevalues
https://duckduckgo.com/?q=home+values+in+new+york&ia=homevalues

However, the above search terms work if the word "in" is removed.

------
IA Page:  http://duck.co/ia/view/quandl_home_values

**Comment by moollaza** [comment]
@PalmerAL thanks a lot for reporting! 

/cc @brianrisk

**Comment by MrChrisW** [comment]
Thanks @PalmerAL 

Resolved by @brianrisk in #2105 

https://duckduckgo.com/?q=home+values+in+california&ia=homevalues
https://duckduckgo.com/?q=home+values+in+new+york&ia=homevalues
