### ISSUE TITLE
Arch User Repository: undefined parameter in "More at aur.archlinux.org" link

### ISSUE THREAD

**Issue by claudiodangelis** [duckduckgo/zeroclickinfo-spice#2093]
The "More at aur.archlinux.org" link has an undefined parameter (&arg=undefined). Tested on Firefox and Chrome.

http://aur.archlinux.org/rpc.php?type=search&arg=undefined

![image](https://cloud.githubusercontent.com/assets/941963/9224029/a2a29e4a-40ff-11e5-914a-41b2102fcecb.png)

------
IA Page:  http://duck.co/ia/view/aur

**Comment by moollaza** [comment]
@claudiodangelis thanks a lot for reporting this!

**Comment by moollaza** [comment]
@MrChrisW as always, thanks for fixing it :)
