### ISSUE TITLE
MTG: API has gone offline! We need a new data source.

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2097]
As of this morning the data source,  https://www.mtgdb.info/ website seems to be offline.

I'm not sure if this is permanent, but in case it is, we'll need a new data source/API.

/cc @puskin94

**Comment by moollaza** [comment]
It looks like the change may be permanent. The Twitter handle for the site seems to be gone now: https://twitter.com/mtgdb

I found the Repo for the API which has all the original data: https://github.com/planeswalkers/api.mtgdb.info/blob/master/db/dump.zip

We may be able to use this to create another type of IA, e.g Fathead or Longtail + Spice to recreate this.

**Comment by loganom** [comment]
According to that repo, yes, it is permanent. This is unfortunate.

https://github.com/planeswalkers/api.mtgdb.info

**Comment by soleo** [comment]
http://mtgjson.com/ could be a good option for reinvent this.

**Comment by loganom** [comment]
@soleo thanks for sharing this! I'll take a look when I get a chance.

**Comment by loganom** [comment]
@soleo looks like it is simply a json file with all of the card data from every set (14.7MB). I'm not sure if there's really a good API out there at the moment. @moollaza I'm going to presume that this is too large of a data set for us to implement as an instant answer, correct?

**Comment by moollaza** [comment]
@loganom ya the JSON endpoint approach really isn't ideal, especially if it’s a massive 14MB file (a large API response is ~500Kb).

If this info isn't expected to change anytime soon, a Fathead could be made, but ideally we need a search endpoint, or an endpoint we can pass a character name to, and only get the info we need back.

**Comment by tagawa** [comment]
Closing this, as the IA has been updated to use the Deckbrew API.
