### ISSUE TITLE
Last.fm Artist: reign in triggering

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#2099]
It's blindly triggering on artist in a lot of places it shouldn't:
https://duckduckgo.com/?q=artist+of+the+year
https://duckduckgo.com/?q=music+artist
https://duckduckgo.com/?q=street+artist

Related to why there were so many empty api responses coming back from last.fm #2098 

cc @moollaza @russellholt 

------
IA Page:  http://duck.co/ia/view/lastfm_artist

**Comment by moollaza** [comment]
We could probably drop the word "artist" as a trigger for now. It seems like it's causing too many false positives.
