### ISSUE TITLE
PeopleInSpace: Images Broken

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#2109]
![screen shot 2015-08-18 at 9 16 18 am](https://cloud.githubusercontent.com/assets/126358/9330841/e7f144e0-4589-11e5-90c2-e275a5181248.png)

@moollaza 

------
IA Page:  http://duck.co/ia/view/people_in_space

**Comment by moollaza** [comment]
@bsstoner they seem to be working for me. Are you still seeing this?

**Comment by moollaza** [comment]
![people_in_space_at_duckduckgo](https://cloud.githubusercontent.com/assets/873785/9349695/6ba300a2-4617-11e5-8c95-6801db24e806.png)

**Comment by bsstoner** [comment]
:+1: looks good, must have been on their end.
