### ISSUE TITLE
Images: Brest showing breast

### ISSUE THREAD

**Issue by slashbang** [duckduckgo/zeroclickinfo-spice#2111]
Searching for Brest results in images of women and breasts. It should return images of Brest in France.

If Brest, France is searched instead it results in correct results.

------
IA Page:  http://duck.co/ia/view/images

**Comment by Asternitix** [comment]
This problem is caused by not enough precision in the interpretation of the query. Adding a spell checker should solve this problem.

**Comment by Asternitix** [comment]
This problem could be solved with more precision in the interpretation. Adding a spelling check should solve this problem.

**Comment by moollaza** [comment]
@slashbang are you seeing mostly irrelevant images? For me I only see about 2 or 3 images that aren't great, but the rest are pictures of France.

**Comment by edgesince84** [comment]
this one is showing very, very limited "breast" images, and nothing NSFW.  To put it in perspective, Google Images shows an equal amount of "breast" pics.  Closing this, thanks!
