### ISSUE TITLE
Geometry: Should have brackets for clarity

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#2113]
To help users, formulae would be easier to understand if they had brackets/parentheses, e.g. 
`V = (4/3)πr^3` instead of  `V = 4/3πr^3`

---

IA Page:  http://duck.co/ia/view/geometry

**Comment by sekhavati** [comment]
@tagawa How about we take this idea one step further and use something like [MathJax](https://www.mathjax.org/)? 

Here's an example using the formula you mentioned: https://jsfiddle.net/fm80d907/3/

**Comment by tagawa** [comment]
Good idea. I still think brackets should be added here in the meantime, but have made a separate feature request for MathJax: https://github.com/duckduckgo/duckduckgo/issues/176

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
