### ISSUE TITLE
Cryptocurrency: JS Error in console `leadingZeroRegex` failing

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2128]
I was just testing the query "1000 doge" and noticed we didn't show a result. There's an error in the console: `TypeError: leadingZerosRegex.exec(...) is null`.

Looks like a regex is failing? Let's fix ASAP!

/cc @claytonspinner 

-----
IA Page: https://duck.co/ia/view/cryptocurrency

**Comment by MrChrisW** [comment]
@moollaza I'm unable to reproduce this using the query `1000 doge`
`x` shouldn't be null on [L197](https://github.com/duckduckgo/zeroclickinfo-spice/blob/mrchris/cryptocurrency-hotfix/share/spice/cryptocurrency/cryptocurrency.js#L197) as there's a value passed to it.

**Comment by moollaza** [comment]
Seems to be working now!
