### ISSUE TITLE
Quandl IAs: Remove `{{url}}` from content.handlebars

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2131]
It seems like these IA's have an unnecessary link in the title of the result that simply links back to the page (because there's no defined `url` property.

@brianrisk did/do we have something to link to instead or is removing the links OK?

-----
IA Pages: 
https://duck.co/ia/view/quandl_fundamentals
https://duck.co/ia/view/quandl_home_values
https://duck.co/ia/view/quandl_world_bank

**Comment by jagtalon** [comment]
:heart:
