### ISSUE TITLE
GoWatchIt: Increase margin-top on footer to 1em

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/zeroclickinfo-spice#2136]
![screen shot 2015-08-27 at 8 56 08 am](https://cloud.githubusercontent.com/assets/7061920/9525635/e3b57fb0-4c99-11e5-879b-28fe1bcf8401.png)

------
IA Page:  http://duck.co/ia/view/go_watch_it

**Comment by altern8tif** [comment]
Any particular reason why 1em?  Thought 0.5em looks better.

**Comment by chrismorast** [comment]
For padding consistency. 
![screen shot 2015-09-01 at 1 22 35 pm](https://cloud.githubusercontent.com/assets/7061920/9615400/a24b5cea-50ac-11e5-90fc-c922f1071273.png)
