### ISSUE TITLE
Sunrise/Sunset: Add triggering for "when is the sunrise in", "when does the sun rise in", etc

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2145]
We should be able to trigger on queries of these forms:

- "when is the sunrise/sunset in ..."
- "when does the sun rise/set in ..."
- "when will the sun rise/set in ..."
- "sun rise/set in ..."

------
IA Page:  http://duck.co/ia/view/sun_rise_set

**Comment by benabrahamson** [comment]
Will this be enough triggers? https://gist.github.com/benabrahamson/aad291669ccb60af83ae
