### ISSUE TITLE
Implement Wikidata on Wikipedias 0-click info

### ISSUE THREAD

**Issue by airon90** [duckduckgo/zeroclickinfo-spice#2148]
By now, (English) Wikipedia 0-click info fetch information on infobox and display a table with those data. 

Example: https://beta.duckduckgo.com/?q=roma-bangkok&ia=about

However, on Wikidata information are more precise than on Wikipedia

Example: https://www.wikidata.org/wiki/Q20731348

I think you should adapt the code to obtain those information from Wikidata instead from Wikipedia's infoboxes.

See also PR #1991 
Thank you very much!

**Comment by moollaza** [comment]
Thanks a lot for the suggestion. Our Wikipedia results are actually based on a special, internal Fathead Instant Answer. We're constantly scraping Wikipedia and their infoboxes and using that info to produce the Wiki results you see.

We're interested in Wikidata and will continue to investigate it, but for now I don't think this would be considered a very high priority so I'm marking it as tolerated.

We do have plans to do a better job of replicating the Wiki infoboxes, but that too is not a very high priority.

**Comment by Airon90** [comment]
Thank you very much for your answer! I'm happy to see in the future progress about Wikidata on DuckDuckGo so please keep us informed about that! :)

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
