### ISSUE TITLE
CitiBike: Need to normalize dates to standard format and UTC Timezone

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2156]
I realized that the date string we get from the CitiBike API (https://www.citibikenyc.com/stations/json) is a non-standard date format which the `new Date()` constructor cannot parse. Also, it's given in EDT instead of UTC, but the string doesn't indicate the timezone, causing further problems.

@marianosimone do you know if we can get CitiBike to give us a proper, UTC formatted string? As well, can you update the code to replace the `-` with `/` then convert the time to UTC (you'll probably need to set timezone for the date to EDT first)

This way when dealing with other timezones everything will be normalized :+1: 

/cc @xuv

-----
IA Page: https://duck.co/ia/view/citi_bike_nyc

**Comment by xuv** [comment]
@marianosimone: Here's the line of code that worked for me to replace the `-` with `/` (on line 90):  
```lastCommunication: moment(new Date( (item.lastCommunicationTime).replace(/\-/g,'/') ) ).fromNow()```

**Comment by marianosimone** [comment]
Quick update: The people behind the data feeds for CitiBike NYC (and many other bike sharing services) released a new format called [GBFS](https://github.com/NABSA/gbfs), and they won't be adding features/fixing the legacy ones anymore.

- The good news is that the new format handles dates better (using Posix timestamps)
- The bad news is that they splitted the feed in two parts (actually, many more, some of them interesting for us, but not directly related to this), so the station information (like location, name and address) is separated from the status (how many available bikes there are)... So we can't migrate to it without significantly changing how we do it (as I understand, spices can only hit one url to get the data)
- The hopeful news is that I've been talking with one of the people from the project, and he encouraged me to open a [new ticket](https://github.com/NABSA/gbfs/issues/21) asking for an aggregate feed that would allow us to keep the current implementation
