### ISSUE TITLE
Twitter: Title link should point to result's Twitter profile

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2158]
We need to define a `url` property in the `normalize()` function that should be identical to the `sourceURL` we create. That way clicking the title link will take you to the Twitter profile for the result we're showing, instead of linking back to the current page!

------
IA Page:  http://duck.co/ia/view/twitter

**Comment by samskeller** [comment]
@moollaza I've submitted a <a href="https://github.com/duckduckgo/zeroclickinfo-spice/pull/2182">pull request</a> to fix this issue!
