### ISSUE TITLE
Airlines does not pluralize "Flight"

### ISSUE THREAD

**Issue by bradcater** [duckduckgo/zeroclickinfo-spice#2160]
I searched for "flight pd143" and got "Showing 2 Flight."

![flight_not_pluralized](https://cloud.githubusercontent.com/assets/48050/9750044/cf0348a6-5660-11e5-8462-89e8043da79a.png)

**Comment by iambibhas** [comment]
This will be fixed when #1736 gets merged.

**Comment by jagtalon** [comment]
@iambibhas :+1:

**Comment by zekiel** [comment]
closing for #2602 2602
