### ISSUE TITLE
When Searching for 2 flights, one flight is repeated twice

### ISSUE THREAD

**Issue by tomtclai** [duckduckgo/zeroclickinfo-spice#2165]
Expected
-----
![screenshot 2015-09-09 07 35 26](https://cloud.githubusercontent.com/assets/6173427/9829165/b2e5412e-58ae-11e5-9071-b3057c43bfc2.png)

Actual
-----
![screenshot 2015-09-09 07 35 26](https://cloud.githubusercontent.com/assets/6173427/9764730/7d808330-56c5-11e5-8765-87391f9197fd.png)

EDIT: I tried reversing the order (2423 first) and see that It's doesn't always repeat the last flight.
![screenshot 2015-09-09 07 52 10](https://cloud.githubusercontent.com/assets/6173427/9765183/cb8e60cc-56c7-11e5-958a-c55008bad477.png)

------
IA Page:  http://duck.co/ia/view/airlines

**Comment by moollaza** [comment]
@tomtclai thanks for reporting. This IA isn't really meant to take more than one flight number as input, so I believe in all these cases, we're actually ignoring the 2nd flight number. The reason you're seeing two flights is because we've widened the window for all matching flights within 24 hours, that are in-transit and about to leave.

Do you remember what day/time you searched this? I'm assuming between 8:35-10:18AM on Wed, Sept 9th?

**Comment by tomtclai** [comment]
@moollaza The screenshots were taken between Sept 9, 2015, 07:35 and Sept 9, 2015, 7:52

**Comment by moollaza** [comment]
@tomtclai thanks, it's as I suspected. The first flight hadn't landed yet, and the 2nd was waiting to depart. It's almost impossible to know which flight you're expecting to see in this case though: i.e. are you waiting to check if your friend has landed, or to see if your flight is still on time? so for now we're showing both.

I'm not sure if there's much we can "fix" in this case, but I'm open to ideas? For now, searching two+ flights isn't really possibly unless we do some refactoring.

Out of curiosity, did you happen to compare against Google to see what they showed?

**Comment by tomtclai** [comment]
@moollaza Oh. I didn't realize the second box was a different flight! I checked out #2000 and see that they want all flights happening today... but here the second box is showing the flight tomorrow, not today.

So, how about only showing flights that's gonna happen today? I didn't compare but I think that's what google does.
