### ISSUE TITLE
Relative Cost of Living IA

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/zeroclickinfo-spice#2174]
> If I search "Relative Cost of Living Paoli, PA" (or other places that don't seem to be in Expatistan's database) it shows the Cost of Living index for LA. The IA seems like it needs a catch if the location is not in the database to not show or something like that.

cc @epik

move of: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1551

**Comment by pardocz** [comment]
I'm looking at it right now. I will probably be able to solve this on my end. I will update with progress soon.

**Comment by pardocz** [comment]
I have a fix ready to go.

The matching was overly broad and I was interpreting the 'la' inside 'reLAtive' as the short name of Los Angeles. The matching for city names now only happens on words boundaries (i.e. a whole word has to match).

I'll push it live now unless you guys would prefer to wait for some reason.

**Comment by moollaza** [comment]
@pardocz thanks!

@MrChrisW once the API is updated, will your PR still be necessary?

**Comment by pardocz** [comment]
The API is updated on my side. Queries like "Relative Cost of Living Paoli, PA" will now return a "NOT FOUND" result.

**Comment by MrChrisW** [comment]
Thanks @pardocz awesome!

@moollaza No need for #2375

Closing, fixed upstream by @pardocz
