### ISSUE TITLE
Cryptocurrency: console error causing Images fallback

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#2177]
https://duckduckgo.com/?q=electrons
<img width="1279" alt="screen shot 2015-09-13 at 5 30 47 pm" src="https://cloud.githubusercontent.com/assets/126358/9839123/8773c0de-5a3d-11e5-8e1e-9eba68e1890f.png">

Why is it even triggering on this query?

------
IA Page:  http://duck.co/ia/view/cryptocurrency

**Comment by bsstoner** [comment]
The error is `Uncaught TypeError: Cannot read property 'created' of undefined`

**Comment by moollaza** [comment]
@claytonspinner @MrChrisW -- Care to investigate?

Looks like we need to reign in the triggering a bit here too

**Comment by claytonspinner** [comment]
@moollaza @MrChrisW looking into it.

**Comment by Jedidiah** [comment]
Has this been fixed? I can't reproduce the error.

**Comment by MrChrisW** [comment]
@Jedidiah This will most likely be addressed in #2306 at least the triggering part.

**Comment by MrChrisW** [comment]
Fixed in #2369
