### ISSUE TITLE
Currency: Live mid-market rates? 

### ISSUE THREAD

**Issue by ashishlth** [duckduckgo/zeroclickinfo-spice#2178]
Hi,

I have noticed that the rates used by this currency conversion tool uses previous day's closing rate, rather than the current mid-market rates. Could this be changed? Google responds to current mid market rates.

---

IA Page:  http://duck.co/ia/view/currency

**Comment by moollaza** [comment]
Hi @ashishlth I was under the impression we were getting mid-market rates, but you correct that we're getting daily rates. I'll have the team investigate switching.

**Comment by pjhampton** [comment]
We're currently working with the upstream provider to improve this IA. This isn't something that will be done in the open though.
Hopefully, we can provide more real-time information in the future.
