### ISSUE TITLE
Forecast: Add triggers for other languages

### ISSUE THREAD

**Issue by Leetcore** [duckduckgo/zeroclickinfo-spice#2179]
Hello,

the weather answer should also start if i search "weather" in other languages. Example: "wetter" (Germany).

wetter in stadtname should also work.

Can you make more hotwords?

---

IA Page:  http://duck.co/ia/view/forecast

**Comment by Leetcore** [comment]
Title changed

**Comment by moollaza** [comment]
Hi @Leetcore , currently we're only using english trigger words for all Instant Answers. We do plan to internationalize the trigger of Instant Answers, but simply adding more triggers in various languages is the best way to do that. I would imagine the code would quickly become bloated with hundreds of words, making it hard to work with.

Ideally we'd like to tokenize our triggers and use our community to translate them, and make multi-lingual triggering a deeper component of the platform. We don't have any immediate plans to act on this currently though and still need to flesh out the planning to figure out how this would all work.

We do currently use the organic results to help us signal if the query should trigger our weather Instant Answer, so we may be able to tweak that in the shorter term.

I'll make a task for the team to investigate!

**Comment by ToX82** [comment]
I was going to ask the same thing when I found this issue. I think that this would be a huge boost to make non english speakers to try and love duckduckgo.

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
