### ISSUE TITLE
BitcoinAddress: QRCode Images not loading

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2183]
https://duckduckgo.com/?q=1J6EZsQLTppftPTbqYbbRDYFJMW5Ex3Bqi&ia=bitcoinaddress

Seems like the image URLS aren't working. @biteasy have the URL's changed? Does the code need to be fixed?

------
IA Page:  http://duck.co/ia/view/bitcoin_address

**Comment by Mailkov** [comment]
The URL: https://www.biteasy.com/blockchain/addresses/1Biteasym3p5E4soZq8So6NjkjYugEnz2X/qrcode.jpg
works.

The error is: 
https://images.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.biteasy.com%2Fblockchain%2Faddresses%2F1Biteasym3p5E4soZq8So6NjkjYugEnz2X%2Fqrcode.jpeg&f=1
Failed to load resource: the server responded with a status of 500 (OK)
500 Internal Server Error

I have one problem to debug on codio with (duckpan server) this IA ... when I try it returns: Spice.failed() called by Spice with ID "bitcoin_address".

**Comment by moollaza** [comment]
> I have a doubt: does basic_image_item require title ? In this code, title is not set.

It's not required, but we assume a `description` or `title` will be present.

You can see the template here: https://github.com/duckduckgo/duckduckgo-answerbar-templates/blob/master/item/basic_image_item.handlebars

@Mailkov it looks like this is a DDG problem. If you remove the `images.` subdomain, our image proxy works correctly:

https://duckduckgo.com/iu/?u=https%3A%2F%2Fwww.biteasy.com%2Fblockchain%2Faddresses%2F1Biteasym3p5E4soZq8So6NjkjYugEnz2X%2Fqrcode.jpeg&f=1

>I have one problem to debug on codio with (duckpan server) this IA ... when I try it returns: Spice.failed() called by Spice with ID "bitcoin_address".

Hmm it should fallback to making the API call on one of our DDH Machines (ddh10, ddh9 ... ddh1.duckduckgo.com) so that things still work. Whats the terminal output from DuckPAN?

**Comment by alolis** [comment]
@moollaza , apologies, just saw your ping. Let me know if you need anything on my side

**Comment by Mailkov** [comment]
@moollaza  this is  the terminal output:
```
API key not found. Using DuckDuckGo's endpoint:                                                                                             
"https://ddh10.duckduckgo.com/js/spice/bitcoin_address/1Biteasym3p5E4soZq8So6NjkjYugEnz2X"                                                  
172.17.42.1 - - [17/Nov/2015:13:50:13 +0000] "GET /js/spice/bitcoin_address/1Biteasym3p5E4soZq8So6NjkjYugEnz2X HTTP/1.1" 200 29 "http://ferr
ari-parker.codio.io:1234/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36"       
172.17.42.1 - - [17/Nov/2015:13:50:13 +0000] "GET /share/spice/bitcoin_balance/bitcoin_balance.css HTTP/1.1" 200 1443 "http://ferrari-parker
.codio.io:1234/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36"                 
172.17.42.1 - - [17/Nov/2015:13:50:13 +0000] "GET /country.json HTTP/1.1" 200 17 "http://ferrari-parker.codio.io:1234/" "Mozilla/5.0 (X11; L
inux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36"                                                      
172.17.42.1 - - [17/Nov/2015:13:50:13 +0000] "GET /assets/flags/20/wt.png?v=4 HTTP/1.1" 200 1541 "http://ferrari-parker.codio.io:1234/" "Moz
illa/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36" 
```

**Comment by alolis** [comment]
@Mailkov , can you please try now? I think the problem was on biteasy side after all

**Comment by Mailkov** [comment]
@alolis the same error:
```
API key not found. Using DuckDuckGo's endpoint:                                                                                             
"https://ddh10.duckduckgo.com/js/spice/bitcoin_address/1Biteasym3p5E4soZq8So6NjkjYugEnz2X"                                                  
172.17.42.1 - - [17/Nov/2015:13:50:13 +0000] "GET /js/spice/bitcoin_address/1Biteasym3p5E4soZq8So6NjkjYugEnz2X HTTP/1.1" 200 29 "http://ferr
ari-parker.codio.io:1234/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36"       
172.17.42.1 - - [17/Nov/2015:13:50:13 +0000] "GET /share/spice/bitcoin_balance/bitcoin_balance.css HTTP/1.1" 200 1443 "http://ferrari-parker
.codio.io:1234/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36"                 
172.17.42.1 - - [17/Nov/2015:13:50:13 +0000] "GET /country.json HTTP/1.1" 200 17 "http://ferrari-parker.codio.io:1234/" "Mozilla/5.0 (X11; L
inux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36"                                                      
172.17.42.1 - - [17/Nov/2015:13:50:13 +0000] "GET /assets/flags/20/wt.png?v=4 HTTP/1.1" 200 1541 "http://ferrari-parker.codio.io:1234/" "Moz
illa/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36" 
```

I think the problem is in ddh10 
After some tests I can say you that only ddh1, ddh2 and ddh3 return the api key !

**Comment by alolis** [comment]
@Mailkov ok, I just checked the DDG api key again and it seems to be valid indeed (with both v1 and v2 API)

**Comment by moollaza** [comment]
>After some tests I can say you that only ddh1, ddh2 and ddh3 return the api key !

Thanks for pointing that out -- looks like some of the ddh machines are a little behind and need to be updated.

They should all have the same API key that we use in production, which I confirmed works, so everything should be OK on that front.

I beleive the problem is with our images endpoint, and I've made a task for the team to investigate what's going on there.

> Ok, I suggest to change the documentation https://duck.co/duckduckhack/templates_reference#codebasicimageitemcode-template
title is setted as required.

I guess we use the term `required` loosely. Technically nothing is ***required*** to make the templates work. If you pass them no data, they'll render what they can and things will look broken. If you pass them data they don't need, they'll ignore it. If you pass them any of the properties mentioned in the docs, they'll try to use it.

We put `required` because if you're using that template, you *should* have a `title`. We're working on a revised version of the docs right now actually which you can see here: https://talsraviv.gitbooks.io/duckduckhackdocs/content/

**Comment by moollaza** [comment]
We've fixed this internally :+1:
