### ISSUE TITLE
Tvmaze: Can't search for "The Walking Dead" episodes

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#2185]
"Fear the Walking Dead" is coming up instead of "The Walking Dead". Is this a bug or a feature since "The Walking Dead" season just ended? 

![screen shot 2015-09-17 at 2 49 07 pm](https://cloud.githubusercontent.com/assets/81969/9942843/522d4498-5d4b-11e5-8d44-b18d97071e45.png)

-----
IA Page: https://duck.co/ia/view/tvmaze_nextepisode

**Comment by moollaza** [comment]
@tvdavid do you know why the singlesearch endpoint is giving us this result over the show with the same name? The regular search endpoint returns the correct show first

**Comment by tvdavid** [comment]
@moollaza Wow, sorry for the late reply, this apparently got buried. Fortunately, this bug has been fixed on our end for quite a while. Let us know if you find any more of these.

**Comment by moollaza** [comment]
>@moollaza Wow, sorry for the late reply, this apparently got buried. Fortunately, this bug has been fixed on our end for quite a while. Let us know if you find any more of these.

@tvdavid its no prob, thanks for letting us know it's fixed!

**Comment by moollaza** [comment]
https://duckduckgo.com/?q=The+Walking+Dead+next+episode&t=ffab&ia=entertainment
