### ISSUE TITLE
XKCD: Make Prev&Next buttons not open in a new window with 'New window' On.

### ISSUE THREAD

**Issue by viluon** [duckduckgo/zeroclickinfo-spice#2196]
It'd be nice if the Prev & Next buttons wouldn't open another query /in a new tab/ when the setting 'New window' is On (true), in order to make browsing of xkcd comics more comfortable. The Explain link should follow the current behaviour though.

------
IA Page:  http://duck.co/ia/view/xkcd

**Comment by moollaza** [comment]
@viluon thanks for the suggestion.

I don't believe we currently have a way to fine tune the link behaviour right now but I'll check with the team...

**Comment by zekiel** [comment]
@moollaza  what was the result of investigation here?

**Comment by sdball** [comment]
This is a great, fun plugin to work on but I [don't have the time to volunteer](https://github.com/duckduckgo/zeroclickinfo-spice/issues/992#issuecomment-206559354).

**Comment by zekiel** [comment]
@sdball  you are too kind! We'll update the IA and open it up for adoption so that you're not pinged for XKCD as maintainer.

**Comment by gaulrobe** [comment]
@moollaza @viluon 

It looks like when `New Window` is ON only the `Explain it!` link opens in a new window. The other links that link back to another DuckDuckGo query remain in the same tab. Looks like there remains nothing else to do here? Can this issue be closed?

**Comment by gaulrobe** [comment]
@moollaza @viluon 

Currently, when `New Window` is ON the behavior is that the `Explain it!` link opens in a new tab while the other links (that link back to DDG) remain in the current tab. Did this get fixed recently? If so, can this issue be closed?

**Comment by moollaza** [comment]
> Did this get fixed recently? If so, can this issue be closed?

Looks like it!
