### ISSUE TITLE
ColorPicker: disable page-level left/right arrow keys while typing into field

### ISSUE THREAD

**Issue by maxpolk** [duckduckgo/zeroclickinfo-spice#2197]
The left and right arrow keys in color picker are intercepted to move between "Color Picker | Images | Videos | About", rather then move the cursor while inside a text entry field.

This issue is a request to disable the page-level left and right arrow key processing when you are typing into an instant answer text field.

Here is a more detailed explanation.  A problem occurs when you click inside a text entry area of color picker to edit the text, for example, click inside the "R" text area showing "161".  When you begin to move the cursor within the text of the text field, you will discover that the right arrow key gets intercepted to move between instant answers "Color Picker | Images | Videos | About", and you suddenly are on "Images".  Move right again and you are on "Videos", etc.  When you move arrow key left enough times, you finally return to "Color picker" and if you move the arrow key left one more additional time, it finally actually moves the cursor one left within the text area.  If you use the right arrow, it fails to behave as expected.

I did notice that down arrow key does *not* take you to the first search result below the instant answer, so it does seem possible to stop intercepting the arrow keys while inside an instant answer. 

------
IA Page:  http://duck.co/ia/view/color_picker

**Comment by moollaza** [comment]
@maxpolk thanks for posting this! I think something has changed because this is affecting all IA's that have inputs, which wasn't the case before.

I'm going to have the team investigate asap!

**Comment by sekhavati** [comment]
I can't reproduce this issue. Has it already been fixed?

**Comment by moollaza** [comment]
@sekhavati yes I believe so!
