### ISSUE TITLE
IsItUp: Add support for domains containing unicode characters

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#220]
Eg. ["is føtex.dk up"](https://duckduckgo.com/?q=is+f%C3%B8tex.dk+up)

- "expand føtex.dk"
- "whois føtex.dk".

Seems that their API might not support unicode. Needs further investigation!

https://duck.co/ia/view/is_it_up

**Comment by ScreapDK** [comment]
Tee hee! ^_^ ;D :P :)
I had actually already reported that [over here](https://duck.co/forum/thread/4799/new-instant-answer)! ...a looong time ago! :D

See these comments for more example queries:
[example queries](https://duck.co/forum/comment/32078)
[(also this)](https://duck.co/forum/comment/32079)

**Comment by javathunderman** [comment]
@moollaza @ScreapDK Should we look for a new API then?

**Comment by iambibhas** [comment]
Their API is not very Unicode friendly. They just omit the unicode character. - http://isitup.org/f%C3%B8tex.dk.json?callback=ddg_spice_is_it_up

Right now the regex being used in the Spice doesn't allow unicode character. In the regex, using `\p{L}` seems to work. L for `Letter`. [Doc](http://perldoc.perl.org/perlunicode.html#Unicode-Character-Properties).

**Comment by MrChrisW** [comment]
This issue is being handled in the upstream *isitup.org* repository - See [Support for internationalized domain names #18 ](https://github.com/sjparkinson/isitup.org/pull/18)

**Comment by sjparkinson** [comment]
Thanks to @MrChrisW internationalized domain names are now supported:

https://isitup.org/f%C3%B8tex.dk.json?callback=ddg_spice_is_it_up

![image](https://cloud.githubusercontent.com/assets/51677/12468050/4062ed7c-bfd8-11e5-8595-77e372684a7d.png)

**Comment by MrChrisW** [comment]
@sjparkinson Thanks for providing an awesome API :smiley: 

@moollaza It looks like the IA is disabled on your side - see https://duckduckgo.com/js/spice/is_it_up/duckduckgo.com 

>I assume the regex used to verify domains is throwing it out given the Unicode characters.

This is correct, the IA fails to parse the IDN correctly. I'll be investigating this shortly...

**Comment by moollaza** [comment]
@MrChrisW FWIW the IA is back online -- we had an NGINX bug that has now been fixed...

**Comment by MrChrisW** [comment]
This can be fixed by adding support for IDN within the regex query https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/IsItUp.pm#L8

**Comment by moollaza** [comment]
@duckduckgo/duckduckhack-active-contributors anyone interested in tackling this?

As @MrChrisW mentioned, the required fix is updating the regex linked above to be a little more unicode friendly. Right now it limits the accepted URLs to those which contain `a-zA-Z0-9`

**Comment by altern8tif** [comment]
@moollaza will work on this.

Also noticed that the [newer TLDs](https://www.wikiwand.com/en/List_of_Internet_top-level_domains#/ICANN-era_generic_top-level_domains) don't work with this Spice.

**Comment by MrChrisW** [comment]
@altern8tif - I think we should move to using something like [`Domain::PublicSuffix`](http://search.cpan.org/dist/Domain-PublicSuffix/lib/Domain/PublicSuffix.pm) and avoid using Regexp to phrase domains.. which is generally a bad idea.

See an example usage in Whois: 
https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Whois.pm#L16-L17

@moollaza Would it be possible to keep this public_suffix_list.dat list updated on server side as it seems to be updated quite frequently, alternatively we can just keep updating the module on each release. 

https://github.com/publicsuffix/list

**Comment by zekiel** [comment]
@MrChrisW are you able to assign to @altern8tif  if you want to pass along? Just curious if that works since you have commit access (also, if you want to hold on to the task).

**Comment by MrChrisW** [comment]
No problem @zekiel - I'm unable to assign to @altern8tif his name does not appear in the list. Can you confirm?

**Comment by altern8tif** [comment]
@zekiel @MrChrisW sorry guys... Just realised I might be really busy over the next 3 weeks.  Might be better to let someone else in the community take this up instead.

**Comment by zekiel** [comment]
np! thanks for the heads up @altern8tif  we'll be here when you get back but hopefully someone will address it by then. 

@MrChrisW I realize now that @altern8tif  wasn't apart of https://github.com/orgs/duckduckgo/teams/duckduckhack-contributors at the time so couldn't be assigned. Supposing it doesn't matter now tho lol

**Comment by rasikapohankar** [comment]
@MrChrisW  @moollaza Is this being worked on? If not, I'd like to try.

**Comment by MrChrisW** [comment]
@rasikapohankar This is not being worked on, feel free to take it up 👍

**Comment by rasikapohankar** [comment]
Thank you @MrChrisW, I'll try to do this.

**Comment by rasikapohankar** [comment]
@MrChrisW @moollaza On changing the regex to https://github.com/rasikapohankar/zeroclickinfo-spice/blob/00161ffffac4e1eb1826337c6ecc8f04028b0ea5/lib/DDG/Spice/IsItUp.pm#L9, the Unicode characters match and it works with the current regular expression for `regex_domain`. 
This does not work for the new TLDs as @altern8tif mentioned, so I tried to `use Domain::PublicSuffix` similar to Whois.pm. But `get_root_domain` gives a `Malformed domain` error for names with Unicode characters, for example, 'Bücher.ch' . This is also why "whois føtex.dk" is not giving an answer. 
I found https://github.com/nmelnick/Domain-PublicSuffix/blob/master/lib/Domain/PublicSuffix.pm#L296 and the [documentation](http://search.cpan.org/~drolsky/Data-Validate-Domain-0.12/lib/Data/Validate/Domain.pm#is_domain($domain,_\%options)) says it takes `(A-Z), digits (0-9), minus sign (-), and period (.)` in the name.
Should I make a pull request with the changed regex for query but without using Domain::PublicSuffix?

**Comment by moollaza** [comment]
@rasikapohankar would using https://metacpan.org/pod/Net::IDN::Encode help? You could convert the input domain to ascii, which should then work with PublixSuffix, I think.

As well there's https://metacpan.org/pod/Net::Domain::TLD if we need to check for a TLD.

Most importantly, it doesn't look like this IA needs to be using a regex trigger. We can use `triggers end => "working", "up", "down" ...` to trigger the IA. Then we can deal with the remainder and see if it's a domain. I think that should simplify things.

**Comment by rasikapohankar** [comment]
@moollaza Yup, using `domain_to_ascii` from Net::IDN::Encode on the query works with PublicSuffix. I was happy and about to make a pull request when I realised it works only if the tld does not have unicode characters. The `tld_tree` that Domain::PublicSuffix makes from public_suffix_list.dat has names as `\x{...}` and so if we do domain to ascii, the tld as 'xn--' is not found. I was trying to search if there was anything more, will see Net::Domain::TLD.
If we remove the regex trigger and make it a word we'd still need to do these operations on the remainder, no?
