### ISSUE TITLE
Timer: after switching to another tab, the timer resets each time the tab is shown

### ISSUE THREAD

**Issue by miloszmazur** [duckduckgo/zeroclickinfo-spice#2201]
Furthermore, if there's more then one timer present, only the rightmost timer will reset.

------
IA Page:  http://duck.co/ia/view/timer

**Comment by moollaza** [comment]
@miloszmazur thanks for reporting this. We've just released several fixes, including the Timer fixes. This looks to be solved. Care to confirm?

**Comment by miloszmazur** [comment]
Works as intended, confirmed. Thanks!
