### ISSUE TITLE
Octopart: triggering for "___ specs"

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#2207]
Is there a way to adjust the trigger so it doesn't show for queries like "<product> specs"? These look pretty bad and are probably popular searches:

![screen shot 2015-09-28 at 1 18 23 pm](https://cloud.githubusercontent.com/assets/126358/10142912/7bf8f9ac-65e3-11e5-8d47-841786379510.png)
![screen shot 2015-09-28 at 1 19 55 pm](https://cloud.githubusercontent.com/assets/126358/10142949/a7ad7172-65e3-11e5-8699-a2a5109e6f17.png)

------
IA Page:  http://duck.co/ia/view/octopart

**Comment by moollaza** [comment]
Ugh. Relevancy checking should be used to catch these. I think "specs" is a fair trigger, but it should obviously only return results when necessary
