### ISSUE TITLE
Quixey: "Android>Apple"

### ISSUE THREAD

**Issue by xzoky** [duckduckgo/zeroclickinfo-spice#2209]
Wow. That's real mature…
![screen shot 2015-09-29 at 10 11 07](https://cloud.githubusercontent.com/assets/339784/10172101/8224ed0e-6692-11e5-88f0-30ab2f2e9213.png)

------
IA Page:  http://duck.co/ia/view/apps

**Comment by MrChrisW** [comment]
@xzoky Nice catch. This is actually exactly what the [Quixey API](https://duckduckgo.com/js/spice/quixey/testflight/[2004%2C2005%2C2008%2C2015%2C8556073]/999999/2414062669) is returning `developer name = Android>Apple` which is incorrect as the Developer of TestFlight is Apple as per the App page https://itunes.apple.com/us/app/testflight/id899247664?mt=8

We'd need to lodge a report with Quixey to get this one resolved.

````json
  "results" : [ { "custom" : { "features" : { "allversions_rating" : 2,
                "allversions_rating_count" : 300,
                "category" : "Utilities",
                "currentversion_rating" : 2,
                "currentversion_rating_count" : 300,
                "downloads" : 0,
                "id" : 899247664,
                "itunes_url" : "https://itunes.apple.com/us/app/testflight/id899247664?mt=8",
                "languages" : "English",
                "rating" : "4",
                "release_dt" : 1406173688.0,
                "requirements" : "Requires iOS 8.0 or later. Compatible with iPhone, iPad, and iPod touch.",
                "size" : 3774873,
                "source" : "itunes",
                "update_dt" : 1443168000.0,
                "version" : "1.3.0",
                "whatsnew" : ""
              },
            "url" : "https://itunes.apple.com/us/app/testflight/id899247664?mt=8"
          },
        "developer" : { "dir_url" : null,
            "icon_url" : null,
            "id" : 4366477836318192330,
            "id_str" : "4366477836318192330",
            "name" : "Android>Apple",
            "url" : "https://play.google.com/store/apps/developer?id=Android%3EApple"
          },
````

**Comment by moollaza** [comment]
@xzoky thanks for pointing this out and @MrChrisW thanks for investigating. I'll pass this on to Quixey, but other than that, there's not too much we can do about this. I've marked it as tolerated and will close this out.

**Comment by xzoky** [comment]
I hope Quixey fixes it. Thanks guys!
