### ISSUE TITLE
Forecast: 

### ISSUE THREAD

**Issue by DGMurdockIII** [duckduckgo/zeroclickinfo-spice#2214]
when i search for weather on  duckduck go it not showing the correct city that i live in I live in   indianapolis, IN not what is show in screenshot http://i.imgur.com/7Gu0xaM.png

------
IA Page:  http://duck.co/ia/view/forecast

**Comment by moollaza** [comment]
@DGMurdockIII it seems like Boggstown is quite close to Indianapolis? For these kinds of Instant Answers, we need to infer your location based on an IP that's in the same region as yours, so there's a small margin of error.

We're working on a way to improve this, but for now I'm not sure there's an easy way for us to get your exact location. We're considering an opt-in method of specifying your location to us for higher accuracy.
