### ISSUE TITLE
Forecast: Default unit should be °C, not °F

### ISSUE THREAD

**Issue by cathalgarvey** [duckduckgo/zeroclickinfo-spice#2216]
Fahrenheit is used in very few countries, and the [International System of Units](https://en.wikipedia.org/wiki/International_System_of_Units) is used now in most of the internet-using world; it standardises Kelvin, but Celsius is adopted in common usage and by national and semi-national bodies because of its equivalence and easy-to-understand framing.

Given that both options are permitted by the Forecast view, it would make sense either to:

* Defer to the international standard
* Defer to a regionally-selected unit, meaning "F" for USA and "C" for basically everywhere else. :)

Thanks for a great service!

------
IA Page:  http://duck.co/ia/view/forecast

**Comment by estebanz01** [comment]
If I search `weather in [myCity]` in DDG for Android, I can see the results in Celsius. I guess it has to be with the location, isn't ?

**Comment by MrChrisW** [comment]
@estebanz01 @cathalgarvey Currently the units that the Forecast IA uses is based on what's returned by the forecast.io API. You can see this on [L15 - forecast.js](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/forecast/forecast.js#L15)

Basically it's using the system of measurement for the **searched location not the users locations.** 

Example API responses - see flags.units 

+ https://duckduckgo.com/js/spice/forecast/new%20york

````json
flags: {
    units: "us"
}
````
+ https://duckduckgo.com/js/spice/forecast/sydney%20australia%20as

````json
flags: {
    units: "si"
}
````

**Comment by cathalgarvey** [comment]
Huh, perhaps I was out of the country at the time? I thought I was in Ireland, but maybe I'm mis-remembering.

Good to hear that the system defaults to sane units by location, anyway. Thanks!

**Comment by moollaza** [comment]
@cathalgarvey @estebanz01 by the way, you can also set you preferred units in the DDG settings and then we'll default to that when set ;)

**Comment by MrChrisW** [comment]
>Huh, perhaps I was out of the country at the time? I thought I was in Ireland, but maybe I'm mis-remembering.
>Good to hear that the system defaults to sane units by location, anyway. Thanks!

No problem! As @moollaza said you can also change your default units in the [DDG Settings]( https://duckduckgo.com/settings) page.Thanks again for taking the time to respond and log an issue, it's what helps make DDG better! :+1:
