### ISSUE TITLE
Octopart: JS error

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#2218]
Seeing this error get thrown periodically, need to guard against it:
```
TypeError: null is not an object (evaluating 'item.avg_price_v2[0].toFixed')
```

------
IA Page:  http://duck.co/ia/view/octopart

**Comment by bsstoner** [comment]
Example: https://duckduckgo.com/?q=specs+for+torque+c146

![screen shot 2015-10-08 at 4 53 08 pm](https://cloud.githubusercontent.com/assets/126358/10379589/156c4cd2-6ddd-11e5-8c3a-c595c1b62090.png)

**Comment by SibuStephen** [comment]
Please review `#2226`
