### ISSUE TITLE
'UV Index' Query doesn't trigger UV Index IA as Default

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/zeroclickinfo-spice#2221]
Can we set this to show the UV Index IA to show by default rather than showing the 'About' tab?

------
IA Page:  http://duck.co/ia/view/uv

**Comment by jagtalon** [comment]
This can be done by adding `signal: 'high'` https://github.com/duckduckgo/zeroclickinfo-spice/search?utf8=%E2%9C%93&q=signal+high&type=Code
