### ISSUE TITLE
InTheaters: Translation

### ISSUE THREAD

**Issue by puzich** [duckduckgo/zeroclickinfo-spice#2223]
Is it possible to translate the search string for this instant answer, for people from other countries, like germany oder spain, so that they can use it too?

------
IA Page:  http://duck.co/ia/view/in_theaters

**Comment by moollaza** [comment]
@puzich we don't currently have a way to translate the user's query, but internationalization of the Instant Answers is on our roadmap and we do plan to allow them to trigger in different languages

**Comment by puzich** [comment]
OK! If you need any help with the german translation, let me know!

**Comment by moollaza** [comment]
@puzich sure thing. I suggest you checkout our Community Platform, duck.co. Where you can become a Translation Manager. I'm sure once we start internationalizing things, we'll speak to our TM's first!
