### ISSUE TITLE
Images: Loads images in Firefox; eats up bandwidth

### ISSUE THREAD

**Issue by jwalantsoneji** [duckduckgo/zeroclickinfo-spice#2225]
Search result page on DDG mobile website on FireFox even if doesn't show the image at first, it does load all images in the back. This is visible when switching tabs, when the window gets small.

Requesting DDG to release ultra-lite version of mobile search page which doesn't load images, vids, news unless clicked on that tab on the search result page.

------
IA Page:  http://duck.co/ia/view/images

**Comment by moollaza** [comment]
By default we only load the low-res version of the first few images (I think 12?) when the images tab shows by default.

When the images tab is clicked, we lazy-load the first few results in low-res (because you've indicated you want to see images).

Are you suggesting we should only load the first 3 results when the images show by default, and load the res when you click the "Show more" button?

**Comment by jwalantsoneji** [comment]
now, not able to replicate this scenario because of "Web" being the first tab in the results and by default that being open for something not exactly asking for images.

Sometime back.......
###
Well, Its different behaviour on the mobile site.
here are steps to reproduce the issue:

Open ddg.gg in Firefox in your mobile
Search for anything which gets images tab.. may be like "duckduckgo"
The search results should have had an images tab available but not opened
Now, click on the tab button, this will show the images of opened tabs
there Firefox loads and shows pics of each tab
there you can see duckduckgo tab showing images in it

This doesn't seem to be lazy load
####

**Comment by edgesince84** [comment]
@jwalantsoneji I'm trying to recreate your issue - are you referring to this kind of screen when you say "click on the tab button?" http://imgur.com/vlStiJr

**Comment by jwalantsoneji** [comment]
Yes. However, I had checked in Firefox.

रवि, 22 मई 2016, 6:19 am को Bill <notifications@github.com> ने लिखा:

> @jwalantsoneji <https://github.com/jwalantsoneji> I'm trying to recreate
> your issue - are you referring to this kind of screen when you say "click
> on the tab button?" http://imgur.com/vlStiJr
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/duckduckgo/zeroclickinfo-spice/issues/2225#issuecomment-220808206>
>
-- 

Regards,
Jwalant Natvarlal Soneji (http://jwalantsoneji.com)
