### ISSUE TITLE
Coursebuffet: Should trigger on "Learn X Online"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2228]
I just tried a query that didn't trigger this IA, which I was hoping it would.

This IA should trigger on queries like "Learn X Online" and "Online X courses".

E.g. "Learn computer science online", "online computer science courses"

------
IA Page:  http://duck.co/ia/view/coursebuffet

**Comment by altern8tif** [comment]
Was going to suggest that this can be closed.

And I'm assuming that the fix (on [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=computer+science+coursera&ia=onlinecourses)) is still not pushed to production yet?  'cause the original trigger words don't seem to be working on [duckduckgo.com](https://duckduckgo.com/?q=computer%20science%20coursera&ia=onlinecourses).

**Comment by moollaza** [comment]
Yup,  Updates will go live with next release
