### ISSUE TITLE
AUR third party issues

### ISSUE THREAD

**Issue by andrey-p** [duckduckgo/zeroclickinfo-spice#2233]
It seems the AUR API is having trouble with our callback format, and throws an error if we pass a callback with underscores.

Compare: https://aur.archlinux.org/rpc.php?type=search&arg=foobar&callback=foo and https://aur.archlinux.org/rpc.php?type=search&arg=foobar&callback=foo_bar

Discovered that with our new error logging thingamajig :)

**Comment by moollaza** [comment]
@andrey-p thanks!

It looks like we'll need to use `spice wrap_jsonp_callback` to make NGINX wrap the response in a callback

**Comment by moollaza** [comment]
@andrey-p my mistake, looks like this was already solved a few days ago: https://github.com/duckduckgo/zeroclickinfo-spice/issues/2233

It will go live with the next release!
