### ISSUE TITLE
PeopleInSpace: 'People in space' triggering Q/A IA as default 

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/zeroclickinfo-spice#2237]
![screen shot 2015-10-20 at 6 33 01 pm](https://cloud.githubusercontent.com/assets/7061920/10626255/14520a1a-7762-11e5-86ac-cee82b315c10.png)

------
IA Page:  http://duck.co/ia/view/people_in_space

**Comment by altern8tif** [comment]
That seems to work fine for me.

**Comment by moollaza** [comment]
@chrismorast @altern8tif this works properly for me too. @chrismorast are you still having this issue?

We can force the IA to show by setting `signal: "high"` if it persists

**Comment by jagtalon** [comment]
Ran into this problem as well. `signal: "high"` needs to be set.

**Comment by chrismorast** [comment]
Yes, this is still happening for me @moollaza and @altern8tif
