### ISSUE TITLE
Dogo Books: broken and throwing console error

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#2240]
![screen shot 2015-10-21 at 8 20 10 am](https://cloud.githubusercontent.com/assets/126358/10636260/97fa99da-77cc-11e5-9fbc-ae63523a62f0.png)

------
IA Page:  http://duck.co/ia/view/dogo_books

**Comment by moollaza** [comment]
@dogomedia would you be be able to investigate and fix this? Has your API changed?

**Comment by dogomedia** [comment]
@moollaza, @bsstoner Thank you for bringing this to our attention.  It looks there was at some point a bug was introduced into the API which affected certain queries.  We have resolved this issue on our end so everything should be working again.

**Comment by dogomedia** [comment]
<img width="1770" alt="scary kids books" src="https://cloud.githubusercontent.com/assets/10837292/10708988/e68e301e-79d1-11e5-8141-55d0050787c6.png">

**Comment by mintsoft** [comment]
@dogomedia @bsstoner This looks resolved to me

**Comment by mintsoft** [comment]
Thanks for the quick fix @dogomedia !

**Comment by moollaza** [comment]
:+1: Thanks guys
