### ISSUE TITLE
Zanran: Is this down?

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#2242]
None of the example queries return anything.

------
IA Page:  http://duck.co/ia/view/zanran

**Comment by moollaza** [comment]
Hmm the website seems to have gone offline suddenly. It was working last week though!

I can't find any mention of the company shutting down, but it doesn't seem like they've done much of anything since February..

http://www.zanran.com/

**Comment by moollaza** [comment]
We can take the IA offline for now and see what happens with the website.

**Comment by bsstoner** [comment]
interesting, yea, let's disable it for now.

**Comment by jagtalon** [comment]
@moollaza @bsstoner now up. I think we can close this.
