### ISSUE TITLE
Forecast: Expand trigger to include 'forecast'

### ISSUE THREAD

**Issue by b1ake** [duckduckgo/zeroclickinfo-spice#2248]
Currently, it triggers for 'weather' but not for 'forecast'. Seems like an easy win to expand it. :)

Compare 'weather' vs 'forecast':
https://duckduckgo.com/?q=weather&ia=weather
https://duckduckgo.com/?q=forecast&ia=weather

------
IA Page:  http://duck.co/ia/view/forecast

**Comment by moollaza** [comment]
@b1ake We are actually handling the triggers internally for this one because of relevancy issues, but

**Comment by moollaza** [comment]
@tommytommytommy is there any reason we can't bring back the forecast trigger?

I think we were worried that it was too ambiguous?

**Comment by tommytommytommy** [comment]
This particular IA has a history of overtriggering...taking a look at issues/PRs, we made several rounds of attempts to try to fix it, but all with mixed success. Here are the more recent conversations that I found:

https://github.com/duckduckgo/zeroclickinfo-spice/issues/1170
https://github.com/duckduckgo/zeroclickinfo-spice/pull/1173 (a lot of work trying to reign in triggering for "forecast")
https://github.com/duckduckgo/zeroclickinfo-spice/pull/1650 (overtriggering complaints from users)

In the end, we decided that this would be more appropriate to handle internally until we can verify that a substring of the query is (at least probabilistically, if not certainly) a geographic location. I'm not at all opposed to re-enabling the keyword trigger, but I suspect that writing a great keyword trigger is actually not low-hanging fruit. I think the more robust and useful approach would be to use this IA as an example for exposing geolocation features to DDH in general, and then using that new technology to re-enable (and bound) the keyword trigger.

**Comment by b1ake** [comment]
@tommytommytommy Gotcha, does that mean that we don't want the IA to trigger for the simple queries, 'weather' and 'forecast'? Neither of those have a geographic location as a substring of the query.

For me as a user, I'd expect 'weather' and 'forecast' to trigger, as well as variations of those with a geographic location (e.g. 'weather in paris'), as well as simple queries like 'weather today' and 'forecast tomorrow'.

I think if we had a whitelist of words that could go with trigger keywords (i.e. 'today' and 'tomorrow' would be whitelisted words, and 'weather' and 'forecast' would be trigger words), then we could safely trigger when every word in the query is known / whitelisted.

Sports does something similar for it's internal triggering, where every word has to be 'known' and there's a list of known words.

**Comment by tommytommytommy** [comment]
I think it would be great to have those triggers in, as the current open source trigger simply then attaches the user's approximate location and makes an upstream request. Would be nice to be able to internationalize this somehow too for other languages...

**Comment by tagawa** [comment]
Works now
