### ISSUE TITLE
Expatistan: Not triggering at all

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/zeroclickinfo-spice#2250]
It seems that this IA is not working at all

------
IA Page:  http://duck.co/ia/view/expatistan

**Comment by codenirvana** [comment]
It looks like API is removed...

**Comment by chrismorast** [comment]
Thanks for looking in to this @codenirvana . @moollaza , what are our options?

**Comment by moollaza** [comment]
Looks like the API is redirecting to HTTPS. We just need to update the code and it will work as expected. I'll fix it
