### ISSUE TITLE
IsItUp: 

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/zeroclickinfo-spice#2255]
@mrshu this seems down

------
IA Page:  http://duck.co/ia/view/is_it_up

**Comment by mrshu** [comment]
Hmm, the API does not seem to be down:

https://isitup.org/duckduckgo.com.json?callback=ddg

**Comment by altern8tif** [comment]
Seems to be working on Duckpan though.

**Comment by codenirvana** [comment]
@zekiel Issue fixed already : 09487ad08fe93eef9e9a8616be45d6c7dbd07d43
It will be live soon!

**Comment by moollaza** [comment]
@codenirvana is correct :+1:  This will be fixed with next release
