### ISSUE TITLE
Homebrew: API down

### ISSUE THREAD

**Issue by altern8tif** [duckduckgo/zeroclickinfo-spice#2258]
Getting a 502 Bad Gateway error from brewformulas.org's API.

Is there an alternative API that we can tap on for this IA?  [Braumeister](braumeister.org) looks like a good resource but it doesn't seem to have an API.

-----
IA Page: https://duck.co/ia/view/homebrew

**Comment by moollaza** [comment]
@altern8tif the Repo still looks active: https://github.com/zedtux/brewformulas.org -- there was some activity 9 days ago so I think it's a temporary outage. If not, we can look elsewhere.

/cc @SalGnt any ideas on the status of BrewForumlas.org?

**Comment by moollaza** [comment]
I sent them a tweet to see what's up...

**Comment by altern8tif** [comment]
@moollaza seems like it's up again.. will go ahead and close this issue then.

**Comment by moollaza** [comment]
:+1:
