### ISSUE TITLE
PeopleInSpace: Code should be cleaned up

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2261]
Looking at the source of this IA, it's silly that we call `Spice.add()` in two places, and define most of the same data in an anonymous object for each call.

We should define an object with the common case (1+ Astronauts in Spce) and conditionally modify the object when there are no astronauts.

This object should be passed to a single `Spice.add()` call

E.g.

```js

var spiceObj = {
    id: 'people_in_space',
    name: "...",
    meta: { ... },
    templates: { ... }
}

if (noAstronauts) {
    // redefine properties as needed
    // you could alternatively overwrite the object with $.extend()
    spiceObj.meta = {
        ...
    }
    spiceObj.templates = {
        ...
    }
    ....
}

Spice.add( spiceObj );
```

Also, we should be defining constants (and private functions), like the `codes` object outside our callback fn definition.

------
IA Page:  http://duck.co/ia/view/people_in_space

**Comment by altern8tif** [comment]
Good to close :smiley:

**Comment by jagtalon** [comment]
@altern8tif thanks!
