### ISSUE TITLE
Yoga Asanas: No info box/attribution

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#2263]
@zachthompson @abeyang 

The yoga asanas IA doesn't have the "i" icon to show the info box/developer attribution.
E.g. https://duckduckgo.com/?q=surya+namaskara+a&ia=yogaasanas

------
IA Page:  http://duck.co/ia/view/yoga_asanas

**Comment by altern8tif** [comment]
Is this an internal bug?  Have been searching the documentation to see how the info box attribution is derived but it doesn't say.

Amending the `attribution` or `metadata` code in the Perl files don't work...

**Comment by zachthompson** [comment]
@moollaza something from the Solr API colliding maybe?  I'm not entirely sure which values are getting pulled in.

**Comment by moollaza** [comment]
@zachthompson no idea! @jdorweiler any idea why this IA might not be showing an Info link on the SERP? 

https://duckduckgo.com/?q=Surya+Namaskara+A&ia=yogaasanas

**Comment by jdorweiler** [comment]
Looks fine to me.  I tried with both firefox and chrome.

**Comment by zachthompson** [comment]
Strange, it's working for me on a variety of browsers and Oses.  @tagawa are you still seeing this?

**Comment by tagawa** [comment]
Yes, I only have Ubuntu to hand but on Firefox, Vivaldi and Midori there's no info box/dev attribution displayed:

![yoga-asanas](https://cloud.githubusercontent.com/assets/94173/11199693/543edf06-8d13-11e5-946d-fab0432ecbf8.jpg)

**Comment by moollaza** [comment]
@tagawa @zachthompson 

It's now working for me. I fiddled with the IA Pages a bit yesterday, I must have done something right?

**Comment by moollaza** [comment]
<img width="1442" alt="surya_namaskara_a_at_duckduckgo_and_calendar" src="https://cloud.githubusercontent.com/assets/873785/11217987/0d21c7ce-8d21-11e5-9458-4cd93915da97.png">

**Comment by tagawa** [comment]
Yay, looks good to me now. Thank you!
