### ISSUE TITLE
Investigate Switching AQI Spice to Breezometer API for Global support

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2266]
http://breezometer.com/api/

Looks like this API is free and might support more than just US Zipcodes. If so we should definitely switch to this API to improve coverage.

-----
IA Page: https://duck.co/ia/view/aqi

/cc @schluchc

**Comment by schluchc** [comment]
Hi there

It looks cool, but I don’t think it is free for that use: http://breezometer.com/our-plans/

Cheers,
Christian

**Comment by moollaza** [comment]
The landing page says it's free for 1000 calls. Let's use that and see how it goes. If someone wants to reach out to them and explain the use case, there's a chance they (like many others) will give us free access because of the prominent "More at" link we will provide, linking back to them.

**Comment by schluchc** [comment]
I registered for an API key and had a quick look into the breezometer API. It would easily be possible to do something with it, but the data provided is a bit different from what Airnow provided.

I guess not too many users actually use the AQI IA now, so I wouldn't hesitate changing the data the IA provides. But in case I'm wrong and there is a small user base, I'd prefer to provide the airnow data along the breezometer data if both are available.

So, before I continue, do you possibly have any user statistics of the current AQI IA?

Also, could you register for an API key I could use via an environment variable?

**Comment by moollaza** [comment]
>I registered for an API key and had a quick look into the breezometer API. It would easily be possible to do something with it, but the data provided is a bit different from what Airnow provided.

Can you expand on that? How is it different?

> So, before I continue, do you possibly have any user statistics of the current AQI IA?

I wouldn't worry about the current popularity, if this API provides more data, or opens up the IA to more users/queries, we should definitely upgrade it because of the improved experience.

> Also, could you register for an API key I could use via an environment variable?

While developing you should use your own API key. You can add it to the env on the command line `KEY=value duckpan server` or by using `duckpan env` to save it locally

**Comment by navneetzz** [comment]
@moollaza I have worked with breezometer API before in one of my project
But the details provided by it is not up-to the mark.
Means it only provide accurate details related to Non Asian cities.
But if you wanna work on it I willing to work on this

**Comment by farmazon3000** [comment]
This is way better than breezo: http://aqicn.org

**Comment by moollaza** [comment]
@navneetzz thanks for the info! Do you know of any better solutions? Right now the current source only has US data, so Breezometer seemed much better as it has data for several countries.

@farmazon3000 thanks as well, does aqicn have an api? I don't see any mention of one...

**Comment by navneetzz** [comment]
@moollaza to my knowledge Breezometer is best for current situation.No, other API provider has this much accurate details.

**Comment by moollaza** [comment]
@navneetzz sounds like it's our best choice then -- would you still like to work on this or shall we open it up to the community?

**Comment by navneetzz** [comment]
@moollaza I would like to work on that.

**Comment by schluchc** [comment]
Sorry guys for being irresponsible the last few months here. I switched to a new job and just didn't find any time recently. Unfortunately, this will also not change very soon, so please feel free to continue with this IA as you wish. I hope I will find time again later to continue doing something with duckduckgo.

**Comment by moollaza** [comment]
> Unfortunately, this will also not change very soon, so please feel free to continue with this IA as you wish.

@schluchc thanks for the update and congrats on the new job!

@navneetzz looks like you're good to go!

>I hope I will find time again later to continue doing something with duckduckgo.

@schluchc I look forward to your next PR :+1:

**Comment by marcoslater** [comment]
Any updates on this? Would love to see more countries then just the US being covered! 👍  😄

**Comment by navneetzz** [comment]
Sorry guys for delay I will be Putting the PR probably this week.

**Comment by alohaas** [comment]
@navneetzz how's it going? :)

**Comment by navneetzz** [comment]
@alohaas I'm going to Create PR in couple of days. Only problem is that the Breezometer is free only for 30 days, while I have API key which was generated when there was no Pricing policy. So, what you say? Should we go ahead with this?

**Comment by moollaza** [comment]
> Only problem is that the Breezometer is free only for 30 days,

@navneetzz looks like this API is no longer an option then -- you're correct that there's no free usage tier anymore 😞

**Comment by edgesince84** [comment]
hey @navneetzz I wanted to see if you still planned on working on finding a new API for this - we really appreciate your contribution and want to see this go live. 

If you'd rather work on something new, we'd like to invite you to our [new forum](https://forum.duckduckhack.com/) to preview how we're improving programming-related searches. There are a lot of important tasks up for grabs that we'd like your help with, so feel free to and [jump in](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53).
