### ISSUE TITLE
Similar Sites: Limited Daily Requests for Anonymous API

### ISSUE THREAD

**Issue by altern8tif** [duckduckgo/zeroclickinfo-spice#2278]
API endpoint is giving a 404 response. Seems like the anonymous API only allows a limited number of requests a day.  Perhaps we can request for an API key instead.

More info on their [API](http://www.similarsitesearch.com/api.html).

---

IA Page: https://duck.co/ia/view/similar_sites

**Comment by moollaza** [comment]
Hey guys this is known problem. I've reached out a few times to the API maintainer and they haven't responded. I've looked for alternatives and there aren't many. I'm still actively looking.

**Comment by altern8tif** [comment]
Heh this is quite meta... Doing a similar site search on similarsitesearch.com.

@moollaza @MrChrisW Anyway I've discovered this [API](https://developer.similarweb.com/similar_websites_api) from SimilarWeb.  It looks pretty good in that it gives back only 20 results as well as a similarity score, although it doesn't seem like it's free.  

Perhaps DDG can get in touch with them to see if they have some sort of discounted or free price for open source projects?

**Comment by moollaza** [comment]
>Perhaps DDG can get in touch with them to see if they have some sort of discounted or free price for open source projects?

One step ahead of you :) -- I've already reached out and in touch wit them. They're being a little silly and won't give me the beta access I was promised  (and apparently will only discuss pricing on the phone) so it look l will be speaking with them some time soon.

**Comment by MrChrisW** [comment]
@moollaza Any update on the API requests for similarsitesearch.com ?

**Comment by moollaza** [comment]
I've messaged the website maintainer 3 times now, using the form on the website, still no response...

I haven't been able to actually get any useful information from SimilarWeb either, they're forcing me to do a phone call in order to get demo access to the API, which is ridiculous. Also I doubt they'll give us free access. We may have to kill this IA for now :frowning:

**Comment by moollaza** [comment]
IA was removed long ago
