### ISSUE TITLE
Flights - Link to local weather at departure/arrival airports

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#228]
Perhaps a 3rd party service could be used via another API call on page load. Or, rather a link to a search on duckduckgo that uses the Forecast spice would suffice.

------ 

IA Page:  https://duck.co/ia/view/route

**Comment by javathunderman** [comment]
@chrismorast @jagtalon Is this done? Doesn't seem to be live...

Also, the keyword used here (wn 133) won't work because of #217.

**Comment by chrismorast** [comment]
@javathunderman , I don't believe this has been implemented yet. We've actually made some pretty drastic visual updates to the flights tile that we're hoping to have implemented in the next couple weeks.

**Comment by javathunderman** [comment]
@chrismorast ping! Any updates?

**Comment by chrismorast** [comment]
Hey @javathunderman , thanks for keeping us on our toes :) - the new flight tile design is still being implemented. @moollaza , can you share the link to the GH issue for that so we can keep up with the progress?

**Comment by javathunderman** [comment]
@chrismorast Lol no problem. :)

**Comment by moollaza** [comment]
https://github.com/duckduckgo/zeroclickinfo-spice/pull/1736
