### ISSUE TITLE
Timer: Doesn't show time in title bar

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#2286]
With the recent redesign it seems this has changed. Having the time updated in the title bar would be useful e.g. when running it in a background tab.

---

IA Page:  http://duck.co/ia/view/timer

**Comment by jagtalon** [comment]
@tagawa since there can be multiple timer, not sure how it will be properly displayed in the title. Maybe just show if there's one but none if there are multiple ones? @moollaza @abeyang

**Comment by plasmoctopus** [comment]
I would just show the timer closest to finish!

**Comment by moollaza** [comment]
>  I would just show the timer closest to finish!

I think that would be fine, or even simpler, just use the most recently created timer.

**Comment by plasmoctopus** [comment]
Then you should be able to (drag&drop) reorder the timers. Then it would make more sense to show the first timer (from left to right).

**Comment by jagtalon** [comment]
One that's closest to finish seems like it's the best solution!

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
