### ISSUE TITLE
Time: Please list the time zone as well

### ISSUE THREAD

**Issue by notfoss** [duckduckgo/zeroclickinfo-spice#2288]
@MrChrisW 

For example, I searched for "sri lanka time zone". It returned the time and date, but not the time zone. It would be great if searching for time or time zone returns the time zone info as well.

------
IA Page:  http://duck.co/ia/view/time

**Comment by MrChrisW** [comment]
@notfoss Thanks for the suggestion! 

I agree it would be helpful to show the timezone information within the Time IA. The current design was created with the help of the DuckDuckGo design team, maybe they can assist with this suggestion? @abeyang @moollaza

**Comment by moollaza** [comment]
Hmm. I think we could possibly add the UTC offset to to the title?

e.g.

> Time in **Colombo, Sri Lanka** | UTC+05:30

**Comment by notfoss** [comment]
On 17 November 2015 22:16:08 GMT+05:30, Zaahir Moolla <notifications@github.com> wrote:
>Hmm. I think we could possibly add the UTC offset to to the title?
>
>e.g.
>
>> Time in **Colombo, Sri Lanka** | UTC+05:30
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/duckduckgo/zeroclickinfo-spice/issues/2288#issuecomment-157427374

Yes, that would be perfect!

**Comment by MrChrisW** [comment]
@notfoss this has been fixed in #2299 and changes will be live on duckduckgo.com soon. 

https://duckduckgo.com/?q=sri+lanka+time

Thanks again for reporting this :+1:

**Comment by notfoss** [comment]
Thanks for implementing this. Can't imagine Google listening to the users in such an open manner ;)
