### ISSUE TITLE
Symbolab example is inaccurate

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/zeroclickinfo-spice#2290]
This should read: `compute integral of x^2 dx`

Moved from: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1774

cc @Airon90

-----
IA Page: https://duck.co/ia/view/symbolab

**Comment by moollaza** [comment]
Fixed :+1: 

https://duck.co/ia/view/symbolab

**Comment by Airon90** [comment]
Thank you for your answer! Now it's clear the differences between the 4 categories!
