### ISSUE TITLE
Anime: Title should be visible without having to click on the poster

### ISSUE THREAD

**Issue by ghost** [duckduckgo/zeroclickinfo-spice#2303]
@iambibhas I think the title should be visible directly in the instant answer. Sometimes, it's not easy to see on the poster or is in Japanese. Having to click all the posters to find the correct title is annoying.

Maybe display the poster as cards, like many other Instant Answers, with the poster on top of the card and the title underneath, with maybe the year as a subtitle ?

---

IA Page:  http://duck.co/ia/view/anime

**Comment by iambibhas** [comment]
@moollaza is it possible to show title for `movies` template group?

**Comment by MrTimscampi** [comment]
Maybe use the `media` template when there are multiple items ?  
Seems like `movies` can only show an image, but `media` can show an image, a title and a rating.

**Comment by moollaza** [comment]
Yes it's certainly possible to show the titles. The `movies` group automatically adds the `is-hidden` class to the `tileBody` -- you could overwrite that to add an empty string:

https://github.com/duckduckgo/duckduckgo-answerbar-templates/blob/master/templates.js#L71

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
