### ISSUE TITLE
Anime: Support for "currently airing anime"

### ISSUE THREAD

**Issue by MrTimscampi** [duckduckgo/zeroclickinfo-spice#2304]
@iambibhas It would be a cool feature to add a specific search term for "currently airing anime"

Right now, https://duckduckgo.com/?q=currently+airing+anime only reports a "No results found", because no anime is named "currently airing".  
Ideally, the instant answer should return a list of the anime currently airing on TV when supplied with "currently airing", not an error message.

------
IA Page:  http://duck.co/ia/view/anime

**Comment by MrTimscampi** [comment]
This would probably need its own spice. I'll close this and will try to work on this as my first spice.

**Comment by iambibhas** [comment]
Hummingbird API doesn't have any method to search animes by their airing status. If you know any API that does, we can implement it. For now I am ignoring `currently airing` from the Anime IA. thanks for bringing this up.

**Comment by MrTimscampi** [comment]
I believe MyAnimeList has that capability, as AniCharts uses their API and does it.

**Comment by iambibhas** [comment]
Hmm. Anilist looks like a good source. I'll give their API a spin. If their results are good, we can move the spice to their API too. May have to talk to them about how much traffic they can handle.
