### ISSUE TITLE
Time query incorrectly triggers Indeed Jobs IA

### ISSUE THREAD

**Issue by MrChrisW** [duckduckgo/zeroclickinfo-spice#2305]
Query: [time in hobart](https://duckduckgo.com/?q=time+in+hobart)

Expected: Show current time in Hobart and deep trigger [Time IA](http://duck.co/ia/view/time)

Actual: Displays indeed job IA - Due to deep triggering only

**Screenshot**
![2015-11-25-01-time in hobart at duckduckgo](https://cloud.githubusercontent.com/assets/5282264/11395072/ce90a5be-93a3-11e5-8055-226676dddfa6.png)

------
IA Page:  http://duck.co/ia/view/indeed_jobs

**Comment by moollaza** [comment]
@MrChrisW thanks -- I've made a task for this internally because this is the result of our internal, "deep" triggering.

**Comment by MrChrisW** [comment]
Fixed internally.
