### ISSUE TITLE
Limit Cryptocurrency IA triggering for general queries

### ISSUE THREAD

**Issue by MrChrisW** [duckduckgo/zeroclickinfo-spice#2306]
Query: https://duckduckgo.com/?q=1+VPN

Actual: Cryptocurrency IA is triggered and displays rate incorrectly "Vpn%"

Expected: No IA triggered - limit query for Cryptocurrency IA to trigger on conversion to other cryptocurrecies only.

![2015-11-25-02-1 vpn at duckduckgo](https://cloud.githubusercontent.com/assets/5282264/11395140/4334c3a0-93a4-11e5-808d-8ea61276adc1.png)

________
https://duck.co/ia/view/cryptocurrency

**Comment by moollaza** [comment]
@MrChrisW thanks for reporting

>Actual: Cryptocurrency IA is triggered and displays rate incorrectly "Vpn%"

Definitely looks like a bug we should fix!

>Expected: No IA triggered - limit query for Cryptocurrency IA to trigger on conversion to other cryptocurrecies only.

I'd like to hear other opinions on that. I think its OK to show conversions to other currencies when a user searches `"1 <currency>"` as we handle that the same way for the Currency Spice: https://duckduckgo.com/?q=1+CAD&t=ffab&ia=currency

However when the amount is great (or less) than `1` we only convert it to the currency most commonly used as a reference: https://duckduckgo.com/?q=1000+cad&t=ffab&ia=currency (this is all handled by the API we're using).

We could possibly do the same for crypto currencies, or always convert to BTC, for example, if that's considered the standard that cryptocurrencies are measured against.

**Comment by MrChrisW** [comment]
>I'd like to hear other opinions on that. I think its OK to show conversions to other currencies when a user searches "1 <currency>" as we handle that the same way for the Currency Spice

@moollaza Sure I understand that's expected behavior however i think it should be limited in someway to avoid general terms or searches for example the following queries **should** trigger the cryptocurrencies IA, I think that's a little overreaching as these are fairly general terms - again just my opinion. 

+ `1 electron`
+ `1 gig`
+ `1 leaf`

Maybe we could limit the `"1 <currency>"` searches to a top few cryptocurrencies (most popular)? Anyway this could be a non-problem just thought I'd bring it up.

[cryptocurrencylist.txt](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/cryptocurrency/cryptocurrencylist.txt)

**Comment by moollaza** [comment]
> For example the following queries should trigger the cryptocurrencies IA, I think that's a little overreaching as these are fairly general terms - again just my opinion.

@MrChrisW great point, totally agreed, dictionary terms should be excluded to avoid confusion in those cases. 

>Maybe we could limit the "1 <currency>" searches to a top few cryptocurrencies (most popular)? Anyway this could be a non-problem just thought I'd bring it up.

I think that would be fine, for the dictionary words it seems like if `/s?coin/` is present it should also work:

- 1 electron coin
- 1 leafcoin
- 1 gigcoin

**Comment by MrChrisW** [comment]
Additional query from @darkestelephant #2311 `4shared`

**Comment by MrChrisW** [comment]
@moollaza Just to re-cap the decision is to make the following change:

Limit triggering of the query `1 <currency>` for the top 10 cryptocurrencies **unless** the currenccy name has `coin` in it's name, in which case allow the tirgger

Sound right?

**Comment by claytonspinner** [comment]
@moollaza @MrChrisW Hi guys. Sorry, I was going to look into this issue but then it totally fell off my radar! I can work on this.

I think `"4shared"` is triggered because the current regex accepts a missing space in the search query to allow for typing errors. For example, `"1ltc to bitcoin"` still triggers. I was thinking of changing it to require the space instead, so that only `"1 ltc"` would trigger and not `"1ltc"`. What do you think?

**Comment by MrChrisW** [comment]
@claytonspinner Hi! No problem :+1:  

> I was thinking of changing it to require the space instead, so that only "1 ltc" would trigger and not "1ltc". What do you think?

That sounds like a good fix !

@claytonspinner What are you thoughts on limiting the top 10 cryptocurrencies for queries like `1 <currency>` ? 

See @moollaza comments [above](https://github.com/duckduckgo/zeroclickinfo-spice/issues/2306#issuecomment-159985482)

**Comment by claytonspinner** [comment]
@MrChrisW

> What are you thoughts on limiting the top 10 cryptocurrencies for queries like 1 <currency> ?
I like it, along with triggering when `"coin"` is included to solve the dictionary word issue.

I was checking up on some of the currencies in the cryptocurrency list and a lot of them seem to be abandoned or no longer actively traded. There's A LOT of the currencies on that list, and I was thinking of ways to trim it down to something more reasonable. Maybe just the top 100 currencies, or only currencies with a certain threshhold of daily volume. I'll research it more first though.

**Comment by MrChrisW** [comment]
@claytonspinner Cool. 

>Maybe just the top 100 currencies, or only currencies with a certain threshhold of daily volume. I'll research it more first though. 

Sounds like a good plan! Feel free to push a PR with the changes to [cryptocurrencylist.txt](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/cryptocurrency/cryptocurrencylist.txt) and we can have a look.

**Comment by moollaza** [comment]
>Limit triggering of the query 1 <currency> for the top 10 cryptocurrencies unless the currenccy name has coin in it's name, in which case allow the tirgger

>Sound right?

@MrChrisW yup :+1:

**Comment by bsstoner** [comment]
More examples of triggering issues reported from people on Twitter:

![cqn0wutveaeia9k](https://cloud.githubusercontent.com/assets/126358/12079786/fdfb7ffc-b213-11e5-82aa-8fefe657b652.png)
![cxxhhwbuqaed_3k](https://cloud.githubusercontent.com/assets/126358/12079788/ff2e81da-b213-11e5-8a02-4e2272490572.jpg)

/cc @nilnilnil

**Comment by MrChrisW** [comment]
@bsstoner this is fixed in #2369 by @claytonspinner - these queries will not trigger
![zeroclickinfo-spice](https://cloud.githubusercontent.com/assets/5282264/12086388/bf1190a0-b304-11e5-826d-fe74c36bae4d.png)

**Comment by bsstoner** [comment]
Awesome, thank you @claytonspinner @MrChrisW!
