### ISSUE TITLE
Cryptocurrency: Limit IA showing with space in between currencies

### ISSUE THREAD

**Issue by darkestelephant** [duckduckgo/zeroclickinfo-spice#2311]
@claytonspinner 
Query: https://duckduckgo.com/?q=4shared
Displays clearly unrelated cryptocurrency info. I can't see any instances where you would search without a space between currencies
Expected no cryptocurrency information
![image](http://snag.gy/4QVL3.jpg)

------
IA Page:  http://duck.co/ia/view/cryptocurrency

**Comment by MrChrisW** [comment]
Thanks @darkestelephant ! We'll try and keep track of the issue in #2306 I've added that query `4shared`
