### ISSUE TITLE
Launch Library: Add ability to filter by time or country

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#2313]
E.g. with triggers such as "next rocket launches in Japan" or "upcoming rocket launches in December".

Originally requested on Twitter: https://twitter.com/flashdrive2049/status/671166709110349825

------ 

IA Page: https://duck.co/ia/view/launch_library

**Comment by zekiel** [comment]
//cc original author @globalspin

**Comment by globalspin** [comment]
Great idea. Filtering by date might be the simpler of the two, at least to start. Filtering by launch location is possible, but it might take some work to get from a location like "Japan" to a set of launch locations to filter on.

http://launchlibrary.net/1.1/docs/api.html#launch

I wonder how common these terms might be. If the locations are likely to be on a short list, and dates are likely to be on a short list, a first version might hard-code a conversion from a set of possible terms to the corresponding search filters on the API.

The gold star version might handle a chain of both, like "next rocket launch in Japan in December".

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.

Also IA is no longer online.
