### ISSUE TITLE
SublimePackages: Tile icons have alignment issues

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#2314]
![screen shot 2015-12-01 at 4 19 39 pm](https://cloud.githubusercontent.com/assets/126358/11514715/f64b8792-9847-11e5-8565-3ab31258ff31.png)

---

IA Page:  http://duck.co/ia/view/sublime_packages

**Comment by MrChrisW** [comment]
@bsstoner Can you be more specific as to the alignment issues? Thanks :+1:

**Comment by Jedidiah** [comment]
The clock icon is not on the baseline?

**Comment by MrChrisW** [comment]
@Jedidiah Ahh I see now

![2015-12-02-13-sublimetext package code at duckduckgo](https://cloud.githubusercontent.com/assets/5282264/11520467/b65bbb9c-98de-11e5-94dd-b5ab42ea17f8.png)

**Comment by bsstoner** [comment]
Thanks @Jedidiah. Sorry for the lack of details here @MrChrisW. I think the left icon should come down 1px too? Ideally that line at the bottom of the icon should probably align with the bottom of the number.

**Comment by moollaza** [comment]
@bsstoner I think we may want to fix this in the global CSS? Other IA's (like Jobs) seem to have the same issue:

https://duckduckgo.com/?q=javascript+jbos&t=ffab&ia=jobs&iai=1
![javascript_jbos_at_duckduckgo](https://cloud.githubusercontent.com/assets/873785/11521581/7f1392bc-987b-11e5-8fa9-acd088404b7e.png)

**Comment by moollaza** [comment]
IA is no longer online and will likely remain that way.
