### ISSUE TITLE
Timer: Start automatically if time was given as search query

### ISSUE THREAD

**Issue by jkirk** [duckduckgo/zeroclickinfo-spice#2315]
If I enter "timer 10 minutes" the timer is set to 10 minutes which is fine. It would be even better if the timer would start automatically if searched for timer with a given time.

______
IA: https://duck.co/ia/view/timer

**Comment by v2px** [comment]
I think the timer should only start automatically if the search query includes a "start" keyword so you can still preset timers without pausing and then manually resetting them every time.

**Comment by jkirk** [comment]
That would be fine too. But what about the idea to have the timer paused if the search query includes a "paused" keyword? So you still have preset timers without pausing and then manually resetting them every time AND still have a quick way to have a started timer... JM2C
