### ISSUE TITLE
Riffsy: Loader Animation is not smooth

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#2316]
https://youtu.be/6BdRYSbaAG0

Looks like the problem is that there are two keyframes named `loader-animate` and they're both doing different things.

<img width="2025" alt="screen_shot_2015-12-02_at_10_27_20_pm" src="https://cloud.githubusercontent.com/assets/81969/11551134/813e68b8-9944-11e5-9f41-7ba325feab39.png">

I suggest renaming the keyframe in Riffsy to something else. This doesn't affect anything else except for Riffsy so this is a localized problem not to worry.

\+ @bsstoner @moollaza

**Comment by bsstoner** [comment]
gah! it's conflicting with the global one we just added, sorry about that. Another option is maybe we could switch over to use the new template helper? I think it should just be `{{{loader 'white'}}}` It will probably require some modification to the existing Riffsy JS/CSS to make it work though...I'm not sure how involved that would be.

**Comment by bsstoner** [comment]
Oh, but it's using the built-in image templates, so this wouldn't work. You could call `Handlebars.helpers.loader('white')` directly I guess. Or maybe we should just fix this in the global image templates now and be done with it ;)
