### ISSUE TITLE
InTheaters: Should support British spelled trigger words

### ISSUE THREAD

**Issue by viluon** [duckduckgo/zeroclickinfo-spice#2321]
@jagtalon 

It'd be nice if InTheaters also reacted to queries like "currently in theat**res**". Also, queries like "new movies/films" and "latest movies/films" could be added.

*Update from discussion:* Also "currently in cinemas"`

------
IA Page:  http://duck.co/ia/view/in_theaters

**Comment by jagtalon** [comment]
@viluon I think that's a good idea!

**Comment by viluon** [comment]
@jagtalon Thank you! Also, just realized that British people would rather say "currently in cinemas"... Since I am not a native speaker, I'd recommend someone else to design the possible triggers instead :smiley:

**Comment by mintsoft** [comment]
@viluon that's indeed correct. We exclusively refer to 'the movies' as the cinema, theatre is usually reserved for plays, performances et cetera.

**Comment by jagtalon** [comment]
@mintsoft Oh, I didn't know that! Thanks for the info.

**Comment by mintsoft** [comment]
@jagtalon I'm always at your disposal for information about :tea and associated linguistics!

**Comment by jagtalon** [comment]
@mintsoft sweet! Ok important question: do you drink :tea: on its own or do you add honey or do you add milk?

**Comment by mintsoft** [comment]
@jagtalon Depends on the type of :tea: of course!

**Comment by moollaza** [comment]
@mintsoft @jagtalon Personally:

Mint tea + Honey
Orange Pekoe + Milk

**Comment by mintsoft** [comment]
@moollaza I'll agree with that; although I do like a good cup of lapsang souchong

**Comment by jagtalon** [comment]
@moollaza @mintsoft yeah, uhm, I put milk in all my teas so I think I'm going to show myself out.
