### ISSUE TITLE
GoWatchIt: bad result for "stream star wars online"

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#2323]
1) Why does this show when the only option is Fandango and I was only looking for options to "stream online"?
2) What is up with the `$&` in the Fandango tile?

<img width="1280" alt="screen shot 2015-12-06 at 6 11 00 pm" src="https://cloud.githubusercontent.com/assets/126358/11616260/ed911530-9c44-11e5-913f-363a61347acb.png">

------
IA Page:  http://duck.co/ia/view/go_watch_it

**Comment by moollaza** [comment]
@bsstoner I think the lack of results is due to their API showing us results for "The Force Awakens" which isn't released yet, hence the Fandango result. I'm not sure if there's a better way to disambiguate between movies...

@jagtalon can you look into the weird price issue?
