### ISSUE TITLE
Have I Been Pwned: Add message for zero results (i.e. not comprised)

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#2324]
@b2ddg 

When no results are found, a message should be displayed saying something like "To the best of our knowledge, [someperson@example.com] has not been compromised".
https://duckduckgo.com/?q=someperson%40example.com+pwned

---

IA Page:  http://duck.co/ia/view/pwned

**Comment by b2ddg** [comment]
Interesting, there was supposed to be a fallback message displayed when no result was found, https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Pwned.pm#L14. It's possible the update to the duckduckgo repo wasn't released. Thanks for the heads up!
