### ISSUE TITLE
Have I Been Pwned: Nothing happens when clicking result item boxes

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#2325]
@b2ddg 

Items in the IA results list look clickable but nothing happens. They should either be given a target link or made unclickable.
https://duckduckgo.com/?q=pwned+test%40example.com&ia=answer&iai=1

------
IA Page:  http://duck.co/ia/view/pwned

**Comment by b2ddg** [comment]
@moollaza Is there a quick way to link out from the tile, or does this need to updated at the template level?

**Comment by moollaza** [comment]
Whoops, I thought I added that in. We need to set a `url` property for each `item`.

I think we'll need to use the same `url` for each tile. It should look something like: `https://haveibeenpwned.com/account/<email>`
