### ISSUE TITLE
Feedback for Sentiment Analysis IA (PR #2317)

### ISSUE THREAD

**Issue by gpestana** [duckduckgo/zeroclickinfo-spice#2327]
The sentiment analysis IA (PR #2317) has now support for overall document analysis and document's entity analysis.

As an example, if we search for 'sentiment analysis of http://paulgraham.com/bias.html', we get the following result:
![In the first iteration] (http://i.imgur.com/99lWpuT.png)

I believe this IA can be helpful when making sense of large texts, for example in research or scholar works. This Spice is using the IBM's [alchemy api](alchemyapi.com).

Do you have any ideas how we could improve this IA?

**Comment by moollaza** [comment]
@gpestana I typically leave feedback in the PR, and discuss changes/improvements there. I'll close this and continue over there
