### ISSUE TITLE
Forecast: Unicode icon not showing up appropriately

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/zeroclickinfo-spice#233]
![fe_icon](https://f.cloud.github.com/assets/347240/1282557/e3484866-2f75-11e3-8e8c-c3a245f3fce5.PNG)

**Comment by MrChrisW** [comment]
This issue is resolved. Tested on all major browsers.

![2016-01-05-32-weather at duckduckgo](https://cloud.githubusercontent.com/assets/5282264/12118389/1d03c582-b401-11e5-9285-379dbc3b418c.png)

https://www.browserstack.com/screenshots/bd23e2d7ee04c120393ef49974a4bcaaa48ba8d9
