### ISSUE TITLE
Forecast: Australian postcodes

### ISSUE THREAD

**Issue by statusred** [duckduckgo/zeroclickinfo-spice#2332]
Weather doesn't seem to work with Australian postcodes, but the first search is for willyweather.com.au and it has the correct location.

---

IA Page:  http://duck.co/ia/view/forecast

**Comment by moollaza** [comment]
@statusred thanks for reporting this. Can you please give us some examples?

**Comment by statusred** [comment]
weather sydney = works
weather 2000 doesn't

Australian postcodes are 4 numbers, the ones ended in '000' are middle of state captial city.

**Comment by MrChrisW** [comment]
@moollaza This would be an internal issue as the forecast IA is triggered internally.

**Comment by mrshu** [comment]
Does this issue still persist?

[`weather australia 2000`](https://duckduckgo.com/?q=weather+australia+2000&ia=weather) does actually trigger the Forecast Spice for me.

**Comment by statusred** [comment]
It does.

Also **weather <city name>** only seems to work on a few major cities. 

I'm not sure if this related but search **weather newcastle** showed the weather for Anchorage, AK. I was expecting Newcastle, Australia or Newcastle, UK to show as I guessed they be the two most famous Newcastles.

**Comment by statusred** [comment]
I tried searching for **weather australia 2000** again it worked, it didn't 5 mins ago, but **weather australia 4000** doesn't even after a few tries

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.

This IA was never intended to support searches by zip/postal code.
