### ISSUE TITLE
GoWatchIt: Ensure we cache compiled regex in variables, cleanup code

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2340]
We're using several identical regular expressions here that are each being compiled separately. They should all be stored in variables so they're only compiled once which should give a small performance boost.

The code may also need a refactor/reorganizing.

---

IA Page:  http://duck.co/ia/view/go_watch_it

**Comment by tagawa** [comment]
@moollaza Just to clarify - do you mean the regular expressions in this part of the code? https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/go_watch_it/go_watch_it.js#L318

**Comment by sahildua2305** [comment]
@moollaza This should be closed now via #2823 ?

**Comment by moollaza** [comment]
IA was removed long ago
