### ISSUE TITLE
Quixey: Should default to custom `rating_avg` for more accuracy

### ISSUE THREAD

**Issue by anothernewphone** [duckduckgo/zeroclickinfo-spice#2342]
The IA for "wolfram alpha mobile app" shows the wrong rating for the WA app.  It shows the apps are rated .5/5, when it should show 4/5.

------
IA Page:  http://duck.co/ia/view/apps

**Comment by moollaza** [comment]
Looks like the API response is actually providing a rating of `0.71 hence the half star.

We could possibly use the `custom.avg_rating` property which seems to be correct and fallback to the `item.rating` when not present.
