### ISSUE TITLE
Google Plus Profiles: Titles need consistent height, text overflow needs to be hidden

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2344]
This IA is looking pretty bad right now...lots of visual breakage: https://duckduckgo.com/?q=google%2B+duckduckgo&t=ffcm&ia=social&iai=11

The tiles need to have consistent heights and the text needs to be prevented from overflowing its container (see the last tile, with a very long name)

Would any @duckduckgo/community-leaders or @duckduckgo/duckduckhack-mentors be interested in tackling this one?

With the `elClass` property we can center the text with `text-center` instead of CSS. We should also remove the CSS for the `display: table-cell` and vertical alignment.

Consistent height may need to be applied with CSS, but ideally we should use a `variant` for a `tileTitle: '3line-large'` which should normalize the heights.

------
IA Page:  http://duck.co/ia/view/google_plus

**Comment by javathunderman** [comment]
@moollaza I'll take a look at this one...You're right, seems to be a lot of breakage here.

**Comment by davidofferman** [comment]
I hopped in on this issue, I hope you don't mind @javathunderman. I didn't see any repo's on your profile that were working on this yet.

**Comment by javathunderman** [comment]
no problem! Got a bit busy. :)

**Comment by MrChrisW** [comment]
Fixed by @davidofferman in #2359 - Thanks again!
