### ISSUE TITLE
Political Polls: Results don't change with different queries

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#2347]
@alexander95015 

Whatever the search query, the polls displayed are the same, for example [election poll](https://duckduckgo.com/?q=election+poll&ia=polls), [healthcare poll](https://duckduckgo.com/?q=healthcare+poll&ia=polls), [economy poll](https://duckduckgo.com/?q=economy+poll&ia=polls).

------
IA Page:  http://duck.co/ia/view/political_polls

**Comment by alexander95015** [comment]
@tagawa The source doesn't seem to provide a way to search and filter for the query.
(http://elections.huffingtonpost.com/pollster/api)

**Comment by tagawa** [comment]
Ah, thanks @alexander95015. I thought they could handle search terms as well but it seems not.

**Comment by moollaza** [comment]
@tagawa @alexander95015 if those queries trigger the IA but don't modify the results, I would consider that a relevancy bug. We should prevent it from triggering on "healthcare poll", "economy poll" etc

**Comment by alexander95015** [comment]
@moollaza That is true. How would we go about making it trigger on something like "opinion poll", "election poll", etc?

**Comment by moollaza** [comment]
@alexander95015 good question! Checkout my comment here: https://github.com/duckduckgo/zeroclickinfo-spice/issues/2348#issuecomment-166322213

We either need to use an explicit list of phrases and ensure there's no remainder to the query, or add a regex to our existing handle.
