### ISSUE TITLE
Political Polls: Triggering needs to be reigned in -- triggers on anything with "poll"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2348]
Looks like just about any query containing "poll" is triggering this IA. We definitely need to reign this in!

Examples:
- [poll dance](https://duckduckgo.com/?q=poll+dance&t=ffab&ia=polls)
- [jobs poll](https://duckduckgo.com/?q=jobs+poll&t=ffab&ia=polls)
- [poll poll](https://duckduckgo.com/?q=poll+poll&t=ffab&ia=polls)

/cc @alexander95015 

---

IA Page:  http://duck.co/ia/view/political_polls

**Comment by moollaza** [comment]
We need to determine a set of phrases we want to trigger this and use then as trigger words, or use a regex in the `handle` to verify that the query matches our expectation.

**Comment by alexander95015** [comment]
There might be a substantial number of trigger words, like candidate names, election years, states, among other things.

**Comment by davidofferman** [comment]
I was thinking you could make the trigger words include the `topic` values for the Charts API (remove delimiters), along with some predefined values such as voters, elections, presidential, and years.

Then once a request comes in, you can filter the results by using the `topic` that most closely matches the query, which would solve the issue some users reported with the results not changing. If the term is too generic, then you just return all the charts.

At this time it doesn't appear the HuffPost API allows for multiple topics per request (from what I can tell and tested). Possibly we could make multiple API requests and merge the results.

**Comment by moollaza** [comment]
@alexander95015 for now we need to choose a reasonable subset that are likely to occur, or narrow it by required "election poll" as the trigger.

Right now it's way over triggering and showing irrelevant info is a major concern.

@davidofferman thanks for chiming in! Are the list of topics static? Can we put them in a YAML file?

**Comment by moollaza** [comment]
Hey guys anyone interested in fixing this? Aside from the broad triggering, I didn't realize before that we're not running any relevancy check against the results and the query.

This means this IA is **way** too broad because it's surfacing the same results for any query that mentions "polls" -- even if they're not political: https://duckduckgo.com/?q=basketball+polls&t=ffab&ia=polls. We need to use a relevancy block to ensure the polls we show are related to the query, and/or use those topics to tailor the results to the query, when one of those terms is there. 

>At this time it doesn't appear the HuffPost API allows for multiple topics per request (from what I can tell and tested). Possibly we could make multiple API requests and merge the results.

@davidofferman that would be possible to. The `handle` could `return` an array of topics, when necessary, and the JS could grab those and load additional results. That functionality may be better suited to a V2 though. For now we need to reign this thing in and make sure its only triggering when we have a "political" query.

**Note**: We're probably going to take this offline for now until it's fixed. Showing false positives is a big problem.

**Comment by davidofferman** [comment]
Hi,
Is there any way we can store the API result on DuckDuckGo's servers (update on first request of the day) and then have the spice itself return a partial result of the actual data? The topics that are available are not the greatest at filtering data, and there is no good way to get the new topics that will be added in the future.

I would like to be able to filter charts by candidates names, years, state, and other details that are available in the JSON response. 

If that isn't possible, I guess we could parse the data on the client side, but then we would have the spice triggering a lot for no good reason, which is what we are trying to prevent.

**Comment by moollaza** [comment]
> Is there any way we can store the API result on DuckDuckGo's servers (update on first request of the day) and then have the spice itself return a partial result of the actual data?

@davidofferman unfortunately not, we've never needed, or done something like that. Typically we just use API's that do all the heavy lifting for us :)

> I would like to be able to filter charts by candidates names, years, state, and other details that are available in the JSON response.

That would definitely be awesome...

>If that isn't possible, I guess we could parse the data on the client side, but then we would have the spice triggering a lot for no good reason, which is what we are trying to prevent. 

Exactly. It seems like with the current capabilities of the IA we're going to have to greatly reduce its query space to more generic queries that are well served by the API topics.

However, I think we should also reach out to the API maintainers to explain to them what we're doing with the API to see if they're willing to implement search functionality on their end.

Dealing with these "APIs" that just provide a JSON dump in a more clever way is something I'd like us to do, but right now it's not a top priority. Ideally it'd be great if we could proxy the request to a service that doesn't what you've described above: grabs a fresh copy of the JSON daily/hourly/etc and provides filtering functionality on-top of it so we don't need to do it client side.

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.

**Comment by moollaza** [comment]
This IA is also offline
