### ISSUE TITLE
Time: No IA for Gurgaon (India) but source has it 

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/zeroclickinfo-spice#2353]
@MrChrisW 

sedition on IRC reported that https://duckduckgo.com/?q=time+in+gurgaon  doesn't show the Time IA. Noting that timeanddate.com have it on their site. 

------
IA Page:  http://duck.co/ia/view/time

**Comment by MrChrisW** [comment]
Thanks @zekiel added to #1730
