### ISSUE TITLE
Sunrise/Sunset: Netherlands or Amsterdam wrong

### ISSUE THREAD

**Issue by preemeijer** [duckduckgo/zeroclickinfo-spice#2354]
@iambibhas 

Hello,
@moollaza talked about this ia so I want to test this for myself, so I can tell others about this ia.
It will always give me Amsterdam Island (that is not here)

The following happens if I want to search with the keywords sunrise Netherlands:
![screenshot-sunrise-netherlands](https://cloud.githubusercontent.com/assets/356869/11994766/a2462350-aa44-11e5-8aaa-e20575c70e1b.png)

The following happens with the keywords sunrise Amsterdam:
![screenshot-sunrise-amsterdam](https://cloud.githubusercontent.com/assets/356869/11994772/c2796b46-aa44-11e5-9235-a85de50faf18.png)

The following happens is I put in sunrise Amsterdam Netherlands:
![screenshot-sunrise-amsterdam-netherlands](https://cloud.githubusercontent.com/assets/356869/11994774/dc8997fe-aa44-11e5-964e-cb05df9e850f.png)

---

IA Page:  http://duck.co/ia/view/sun_rise_set

**Comment by moollaza** [comment]
This a problem with our relevancy checking. We need to do a better job of taking the city + country and comparing it to the results from their API.

For some reason they give us Amsterdam in the French Southern Territories as the first result, ahead of Amsterdam in the Netherlands.
