### ISSUE TITLE
Forecast: Incorrect results for searched location

### ISSUE THREAD

**Issue by SiemEik** [duckduckgo/zeroclickinfo-spice#2363]
Weather Ireland gives you the weather for Dublin Texas :(

------
IA Page:  http://duck.co/ia/view/forecast

**Comment by MrChrisW** [comment]
@SiemEik Thanks for reporting this issue. There are currently a few known relevancy issues internally with the forecast instant answer, these are being investigated. Hopefully relevancy will improve over time with further development.

**Comment by edgesince84** [comment]
this issue is a duplicate of https://github.com/duckduckgo/zeroclickinfo-spice/issues/2362 and we'll be working toward addressing it!  thanks
