### ISSUE TITLE
GoWatchIt: Incorrect availability for DVD title (API Issue)

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/zeroclickinfo-spice#2365]
@plexusent  there is an error with this IA source. "Groundhog Day" is not available for streaming but says so from GoWatchIt

![screen shot 2015-12-29 at 2 48 56 pm](https://cloud.githubusercontent.com/assets/1846953/12040980/6bd1002e-ae3b-11e5-83c0-6fa69ebca80a.png)

---

IA Page:  http://duck.co/ia/view/go_watch_it

**Comment by MrChrisW** [comment]
Hey @zekiel this source says the title should be available http://www.flixlist.co/titles/563104 
Can you double check it's not available with your US subscription

**Comment by MrChrisW** [comment]
Confirmed this is an external API issue. GoWatchIt listed this title as available on-demanding/streaming when it's DVD online.

See:
http://gowatchit.com/movies/groundhog-day-30385
![2016-01-11-30-watch groundhog day online and on dvd _ gowatchit](https://cloud.githubusercontent.com/assets/5282264/12236291/dfc19c64-b8b3-11e5-8a39-b562b187c1ea.png)

**Comment by jagtalon** [comment]
@zekiel @MrChrisW maybe it's not _entirely_ false. If you look at Moreflix, it is available on Netflix, but in other countries: http://www.moreflicks.com/titles/movies_groundhog-day_1993

I wonder if it's possible to get that kind of data from Gowatchit CC @moollaza

**Comment by jagtalon** [comment]
<img width="1136" alt="screen shot 2016-01-17 at 6 18 53 pm" src="https://cloud.githubusercontent.com/assets/81969/12380693/f9896e46-bd46-11e5-9769-f266acc71de2.png">

**Comment by zekiel** [comment]
good point @jagtalon  

@MrChrisW  thanks for the additional help.

flags would be helpful if so :)

**Comment by moollaza** [comment]
IA no longer online
