### ISSUE TITLE
Time: 24 hour time

### ISSUE THREAD

**Issue by Darkyenus** [duckduckgo/zeroclickinfo-spice#2372]
@MrChrisW 

Can you please display time in 24 hour mode for users in countries which use that time? AM/PM for times especially around noon/midnight can get a bit confusing for users which are not used to it.

Thanks!

---

IA Page:  http://duck.co/ia/view/time

**Comment by MrChrisW** [comment]
Hey @Darkyenus, thanks for the suggestion  - We'd love to implement this, maybe even the ability to interactively switch between 24/12 hour times. 

I've found it a little difficult to find reliable and accurate information on which continues are 24hrs vs 12hrs. 

The following links are useful:

+ https://en.wikipedia.org/wiki/Date_and_time_representation_by_country#Time
+ http://travel.stackexchange.com/questions/34950/which-large-countries-use-12-hour-time-format-am-pm
+ https://www.reddit.com/r/MapPorn/comments/1ktabp/1224_hour_time_format_used_around_the_world/

@jagtalon @moollaza thoughts?

**Comment by moollaza** [comment]
@MrChrisW @Darkyenus if we trust Moment.js, we could use their Locale support. It seems to change to 24hr time for certain locales.

http://momentjs.com/ -- If you go here and click some of the buttons at the bottom (e.g. Ireland) it switches to 24hour. I'm not sure how to just request the time in the localized format though...

**Comment by moollaza** [comment]
Read the docs, I think `moment.format('LT') would do it

**Comment by MrChrisW** [comment]
@moollaza First we need to convert the Time spice to use moment.js! [#1554](https://github.com/duckduckgo/zeroclickinfo-spice/issues/1554#issuecomment-75188309) - I'll try and start this during the week.

**Comment by MrChrisW** [comment]
@moollaza Looks like moment.js will default to the English locate unless specified - see http://stackoverflow.com/questions/25725882/locale-detection-with-moment-js 

Need to supply moment with the users locate.

**Comment by bsstoner** [comment]
Another piece of user feedback about this:
**time cairo**
[https://duckduckgo.com/?q=time%20cairo](https://duckduckgo.com/?q=time%20cairo)
_"When searching for "time Kairo" the result is in 12 hour clock. I would like to see it in 24 hour."_

**Comment by Qwertie-** [comment]
I am in a place which uses 12 hour time but use 24 hours myself so an option to switch would be much better.

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
