### ISSUE TITLE
Timer: Shouldn't auto-start timer when the query is `timer`

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2380]
Seeing as the user hasn't specified a time for the timer, it's unexpected that it would start a 1 minute countdown.

We can still suggest a time span (maybe something a little longer, like 10 min or 3 mins would be ideal?), but we shouldn't autostart a count-down unless they specify a time.

------
IA Page:  http://duck.co/ia/view/timer

**Comment by MrChrisW** [comment]
Fixed in #2381 by @davidofferman
