### ISSUE TITLE
LeakDB - API is shutting down

### ISSUE THREAD

**Issue by davidofferman** [duckduckgo/zeroclickinfo-spice#2385]
Hello,
The API (and service) for LeakDB is shutting down at the end of January 2016. Since we already have an alternative AI called "Pwned", which I believe is almost the same service (other than password search), we could probably safely remove LeakDB from the IA's.

Also it seems that the LeakDB API isn't even working properly at the moment. I believe the API takes too long and DuckDuckGo just terminates the request after a few seconds.

LeakDB Shutdown Notice
https://leakdb.abusix.com/
https://twitter.com/abusix/status/681812050394386432

----
LeakDB: https://duck.co/ia/view/leak_db
Pwned: https://duck.co/ia/view/pwned

**Comment by moollaza** [comment]
@davidofferman thanks for letting us know!

@MrChrisW has been awesome enough to remove it for you :+1:
