### ISSUE TITLE
Geometry: expand trigger space to cover more common queries

### ISSUE THREAD

**Issue by russellholt** [duckduckgo/zeroclickinfo-spice#2386]
let's add "area of" and "perimeter of" and similar terms to expand the trigger space.

the query "area of a square" should definitely trigger this. it seems to me that "geometry square" is a fairly unlikely query when wondering about the area.

---

IA Page:  http://duck.co/ia/view/geometry

**Comment by jagtalon** [comment]
This does trigger on things like "area of a square", but it's not ideal because you'd still need "geometry": 

https://duckduckgo.com/?q=geometry+area+of+rectangle&ia=geometry

**Comment by bsstoner** [comment]
**the volume of cylinder**
[https://duckduckgo.com/?q=the%20volume%20of%20cylinder](https://duckduckgo.com/?q=the%20volume%20of%20cylinder)

**Comment by adityatandon007** [comment]
I'll will take this

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
