### ISSUE TITLE
No PGP keys for e-mail?

### ISSUE THREAD

**Issue by kewde** [duckduckgo/zeroclickinfo-spice#2389]
Hi,

I'd like to propose the usage of PGP encryption for the email addresses such as:
quackslack@duckduckgo.com
merch@duckduckgo.com
And others..

DuckDuckGo is a search engine loved by people who care about their privacy, yet no PGP for e-mail? :'(

**Comment by MrChrisW** [comment]
@kewde Completely agree! I've requested this before. The best place to discuss this request is on the duck.co community as it doesn't relate to the Instant Answer development - https://duck.co/forum/general
