### ISSUE TITLE
Nutrition: Triggers on "count calories"

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#2419]
"count calories" shouldn't show this IA because we're not specifying any food:

<img width="837" alt="screen shot 2016-01-18 at 2 06 37 pm" src="https://cloud.githubusercontent.com/assets/81969/12400220/c7f311b0-bdec-11e5-8be6-94ebaf3e0678.png">

**Comment by MrChrisW** [comment]
Don't think the wording length should extend past the dropdown symbol... looks a little strange 

![2016-01-20-44-count calories at duckduckgo](https://cloud.githubusercontent.com/assets/5282264/12450150/cee9b312-bfbc-11e5-954b-9af66ff818ae.png)
