### ISSUE TITLE
Timer: No "i" infobox button

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#2429]
The `i` icon to bring up the infobox is not visible: https://duckduckgo.com/?q=timer&ia=timer

---
https://duck.co/ia/view/timer

**Comment by moollaza** [comment]
Looks like the metadata was a little broken. I've fixed it and this should go live with the next deploy

**Comment by GuiltyDolphin** [comment]
@moollaza @tagawa Looks fixed to me. https://duckduckgo.com/?q=timer&ia=timer

**Comment by tagawa** [comment]
Oh yes, thanks.
