### ISSUE TITLE
A bit strange results for query

### ISSUE THREAD

**Issue by extempl** [duckduckgo/zeroclickinfo-spice#2440]
Tried to search more info about https://developers.google.com/structured-data/actions/watch-movies:
https://duckduckgo.com/?q=knowledge+panel+movie+card+watch+google, but instead received multiple links to main pages of Google services.

**Comment by MrChrisW** [comment]
@extempl Thanks for taking the time to report an issue with the search results. As this doesn't have anything to do with the DuckDuckGo spice instant answers I'll close this issue. 

The best place to report these types of problems would be https://duckduckgo.com/feedback
