### ISSUE TITLE
Images: 

### ISSUE THREAD

**Issue by kranthic** [duckduckgo/zeroclickinfo-spice#2442]
![screen shot 2016-01-25 at 11 39 08 am](https://cloud.githubusercontent.com/assets/4584160/12562166/86ab9490-c358-11e5-83c3-ac3ca01bb9ff.png)
searching for 202 754 8440 phone number is showing explicit images

------
IA Page:  http://duck.co/ia/view/images

**Comment by moollaza** [comment]
@kranthic thanks for this, we're removing the images.
