### ISSUE TITLE
News: 

### ISSUE THREAD

**Issue by tebicap** [duckduckgo/zeroclickinfo-spice#2443]
can you add "NOTICIAS" keyword in addition to "NEWS" for support spanish speakers? :)
------
IA Page:  http://duck.co/ia/view/news

**Comment by GuiltyDolphin** [comment]
@tebicap At the moment we [do not accept](http://docs.duckduckhack.com/backend-reference/triggers-handle-functions.html#triggers-in-multiple-languages) non-English languages in triggers (there would be too much duplication and inconsistency). Hopefully this will be sorted globally at some point.

**Comment by MrChrisW** [comment]
Closing this now. Tnx for the quick response @GuiltyDolphin :smiley: 

@tebicap You can keep up-to-date with any changes that happen with non-english language triggers on https://duck.co/blog or follow https://twitter.com/duckduckgo 

Gracias!
