### ISSUE TITLE
Whois: No "i" icon is displayed

### ISSUE THREAD

**Issue by swapagarwal** [duckduckgo/zeroclickinfo-spice#2451]
@MrChrisW @b1ake 

The ```i``` icon that brings up the infobox is not visible.

Sample query: https://duckduckgo.com/?q=who+owns+duckduckgo.com&ia=whois

------
IA Page:  http://duck.co/ia/view/whois

**Comment by MrChrisW** [comment]
Thanks for reporting this. Issue with metadata.

**Comment by pecey** [comment]
Infobox is visible to me.

**Comment by moollaza** [comment]
@swapagarwal @pecey looks like I fixed it :+1:
