### ISSUE TITLE
Dictionary Definition: Sync up with Pronounce Command

### ISSUE THREAD

**Issue by vCillusion** [duckduckgo/zeroclickinfo-spice#2454]
When we search **Pronounce say**
 Dictionary defines _"pronounce"_. 

> Need to define "say" instead.

------
IA Page:  http://duck.co/ia/view/dictionary_definition

**Comment by moollaza** [comment]
@vCillusion the Forvo Instant Answer is being revived in #2444 -- it will trigger on the word "pronounce" and provide the audio for the word pronunciation :+1:
