### ISSUE TITLE
Timer: Extend the trigger words

### ISSUE THREAD

**Issue by vCillusion** [duckduckgo/zeroclickinfo-spice#2460]
@mattr555 

Let it trigger on "start timer", "start countdown timer", "start timer with 5 minutes", and "online countdown timer alarm"

------
IA Page:  http://duck.co/ia/view/timer

**Comment by jagtalon** [comment]
Thanks, @vCillusion this is useful!

**Comment by GuiltyDolphin** [comment]
@jagtalon Resolved in #2459.
