### ISSUE TITLE
Whois : Not working with xyz domains

### ISSUE THREAD

**Issue by pecey** [duckduckgo/zeroclickinfo-spice#2461]
`whois edgx.xyz` doesnt return a result, while it is registered.

https://who.is/whois/edgx.xyz

IA : https://duck.co/ia/view/whois

**Comment by gautamkrishnar** [comment]
it may have whoisguard enabled

**Comment by altern8tif** [comment]
API seems to be working fine.  I'm getting a result...

<img width="765" alt="screen shot 2016-02-01 at 2 22 51 pm" src="https://cloud.githubusercontent.com/assets/5793364/12710217/568e7902-c8ef-11e5-968a-b597c748472a.png">

**Comment by swapagarwal** [comment]
@altern8tif I'm getting the expected result for `edgx.xyz` but not for `edge.xyz` 
Can you check?

**Comment by altern8tif** [comment]
Strangely it's not working for `edge.xyz`.

But the API seems to be returning a [JSON result](https://www.whoisxmlapi.com/?domainName=edge.xyz&outputFormat=json)...

**Comment by pecey** [comment]
![screenshot from 2016-02-01 13-22-28](https://cloud.githubusercontent.com/assets/11463842/12711551/e1c4584c-c8e6-11e5-9825-bb2fe9ead7b6.png)


It doesn't work for me.

**Comment by gabhi** [comment]
Looks like it is working for me

**Comment by altern8tif** [comment]
Hmmm it also works for me now...

@moollaza seems like it's quite intermittent.  How can we tell if it's caused by the API or DDG itself?  Doesn't bode well for user experience if we can't predict when it will work...

**Comment by moollaza** [comment]
@altern8tif I suspect it’s the whois API being slow. I've seen it act up a couple times recently but didn't think much of it. We may need to increase the timeout if the API is taking too long to return, or have them speed things up!

Your should see a call in the network tab of dev tools from DDG to their API. If the response is an empty function call, then we didn't get any JSON from them. By default we have a 5000ms timeout I think

**Comment by moollaza** [comment]
Yup I just tried `abc.xyz` and the response initially 404'd then worked, taking 5100ms. I think the call is timing out. Will speak to the team...

**Comment by pnpninja** [comment]
Works fine. Checked as of 7 Feb

**Comment by moollaza** [comment]
I've updated the timeout value for the endpoint. Set it to 5200ms which is hopefully enough. I can bumb it to 5500 if needed.

**Comment by moollaza** [comment]
I don't believe the change has gone live yet, I'm still experiencing problems when trying domains that haven't been searched (and cached) yet.

**Comment by jagtalon** [comment]
@moollaza thanks! Looks like this is working already!
