### ISSUE TITLE
ExpandURL: 

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2462]
Looks like this IA isn't working correctly anymore. There seems to be API responses coming back but the tab is not showing!

Anyone interested in investigating further?
/cc @duckduckgo/instant-answer-maintainers 

------
IA Page:  http://duck.co/ia/view/expand_url

**Comment by Mailkov** [comment]
@moollaza I'll work on this

**Comment by moollaza** [comment]
@Mailkov thanks! :+1:

**Comment by Adman** [comment]
@moollaza fixed https://github.com/duckduckgo/zeroclickinfo-spice/pull/2464

**Comment by jagtalon** [comment]
Fixed in https://github.com/duckduckgo/zeroclickinfo-spice/pull/2464. Thanks, @Adman!
