### ISSUE TITLE
InTheaters: rotton tomatoes icon displaying double the size on retina screens

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/zeroclickinfo-spice#2469]
@jagtalon 

On retina screens the rotten tomatoes icon is twice the size it should be.

Non-retina (correct)
![screen shot 2016-02-02 at 1 57 35 pm](https://cloud.githubusercontent.com/assets/7061920/12765816/40b39452-c9b5-11e5-9370-d5048331ff32.png)

Retina (Incorrect)
![screen shot 2016-02-02 at 1 58 52 pm](https://cloud.githubusercontent.com/assets/7061920/12765824/4a4db434-c9b5-11e5-848e-8f6b0070b7aa.png)

------
IA Page:  http://duck.co/ia/view/in_theaters

**Comment by moollaza** [comment]
@duckduckgo/instant-answer-maintainers -- anyone interested in investigating this? I suspect it's a CSS issue...

**Comment by simbs** [comment]
@chrismorast @moollaza [the CSS](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/in_theaters/in_theaters.css#L1-L5) doesn't specify the size of the icon, so it's just displaying the larger image that is served for retina displays. Setting `max-width: 26px;` , the same size as the normal icon, should do.
