### ISSUE TITLE
InTheaters: Update detail pane layout

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/zeroclickinfo-spice#2470]
@jagtalon 

Seems that we've had a regression in the layout of the movie information in the detail pane.
Anyone out there open to updating this?

Currently in production:
![screen shot 2016-02-02 at 2 11 54 pm](https://cloud.githubusercontent.com/assets/7061920/12766154/1c9c09a8-c9b7-11e5-876e-f4b232fb08b7.png)

Intended layout:
![screen shot 2016-02-02 at 2 10 46 pm](https://cloud.githubusercontent.com/assets/7061920/12766174/34a00c70-c9b7-11e5-9dc8-34033df44a05.png)

General specifications:
![specs](https://cloud.githubusercontent.com/assets/7061920/12766309/0b8051fa-c9b8-11e5-9395-16b62a34ba22.jpg)

---

IA Page:  http://duck.co/ia/view/in_theaters

**Comment by jagtalon** [comment]
Thanks, @chrismorast!
