### ISSUE TITLE
Riffsy: Restrict character matching to Emoji only 

### ISSUE THREAD

**Issue by Dasrakel** [duckduckgo/zeroclickinfo-spice#2473]
Gifs that match Emoji zeroclick doesn't just match Emoji, but other high unicode characters as well. It should restrict it to only match the appropriate range of characters.

------
IA Page:  http://duck.co/ia/view/riffsy
Maintainer: @bryanhart

**Comment by jagtalon** [comment]
Thank you @Dasrakel!

**Comment by moollaza** [comment]
@Dasrakel would you care to fix it?

**Comment by jagtalon** [comment]
Something like this would be perfect: https://github.com/twitter/twemoji/blob/gh-pages/twemoji.js#L236

**Comment by Dasrakel** [comment]
Yes, I would, should learn how to contribute to something like this eventually anyway.

**Comment by swapagarwal** [comment]
Can you give an example of a false triggering, i.e. a query on which ddg is showing gifs but is not an emoji?

**Comment by moollaza** [comment]
> Can you give an example of a false triggering, i.e. a query on which ddg is showing gifs but is not an emoji?

I don't believe we're showing incorrect results, but we're still firing off a useless API call, and when we trigger IA's the display system assumes we're going to show that IA, so if we can prevent making useless API calls, we definitely should!

**Comment by Dasrakel** [comment]
Some examples:

"語" (Japanese glyph for "language")
"Ф" (Cyrillic letter "Ef")
"𓆣" (Egyptian hieroglyph "beetle")
"Σ" (Greek capital letter sigma)

I do think the results are actually _wrong_. But you can blame Giphy if you want.
Giphy shows the identical results all for things it can't match: walrus, Steve Carell, toddler, spongebob, every time.

**Comment by moollaza** [comment]
@Dasrakel thanks for point those out! I didn't realize their API was actually providing results for those. In that case this is definitely a higher priority and needs to be addressed ASAP. Those are definitely irrelevant results.
