### ISSUE TITLE
RubyGems IA - Lots of useful info from API not being used

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#248]
There's tons of great info for each list item coming through the API such as:

- # of downloads
- date last update
- link to homepage (though this will be linked from the rubygems.com link we send the user too
- Gem version

https://duck.co/ia/view/ruby_gems

**Comment by GregorioMartinez** [comment]
Thanks for the link!
I added the exact match and download #'s to the footer like Packagist has.
Did you have any suggestions for displaying the additional information?

**Comment by jagtalon** [comment]
Fixed by @iambibhas
