### ISSUE TITLE
Geometry: Diagrams should have labels

### ISSUE THREAD

**Issue by sekhavati** [duckduckgo/zeroclickinfo-spice#2492]
The shape diagrams this IA draws don't have labels. They ought to help qualify the formula variables. For example, when you search for ["geometry circle"](https://duckduckgo.com/?q=geometry+circle&ia=geometry) the diagram should depict the variable `r` as relating to the radius of the circle like this: https://jsfiddle.net/yt6nw2vk/

---

IA Page:  http://duck.co/ia/view/geometry

**Comment by MrChrisW** [comment]
@sekhavati Thanks! @pixunil do you have any thoughts on this improvement?

**Comment by yash14123** [comment]
I would like to take this up. Can you guide me a bit for this?

**Comment by altern8tif** [comment]
@MrChrisW Something like [this](http://www.wolframalpha.com/input/?i=area+of+a+circle) would be pretty awesome...

![screen shot 2016-02-10 at 10 02 25 pm](https://cloud.githubusercontent.com/assets/5793364/12949314/11c86328-d042-11e5-851b-9c37c046291e.png)

**Comment by moollaza** [comment]
@sekhavati it's not initially very obvious but if you hover over the elements on the left, the diagram changes colour to indicate what part of the given element. 

e.g. hovering over radius highlights the border.

We should probably provide some instruction or a stronger hint. We may still want/need labels though

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
