### ISSUE TITLE
SublimePackages: Triggering for "sublime text alternatives"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2495]
https://duckduckgo.com/?q=sublime+text+alternatives+for+linux&ia=software

We shouldn't be triggering/showing a result for queries like `sublime text alternatives ...`

------
IA Page:  http://duck.co/ia/view/sublime_packages

**Comment by samskeller** [comment]
I'll take a stab at this one

**Comment by pnpninja** [comment]
I've done it. PR #2496
