### ISSUE TITLE
Sales Tax: Use new API, display tax range

### ISSUE THREAD

**Issue by ajainy** [duckduckgo/zeroclickinfo-spice#2497]
@MrChrisW @javathunderman 

As guided, I have created this issue, to replace implementation of existing implementation. 
New implementation will have 

- Sales tax range for a state. Generally net sales tax can vary between different addresses.

------
IA Page:  http://duck.co/ia/view/sales_tax

**Comment by MrChrisW** [comment]
@ajainy Closing this as discussion can continue in your PR #2498
