### ISSUE TITLE
IsItUp: Should not trigger on "is it up", "is it down", "is site down"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2499]
We should ignore these specific queries. We may also want to put a minimum character count (5?) for candidate domains that don't have a TLD (i.e. missing ".com"). This would allow "is facebook down" but prevent "is it down".

------
IA Page:  http://duck.co/ia/view/is_it_up

**Comment by tagawa** [comment]
Looks good now thanks to the fix from @Sayanc93 :-)
