### ISSUE TITLE
Places: Link to OpenStreetMap under the yelp link?

### ISSUE THREAD

**Issue by petacat** [duckduckgo/zeroclickinfo-spice#2503]
Can we get a link to OpenStreetMap under the yelp link?

------
IA Page:  http://duck.co/ia/view/maps_places

**Comment by moollaza** [comment]
@petacat we're working on something along these lines...

**Comment by petacat** [comment]
Nice to here that.

**Comment by jagtalon** [comment]
This has been implemented! https://duck.co/blog/post/291/directions
