### ISSUE TITLE
TVMaze Next Episode: Improvement by showing time zone

### ISSUE THREAD

**Issue by pnpninja** [duckduckgo/zeroclickinfo-spice#2508]
@tvdavid 

![bug](http://i.imgur.com/arR6ffP.png)

The timezone of when it is released isn't displayed. Can it be displayed?

---

IA Page:  http://duck.co/ia/view/tvmaze_nextepisode

**Comment by moollaza** [comment]
@pnpninja looks like the image you posted didn't work. Also, please be sure to add a link to the IA Page so that the issue is connected to the IA!

**Comment by moollaza** [comment]
If you click the `i` icon beside and Instant Answer and visit its Instant Answer page, there will be a "Create Issue" button that will automatically fill in the link for you ;)

**Comment by pnpninja** [comment]
@moollaza : I added the details and the image now works..

**Comment by moollaza** [comment]
@pnpninja image still doesn't work for me..

**Comment by moollaza** [comment]
![tvmaze_next_episode__improvement_by_showing_time_zone_ _issue__2508_ _duckduckgo_zeroclickinfo-spice](https://cloud.githubusercontent.com/assets/873785/13123775/e33e37a4-d58b-11e5-84b1-67d0e7b5002f.png)

**Comment by pnpninja** [comment]
@moollaza I just dragged it and dropped it into the comment box in Github.. However, i uploaded it on imgur and put that link (probably big link is causing error) .

**Comment by pnpninja** [comment]
ping @moollaza . is the image visible now?

**Comment by moollaza** [comment]
IA is no longer online
