### ISSUE TITLE
Forecast: Add % humidity to answer

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2510]
This was a suggestion sent over email.

It looks like we have the information available to us through the API already :)

Would anyone else find this useful?

------
IA Page:  http://duck.co/ia/view/forecast

**Comment by AnthonyNeace** [comment]
It would be helpful for people looking to get an impression of what it will actually feel like outside.  An 80°F day at 0% humidity would feel quite pleasant, where the same day at 100% humidity would be oppressive.

**Comment by kwaping** [comment]
Humidity is very important for people living in certain areas. :+1: this suggestion.

**Comment by vikashvverma** [comment]
@moollaza I would work on this
