### ISSUE TITLE
Specify version in requests made to timeanddate.com API

### ISSUE THREAD

**Issue by sekhavati** [duckduckgo/zeroclickinfo-spice#2511]
IAs that use the timeanddate.com API don't include a version number with their requests. The [documentation](http://services.timeanddate.com/api/doc/v2/ch02s01.html) suggests it should always be specified. As a consequence results being returned from our API calls have the following warning in the JSON:

`"warnings":["Please specify request version, defaulting to version 1."]`

Here's a list of IAs that use this API:

- [Location Sunrise/Sunset](https://duck.co/ia/view/sun_rise_set)
- [Seasons](https://duck.co/ia/view/seasons)
- [Time](https://duck.co/ia/view/time) 

I'm happy to fix this if a DDG team member can confirm which version we need to use. I presume we want v2 (latest)?

**Comment by moollaza** [comment]
@sekhavati thanks for pointing this out. If it's been defaulting to V1 then I think we should continue to use it. Do you know what the difference is with V2?

**Comment by sekhavati** [comment]
@moollaza see below 

> 2015-04-21
> Initial release of request API version 2.
>        
> - holidays service: holidays without time are now exported with a date only. Holidays including a timestamp will have the timestamp always in local time and including time zone information. Times and time zones pertain to the capital city for countries with multiple time zones.
> -         All relevant services (astronomy, converttime, timeservice) now support IATA/ICAO-codes to specify locations: see Location Id for details.
> -         Specifying a request version is mandatory from version 2 on. Omitting the version will stick to version 1 with an added warning message.
