### ISSUE TITLE
GitHub Status: Should not show a result for the query "github"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2513]
https://duckduckgo.com/?q=github -- we should not show a result when the query is just "github".

---

IA Page:  http://duck.co/ia/view/github_status

/cc @Feral2k

**Comment by Sayanc93** [comment]
Hey @moollaza if you see the perl file they return none if the query is just github. Not clear on the issue. FYI I can take this up.

**Comment by yash14123** [comment]
@Sayanc93 can I take this up? I see you have already done quite a few low hanging ones already.
I am fairly new and starting with this might help me. :)

**Comment by moollaza** [comment]
@Sayanc93 the Perl looks wrong. 

We should have:

```perl 
triggers start => "github status", "github system status";

handle remainder => sub {
    return if $_; #
    return '';
}
```

This defines two triggers and checks that the query is identical to the trigger. It returns `''` which makes an API call.

**Comment by altern8tif** [comment]
@theaverageguy did you open a pull request for this?  Looks like you've only pushed to your forked zeroclickinfo-spice repo instead of [duckduckgo/zeroclickinfo-spice](https://github.com/duckduckgo/zeroclickinfo-spice)...

**Comment by Feral2k** [comment]
@theaverageguy Thanks so much for fixing this issue. Have you made a pull request yet? I've been looking but maybe it went under my radar.

**Comment by moollaza** [comment]
Fixed
