### ISSUE TITLE
Github: Show more info in results

### ISSUE THREAD

**Issue by swapagarwal** [duckduckgo/zeroclickinfo-spice#2518]
GitHub provides the following data as well in their search results:
- Language
- Number of Forks

Should we include it too?

IA Page: https://duck.co/ia/view/github

**Comment by moollaza** [comment]
@swapagarwal I think the language could be useful. I would really like to see the stargazers count which I find more useful than the forks count

**Comment by swapagarwal** [comment]
Yes, the timestamp indeed provides an insight into the repo's activity.
Using fork count as an indicator is subjective.
I'll go ahead and add the language then! Should I include fork count too?

**Comment by moollaza** [comment]
>  I'll go ahead and add the language then! Should I include fork count or let it be for now?

You can go ahead and include it. I'll have the design team review your PR and they can suggest any changes

**Comment by swapagarwal** [comment]
Okay, I have included it. However, the fork icon needs to be present in order to render nicely..

**Comment by swapagarwal** [comment]
Done!

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
