### ISSUE TITLE
Currency: Local currency if Region is ON

### ISSUE THREAD

**Issue by Co2p** [duckduckgo/zeroclickinfo-spice#2527]
The currency should change to the active region when it is switched on.
In the screenshot currency should change from EUR to SEK

![capture](https://cloud.githubusercontent.com/assets/6750851/13203300/58763838-d8b5-11e5-8c3c-0e011f021b9d.PNG)
------
IA Page:  http://duck.co/ia/view/currency

**Comment by MrChrisW** [comment]
@Co2p Thanks you for the suggestion, this is currently being addressed in #2069 - although there's not much process at this stage. I'll close this as a duplicate.Thanks!
