### ISSUE TITLE
DogoNews: Footer breaks on smaller screens

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#2528]
<img width="540" alt="screen shot 2016-02-22 at 7 21 40 am" src="https://cloud.githubusercontent.com/assets/81969/13218067/08006a1a-d935-11e5-9355-dc52601ad2aa.png">

Reducing the number of characters to, say, 10 should do the trick (see highlighted line):

<img width="719" alt="screen shot 2016-02-22 at 7 22 39 am" src="https://cloud.githubusercontent.com/assets/81969/13218098/342725ca-d935-11e5-82a1-af00567a34bf.png">

**Comment by CruiseDevice** [comment]
Will replacing 10 in place of 15 work?
