### ISSUE TITLE
Recipes: triggering on `recipes.com`

### ISSUE THREAD

**Issue by bbraithwaite** [duckduckgo/zeroclickinfo-spice#2530]
For queries such as recipe.com, the IA triggers and the message is 'Recipes for .com'. Perhaps the triggering needs to be tweaked?

https://duckduckgo.com/?q=recipe.com&ia=recipes

------
IA Page:  http://duck.co/ia/view/recipes

**Comment by sekhavati** [comment]
@bbraithwaite I agree that the IA looks to be misbehaving. You may be under the false impression that I developed this IA as this is what the info box suggests. In reality I'm a contributor towards it who fixed an unrelated bug recently.

**Comment by sekhavati** [comment]
@bbraithwaite At the moment I'm developing another IA which my spare time is going towards. Afterwards I'll try make some time to investigate this further.

**Comment by bbraithwaite** [comment]
@sekhavati Your handle was pre-populated when I clicked the link to create the issue, I'm not delegating to you directly to fix! I will remove your handle from the description, so that others can pick up in the meantime if they wish to do so.
