### ISSUE TITLE
Currency: triggers on "mars" because of `m` prefix + `ars` symbol

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2533]
It looks like we have a regex that checks for `million` but also `m`. As well, `ars` is a currency name.

So together, `mars` looks like a valid trigger. This also happens for `musd` for example.

I think if the trigger contains `million` or `m` it should also have a number, or we may want to whitelist the phrase `mars`.

@laouji @MrChrisW, what are your thoughts?

------
IA Page:  http://duck.co/ia/view/currency

**Comment by laouji** [comment]
The space between the number and the currency is currently optional, which is why this triggers.

I think it would be reasonable to make the space mandatory so that `1m ars` will trigger but not `1 mars` or '1mars`.

**Comment by moollaza** [comment]
@laouji I agree :+1:

**Comment by kwaping** [comment]
This isn't entirely user-friendly, but technically "1m" in finance generally refers to 1 mille, or 1000. One million is generally referred to as 1MM. Not sure if forcing that convention would delight DDG users, though. It would definitely fix this issue though.

**Comment by moollaza** [comment]
> One million is generally referred to as 1MM. Not sure if forcing that convention would delight DDG users, though. It would definitely fix this issue though.

@kwaping that’s a good point! It looks like a PR was already made but would you like to add support for `MM` and any other triggers after it's merged?

**Comment by GuiltyDolphin** [comment]
@kwaping Still interested in adding the additional triggers? It'd be a great addition.

**Comment by kwaping** [comment]
Sure! Thanks for the reminder.
