### ISSUE TITLE
Forecast: searching for Taipei weather shows Beinwil, Switzerland weather

### ISSUE THREAD

**Issue by heycam** [duckduckgo/zeroclickinfo-spice#2537]
@himanshu0113 

When I search "taipei weather" I am shown the weather for Beinwil, Switzerland.

------
IA Page:  http://duck.co/ia/view/forecast

**Comment by heycam** [comment]
![weather](https://cloud.githubusercontent.com/assets/1484434/13341633/950c3194-dc8e-11e5-97df-d15362ba1c71.png)

**Comment by moollaza** [comment]
@heycam thanks for reporting. Can you send me a picture of your results? Do you have any location boost on?

I see the expected results but I suspect you're seeing something else because of the organic results and our "Deep" trigger...

![taipei_weather_at_duckduckgo](https://cloud.githubusercontent.com/assets/873785/13366877/112120ce-dcac-11e5-9732-e4e69b609ebd.png)

**Comment by heycam** [comment]
Here's a screen shot of the entire results page in my usual browser:

![weather1](https://cloud.githubusercontent.com/assets/1484434/13369352/cc30b03c-dd47-11e5-9a35-d452f562a425.png)

In a private browsing window (with the region option turned off):

![weather2](https://cloud.githubusercontent.com/assets/1484434/13369361/e4420af4-dd47-11e5-913d-22fe3b3c3755.png)

In a private browsing window (with the region option turned on):

![weather3](https://cloud.githubusercontent.com/assets/1484434/13369363/ec901a7a-dd47-11e5-8d84-d9fc3c1d80ab.png)

Let me know if I can provide any other useful information from my regular browsing session.

**Comment by moollaza** [comment]
@heycam thanks for the update -- out of curiosity, if you try a differ form of the query: "weather taipei" does it correct the Switzerland result?

I'm wondering if somehow the bad results was cached..

**Comment by heycam** [comment]
I can't test from my usual location since I'm in Taipei currently. :) But I can test again when I'm home in a couple of weeks.

**Comment by edgesince84** [comment]
we have multiple location-weather issues open right now, so I'm going to close this as a duplicate to https://github.com/duckduckgo/zeroclickinfo-spice/issues/2362
