### ISSUE TITLE
Arch User Repository: Instant Answer broken, API URL has changed and needs update

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2543]
Need to update the `spice to` to match the new URL format: `https://aur.archlinux.org/rpc/?v=5&type=search&arg=$1`

------
IA Page:  http://duck.co/ia/view/aur

/cc @natebrune

**Comment by moollaza** [comment]
@NateBrune thanks :+1:

**Comment by moollaza** [comment]
@NateBrune I see it's working again. Did you fix on the API side?

**Comment by NateBrune** [comment]
I emailed them and asked them to add support for backwards compatibility. Some package managers where broken too. I guess they fixed it.

**Comment by moollaza** [comment]
> I guess they fixed it.

Yes it does! Thanks for emailing them!
