### ISSUE TITLE
InEveryLang: Website and API Offline. Remove IA from Repo

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2549]
@josephwegner it looks like the website is offline? Is this permanent?

http://www.ineverylang.com/

If so would you mind removing the code, or updating the IA to use a new source?

---

IA Page:  http://duck.co/ia/view/in_every_lang
Maintainer: @josephwegner

**Comment by vikashvverma** [comment]
@moollaza I can work on this, if nobody is working on this.

**Comment by moollaza** [comment]
@vikashvverma thanks -- I'm going to take the IA offline for now as it's not working. You're welcome to investigate if any alternatives exist. I'd like to wait for some input from @josephwegner before we making any changes to the code though.

**Comment by vikashvverma** [comment]
@moollaza sure, let's see what @josephwegner says

**Comment by moollaza** [comment]
This has been offline for a few months and the website seems to be gone as well. We should remove the IA and deprecate the IA page.

@josephwegner if you plan to get the API back online please let us know ASAP.

**Comment by moollaza** [comment]
@vikashvverma would you like to make a PR removing the code?

**Comment by vikashvverma** [comment]
@moollaza Do you have any website in mind?
