### ISSUE TITLE
Transit NJT: API Broken? 

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2552]
The API is returning HTTP 500 errors for API calls: http://njt-api.appspot.com/njt/times/metropark/new-york-penn

@mattr555 any idea what's going on?

------
IA Page:  http://duck.co/ia/view/transit_njt

**Comment by mattr555** [comment]
Should be good to go now, the data needed to be updated. Automatic downloads of the transit data is something I really want, but the process is pretty arcane (you need to log in with an account). Would definitely help to increase the [bus factor](https://en.wikipedia.org/wiki/Bus_factor) :wink:
