### ISSUE TITLE
Design proposal for Insant Answer Tides

### ISSUE THREAD

**Issue by xaviervalarino** [duckduckgo/zeroclickinfo-spice#2558]
I would like to create a tide chart as an enhancement for [tides](https://duck.co/ia/view/tides).

My idea is to take the response data and use it to create an SVG path. I would then pass it as an unescaped string to a custom sub-template.

@moollaza mentioned that support for [Chart.js](http://www.chartjs.org/) was recently added, which would probably take a lot of the work out of creating the sine graph. Still, regardless of how the graph is created, there doesn't seem to be a good sub-template `option` for plugging it into IA. Would this warrant using [`base_template`](http://docs.duckduckhack.com/frontend-reference/templates-reference.html#baseitem-template)?

Here is a concept where the chart would be styled like the infoBox from [`basic_info_detail`](http://docs.duckduckhack.com/frontend-reference/templates-reference.html#basicinfodetail-template)

![0307_duckduckgo_tides_concept](https://cloud.githubusercontent.com/assets/4262486/13582411/0b51eda6-e461-11e5-85e0-d1fc4dcac71c.png)

------ 

IA Page:  https://duck.co/ia/view/tides

**Comment by moollaza** [comment]
@abeyang would like your input here please!

> Would this warrant using base_template?

@xaviervalarino at one point we allowed a custom template to be used for the infobox -- AFAIK that functionality no longer exists.

Technically we could just create the chart and add it to the page via JS and create a CSS file to style it correctly. I imagine that approach would break on mobile though -- we would need a lot better handling of the UI. The list template wasn't made to have an images or extra content beside it...

**Comment by mattr555** [comment]
Commenting to follow -- @xaviervalarino first got in contact with me. Looks great so far, a graph view is something I've always wanted for this spice :+1:

**Comment by xaviervalarino** [comment]
@abeyang _if_ this sort of thing requires using a custom base template, I could come up with a better design for the data set. I am not particularly married to the concept mockup above, since it was mainly an attempt to base a design off of existing sub-templates.

One idea that comes to mind, since the data set includes the tidal highs and lows for the next three days, would be to have series of grouped buttons/tabs that would allow a user to toggle between each day. 

@moollaza *w.r.t* making the chart responsive, what if the chart's container used the responsive grid system outlined in the [style guide](https://duckduckgo.com/styleguide#grouping)?
