### ISSUE TITLE
Equaldex: Broken in Production. Likely Internal issue

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2569]
Not working on live site, API response isn't coming through our NGINX endpoint.

Seems to be an internal issue though, I confirmed the API is up and works in DuckPAN

------
IA Page:  http://duck.co/ia/view/equaldex 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

/cc @kablamo

**Comment by moollaza** [comment]
After `curl`ing the API I noticed that the domain is now redirecting from http://equaldex.com to `http://www.equaldex.com` -- this is likely the issue!

**Comment by moollaza** [comment]
Confirmed updating the URL fixes this. https://moollaza.duckduckgo.com/?q=lgbt+rights+in+china&ia=equaldex

Will make a PR

**Comment by MrChrisW** [comment]
Fixed in #2570
