### ISSUE TITLE
Last.fm: Require description before displaying

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#2571]
It should bail if it's missing a description. It's to prevent things like this:

https://duckduckgo.com/?q=store+dj&ia=music

<img width="850" alt="screen shot 2016-03-11 at 3 21 46 pm" src="https://cloud.githubusercontent.com/assets/81969/13714502/fcf9988c-e79c-11e5-833a-fed3e556804c.png">

---
https://duck.co/ia/view/lastfm_artist

**Comment by Mylainos** [comment]
I would like to take this one please ;)
