### ISSUE TITLE
PeopleInSpace: Add rank

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/zeroclickinfo-spice#2574]
Quoted: @vikashvverma

I think we can add designation such as Commander as well to IA. This is readily available at data source http://www.howmanypeopleareinspacerightnow.com/

Moved from: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2736

---

IA Page:  http://duck.co/ia/view/people_in_space 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @elebow

**Comment by elebow** [comment]
Looks easy enough. @vikashvverma, were you going to make a PR? I can do it, otherwise.

**Comment by vikashvverma** [comment]
@elebow I want to try.

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
