### ISSUE TITLE
Zanran: Weird Characters (encoding?)

### ISSUE THREAD

**Issue by yegg** [duckduckgo/zeroclickinfo-spice#2577]
On a search for 'US Corporate Tax Rates' (see attached), the first result has some strange characters that look like some kind of encoding error.

![us corproate tax rates](https://cloud.githubusercontent.com/assets/127263/13744851/10756dc0-e9c1-11e5-822c-5ce224f67946.png)

------
IA Page:  http://duck.co/ia/view/zanran 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @taw

**Comment by moollaza** [comment]
The broken text is coming straight from the API. @taw this looks like a bug on your end?
![https___duckduckgo_com_js_spice_zanran_us_corporate_tax_rates](https://cloud.githubusercontent.com/assets/873785/13785247/2da4b1b0-eaa9-11e5-8918-58255f05230f.png)

**Comment by taw** [comment]
Jon,

That's presumably just error in the data, aren't site names are coming from
some spreadsheet with manual overrides or something like that?
It's been a while, so I might be misremembering.
