### ISSUE TITLE
Air Quality Index: Overtake About

### ISSUE THREAD

**Issue by yegg** [duckduckgo/zeroclickinfo-spice#2579]
I think this may need internal help, but it seems like it makes sense for when you just type in 'air quality' it would overtake the About tab, and show you your local air quality (like weather does).

------
IA Page:  http://duck.co/ia/view/aqi 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @schluchc

**Comment by moollaza** [comment]
>when you just type in 'air quality' it would ... show you your local air quality (like weather does).

@yegg it should work that way now? That's how it's implemented: https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Aqi.pm#L27. This API is US only though so it only works with US Zip Codes

We should be able to force it to replace the `About` tab by adding `signal: "high"` to the top-level object

**Comment by yegg** [comment]
Yeah I saw that and it is cool. I meant it would be better if it showed automatically. Trying a high signal in that case seems like a good idea.

**Comment by moollaza** [comment]
I've adjusted the priority on the IA Page. This should take effect shortly.
