### ISSUE TITLE
Air Quality Index: City Names

### ISSUE THREAD

**Issue by yegg** [duckduckgo/zeroclickinfo-spice#2580]
Is it possible to show answers for queries like 'air quality las vegas'? I know our internal location API can detect something like 'las vegas,' and I think returns a lat/long but unclear of a zip code, which I think you need in this case. If not, perhaps we can also send back the zip code.

---

IA Page:  http://duck.co/ia/view/aqi 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @schluchc

**Comment by moollaza** [comment]
IA is no longer online
