### ISSUE TITLE
Advanced Calculator: integrate 3x

### ISSUE THREAD

**Issue by yegg** [duckduckgo/zeroclickinfo-spice#2581]
It seems like we should also be triggering on things like:

integrate 3x
integral 3x
derivative 3x

etc.

---

IA Page:  http://duck.co/ia/view/symbolab 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @levaly

**Comment by moollaza** [comment]
Currently we have the triggering of this IA limited to `solve`, `compute` and `calculate`. I think we should be fine with adding `integrate` as a trigger. @levaly we'll also need to update the regex in the `handle` accordingly!

**Comment by levaly** [comment]
@moollaza I will add support for these cases in the coming days.

**Comment by levaly** [comment]
Hi,

I added support for the following type of queries
integral of x^2
integrate x^2
integration of x^2
antiderivative of x^2
derivative of x^2
derive x^2
differentiate x^2
derivation of x^2

all of the above also work if you insert a function of the forms:
f(x)=x^2, i.e integral of f(x)=x^2
y=x^2

I also updated the unit tests to reflect the changes.

This feature is not yet available in symbolab.com, I will notify you once it will be available and then you can test it out.

**Comment by moollaza** [comment]
> This feature is not yet available in symbolab.com, I will notify you once it will be available and then you can test it out.

@levaly thank you very much!

**Comment by levaly** [comment]
a PR is ready for review

**Comment by levaly** [comment]
any idea when this feature will be pushed to production?

**Comment by tagawa** [comment]
@levaly Now that your PR (#2708) has been merged, it should go live with the next release batch. Hopefully this will be in the next week or two. Thanks for your patience.

**Comment by levaly** [comment]
@tagawa thanks.

**Comment by edgesince84** [comment]
can this be closed out by #2708 now?

**Comment by GuiltyDolphin** [comment]
@edgesince84 It doesn't appear to be triggering on `integrate 3x`, but it does trigger on `integrate 3x^2` and `integrate y = 3x`

@yegg That good enough?

**Comment by moollaza** [comment]
This has been Fixed
