### ISSUE TITLE
Astrobin Apod: Trigger on APOD

### ISSUE THREAD

**Issue by yegg** [duckduckgo/zeroclickinfo-spice#2582]
It seems like users of the site also know it as APOD -- should it trigger on that as well (and overtake About)?   

------
IA Page:  http://duck.co/ia/view/apod 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @killerfish

**Comment by moollaza** [comment]
@gvanwaelvelde @rasikapohankar thanks for tackling this!

It looks like you both have made nearly identical pull requests though to solve this?

@rasikapohankar's pull request technically came first but I prefer @gvanwaelvelde's 

Next time, please comment on the issue to let us know you want to work on it. If you've joined the DuckDuckHack Contributors Team then we'll be able to assign you the issue and everyone else will know this is being worked on.

**Comment by moollaza** [comment]
@rasikapohankar I'd like to give you the decisions because your PR was made first.

If you'd like to update your PR to look like @gvanwaelvelde's I'll merge yours. Alternatively, we can close your PR and merge @gvanwaelvelde's, once the maintainer approves it.

**Comment by rasikapohankar** [comment]
@moollaza : You can close the other PR and merge @gvanwaelvelde's.
