### ISSUE TITLE
BrainyQuote: Feynman

### ISSUE THREAD

**Issue by yegg** [duckduckgo/zeroclickinfo-spice#2583]
Why doesn't 'quote feynman' or 'feynman quotes' seem to return results?   

---

IA Page:  http://duck.co/ia/view/brainy_quote 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
@moollaza @yegg I'm not sure why I'm the maintainer for this; I don't think I wrote it! 

However it looks like an issue with the API: 
http://www.brainyquote.com/api/ddg?q=feynman returns an error

**Comment by mintsoft** [comment]
Looking at the history, it looks like this seems to predate the git history; so I'm happy to be the maintainer for it if someone is needed.

**Comment by mintsoft** [comment]
```
 curl --include 'http://www.brainyquote.com/api/ddg?q=feynman'
HTTP/1.1 200 OK
Date: Mon, 14 Mar 2016 13:29:49 GMT
Content-Type: application/json;charset=UTF-8
Content-Length: 14
Connection: keep-alive
Set-Cookie: __cfduid=dcc1f05f8297a4a011ac0def6f9f951e81457962189; expires=Tue, 14-Mar-17 13:29:49 GMT; path=/; domain=.brainyquote.com; HttpOnly
Accept-Ranges: bytes
Age: 0
Cache-Control: no-cache, no-store
cf-ipcountry: GB
Expires: Sun, 13 Mar 2016 13:29:49 GMT
Pragma: no-cache
Set-Cookie: abtesting=a; path=/; expires=Tue, 15 Mar 2016 13:29:49 GMT
Vary: Accept-Encoding, User-Agent
X-Varnish: 2078753491
X-Varnish-Cache: MISS
Server: cloudflare-nginx
CF-RAY: 283813a1486e06d6-LHR

{"error":true}
```

**Comment by mintsoft** [comment]
I've emailed the guys who run the API and referenced this, I've cc'd @moollaza in too

**Comment by ScreapDK** [comment]
Sorry, if this is the wrong place to report (separate issue?):
Searching for

**Comment by MrChrisW** [comment]
@ScreapDK Looks like the same issue - Upstream API is broken
http://www.brainyquote.com/api/ddg?q=about%20motivation

**Comment by moollaza** [comment]
> Searching for quotes on topics seem broken, too.
> E.g. quotes about motivation, quotes on love.
> 
> Sorry, if this is the wrong place to report (separate issue?).

I believe the API they provided to use was only intended to be used for quotes by a named author. Getting support for topics would be nice though

**Comment by MrChrisW** [comment]
@moollaza Interesting, the example triggers contain `quotes about motivation` - https://duck.co/ia/view/brainy_quote

**Comment by mintsoft** [comment]
@MrChrisW I'm pretty sure it worked at some point. Same as feynman; I'm 90% sure I've used it in the last 2 years!

**Comment by MrChrisW** [comment]
@mintsoft :+1: Definitely!  - Topics should work, see the original MR https://github.com/duckduckgo/zeroclickinfo-spice/pull/340

**Comment by moollaza** [comment]
We've spoken to the BrainyQuote team. They're going to update the IA to add support for topic searches. The explained that they only support some searches for an author's last name. In the case of Feynman their API doesn't seem to detect that Feynman implies Richard Feynman. If you do the query with his full name the Instant Answer works: 

https://duckduckgo.com/?q=richard+feynman+quotes&ia=quotations

We'll have to tolerate this for nowl. A potential but ugly solution is to create a list of author names and attempt a fallback API calls when the first fails

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
