### ISSUE TITLE
Bitcoin Addresses, Blocks : missed focus

### ISSUE THREAD

**Issue by fzzr-** [duckduckgo/zeroclickinfo-spice#2584]
![ddg btc issue mov opt](https://cloud.githubusercontent.com/assets/888526/13754244/522d37fa-ea27-11e5-8626-7779aea780ee.gif)
   

------
IA Page:  http://duck.co/ia/view/bitcoin 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jmg

**Comment by moollaza** [comment]
This looks really bad -- Updating priority to High.

@fzzr- can you give us some example queries please?

/cc @MrChrisW -- I know you worked on this IA recently

**Comment by fzzr-** [comment]
>can you give us some example queries please?

To demonstrate the issue I used the query from the [example](https://duck.co/ia/view/bitcoin):

For example follow the first link in that page ⇒ `https://duckduckgo.com/?q=1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa&ia=currency`.

I get this issue sometimes. [screen shot 2016-03-15 at 21 50 36](https://cloud.githubusercontent.com/assets/888526/13790200/4ede279a-eaf8-11e5-9f22-c72d6ae7fc2d.png)

**Comment by GuiltyDolphin** [comment]
@fzzr- I'm not able to replicate this? It sometimes takes a second to appear, but it is definitely showing.

**Comment by moollaza** [comment]
@fzzr- thanks for the link -- it looks like the issue may actually be related to the favicon for the domain. That appears to be taking 2.0s for me and we're waiting that whole time to render the result.

This may actually be an internal issue if that's the case. I'm going to have the team take a look..

**Comment by moollaza** [comment]
I just noticed that the IA Page and `name` in the JS don't match. We should switch these over to `Answer`. I suspect that will solve the problem. It's not switching to the correct tab because it's trying to open a "Currency" but the IA specified "Bitcoin Block", which doesn't match.

**Comment by MrChrisW** [comment]
@moollaza I've seen issues with the response time of the upstream IA before. 

I'll make the above fix. Unfortunately I think the API may be to blame.

**Comment by moollaza** [comment]
@MrChrisW i've just made a fix^
