### ISSUE TITLE
Add proxy_cache_valid to Spices that should not cache responses for 24hrs

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#259]
Many Spice were incorrectly using the `is_cached` parameter (rather than `proxy_cache_valid`) and so in light of removing them here https://github.com/duckduckgo/zeroclickinfo-spice/commit/724812c7aff7b5f5b5fb07c39aa66b28250434e3 many Spice still need to have their responses not cached so `spice proxy_cache_valid` still needs to be set appropriately in those cases.

/cc @jagtalon @nospampleasemam fyi

**Comment by javathunderman** [comment]
@moollaza Ping, is this done?

**Comment by moollaza** [comment]
@javathunderman I'm not sure -- we should gather a list of the IA's that explicitly set `is_cached` and then verify that they are all working as intended!

**Comment by javathunderman** [comment]
@moollaza Compiling that list now.
