### ISSUE TITLE
Public Holidays: Merge duplicate date/events

### ISSUE THREAD

**Issue by MrChrisW** [duckduckgo/zeroclickinfo-spice#2594]
Events on the public holidays IA are repeated several times when the only change in data is the region. 

This is due to the API returning the same event with a new id and new ` "states"` -  [api response](https://gist.github.com/MrChrisW/36f6a27e7d4e52be9305#file-json-L288). Maybe we can merge these events into a single item on the table? 

Examples: 

https://beta.duckduckgo.com/?q=public+holidays+in+united+states&ia=answer&iax=1

![2016-03-17-32-public holidays in united states at duckduckgo](https://cloud.githubusercontent.com/assets/5282264/13844279/d9e88908-ec73-11e5-8b13-079c52c50030.png)

https://duckduckgo.com/?q=public+holidays+in+australia

![2016-03-17-38-public holidays in australia 2400 at duckduckgo](https://cloud.githubusercontent.com/assets/5282264/13844278/d9de9d6c-ec73-11e5-9b70-753fbbd39856.png)

------
IA Page:  http://duck.co/ia/view/public_holidays 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sekhavati

**Comment by moollaza** [comment]
@MrChrisW good catch! -- For some reason I don't see Cesar Chavez day at all for the first link. However with the recent updates to this IA (adding local holidays) I see duplication in the results:

https://beta.duckduckgo.com/?q=public+holidays+in+united+states&ia=answer&iax=1

**Comment by MrChrisW** [comment]
@moollaza 
>For some reason I don't see Cesar Chavez day at all for the first link. 

Yup, I was testing it out on BETA! :wink:

**Comment by sekhavati** [comment]
@MrChrisW Thanks for pointing this out. Please assign this issue to me and I'll fix it. Looks like the API is returning multiple objects for the same holiday with a differing set of `states`. Each have the same `id` though so I think it should be fairly straight forward to fix this.

**Comment by MrChrisW** [comment]
@sekhavati Thanks for the quick fix. It's great to see the holidays IA continually improving! :+1:
