### ISSUE TITLE
Cryptocurrency: "1 Eth" should show conversion, not Wikipedia info

### ISSUE THREAD

**Issue by fzzr-** [duckduckgo/zeroclickinfo-spice#2599]
For example:
- [1 Ltc](https://duckduckgo.com/?q=1+ltc&ia=cryptocurrency) - OK.
- [1 Eth](https://duckduckgo.com/?q=1+Eth&ia=cryptocurrency) - **NOT** (Wiki)

---

IA Page:  http://duck.co/ia/view/cryptocurrency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @claytonspinner

**Comment by moollaza** [comment]
@fzzr- I'm a little unclear -- are you saying you're not seeing the currency IA for that query and you'd like to?

I'm seeing the currency IA first which seems correct to me.

**Comment by fzzr-** [comment]
@moollaza Yes. Last time it was not.

Now I see "Cryptocurrency". I'm not sure in the correctness of this behavior. Focus I didn't change.

* ![screen shot 2016-03-21 at 20 49 11](https://cloud.githubusercontent.com/assets/888526/13928379/d0f3a678-efae-11e5-8152-78c37c533404.png)
* ![screen shot 2016-03-21 at 20 48 55](https://cloud.githubusercontent.com/assets/888526/13928389/db5431be-efae-11e5-9eb6-26b823af26e8.png)

**Comment by MrChrisW** [comment]
I think this is just a race condition based on which `duckbar` tab is loaded first. I've attempted to replicate this and am unable.

**Comment by tagawa** [comment]
I get the same as @fzzr- - the Wikipedia infobox.

**Comment by GuiltyDolphin** [comment]
@tagawa @fzzr- For me it is showing Cryptocurrency... Hmm.. Wait a second...

With region set to UK it shows Cryptocurrency, with no region set it shows Wiki:

Region UK:

![screenshot from 2016-04-08 20 05 10](https://cloud.githubusercontent.com/assets/8598426/14394662/3e92e17a-fdc5-11e5-9950-f77d119f7a44.png)

Region Off:

![screenshot from 2016-04-08 20 05 20](https://cloud.githubusercontent.com/assets/8598426/14394668/49fc06ea-fdc5-11e5-991f-675c024455af.png)

Results are consistent. It looks like the Wiki isn't triggering at all with UK preference.

**Comment by tagawa** [comment]
Strange, I get the wiki whether I set the region or not. Maybe it's the wiki IA that's at fault then, being too aggressive.

**Comment by GuiltyDolphin** [comment]
@tagawa Weird... @MrChrisW Are you able to reproduce the issue with setting region? (I.e, the `Globe`).

**Comment by claytonspinner** [comment]
I get the Wiki IA regardless of region setting as well. I'll take a look at it

**Comment by MrChrisW** [comment]
@GuiltyDolphin Region changes the result, I think this is internal 
![region](https://cloud.githubusercontent.com/assets/5282264/14418048/13812688-ffee-11e5-9608-d2f7e9bf7f34.gif)

**Comment by GuiltyDolphin** [comment]
@MrChrisW We could try setting `signal` to `"high"`; might do the trick.

**Comment by moollaza** [comment]
As of this morning, I'm now seeing the About tab instead of the Spice.

@mrshu this behaviour seems a little odd -- is this happening because of a regional Wiki? When I switch to any region it seems that Wiki result is suppressed.

**Comment by fzzr-** [comment]
I guess it depends on the download speed and order of requests.
Why the change affects the region?
\- Perhaps because of regional settings depends to which server answers or its response speed/latency.
In the [GIF from MrChrisW](https://cloud.githubusercontent.com/assets/5282264/14418048/13812688-ffee-11e5-9608-d2f7e9bf7f34.gif) the Cryptocurrency tab anyway exists. It's not first & open but exists. This behaviour really look like "problem of requests order" or "problem of  order of responses processing".

**Comment by edgesince84** [comment]
I'm getting the Crytocurrency tab on this - region off or set to US - both are Crytocurrency for me.

**Comment by pjhampton** [comment]
I believe this has been sorted in the v2
