### ISSUE TITLE
Currency: Regression: Flags are too big on mobile

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#2603]
https://duckduckgo.com/?q=9000+php+to+usd&ia=currency

![image](https://cloud.githubusercontent.com/assets/81969/13902562/6d8b17e2-ee23-11e5-9904-883ad28cb5ee.png)

---
IA Page: https://duck.co/ia/view/currency
Maintainer: @MrChrisW

**Comment by moollaza** [comment]
@jagtalon what width are the images supposed to be?

**Comment by jagtalon** [comment]
@moollaza It should be like this:

![](https://cloud.githubusercontent.com/assets/81969/4762660/1bc2622e-5b05-11e4-9f97-a43365d309d2.png)

![](https://cloud.githubusercontent.com/assets/81969/4762661/1bc44242-5b05-11e4-97d9-8beaa2fa53cb.png)

**Comment by moollaza** [comment]
@duckduckgo/duckduckhack-active-contributors anyone interested in tackling this?

Please leave a comment to let us know!

The issue here is that the image needs to have a fixed size so that on retina screens we're rendering the 2x sized image at the original size, instead of at 2x the size.

**Comment by flygeneticist** [comment]
Hi @moollaza, I'll try and take a shot at this!

**Comment by zekiel** [comment]
@moollaza please assign to @flygeneticist  when you're able. I just sent an invite. 

Thanks again @flygeneticist !

**Comment by tagawa** [comment]
This looks good to me now. Thanks for the fix @flygeneticist!
