### ISSUE TITLE
ProductHunt: Tile sizes are inconsistent

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#2604]
![image](https://cloud.githubusercontent.com/assets/81969/13902571/c49a6628-ee23-11e5-9982-45221e6f746f.png)

The sizes sre different for some of the tiles. They should all have the same size.

**Comment by mattr555** [comment]
@jagtalon should have been closed in #2598.

**Comment by jagtalon** [comment]
Oh, I missed that! Thanks @mattr555!
