### ISSUE TITLE
ExpandURL: API Gone offline - Update to new API: ExpandURL.com

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2605]
It looks like http://longurl.org is offline -- For now I've turned off this IA. We need to determine if the API is offline permanently and if so, find an alternative or remove the Instant Answer until we have an API.   

------
IA Page:  http://duck.co/ia/view/expand_url 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @adman

**Comment by moollaza** [comment]
It looks like there is another free API we can use, aptly named, ExpandURL: 

http://expandurl.com/api.php

Anyone interested in porting this IA?

**Comment by sahildua2305** [comment]
@moollaza Still open?

**Comment by sahildua2305** [comment]
I worked a bit on this one. @moollaza 
It's returning `406 Not Acceptable` to API calls to http://expandurl.com/api/v1/?url=http://sahildua.com/&format=json&detailed=true which work otherwise in the browser.

Here - http://circus-theory.codio.io:5000/js/spice/expand_url/sahildua.com

**Comment by sahildua2305** [comment]
I did some more research on this. 406 may be due to the response header type which is - `Content-Type:text/html`. Any idea how to make this work? Is this clear or should I put up a PR first to show the changes? @moollaza

**Comment by moollaza** [comment]
> Any idea how to make this work?

@sahildua2305 there's some discussion in #2610 -- it will require some internal investigation, or reaching out to ExpandURL to see why exactly they're sending us a 406
