### ISSUE TITLE
Dictionary: "define fungi" shows two play buttons

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#2609]
And they're in the subtitle--it should be right beside the title.

https://duckduckgo.com/?q=define+fungi&ia=definition
![screen shot 2016-03-21 at 9 58 58 am](https://cloud.githubusercontent.com/assets/81969/13920893/9bd1080e-ef4b-11e5-8b73-34fb90a685aa.png)

---
https://duck.co/ia/view/dictionary_definition
Maintainer: @jagtalon

**Comment by moollaza** [comment]
Hey @duckduckgo/duckduckhack-active-contributors! Anyone interested in fixing this issue?

It'll require a bit of JS knowledge. We had made some changes the the DDG Playbutton for the [Forvo Spice](https://duck.co/ia/view/forvo) and I think this IA will need some adjustments as a result.

A good place to start looking is here: https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/dictionary/definition/dictionary_definition.js#L187

**Comment by marianosimone** [comment]
@moollaza: I'd love to take a look. However, it seems like in my dev environment only 1 play button is shown (working from codio, with latest duckpan installed)

**Comment by moollaza** [comment]
@marianosimone it looks like we're making a secondary API call in production for `fungus`. We should probably add a check that if a player exists on the page, we shouldn't add another?

**Comment by tagawa** [comment]
Fixed internally.
