### ISSUE TITLE
Time: Off by 1-hour for DST affected locations

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2611]
DST has taken affect and so times have shifted by 1 hour. It looks like we're not using the API's results but instead we're using Moment.js to parse the timezone -- this is leading to incorrect information.

When I inspect the results from the API everything looks correct. Similarly, a new JS Date object also has the correct info.

We should trust the API when the location is deemed relevant. I don't think we should be parsing timezones.

------
IA Page:  http://duck.co/ia/view/time 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by MrChrisW** [comment]
>this is leading to incorrect information.
Can you provide some example queries?

**Comment by moollaza** [comment]
@MrChrisW it turns out the problem isn't really with the IA, it's with the anonymized location our Location API gives for my IP. It's giving a location 1200KM away which happens to be in the next time-zone over, so the IA is working correctly.

@MrChrisW I think what we'll want to do is trust the API if we deem the location to be relevant, instead of using DDG's `$loc`

**Comment by MrChrisW** [comment]
@moollaza :+1: Right... These changes were introduced in #2357 

> think what we'll want to do is trust the API if we deem the location to be relevant, instead of using DDG's $loc

You want to check the relevancy of the location returned by DDG `$loc` with the API response and present a result? However that won't fix any issues if the provided `$loc` is incorrect.

**Comment by moollaza** [comment]
> You want to check the relevancy of the location returned by DDG $loc with the API response and present a result? However that won't fix any issues if the provided $loc is incorrect.

@MrChrisW yeah you're right, I'm not sure what I was thinking -- I think we need to update our GeoIP Database :+1:

**Comment by MrChrisW** [comment]
Closing in favour of https://github.com/duckduckgo/zeroclickinfo-spice/issues/2567
