### ISSUE TITLE
Forvo: Layout breaks with long words on small screens

### ISSUE THREAD

**Issue by EpicWolverine** [duckduckgo/zeroclickinfo-spice#2621]
Search results with long words/phrases break the layout on small screens where the result must take up more than one line. For example, searching "pronounce cheese" on the iPhone 6 returns "Peter Anderson cheese [en]", which wraps and takes up two lines in portrait. This causes all of the genders, nationalities, and flags on the right to be offset down by almost a line.
![asset](https://cloud.githubusercontent.com/assets/2897970/14030557/993a6e42-f1de-11e5-8c38-f220002e4cce.PNG)

------
IA Page:  http://duck.co/ia/view/forvo

**Comment by tsl143** [comment]
can we use `css property - ellipsis` to solve this?
also can anyone guide me how to start ?

**Comment by carolyz** [comment]
Just submitted my attempt. This is my first time doing this so please give me a shout if there is anything out of place and I will be happy to fix it!

**Comment by alohaas** [comment]
@carolyz awesome! taking a look.

**Comment by alohaas** [comment]
Hey @carolyz wondering if you saw my feedback on #2763 ? Let me know if you want some support.

**Comment by carolyz** [comment]
Thanks so much for the tip! This thread somehow ended up in the spam
folder. I'll get on it today. Thanks again!
