### ISSUE TITLE
Currency: Default conversion is to Euro, not local currency if location is given

### ISSUE THREAD

**Issue by John-O-Really** [duckduckgo/zeroclickinfo-spice#2623]
This is a suggestion, if possible it would make a ton of sense if the default conversion used the local currency. 
Here's an example. 

Currently searching for "$10" will respond with the conversion in euros. To change it to GBP I have to suffix the figure with "in GBP". I've given DuckDuckGo my region information for relevant results. Ideally this could be used for the default conversion. So searching for just "$10" would give me the price in GBP. 

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by MrChrisW** [comment]
@John-O-Really Thanks you for the suggestion! this is currently being addressed in #2069 - although there's not much process at this stage. I'll close this as a duplicate.Thanks!
