### ISSUE TITLE
Currency: Indian numbering system

### ISSUE THREAD

**Issue by kanishkablack** [duckduckgo/zeroclickinfo-spice#2624]
Support of Indian numbering system

https://en.wikipedia.org/wiki/Indian_numbering_system

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

update: added wiki

**Comment by MrChrisW** [comment]
@kanishkablack Thanks for your suggestion, currently we're focused on English based instant answers until localization is improved.

**Comment by marti1125** [comment]
Hi @MrChrisW how I can spanish translation for this IA ?

**Comment by MrChrisW** [comment]
@marti1125 This is currently not possible until DDG integrates Instant answer translations.

**Comment by edgesince84** [comment]
Since we're not doing IA translations at this time, I'm going to close this one out!  thanks.

**Comment by Breakfastisready** [comment]
Hello.

Is it possible to open this issue again? It's been a while and perhaps IA translations are not so far behind in priorities now? 

Only if you can implement that if commas are placed in Indian numbering system then the splice still shows up, that could be sufficient for now.

**Comment by moollaza** [comment]
> Is it possible to open this issue again?

Sorry @Breakfastisready, but DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.
