### ISSUE TITLE
Forecast: Weather translation and country selection

### ISSUE THREAD

**Issue by valvin1** [duckduckgo/zeroclickinfo-spice#2629]
When I'm searching the weather forcast for my country (France) I'm searching "météo CITY_NAME" "météo" is the french translation of "weather" which is the current keyword to trigger this Instant Answer. 

1/ is it possible to trigger this IA with this french translated keyword ? maybe it concerns other languages ?

"CITY_NAME" is a the city name (in french) located in France. I am using DDG without region so the city name is looking for worldwide. I have USA or Switzeland city name.

2/ is it possible to filter the city name to the translated keyword region ? For example if I search "météo béthune" Forecast IA is looking for a city located in France (or french spoken country) only because it knows "météo" is the french translation of "weather". 

Thanks :)

---

IA Page:  http://duck.co/ia/view/forecast 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @himanshu0113

**Comment by moollaza** [comment]
> 1/ is it possible to trigger this IA with this french translated keyword ? maybe it concerns other languages ?

Thanks for this suggestion. For now we're using English trigger words until we have a plan for translation and localization of Instant Answers.

> 2/ is it possible to filter the city name to the translated keyword region ? For example if I search "météo béthune" Forecast IA is looking for a city located in France (or french spoken country) only because it knows "météo" is the french translation of "weather".

This is a neat idea, but we don't currently have a way to do this. We'd need to be able to determine the language and infer a country. 

The Forecast API quite simple though: it takes a location string as input and gives us a list of potential matches. This is a special Instant Answer that uses the organic links to infer the location. So with a french region boost "béthune" produces a result for France. With Canada it should go to Bethune, Saskatchewan and with a US region boost it should show Bethune, California

**Comment by stormwindy** [comment]
If you need Turkish translation in the future for such things, let me know. @moollaza

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.

**Comment by claell** [comment]
That explanation sounds not right. If the current state is not ideal, why not think about a better solution and only cancel it when the better solution is available? Instead now you change it to almost the worst case and say that you think about a better solution. I don't understand that logic.
