### ISSUE TITLE
Forvo: inconsistent results

### ISSUE THREAD

**Issue by azurely** [duckduckgo/zeroclickinfo-spice#2630]
When triggered with searches such as `pronounce duck` or `how to say electrophotomicrographically`, it works as expected.

Sometimes only one trigger works:
- [x] `pronounce Ralph Fiennes`
- [x] `how to pronounce ralph fiennes`
- [x] `ralph fiennes how to pronounce`

(sorry ralph)

------
IA Page:  http://duck.co/ia/view/forvo
Maintainer: @alexbaforvo

**Comment by zekiel** [comment]
@alexbaforvo there seem to be a collection of issues w/ Forvo right now. Do you want to take a pass at updating?

**Comment by zekiel** [comment]
@azurely  Ralph approves http://media.riffsy.com/images/b8bb3c3b9c50ff594dea56fb7e76aa5f/raw

**Comment by moollaza** [comment]
@azurely I'm seeing results for all of those queries?

https://duckduckgo.com/?q=pronounce+Ralph+Fiennes&ia=answer

https://duckduckgo.com/?q=how+to+pronounce+ralph+fiennes&ia=answer

Please confirm that they're still not working for you. The trigger's can't be "selective" so, they're either working for all queries, or they should be working for none.

**Comment by azurely** [comment]
Nope, still not working for me. Just video results. 
Several of the (broken) examples I was going to use started working while I was testing them!

**Comment by tagawa** [comment]
All these queries are working for me, although the video tab takes priority - I need to click the "Answer" tab to see the pronunciation IA.

**Comment by zekiel** [comment]
@azurely these are all working for me as well but, as @tagawa said, the Answer tab where they appear is not coming up by default. I'm guessing it's do to with a slow response time so the tab falls back to images or videos to prevent the page from bumping: 

https://duckduckgo.com/?q=pronounce+Ralph+Fiennes&ia=answer  
https://duckduckgo.com/?q=how+to+pronounce+ralph+fiennes&ia=answer  
https://duckduckgo.com/?q=ralph+fiennes+how+to+pronounce&ia=answer 

Do you still have this problem? If it's slow for a particular region, it may be a bigger issue than we're seeing here.

**Comment by azurely** [comment]
I am now seeing the answer tab in addition to videos! Should this issue be closed now, or is it useful as a reference for the video fallback dealio?

**Comment by tagawa** [comment]
Me too! The Answer tab is now taking priority. The devs made a little tweak to tabs a few hours ago so I reckon that's had an effect. Anyway, closing for now and we can re-open again if necessary.

Thanks for reporting and checking back @azurely.
