### ISSUE TITLE
AlternativeTo: Add more triggers

### ISSUE THREAD

**Issue by spagy** [duckduckgo/zeroclickinfo-spice#2631]
It looks like you have to type "alternative to foo" in order to trigger this IA.

It would be useful if "foo alternative" and "foo alternatives" also worked.

---

IA Page:  http://duck.co/ia/view/alternative_to 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @vikashvverma

**Comment by vikashvverma** [comment]
I'm not well right now. Will start working after two weeks

**Comment by moollaza** [comment]
>I'm not well right now. Will start working after two weeks

@vikashvverma very sorry to hear that. Please take all the time you need to get better! 

FWIW you don't necessarily have to do the work, you can let others do it and weigh in on their PR :+1: 

Hope you get better soon!

**Comment by vikashvverma** [comment]
@moollaza sure

**Comment by vikashvverma** [comment]
@Spagy @moollaza It seems those triggers are already there but it does not seem to trigger for queries like:

https://duckduckgo.com/?q=notepad+alternatives

**Comment by moollaza** [comment]
@vikashvverma the triggers are there, but the regex in the `handle` prevents "foo alternative(s)" from triggering the IA.

**Comment by vikashvverma** [comment]
@moollaza I will look into it

**Comment by moollaza** [comment]
IA is no longer online
