### ISSUE TITLE
XKCD: Cached comics are outdated

### ISSUE THREAD

**Issue by doebi** [duckduckgo/zeroclickinfo-spice#2634]
The ZCI shows another comic than the website. It is not up to date.
Didn't check the source, but it seems as if it is not able to update properly.

------
IA Page:  http://duck.co/ia/view/xkcd 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sdball

**Comment by sdball** [comment]
What other comic are you getting? It seems to be working fine to me.

<img width="566" alt="ddg_xkcd" src="https://cloud.githubusercontent.com/assets/45837/14154538/f234b826-f68a-11e5-9776-d0b5be0387c2.png">

**Comment by doebi** [comment]
Yeah right. i also get "Podium". but the latest one is "Jack and Jill", isn't it?
What i see: 
![2016-03-30-212341_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1591457/14154675/0f0036aa-f6be-11e5-800c-bf37c08605d1.png)

**Comment by sdball** [comment]
Ahh by "different comic" I thought it was returning something other than XKCD entirely.

**Comment by mattr555** [comment]
Spices are cached for [24 hours by default](http://docs.duckduckhack.com/backend-reference/api-reference.html#caching). Setting a `spice proxy_cache_valid` attribute would fix it.

**Comment by sdball** [comment]
Hey that sounds right, thanks @mattr555! I'll get that changed to something shorter.

**Comment by sdball** [comment]
Unfortunately I just don't have the available time to volunteer for maintain this awesome plugin. https://github.com/duckduckgo/zeroclickinfo-spice/issues/992#issuecomment-206559354

I'm not sure what the process is for switching maintainers, but from the looks of these threads there's no shortage of qualified folks. :smile:

**Comment by gaulrobe** [comment]
@sdball I took a stab at this in #2670! I'd also be more than happy to maintain this :smile:

**Comment by GuiltyDolphin** [comment]
Ping @zekiel.
