### ISSUE TITLE
Beta Instant Answers (Internal): CSS Should be Namespaced

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2635]
The CSS rules for IA's must be prefixed with `.zci--<id>` to ensure that the CSS rules do not affect other elements on the page.

This IA should have it's CSS updated so that it only applies to the `.zci` container for its tiles.

------
IA Page:  http://duck.co/ia/view/experimentalia
Maintainer: @vikashvverma

**Comment by moollaza** [comment]
@duckduckgo/duckduckhack-contributors Anyone willing to help us? We need someone to fix this bug.

You'll only need a basic understanding of CSS to tackle this. Looking at any other CSS files in the repo should indicate how the CSS rules here should look.

As well, seeing as this IA was just open-sourced today, _**it is in need of a maintainer**_. Anyone interested?

----

There is one other noticeable bug which needs to be fixed. Unicode isn't being handled properly causing Unicode example queries to display incorrectly and this needs to be fixed ASAP.

You can see the breakage here: https://beta.duckduckgo.com/?q=testing&t=h&ia=iatesting&iai=53

![testing_at_duckduckgo](https://cloud.githubusercontent.com/assets/873785/14163705/f4387d52-f6c5-11e5-8d74-70de43006188.png)

**Comment by vikashvverma** [comment]
@moollaza I am willing to be a maintainer

**Comment by lxndio** [comment]
@moollaza I'd also maintain if more than one person is needed.

**Comment by Edvac** [comment]
Count on me too!

**Comment by rasikapohankar** [comment]
Hi! I don't know this code but was looking through it for the Unicode bug and found that the answer gets its results from https://beta.duckduckgo.com/installed.json and in this JSON, the example query for Emojipedia is incorrect.
![c44404](https://cloud.githubusercontent.com/assets/8025692/14179557/24839d04-f77d-11e5-8406-ebf24c48788d.png)
So maybe we will have to check the part where the JSON gets generated?

**Comment by jdorweiler** [comment]
@rasikapohankar thanks, I'll fix that.

**Comment by jdorweiler** [comment]
@vikashvverma thanks, I set you as the maintainer.

**Comment by jdorweiler** [comment]
The unicode bug seems to be fixed.
![selection_313](https://cloud.githubusercontent.com/assets/1882892/14320038/8d4a8a9c-fbe1-11e5-9cf1-ea71c93bb5a2.jpg)

**Comment by rasikapohankar** [comment]
@moollaza Can this be closed?
