### ISSUE TITLE
Beta Instant Answers (Internal): Modified time incorrect

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-spice#2637]
I consistently get incorrect times for the 'Last Updated....' field, it was 5 hours behind during EST and switched to 4 hours behind after the switch to EDT, my TZ is currently BST (though was GMT until a few days ago).

![screenshot from 2016-03-31 11 48 49](https://cloud.githubusercontent.com/assets/8598426/14173659/34d300fa-f737-11e5-98f7-7940b1b619ff.png)

------
IA Page:  http://duck.co/ia/view/experimentalia
Maintainer: @vikashvverma

**Comment by vikashvverma** [comment]
@GuiltyDolphin @moollaza I'm not able to run the trigger for this IA locally, Can you help me out?

**Comment by jdorweiler** [comment]
@vikashvverma with duckpan?  Try this `SHOW_IA_TESTING=1 duckpan server`.  It triggers on all queries so I have it disabled unless you set an environment variable.
https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Experimentalia.pm#L15

**Comment by vikashvverma** [comment]
@jdorweiler I did that still it says, `Sorry, no hit for your instant answer`

**Comment by jdorweiler** [comment]
@vikashvverma can you post your output from running that?

**Comment by vikashvverma** [comment]
@jdorweiler I'm trying to access it at this url http://localhost:3000/?q=testing&t=h&ia=iatesting, duckpan server is running  on port 3000

**Comment by jdorweiler** [comment]
@vikashvverma is your repo up to date?  Try setting the environment variable with  `export SHOW_IA_TESTING=1` and then run duckpan.

**Comment by jdorweiler** [comment]
Or if that fails you could just manually set this value to `1`.
https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Experimentalia.pm#L15

**Comment by vikashvverma** [comment]
@jdorweiler It works now, one of the dependency was not installed. Thanks

**Comment by vikashvverma** [comment]
@GuiltyDolphin the problem is because `moment.js` is giving relative time based on timezone,  I will work on this
