### ISSUE TITLE
Thesaurus: "similar looking flags" shows synonyms of "looking"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2638]
We need to ensure the remainder of the query doesn't contain multiple words.

Right now any query that starts with similar will trigger a search for synonyms of the second word in the query, regardless of what the rest of the query is

------
IA Page:  http://duck.co/ia/view/thesaurus 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @lactose

**Comment by sekhavati** [comment]
@moollaza This is already fixed in #2450

**Comment by tagawa** [comment]
Indeed it is - thank you @sekhavati 🍰
