### ISSUE TITLE
Astrobin Apod: Suggestion: Clicking on the picture shows full picture instead of redirecting to AstroBin page

### ISSUE THREAD

**Issue by gvanwaelvelde** [duckduckgo/zeroclickinfo-spice#2641]
If a user clicks on the astronomy picture that appears on the Instant Answer, she is redirected to the AstroBin page that contains that picture (e.g. http://www.astrobin.com/242917/ ). It might be more useful to redirect to the picture itself (like this http://www.astrobin.com/full/242917/0/ ), as I suspect that when a user clicks the image she want to see a larger version of the picture to see it in more detail.

---

IA Page:  http://duck.co/ia/view/apod 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @killerfish

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
