### ISSUE TITLE
BBC: API Deprecation Warning -- Need to update for new API

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2652]
The API has started serving 404 errors and indicates that it will soon be deprecated. 

http://www.bbc.co.uk/bbcone/programmes/schedules/london/2016/4/5.json

---

IA Page:  http://duck.co/ia/view/bbc 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): _**Maintainer Needed!**_

**Comment by MrChrisW** [comment]
Looks like we'll need to wait for the BBC developer site to open registrations for API use. - https://developer.bbc.co.uk/user/register

>The BBC Developer site is currently open for registration to BBC Employees. Account requests from other users are not currently being activated. Please check back soon for more info.

**Comment by bkayaarda** [comment]
Look at this http://www.bbc.co.uk/developer/technology/apis.html 
This API beta release

**Comment by tagawa** [comment]
Still seems to be for employees only: https://developer.bbc.co.uk/

**Comment by moollaza** [comment]
IA is no longer online
