### ISSUE TITLE
Cryptocurrency: Ethereum isn't currency - it's a protocol, network, platform.

### ISSUE THREAD

**Issue by fzzr-** [duckduckgo/zeroclickinfo-spice#2655]
Request [`1 etherium in btc`](https://duckduckgo.com/?q=1+etherium+in+btc) should be not valid because Ethereum isn't a (crypto)currency - it's a protocol, network, platform. Official description is "Ethereum is a decentralised platform that runs smart contracts" [here](https://www.ethereum.org).

But on the Ethereum platform we have couple of buildin currencies:
- Ether (ETH)
- Finney
- Szabo
- Wei

For more info see official wiki ["Currency And Issuance"](https://github.com/ethereum/wiki/wiki/White-Paper#currency-and-issuance).

One ETH isn't Ethereum. Ether is currency on Ethereum platform and `1 Ether = 1000000000000000000 Wei`.

---

![screen shot 2016-04-06 at 23 06 31](https://cloud.githubusercontent.com/assets/888526/14331053/a544cb12-fc54-11e5-9e55-1098aa8061df.png)

---

IA Page:  http://duck.co/ia/view/cryptocurrency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @claytonspinner

**Comment by claytonspinner** [comment]
@fzzr- Thanks for catching this. I'll update it so it triggers on `ether` but not `etherium`.

**Comment by edgesince84** [comment]
can this be closed out by #2698?

**Comment by pjhampton** [comment]
I believe this has been fixed. See: https://www.reddit.com/r/ethereum/comments/6eu7je/duckduckgo_has_an_eth_currency_conversion/
