### ISSUE TITLE
Indeed Jobs: Over-triggering when other job site names are in query

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-spice#2659]
A user on DuckDuckGo reported that this IA is over-triggering. The IA shouldn't display when another job engine is specified in the query (monster, careerbuilder, totaljobs, etc.)    

---

IA Page:  http://duck.co/ia/view/indeed_jobs 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @tagawa

**Comment by tagawa** [comment]
Just remembered this - thanks.
Wondering about the best approach. Probably just hard-coding large job sites (such as the ones you mentioned) into the regex so the query is ignored.
