### ISSUE TITLE
Haxelib: Data Source not provided

### ISSUE THREAD

**Issue by fzzr-** [duckduckgo/zeroclickinfo-spice#2662]
Currently on the [IA-Page](https://duck.co/ia/view/haxelib)

>Data Source
>No data source provided.

But needed mention data-source-server. I think it should be something like "lib.haxe.org with adapter haxelib-json.herokuapp.com". Please correct my wording if I wrong.

------
IA Page:  http://duck.co/ia/view/haxelib 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @TomBebbington

**Comment by tagawa** [comment]
Well spotted @fzzr- 
I've just added the source. I think that field is supposed to have a single URL so I just used lib.haxe.org

**Comment by fzzr-** [comment]
Thank you, @tagawa.
