### ISSUE TITLE
XKCD: Unicode characters in titles are not displayed correctly

### ISSUE THREAD

**Issue by EpicWolverine** [duckduckgo/zeroclickinfo-spice#2663]
https://duckduckgo.com/?q=xkcd+1137&t=ffab&ia=comics

The title returned by the JSON API is `\u00e2\u0080\u00aeLTR`, which should display as "RLT" but instead displays like this for me (Firefox 45.0.1 on Windows 10 and Safari on iOS 9.3.1):

![firefox_2016-04-07_14-49-58](https://cloud.githubusercontent.com/assets/2897970/14363008/11838b44-fcd0-11e5-8377-6c1e75b61fe6.png)

**Comment by gaulrobe** [comment]
@EpicWolverine thanks for finding this issue! I've created a fix for this in #2682.
