### ISSUE TITLE
Add internationalization to instant answers

### ISSUE THREAD

**Issue by claell** [duckduckgo/zeroclickinfo-spice#2666]
I requested an instant answer to be localized for Germany https://duck.co/forum/thread/19943/wheather-instant-answer-is-not-localized-for-germa

I was told that the current approach is to try to use some method working for all answers or translate all answers at once: https://github.com/duckduckgo/zeroclickinfo-spice/pull/1703#issuecomment-87703743

So since there is no issue regarding this (at least I haven't found one) I thought it might be good to create one to keep track of the progress.

In general I think it would be hard to implement a method working for all instant answers.
Maybe it is possible for the **triggers** using a dictionary. That would be a first and probably not to complicated step.

It is also the most important one in my opinion. Most users search in their own language, so they won't get instant answers without this. However (I assume) many speak English so it is not that bad that the answer itself is currently not localized.

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
