### ISSUE TITLE
XKCD: Feature: Show comic based on title

### ISSUE THREAD

**Issue by spagy** [duckduckgo/zeroclickinfo-spice#2668]
It would be cool if this IA triggered when comic titles where searched for.

E.g. searching `xkcd time travel` would have the same result as `xkcd 630`

---

IA Page:  http://duck.co/ia/view/xkcd

**Comment by gaulrobe** [comment]
@Spagy unfortunately the XKCD API doesn't support searches by titles.

https://xkcd.com/json.html

**Comment by GuiltyDolphin** [comment]
Herum, there's always http://imgs.xkcd.com/comics/..., so we could *try* that link if they provide words.

**Comment by gaulrobe** [comment]
@GuiltyDolphin nice idea! Looking at XKCD API results a bit more and I noticed that the image extension can be different (http://xkcd.com/100/info.0.json shows .jpg for example). Don't want this ending up being a lot of guesswork in order to make the call...

**Comment by GuiltyDolphin** [comment]
@gaulrobe There's a [lovely long list](http://www.explainxkcd.com/wiki/index.php/List_of_all_comics_%28full%29) that does indeed show some are JPEG and some are PNG.

**Comment by gaulrobe** [comment]
@GuiltyDolphin those image links don't quite match up with what the API returns (http://xkcd.com/1335/info.0.json shows `now.png` while that link shows `now.gif`). Probably don't want to rely on the Explain site for these assets.

It might be worth reaching out to the API maintainer to see if some kind of fuzzy matching search could be implemented to help us out here?

**Comment by GuiltyDolphin** [comment]
@gaulrobe Sure - it'd be a pretty nifty feature.

I'll ping @moollaza and ask if he can have a look into it, feel free to try and contact them yourself!

**Comment by gaulrobe** [comment]
@GuiltyDolphin @moollaza 

I've reached out to XKCD about this, if I hear back I'll let y'all know! :grinning:

**Comment by gaulrobe** [comment]
@moollaza @GuiltyDolphin I never heard back from XKCD about this :disappointed: 

Should we close this issue for now?

**Comment by gaulrobe** [comment]
#992 implies that @davean is working on a new API for XKCD. We may want to wait and see what that looks like when the time comes to address this issue and 992.

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are only accepting issues for essential bugs/fixes.
