### ISSUE TITLE
XKCD: Maintainer Request

### ISSUE THREAD

**Issue by gaulrobe** [duckduckgo/zeroclickinfo-spice#2674]
I would like to become the maintainer for this! Thanks!

------
IA Page:  http://duck.co/ia/view/xkcd

**Comment by zekiel** [comment]
thanks @gaulrobe! This is now official: https://duck.co/ia/view/xkcd  Please check out the [maintainer guidelines](http://docs.duckduckhack.com/maintaining/guidelines.html) and ask if you have any questions at all!
