### ISSUE TITLE
Color Picker:  Inconsistent behavior when searching for "color picker" and "colorpicker"

### ISSUE THREAD

**Issue by itsrachelfish** [duckduckgo/zeroclickinfo-spice#2675]
When you search for "color picker" your search string is populated as the default: https://duckduckgo.com/?q=color+picker+%23af0eff

But when you search for "colorpicker" your search string is ignored and you get a random color: https://duckduckgo.com/?q=colorpicker+%23af0eff&ia=colorpicker

---

IA Page:  http://duck.co/ia/view/color_picker 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @chrisharrill

**Comment by akanshgulati** [comment]
@moollaza it should also be moved to goodies now.

**Comment by moollaza** [comment]
This was solved when the IA was ported to the Goodie repo
