### ISSUE TITLE
Gravatar: Encoding bug

### ISSUE THREAD

**Issue by Bitsnoxx** [duckduckgo/zeroclickinfo-spice#2676]
Im not sure exactly what the issue is;
If you search up Gravatar x@gmail.com and you have & in your bio is displays as &amp; .

------
IA Page:  http://duck.co/ia/view/gravatar 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @adman

**Comment by moollaza** [comment]
@Bitsnoxx do you have a real example we can investigate?

**Comment by Bitsnoxx** [comment]
Yes!
[Here you go](https://duckduckgo.com/?q=gravatar+simonfolde%40gmail.com&ia=avatar), [Gravatar profile](http://nb.gravatar.com/bitsnoxx)

**Comment by edgesince84** [comment]
@shashankgroovy wanted to tackle this one for his first DDG contribution 💃

**Comment by Adman** [comment]
@moollaza Sorry I haven't noticed this issue. Will fix that
