### ISSUE TITLE
WordMap: Needs to ensure remainder is only 1 word, or remove "similar to" trigger

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2681]
This instant answer triggers on any query that starts with "similar to" and often returns irrelevant results for queries that aren't searching for words/terms.

We need to reduce the IA to only working on single word queries or tighten the triggering to queries that more clearly indicate they're looking for similar _words_.

e.g. https://duckduckgo.com/?q=similar+to+invisible+fence+collar&ia=answer

------
IA Page:  http://duck.co/ia/view/word_map 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @twinword

**Comment by tagawa** [comment]
Fixed by #2683
