### ISSUE TITLE
Spice for movie cast

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-spice#2685]
None of the existing Spice seem to handle `cast of X` for movies. We should either 'upgrade' one of the existing Spice to allow this, or implement one from scratch.

@duckduckgo/duckduckhack-contributors Anyone interested in tackling this?

**Comment by vikashvverma** [comment]
@GuiltyDolphin I'm interested

**Comment by vikashvverma** [comment]
Is there any API available?

**Comment by vishivish18** [comment]
Interested !

**Comment by fzzr-** [comment]
* [The Open Movie Database API](http://omdbapi.com)
* [The Movie DB API](https://www.themoviedb.org/documentation/api)

**Comment by gaulrobe** [comment]
http://developer.rottentomatoes.com/

This one seems pretty good, especially given Rotten Tomatoes status in this department. Looks like you'd have to search for the movie, get its ID, and then hit up another endpoint for the cast info.

https://www.themoviedb.org/documentation/api

This one seems more straightforward to use, but I'm not sure about its reputation...

**Comment by GuiltyDolphin** [comment]
There's a few API's available; it might be worth checking out https://www.themoviedb.org/documentation/api

**Comment by moollaza** [comment]
We already get this info via the Movie IA which uses Rotten Tomatoes, we're just not showing it for those queries.

Should be able to improve this IA to better handle queries like "movie cast x", "movie cast for X", etc

**Comment by GuiltyDolphin** [comment]
@vikashvverma I've just had a chat with @moollaza and it looks like we can use the rotten tomatoes API for this (and extend the functionality of https://duck.co/ia/view/movie).

@moollaza Do you reckon we could display images of the cast (in place of movies) when searching for `cast of X`?

**Comment by vikashvverma** [comment]
@moollaza @GuiltyDolphin Should I improve existing IA to include this or create a new IA.

Also we need movie id instead of movie name in these APIs, that means two API call

**Comment by gautamkrishnar** [comment]
Hey themoviedb looks cool <3

**Comment by GuiltyDolphin** [comment]
@vikashvverma I'd suggest trying to extend the existing IA - most of the work has already been done so it is just a matter of adding the additional features.

If you run into issues with that, just update us here and we can discuss whether or not we wish to use a separate IA/API.

@gautamkrishnar Yeah, looks quite nice. It might be worth trying to use it in the future for more complex answers or answers in which we require greater detail.

**Comment by moollaza** [comment]
> @moollaza Do you reckon we could display images of the cast (in place of movies) when searching for cast of X?

Yes I think that could look good.

**Comment by GuiltyDolphin** [comment]
@moollaza Yeah - I've had a look at the result from the Rotten Tomatoes response, and I can't find any images of the cast? It looks like they provide the 'main' actors in that response, and I believe they have [another, fuller cast API](http://developer.rottentomatoes.com/docs/read/json/v10/Movie_Cast). Images would be useful for recognizing the cast from other movies (faces are sometimes easier to remember than names!).

**Comment by vikashvverma** [comment]
@GuiltyDolphin TMDb provide picture of the cast as well

**Comment by vikashvverma** [comment]
@GuiltyDolphin @moollaza We are already using `TMDb` in movie spice to fetch movie image. I think it would be wise to use `TMDb` to fetch cast info instead of using `RottenTomatoes`

**Comment by GuiltyDolphin** [comment]
@vikashvverma Depending on whether or not we want to extend the existing Spice we could just do the same for cast (use Rotten Tomatoes to get cast then use TMDb for images).

@moollaza Thoughts? Do you want to keep the movie searching within one IA, or are you happy with a new IA for cast?

**Comment by moollaza** [comment]
> @moollaza Thoughts? Do you want to keep the movie searching within one IA, or are you happy with a new IA for cast?

If it's the same API and it isn't too hard to update the code to by dynamic, then keeping it as 1 IA is best. Otherwise 2 IAs is perfectly fine

**Comment by GuiltyDolphin** [comment]
@vikashvverma Status?

**Comment by vikashvverma** [comment]
@GuiltyDolphin Will create a PR in a few days

**Comment by vikashvverma** [comment]
@GuiltyDolphin I will create a PR in a few days

**Comment by vikashvverma** [comment]
@GuiltyDolphin @moollaza It seems same API return the cast info which can be used to display cast info based on original query. But Rotten Tomatoes does not provide picture of cast. I'm thinking of using `TMDb` for cast poster but that will involve network roundup for each cast

**Comment by zekiel** [comment]
@vikashvverma guessing the easier route is the best to start with. After it's on beta (or even live), it should make more sense when pictures would be useful. For example, my guess is that a list of Actors/actresses that link through to a search for them would be just fine for queries like `cast of x` 

A 100% awesome API for movie information has always been an elusive beast :bear: but maybe Mashape has surfaced some new ones? https://market.mashape.com/explore?query=movies&page=1

**Comment by GuiltyDolphin** [comment]
@zekiel Images would be awesome - people sometimes know what the actor *looks* like - but not their name; so they search for `cast of X` to find the actor by face.
