### ISSUE TITLE
Time: shows wrong location and hour is off

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-spice#2686]
It should say "Italy", not "United States". The time is affected too:
![screenshot-duckduckgo com 2016-04-14 18-28-16](https://cloud.githubusercontent.com/assets/3652195/14535590/c75f74de-026e-11e6-9e30-a5dc2cb976a8.png)

---

IA Page:  http://duck.co/ia/view/time 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by GuiltyDolphin** [comment]
@MariagraziaAlastra Just out of curiosity - if you do `time now` and switch to the `Answer` tab, does that display the correct time?

**Comment by MariagraziaAlastra** [comment]
@GuiltyDolphin yeah, that displays the correct time

**Comment by GuiltyDolphin** [comment]
@MariagraziaAlastra Okay, awesome.

Perhaps we should just have a Goodie with some JS for these sorts of queries then? I don't see *why* we need to make any API calls.

**Comment by russellholt** [comment]
The api handles other locations, all the special cases, and we don't have to maintain it.

**Comment by GuiltyDolphin** [comment]
@russellholt Yea, true.

@MariagraziaAlastra Does it display the correct time if you have the region set to Italy?

**Comment by mrshu** [comment]
As far as I can see, the query `date` no longer triggers the `Time` Spice.

I believe this issue is therefore moot and can be closed.
