### ISSUE TITLE
Games 

### ISSUE THREAD

**Issue by hackerone1** [duckduckgo/zeroclickinfo-spice#2689]
------
IA Page:  http://duck.co/ia/view/images 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon

**Comment by mattr555** [comment]
Hi @hackerone1, is there an issue with an instant answer you would like to report? You can reply back to this with an email.

**Comment by edgesince84** [comment]
no response - closing this out for now.
