### ISSUE TITLE
Videos: Why only youtube results

### ISSUE THREAD

**Issue by Rava77** [duckduckgo/zeroclickinfo-spice#2692]
When limiting a search for the type of "Videos" only results from youtube are shown, I never see any results from other video sharing sites, e.g. vimeo, to name just one.
Why is that? And what  can be done to change that behaviour to include all known video sharing sites?
Or is that behaviour set somewhere I am not aware about and that "setting" can be changed?

Cheers

---

IA Page:  http://duck.co/ia/view/videos 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @bsstoner

**Comment by jkrobles** [comment]
YouTube is the only provider since the videos IA is using https://duckduckgo.com/v.js to get the results. That looks like an internal script, someone who has access to it can change it to include other sources.

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
