### ISSUE TITLE
Time: Time does not work certain cities. example: time in Chicago, time for New York

### ISSUE THREAD

**Issue by nningego** [duckduckgo/zeroclickinfo-spice#2694]
<img width="788" alt="screen shot 2016-04-19 at 17 20 57" src="https://cloud.githubusercontent.com/assets/856416/14646947/6c9446fe-0653-11e6-84fa-e435ad3af242.png">

<img width="794" alt="screen shot 2016-04-19 at 17 21 15" src="https://cloud.githubusercontent.com/assets/856416/14646994/a35afec6-0653-11e6-8cec-7681ef34d9c7.png">

------
IA Page:  http://duck.co/ia/view/time 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by MrChrisW** [comment]
@nningego Thanks for reporting this issue. Currently we're tracking a number of triggering issues with the time IA in #1730 - I'll update that issue with the `Chicago` and `New York` triggers and close this one :+1:
