### ISSUE TITLE
Statista: Bad dates showing

### ISSUE THREAD

**Issue by andrey-p** [duckduckgo/zeroclickinfo-spice#2699]
![screenshot_2016-04-22_12-24-52](https://cloud.githubusercontent.com/assets/1431577/14740238/5bf915f2-0885-11e6-9eaf-f5964ad5c878.png)

---
https://duck.co/ia/view/statista
Maintainer: @statista

**Comment by jashgala** [comment]
I am unable to reproduce this.

**Comment by tagawa** [comment]
Me too, I can't get the statistics Instant Answer to trigger at all.

**Comment by statista** [comment]
sorry for the late answer from our side, we changed the API - so the IA should work again

**Comment by tagawa** [comment]
Thanks @statista. Looks like the issue this depends on (#2709) is still having problems so we'll wait for that to get sorted first.

**Comment by edgesince84** [comment]
these look like they're back on track and looking good again.  thanks!
