### ISSUE TITLE
Forecast: Wrong result due to timezone

### ISSUE THREAD

**Issue by vikashvverma** [duckduckgo/zeroclickinfo-spice#2701]
My timezone is IST and the IA is giving forecast of `Phoenixville, PA` which is wrong.

See the snaps below:

<img width="1436" alt="screen shot 2016-04-23 at 10 09 00 am" src="https://cloud.githubusercontent.com/assets/915277/14759309/3a005caa-093c-11e6-86e0-09ef0d20d7d7.png">

<img width="734" alt="screen shot 2016-04-23 at 10 11 59 am" src="https://cloud.githubusercontent.com/assets/915277/14759310/583e0afa-093c-11e6-8e37-2d53d40e8613.png">

Edit: This happened while running locally

IA Page: http://duck.co/ia/view/forecast

**Comment by NaveenKarippai** [comment]
@vikashvverma 

>  let me quote some words from @moollaza here - if you're testing in DuckPAN the location by default is set to US. DuckPAN has no way of knowing where you're located :) In production we are able to detect the country a query came from and the IA uses that to choose the result to show. There are a few testing locations you can force DuckPAN to use: DDG_TEST_LOCATION=de duckpan server for example.
