### ISSUE TITLE
SoundCloud: Text overflows from box

### ISSUE THREAD

**Issue by kirllos** [duckduckgo/zeroclickinfo-spice#2704]
![1](https://cloud.githubusercontent.com/assets/17005305/14762300/8deaa7d6-0990-11e6-8fb3-0a1f0be23cad.png)
![2](https://cloud.githubusercontent.com/assets/17005305/14762301/8def545c-0990-11e6-846d-36b07e560dee.png)

------
IA Page:  http://duck.co/ia/view/sound_cloud 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jdan

**Comment by GuiltyDolphin** [comment]
Uhh, @tagawa this might be a separate issue (not relating to SoundCloud)?

**Comment by tagawa** [comment]
Thanks very much for reporting this @kirllos. It looks like it's something that affects the UI in general so I've moved the issue to our platform repository: https://github.com/duckduckgo/duckduckgo/issues/202
(and thanks for the ping @GuiltyDolphin)
