### ISSUE TITLE
Generalize NYC BikeSharing IA and add more cities

### ISSUE THREAD

**Issue by marianosimone** [duckduckgo/zeroclickinfo-spice#2707]
Given that CitiBike NYC is using the new [GBFS](https://github.com/NABSA/gbfs) format for its feeds, it would be interesting to try to generalize its [Bike Sharing IA](https://duck.co/ia/view/citi_bike_nyc) and make it useful for other cities. A full list of available cities can be found [here](https://github.com/NABSA/gbfs/blob/master/systems.csv) (at this time, there are 19 systems that we could support)

------ 

IA Page: https://duck.co/ia/view/citi_bike_nyc

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
