### ISSUE TITLE
Statistics: API Format Changes -- IA Requires Updates

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2709]
It looks like the API URL Format has changed so this IA broke. We've taken it offline for now. Once repaired we can re-launch this.

@statista can you please update the code accordingly?   

------
IA Page:  http://duck.co/ia/view/statista 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @statista

**Comment by moollaza** [comment]
@statista Ping! Would you be interested in fixing this Instant Answer so it will go live again?

**Comment by moollaza** [comment]
@duckduckgo/duckduckhack-contributors anyone interested in investigating this? 

It looks like the URL Format for the API has changed and so the `spice_to` needs to be updated.

The API Documentation is here: http://www.statista.com/download/Statista-API.pdf -- this should outline the new URL format.

**Comment by NaveenKarippai** [comment]
@moollaza I'd like to tackle this. Please assign it to me, I can try!

**Comment by moollaza** [comment]
@NaveenKarippai thanks! Assigned to you.

**Comment by statista** [comment]
sorry for the late answer from our side, we changed the API - so the IA should work again 
@moollaza : could you doublecheck that?

**Comment by moollaza** [comment]
@statista thanks for getting back to us! I just tried some queries on beta.duckduckgo.com where it's still deployed but I'm not getting any API results back: https://beta.duckduckgo.com/js/spice/statista/fifa

**Comment by moollaza** [comment]
@statista it looks like our API calls are still going to a 404 page -- do any changes need to be made to the Statista Spice's code?

**Comment by statista** [comment]
@moollaza : could you please doublecheck? Unfortunately you were right about this, but we fixed the issue

**Comment by moollaza** [comment]
@statista everything looks good 👍 

The Instant Answer is live again
