### ISSUE TITLE
Advanced Calculator: feedback from user

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-spice#2711]
A user on DDG reported that the calculator IA wasn't triggering for a problem that includes square roots.

ex:
sqrt(5+exp(5+exp(5))+5)

------
IA Page:  http://duck.co/ia/view/symbolab 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @levaly

**Comment by levaly** [comment]
Currently implementation requires inserting the keyword "solve" or "calculate" or "compute.
Here is a link for the above query https://duckduckgo.com/?q=solve+sqrt(5%2Bexp(5%2Bexp(5))%2B5)&ia=calculator

**Comment by GuiltyDolphin** [comment]
@edgesince84 @levaly These sorts of queries should be handled by the Goodie calculator - not the Spice. The Spice should be used for things the Goodie doesn't handle (such as calculus).

**Comment by busyintech** [comment]
Some of the problems are solved through https://www.symbolab.com/ that seem to be possible using the advanced calculator itself. Maybe that needs to be modified
example: https://duckduckgo.com/?q=solve+5*exp6&ia=calculator

**Comment by GuiltyDolphin** [comment]
@busyintech These should be handled fine by the rewrite. We're able to provide higher precision and more functionality (extensibility) *without* needing external API calls. The Spice provides support for calculus (and other operations) which will not be supported by the Goodie for the foreseable future.

**Comment by edgesince84** [comment]
thanks guys, adding "solve" to the query works just fine.  closing this out!

**Comment by busyintech** [comment]
@edgesince84 To improve usability, you may have to consider solving the query without the keyword, just like a modern calculator would do.

**Comment by GuiltyDolphin** [comment]
@busyintech This seems to work fine on Beta with the regular calculator: https://beta.duckduckgo.com/?q=sqrt(5%2Bexp(5%2Bexp(5))%2B5)&ia=answer
