### ISSUE TITLE
Remove Kwixer Spice: Service shutting down

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2712]
As mentioned here: https://github.com/duckduckgo/zeroclickinfo-spice/issues/2710#issuecomment-214572239 Kwixer is shutting down, and has stopped updating their data.

We should remove the code from the repo.

https://duck.co/ia/view/kwixer

**Comment by moollaza** [comment]
If anyone knows of an alternative data source for this information, we can hopefully create a new Spice to handle this query space.

/cc @duckduckgo/duckduckhack-contributors

**Comment by mintsoft** [comment]
@moollaza what about https://www.themoviedb.org/ or http://thetvdb.com/

**Comment by moollaza** [comment]
Looks like those could work!

**Comment by whalenrp** [comment]
Has anyone started this yet? I'd be interested in picking it up if not.

**Comment by tagawa** [comment]
I don't think so @whalenrp so please go ahead! And of course, ping us anytime here or in the Slack channels if you need a hand.

**Comment by iambibhas** [comment]
themoviedb.org doesn't return any result when I search for `films with with Tom Cruise and Emily` or `Tom Cruise and Emily` or `Tom Cruise, Emily`. It only returns result for `tom cruise` or `emily`, but the results are Person type and not movie type. They have a `/find` method, but that requires IMDB ID of the people or movies.

thetvdb.com only returns TV series results. No movie results.
