### ISSUE TITLE
RubyGems: Showing identical repeated results

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#2716]
With this search - https://rubygems.org/api/v1/search.json?query=blacklight - here's what's happening:
<img width="400" alt="ddg-rubygems-blacklight" src="https://cloud.githubusercontent.com/assets/94173/14879800/5bbfe3f0-0d66-11e6-8ccd-ad0adb9f52d4.png">

It looks like the source API is the cause: https://rubygems.org/api/v1/search.json?query=blacklight

------
IA Page:  http://duck.co/ia/view/ruby_gems 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @koosha--

**Comment by iambibhas** [comment]
Looks like it's fixed? 

![](http://storage7.static.itmages.com/i/16/0501/h_1462132249_9322131_141fe8eabf.png)

**Comment by koosha--** [comment]
Apparently, it is fixed as pointed out by @iambibhas.

**Comment by tagawa** [comment]
@iambibhas @koosha-- Oh yes, looks fine now. Thanks for checking.
