### ISSUE TITLE
Rust Cargo Packages: triggering feedback from Reddit user

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-spice#2720]
A Reddit user left feedback on this IA [here](https://www.reddit.com/r/rust/comments/4gujbf/help_improve_duckduckgos_rustrelated_searches/d2l45d5): 

> In particular, I notice that in the Rust Cargo Packages IA, it only links to the one with an exact matching name, which isn't very helpful if you're just looking for crates that deal with a topic without knowing the name. Not sure if IA's can provide a list of the top few matches, but a lot of times that would be more helpful. Also, it can be invoked with "cargo package" or "rust package", but not "cargo crate" or "rust crate", which is generally the terminology used in Rust.   

------
IA Page:  http://duck.co/ia/view/rust_cargo 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @TomBebbington

**Comment by tagawa** [comment]
Looks like both these issues have already been reported, so closing this:
Add fuzzy search: https://github.com/duckduckgo/zeroclickinfo-spice/issues/2718
Add "crate" trigger: https://github.com/duckduckgo/zeroclickinfo-spice/issues/2719
