### ISSUE TITLE
Holiday: Give answers for Mother's Day, Father's Day, etc.

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#2723]
Following a [suggestion on Twitter](https://twitter.com/daytonlowell/status/725342856852824066), it would be helpful if this triggered on things such as `when is mothers day`. This changes depending on country, however, so would probably need to incorporate locale detection as well.

---

IA Page:  http://duck.co/ia/view/holiday 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sekhavati

**Comment by moollaza** [comment]
This should hopefully be resolved when #2722 is fixed

**Comment by sekhavati** [comment]
@tagawa This issue should now be fixed as #2678 has been merged and is live.

**Comment by tagawa** [comment]
@sekhavati Hmm, it doesn't seem to be showing for me: https://duckduckgo.com/?q=when+is+mothers+day

**Comment by sekhavati** [comment]
@tagawa The IA will only search for holidays applicable to your location by default, you can override this by explicitly supplying a country in the query. I took a look at your Github profile and it says you live in Japan but there is no `mothers day` holiday in that country. If you were to query for `when is mothers day in the us` you should find an answer is returned. Let me know if this isn't the case.

On a related note there is a known issue with apostrophes which means queries such as `when is mother's day` won't trigger the IA.

**Comment by tagawa** [comment]
Thanks for the explanation @sekhavati. That's right, I'm in Japan, but we do have mother's day (and father's day) here. Also, I see that "[when is mothers day in the uk](https://duckduckgo.com/?q=when+is+mothers+day+in+the+uk)" is also not triggering, although "[when is fathers day in the uk](https://duckduckgo.com/?q=when+is+fathers+day+in+the+uk)" is OK. I guess these are problems with API though that we can't fix.

**Comment by sekhavati** [comment]
@tagawa I should elaborate, according to `timeanddate.com` there is no holiday in Japan by the name of `fathers day` or `mothers day`, hence why no result is returned. The complete list of known holidays for Japan can be [viewed here](https://www.timeanddate.com/holidays/japan/). 

The second issue relates to aliases which we have yet to implement. Mothers day in the UK is more formerly known as `mothering sunday` hence why your original search did not return a result. Full list of UK holidays can be found [here](https://www.timeanddate.com/holidays/uk/).

**Comment by tagawa** [comment]
@sekhavati Thank you for the details - it's all clear now. I've sent a Tweet to timeanddate.com requesting Mother's Day & Father's Day be added for Japan: https://twitter.com/ourmaninjapan/status/770161403869048833
