### ISSUE TITLE
Currency: Too few decimals for XBT

### ISSUE THREAD

**Issue by MonoMonkey** [duckduckgo/zeroclickinfo-spice#2724]
When calculating any currency into Bitcoins, there are too few decimals (at least for small amounts).
If I enter 0.20 EUR in XBT the answer is 0.00 XBT.

---

IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by iambibhas** [comment]
That's because Bitcoin's price is too high for 0.20 Euro to calculate. Same with any high value currency. E.g. 0.20 INR = 0.00 USD. I think it's a design decision if we want to show more than 2 decimal places.

**Comment by MonoMonkey** [comment]
Maybe it would also help to somehow add the possibility to see the result in mXBT somehow?
That way, we might not even need any more decimal places.
Just throwing out suggestions.

**Comment by iambibhas** [comment]
We can probably add millibitcoin as a currency. But is it a standard? 

Need community input on that.

**Comment by Modanung** [comment]
Yes, mBTC is a common way to display small amounts ([Electrum](https://github.com/spesmilo/electrum) does) and is approximately worth one dollar or euro with the current value of bitcoin.
My first thought would be to simply run a `1 mBTC EUR` query as `0.001 BTC EUR` and display small amounts of bitcoin in mBTC.

**Comment by moollaza** [comment]
Fixed a little while ago in #3140
