### ISSUE TITLE
BaconIpsum: Does not give an answer on live server

### ISSUE THREAD

**Issue by rasikapohankar** [duckduckgo/zeroclickinfo-spice#2726]
The IA is not triggering on the live server but gives an answer on the beta server: https://beta.duckduckgo.com/?q=baconipsum+4&ia=baconipsum
Its in the docs as an example of text template group.

------
IA Page:  http://duck.co/ia/view/bacon_ipsum 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @puskin94

**Comment by stevenmg** [comment]
Seems to be triggering fine: https://duckduckgo.com/?q=baconipsum+4&ia=baconipsum

**Comment by rasikapohankar** [comment]
Yes! :confused: I had checked for two days and it wasn't working when I had made the issue. Sorry I didn't check again later on. Maybe it was temporary?

**Comment by rasikapohankar** [comment]
It is working now, I'll close this.
