### ISSUE TITLE
DNS: Not currently working

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/zeroclickinfo-spice#2727]
Example queries on IA page do not result in the IA

e.g. https://duckduckgo.com/?q=MX%20records%20duckduckgo.com&ia=answer   

---

IA Page:  http://duck.co/ia/view/dns 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @OndroNR

**Comment by OndroNR** [comment]
In fact I wrote only original implementation, which @majuscule rewrote (#113).

**Comment by jonk1993** [comment]
It looks like the example queries trigger fine when running duckpan server on codio, what could cause it to not work on the actual site?

**Comment by stevenmg** [comment]
Works on beta: https://beta.duckduckgo.com/?q=mx+records+duckduckgo.com&ia=answer
Looks like something for DDG staff to look into internally?

**Comment by hughesey** [comment]
Everything is still OK on our end (ViewDNS.info).  We have noticed the query counts dropped to virtually zero from DDG as of June!  @majuscule perhaps this is something you could look into?

**Comment by moollaza** [comment]
IA is no longer online
