### ISSUE TITLE
Advanced Calculator: Compute integral gives wrong result

### ISSUE THREAD

**Issue by mihaiolteanu** [duckduckgo/zeroclickinfo-spice#2731]
I've tried the sample search for "compute integral" but the result is a little bit off:

![duckduckgo_compute_intergral](https://cloud.githubusercontent.com/assets/8273519/15090925/0accde62-1441-11e6-88f1-7f48a0a48a3f.png)

Same with other powers apparently.
The result for x^a always seems to return x^(a+2)/(a+2).

------
IA Page:  http://duck.co/ia/view/symbolab 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @levaly

**Comment by levaly** [comment]
there seems to be a problem with the parser. I will fix asap.

**Comment by levaly** [comment]
this problem is now resolved. cheers!
