### ISSUE TITLE
Zanran: Remove Instant Answer -- Website Offline

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2734]
It looks like Zanran has gone offline (www.zanran.com), we should confirm this and remove the Instant Answer if the website is offline permanently.    

------
IA Page:  http://duck.co/ia/view/zanran 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @taw

**Comment by sahildua2305** [comment]
@moollaza It works now! Website is up again.
