### ISSUE TITLE
Currency: Automatic currency depending on region

### ISSUE THREAD

**Issue by maslic** [duckduckgo/zeroclickinfo-spice#2735]
Could the instant answer choose the default currency based on my region?
I'm in the Czech Republic, so if I enter **$6,5**, the result could be shown in CZK, instead of Euros.

Thanks

---

IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by NaveenKarippai** [comment]
@moollaza I'm interested to tackle this issue. Could you please assign it to me.

**Comment by MrChrisW** [comment]
@NaveenKarippai 👍

**Comment by mintsoft** [comment]
Thanks @MrChrisW
