### ISSUE TITLE
Time: Bad trigger

### ISSUE THREAD

**Issue by Asternitix** [duckduckgo/zeroclickinfo-spice#2738]
This instant answer was triggered by the query: "Duration from Now to 4:15" and showed Athens, Greece.
------
IA Page:  http://duck.co/ia/view/time 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by MrChrisW** [comment]
@Asternitix This doesn't seem to trigger for me
![image](https://cloud.githubusercontent.com/assets/5282264/15586792/d88008b6-234b-11e6-83bf-60af3a647644.png)

**Comment by tagawa** [comment]
It triggers for me on that query, but it shouldn't do. Also, I can't find any of the words ("duration", "now") listed as triggers in https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Time.pm so maybe it's something deeper down that's triggering it?

**Comment by edgesince84** [comment]
This doesn't trigger for me either.

**Comment by MrChrisW** [comment]
This is triggering for me. Looks like internal triggering due to the SERP. 

![image](https://cloud.githubusercontent.com/assets/5282264/17461853/6b429bdc-5ccc-11e6-9d89-72c77598426e.png)
