### ISSUE TITLE
Shorten: IA not functioning

### ISSUE THREAD

**Issue by x-15a2** [duckduckgo/zeroclickinfo-spice#2740]
When using the Shorten IA, no IA interface is displayed, no shortened URL is provided. This was reported in the DDG subReddit and I have verified. The !ISGD !Bang is working correctly and provides a workaround.

------
IA Page:  http://duck.co/ia/view/shorten 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @danjarvis

**Comment by moollaza** [comment]
This IA is now live again 👍

**Comment by moollaza** [comment]
https://duckduckgo.com/?q=shorten+http%3A%2F%2Fwww.duckduckgo.com%2Fabout.html&ia=shortenedlink
