### ISSUE TITLE
Indeed Jobs: overtriggering on "time in (city)" queries

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-spice#2741]
A DuckDuckGo user submitted feedback that this IA is triggering for searches about times in a specific city, such as "time in paoli." The results show part-time jobs.

---

IA Page:  http://duck.co/ia/view/indeed_jobs 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @tagawa

**Comment by moollaza** [comment]
@tommytommytommy Can we address this in the deep trigger?

**Comment by tommytommytommy** [comment]
Apologies for the delay, I've been out! I talked to @jagtalon about this, and there are a few changes that we can make. Assigning to him for follow up.
