### ISSUE TITLE
Just Delete Me: Replace `string.includes()` with IE friendly function

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2743]
Our internal CasperJS tool failed when checking if this Instant Answers was online because of the `string.includes()` method which has been used, because it is not supported across all browsers.

We need to replace this with something that works in Chrome, Safari, FireFox and IE 9+

For now the IA has been disabled in Production

------
IA Page:  http://duck.co/ia/view/just_delete_me 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @riqpe

**Comment by tagawa** [comment]
@moollaza This has just been fixed (and merged) by @riqpe so it should be OK re-enable the IA in production.
