### ISSUE TITLE
Shorten: API Redirecting to HTTPS, Code Update Required

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2744]
This IA has been taken offline because it started failing.

The API now redirects to HTTPS so we need to updated the `spice to` accordingly in order to get this IA online again.   

------
IA Page:  http://duck.co/ia/view/shorten 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @danjarvis

**Comment by moollaza** [comment]
@duckduckgo/duckduckhack-contributors Anyone want to tackle this? The fix is super easy, all you need to do is change `http` to `https` in the `spice_to` string!

**Comment by anthonyn60** [comment]
I can take it
