### ISSUE TITLE
Bike Sharing New York City (Citi Bike): IA Disabled, API URL Changed?

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2745]
This IA has been taken offline because it started failing.

It looks like the URL for the API has changed and is now redirecting to a new subdomain. The `spice to` needs to be updated accordingly to get this IA online again

------
IA Page:  http://duck.co/ia/view/citi_bike_nyc 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @marianosimone

**Comment by marianosimone** [comment]
@moollaza yes... that's why I created https://github.com/duckduckgo/zeroclickinfo-spice/pull/2706 a while ago
