### ISSUE TITLE
Images: https://www.facebook.com/hieu.nguyentrong.10441?pnref=story#

### ISSUE THREAD

**Issue by appleiphonegodfather** [duckduckgo/zeroclickinfo-spice#2747]
------
IA Page:  http://duck.co/ia/view/images 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon

**Comment by moollaza** [comment]
@appleiphonegodfather is there an issue you wanted to report?

Please fill out the Issue Description with details if so. For now I'm closing this issue.
