### ISSUE TITLE
TVMaze Next Episode: IA Taken offline, No longer triggering correctly

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2755]
This IA has been taken offline because it stopped working correctly.

It is still live on Beta and the API response looks to be correct, but the format may have changed? I don't see any console errors, so a more in-depth look needs to be taken to see what's changed and how we can get this IA functioning properly again.   

------
IA Page:  http://duck.co/ia/view/tvmaze_nextepisode 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @tvdavid

**Comment by moollaza** [comment]
@duckduckgo/duckduckhack-contributors would anyone be interested in investigating the problem here?

It would be awesome to get this IA back online again!

**Comment by moollaza** [comment]
My mistake! It looks like this IA is now working again. The API must have been updated!

https://beta.duckduckgo.com/?q=the+big+bang+theory+next+episode&ia=entertainment

**Comment by debprasad** [comment]
Hi,
I'm very interested to contribute. But I'm confused where to start. Can
anybody help me.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by tvdavid** [comment]
Very strange! I'm pretty sure there haven't been any backwards incompatible changes since our API launched, but I can guarantee there haven't been any changes at all in the past weeks.

I think the more likely explanation is that a specific show/episode's generated a response that the code doesn't account for. If you see any problems, let me know the specific query that's causing it and I'll help check it out.

**Comment by moollaza** [comment]
> If you see any problems, let me know the specific query that's causing it and I'll help check it out.

Hey @tvdavid -- our testing system actually uses the example query from the IA Page, so before I changed it today, it was "the big bang theory next episode" which was definitely not working when I made the issue, but is totally working again now.

**Comment by edgesince84** [comment]
@debprasad can you shoot me an email?  I'd love to help you get started on something!  bill@duckduckgo.com 👍

**Comment by edgesince84** [comment]
@debprasad if you're still interested in getting started, please let me know!
