### ISSUE TITLE
Hackage Packages: Provide better information for 'hoogle' searches

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-spice#2756]
When I search for `hoogle a -> b` it would be nice if it displayed which package the function belongs to, as well as the type and short description.

Currently we just have the type and a block description:

![screenshot-2016-05-23-16 02 57_698_272](https://cloud.githubusercontent.com/assets/8598426/15475084/f3faa02c-20ff-11e6-8fc0-f64ff737507e.png)

---

IA Page:  http://duck.co/ia/view/hackage 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nomeata

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
