### ISSUE TITLE
Geometry: Improve triggering

### ISSUE THREAD

**Issue by ghost** [duckduckgo/zeroclickinfo-spice#2757]
The geometry shapes should be triggered just by typing their name ex. Instead of "geometry square" it should trigger with "square" . Please fix it because many people complain about it.

---

IA Page:  http://duck.co/ia/view/geometry 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pixunil

**Comment by GuiltyDolphin** [comment]
@DPAUTH could you link to some complaints (Twitter or some such)? It'd be interesting to see the feedback and specific requests.

**Comment by DPAUTH** [comment]
@GuiltyDolphin Sorry for the late response. I was talking about this with other ducks but if you want to I can tell them to post something on twitter (we all have the same complaint).

**Comment by alohaas** [comment]
@DPAUTH can you link us to those tweets. We'd like to improve triggering for this one if possible.

**Comment by DPAUTH** [comment]
Ok I will tell them to comment it on twitter and I will show the links.

**Comment by alohaas** [comment]
Thanks so much!

**Comment by GuiltyDolphin** [comment]
@DPAUTH BTW this is being ported at the moment (https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3181) - so we might have to wait for that to conclude before we can take *action* on this.

**Comment by moollaza** [comment]
time in paoli
