### ISSUE TITLE
Quote Of The Day: Quote icon cut off on mobile devices

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2758]
On mobile devices the quote icon is clipped making it look broken.

We should fix or remove the icon on smaller screens

------
IA Page:  http://duck.co/ia/view/quote_of_the_day 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pnpninja

**Comment by NaveenKarippai** [comment]
@moollaza I'm interested to pick up this issue. Could you please assign it to me.

**Comment by moollaza** [comment]
@NaveenKarippai assigned!

**Comment by NaveenKarippai** [comment]
@moollaza Please review PR https://github.com/duckduckgo/zeroclickinfo-spice/pull/2781

**Comment by pnpninja** [comment]
Thanks @NaveenKarippai

**Comment by edgesince84** [comment]
Hey @pnpninja, good to see you around these parts again!  Anything new you're thinking of working on?

**Comment by pnpninja** [comment]
Hey there @edgesince1984. I'll try picking up some issues and new features from the list online.. We could extend the quote of the day spice - https://theysaidso.com/api/#qodcat

Showing the quote based on categories

**Comment by pnpninja** [comment]
Hey there @edgesince84. I'll try picking up some issues and new features from the list online.. We could extend the quote of the day spice - https://theysaidso.com/api/#qodcat

Showing the quote based on categories

**Comment by edgesince84** [comment]
@pnpninja sounds good!

**Comment by pnpninja** [comment]
Can we close this issue?
