### ISSUE TITLE
Time: Doesn't seem to trigger for US cities/states

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#2759]
It's fine for "time in paris" or "time in berlin", but not for any US city or state. Have tried Florida, Orlando, Washington, Virginia, Chicago, Boston, Seattle, Maine.

[Reported on Twitter](https://twitter.com/asbradbury/status/735734267104239619)

------
IA Page:  http://duck.co/ia/view/time 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by MrChrisW** [comment]
Thanks @tagawa I'll add this to https://github.com/duckduckgo/zeroclickinfo-spice/issues/1730

**Comment by tagawa** [comment]
Thanks @MrChrisW. You must be busy so much appreciated. Hope things are going well for you by the way.
