### ISSUE TITLE
Color Picker: Use HSL/HSB instead of HSV

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2760]
Suggestion from @russellholt:

The color picker uses HSV whereas the Hex color code IA uses HSL: https://duckduckgo.com/?q=%23ccc&ia=answer

Additionally, Hex color code shows "CMYB"

Our design team mentioned they're more familiar with CMYK and HSB

@duckduckgo/duckduckhack-contributors @duckduckgo/community-leaders I know there are some designers and front-end developers amongst you! Any opinions here?

---

IA Page:  http://duck.co/ia/view/color_picker 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @chrisharrill

**Comment by alohaas** [comment]
I would advocate for CMYK and HSB. Both are valuable for non-digital designers as well!

**Comment by mintsoft** [comment]
@moollaza Just to chime in here; the hex colour code formats are valid CSS formats, that's why they were chosen :)

**Comment by philipmiesbauer** [comment]
I personally use only the hex colour code for android development. But I
can see the advantage of CMYK and HSB for designers. If we want DuckDuckGo
to be used by people other than programmers like us, I think adding those
codes is essential.

**Comment by RCMainak** [comment]
Can we have all the color code formats? That way it'll be a general purpose thing and everyone can use it.

**Comment by xaviervalarino** [comment]
I actually did not realize there was a difference between HSV/B was HSL, until reading this issue!
>_HSL stands for hue, saturation, and lightness, and is also often called HLS. HSV stands for hue, saturation, and value, and is also often called HSB_ (B for brightness) -[Wikipedia]
(https://en.wikipedia.org/wiki/HSL_and_HSV)

For what it's worth, I usually use CMYK when designing for print and RGB(A) or HEX for web, and can't remember the last time I used HSB. That being said I know there are people who use it. We could potentially do both,  but I am concerned it has the potential to crowd the UI and confuse a user like myself (prior to knowing the difference).

My vote would be for making it HSB over HSV.

**Comment by tagawa** [comment]
Looks like HSL has already been added to the IA but I think we should try added HSB as well, to see what it looks like.

**Comment by h4ck3rm1k3** [comment]
Delivered-To: jamesmikedupont@gmail.com
Received: by 10.103.109.70 with SMTP id i67csp1077502vsc;
        Fri, 24 Jun 2016 10:21:43 -0700 (PDT)
X-Received: by 10.200.41.122 with SMTP id z55mr6129396qtz.34.1466788903315;
        Fri, 24 Jun 2016 10:21:43 -0700 (PDT)
Return-Path: <noreply@github.com>
Received: from github-smtp2b-ext-cp1-prd.iad.github.net
(github-smtp2-ext6.iad.github.net. [192.30.252.197])
        by mx.google.com with ESMTPS id r87si5575706qki.259.2016.06.24.10.21.43
        for <jamesmikedupont@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 24 Jun 2016 10:21:43 -0700 (PDT)
Received-SPF: pass (google.com: domain of noreply@github.com
designates 192.30.252.197 as permitted sender)
client-ip=192.30.252.197;
Authentication-Results: mx.google.com;
       dkim=pass (test mode) header.i=@github.com;
       spf=pass (google.com: domain of noreply@github.com designates
192.30.252.197 as permitted sender) smtp.mailfrom=noreply@github.com;
       dmarc=pass (p=NONE dis=NONE) header.from=github.com
Date: Fri, 24 Jun 2016 10:21:39 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466788899;
	bh=ndjyKc3ACkH9B7asHyW3T/5mG/E6isZ4NKW0GdxP/uI=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=WpSdtRwhLyVwofc1IBNgl/pVdK4QXgtygg9PslbEsVk2vox7bXc4m16g+Rl4TymOs
	 6Nd21lQC9KGXK3vrnLf1EEMaaSlBx7ThOr3x5PeFMxuOXxxU4svUSe8LBDWXs4k6zB
	 rNsifiuAIFD5rfiv1P/DlUKHLFjHI5Okh2z8rg+8=

**Comment by moollaza** [comment]
@h4ck3rm1k3 it looks like you had accidentally posted the headers to your email notification here -- did you mean to leave a comment?

**Comment by h4ck3rm1k3** [comment]
I am sorry, I was reporting a bug to github

On Tue, Jun 28, 2016 at 7:29 PM, Zaahir Moolla <notifications@github.com>
wrote:

> @h4ck3rm1k3 <https://github.com/h4ck3rm1k3> it looks like you had
> accidentally posted the headers to your email notification here -- did you
> mean to leave a comment?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/duckduckgo/zeroclickinfo-spice/issues/2760#issuecomment-229214762>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AACIV5wKbnsWxoypGq8ChV-aYrH4y-osks5qQa48gaJpZM4Inre8>
> .
>



-- 
James Michael DuPont
Kansas Linux Fest http://kansaslinuxfest.us
Free/Libre Open Source and Open Knowledge Association of Kansas
http://openkansas.us
Member of Free Libre Open Source Software Kosova http://www.flossk.org
Saving Wikipedia(tm) articles from deletion http://SpeedyDeletion.wikia.com

**Comment by BeRo1985** [comment]
Only as hint, HSB is the exactly same as HSV, only HSL is different, sources:  https://codeitdown.com/hsl-hsb-hsv-color/ and https://stackoverflow.com/a/19602529/371322 and http://www.huevaluechroma.com/093.php
