### ISSUE TITLE
Timer: Have option for alarm to be a quack

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#2761]
For duck-lovers :-)

[Suggested on Twitter](https://twitter.com/xdesigns/status/735888671145132032)

---

IA Page:  http://duck.co/ia/view/timer 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattr555

**Comment by GuiltyDolphin** [comment]
@tagawa I'm just putting this on hold until we've sorted the port - we might want to move the issue to Goodies after that.

**Comment by tagawa** [comment]
Good idea @GuiltyDolphin
