### ISSUE TITLE
Rust Cargo Packages: 

### ISSUE THREAD

**Issue by matthewmorris085** [duckduckgo/zeroclickinfo-spice#2764]
------
IA Page:  http://duck.co/ia/view/rust_cargo 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @TomBebbington

**Comment by zekiel** [comment]
@matthewmorris085  As in #2765, can you please add some descriptive text on what issue you're encountering w/ this IA or what improvement suggestion you have?
