### ISSUE TITLE
Jr.Devjobs: 

### ISSUE THREAD

**Issue by matthewmorris085** [duckduckgo/zeroclickinfo-spice#2765]
------
IA Page:  http://duck.co/ia/view/jr_devjobs 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @HunterMeyer

**Comment by zekiel** [comment]
@matthewmorris085 can you expand on these issues? There's no text and they appear to be working. For this, I noticed that there are multiple "Jobs" tabs so we could potentially rename the tab in this IA

**Comment by zekiel** [comment]
This Instant Answer is being addressed at: https://github.com/duckduckgo/zeroclickinfo-spice/pull/2523
