### ISSUE TITLE
Instant Answers on Beta: 

### ISSUE THREAD

**Issue by shd88** [duckduckgo/zeroclickinfo-spice#2767]
------
IA Page:  http://duck.co/ia/view/experimentalia 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @vikashvverma

**Comment by zekiel** [comment]
@shd88 can you please add some descriptive text on what issue you're encountering w/ this IA or what improvement suggestion you have?

**Comment by zekiel** [comment]
@shd88  would you be interested in helping DuckDuckGo get better at [programming-related searches](https://duck.co/blog/post/297/help-for-programmers)? I'd be happy to sync up w/ you and discuss how to get involved.
