### ISSUE TITLE
Twitter: Add user id in IA Twitter

### ISSUE THREAD

**Issue by vjo** [duckduckgo/zeroclickinfo-spice#2772]
Hello,

I believe adding the `user id` in the Twitter IA card would be useful and almost "free" since it comes in the API response.

I was looking to add it but DuckDuckGo is using a proxy `/tw.js` and it doesn't seems to be available on Github or anywhere else?

Any thoughts or interest in adding the `user id` in the proxy response?

See an example:
https://duckduckgo.com/tw.js?user=duckduckgo

Thanks.

 IA Page: https://duck.co/ia/view/twitter

**Comment by zekiel** [comment]
@vjo  interesting suggestion! Would you use that to get a sense of their twitter join date? Just asking in case there's a better implementation for the info you're taking action on.

**Comment by vjo** [comment]
@zekiel, my use case is just to get `user id` - but maybe I'm the only one that need it from time to time.
To get the date the user joined Twitter, we can get it from the API response as well, using `created_at` field, see https://dev.twitter.com/rest/reference/get/users/show (assuming the proxy use this endpoint).

Ideally, `/tw.js` would proxy to the Twitter API but return all the fields so if we want to enhance the Twitter IA in the future we will have access to all information, such as `id` or `created_at` data.

**Comment by zekiel** [comment]
@vjo  thanks for expanding! Sounds like we found three suggestions from this.  

1. Add `user_id` to twitter IA to show that person's numerical twitter ID.
2. Add "joined on" via `created_at` to twitter IA to show when the person joined twitter
3. Reconfigure Twitter IA to return all fields available so that future updates have all available information. 

I'm not sure why the current implementation doesn't allow that but I'll wait for @jagtalon to respond. We can keep this as one "Improvement" issue for the Twitter IA or tease them out into 3 separate Improvement issues.

**Comment by zekiel** [comment]
@vjo  if @jagtalon  is willing to give up Maintainership of this IA, would you like to lead it instead?

**Comment by vjo** [comment]
@zekiel Thanks for summarizing.
On your 3rd point, I might be wrong but from my understanding, the proxy `/tw.js` is not really part of the IA but a DuckDuckGo owned service we can't access/modify for now. I guess @jagtalon would be able to give us context on it.

Once we figure out this point, I will be happy to help to add available information to the card such as `user_id` and `created_at`.

I have no experience with IA yet, but I'll be happy to contribute to the Twitter IA and maintain it if needed.

**Comment by zekiel** [comment]
thx @vjo  we'll need to think about how we can make this easier to contribute to. I've got an internal task open to evaluate and we'd love your help whenever it's possible.

**Comment by nilnilnil** [comment]
I'm happy to add to the output. Can you be more explicit? I don't see any user_id field in the Twitter API output.

**Comment by vjo** [comment]
Assuming you are using [1.1/users/show.json](https://dev.twitter.com/rest/reference/get/users/show) the `user id` is actually name `id` (or even `id_str` to allow Javascript to deal with long) in the JSON payload.

I'm not sure what's the "integer ID".

On my side, from time to time, I have the need to get the `user id` of a Twitter handle and I figured out it could be nice to add it to your IA card. I understand I may be the only one and it's not worst it, in this case feel free to drop my request.

In the case you plan to modify the `/tw.js` endpoint to add a few more fields, it might be useful to proxy the full Twitter API response in the case we want to enrich the IA with more available data in the future.

**Comment by nilnilnil** [comment]
Thanks for the feedback @vjo. I don't think the id is going to be useful for most people, and would result in clutter for the usual use cases. If there were particular fields that added to the overall experience of the IA, I think those are worth adding.

Closing for now as we're not going to add the ID number to the IA.

**Comment by edgesince84** [comment]
hey @vjo thank you for your suggestions, we really appreciate it!  I'm reaching out to let you know that we recently launched a new forum with the initiative of improving programming-related searches, and I hope you'll [join us](https://forum.duckduckhack.com/)!

There are a lot of important tasks up for grabs that we'd like your help with, so feel free to and [jump in](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53).
