### ISSUE TITLE
Minecraft Status: Use Mojang status API

### ISSUE THREAD

**Issue by marcoslater** [duckduckgo/zeroclickinfo-spice#2774]
Hello,

It would be best to perhaps use a direct Mojang API to query for the status, to prevent misleading error messages in case your personal site may be having any issues.

You can try `https://status.mojang.com/check`, which Mojang use for the https://help.mojang.com/ site as well. 

You can also query info of a specific service: 
`https://status.mojang.com/check?service=sessionserver.mojang.com`

This is just a suggestion, based on my personal opinion, if you have specific reasons to use your own-made api for it, feel free to close it. 😄 

---

IA Page:  http://duck.co/ia/view/minecraft_status 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @destruc7i0n

**Comment by destruc7i0n** [comment]
I made my own API as I wanted to include the status of realms which is not available from this endpoint. I use one of [these](http://wiki.vg/Realms_API) endpoints, see if the endpoint works and then combine that with the data from the official endpoint.

**Comment by alohaas** [comment]
@marcoslater are you interested in trying out @destruc7i0n 's suggestion and making a PR? If not, we can see if other members of the community would like to take this on.

**Comment by destruc7i0n** [comment]
@alohaas I'm actually working on updating my version to be much faster and reliable, as my old version used some pretty outdated code. It would be at the same endpoint as well.

**Comment by alohaas** [comment]
Woohoo 🐎

**Comment by edgesince84** [comment]
@destruc7i0n I wanted to see if you still planned on finishing this up - we really appreciate your contribution and want to see this go live. We're closing up old PRs in the next week, so let me know if I should leave this open for you!

If you'd rather work on something new, we'd like to invite you to our [new forum](https://forum.duckduckhack.com/) to preview how we're improving programming-related searches. There are a lot of important tasks up for grabs that we'd like your help with, so feel free to and [jump in](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53).

**Comment by destruc7i0n** [comment]
Sorry for the extremely late reply, but I have just pushed the new version of the checker. It should already be up in action.

Feel free to close this issue.
