### ISSUE TITLE
Playing cards: Triggers on Irellevant Queries -- Validation Regex Needs Improvent

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2788]
The query validation regex only requires there to be a number in the query, meaning any query that starts or ends with "deal" or "draw" and contains a number will trigger this Instant Answer:

Looking at the autocomplete, all the queries listed trigger and show a result and none of them are relevant. The regex needs to be improved to validate the whole query contains the words we expect, and nothing we don't.

![deal_4_at_duckduckgo](https://cloud.githubusercontent.com/assets/873785/15859686/27792938-2c94-11e6-80b8-73a52cdf9e1e.png)

Anchoring the regex would be a good start. We should probably require `cards` to be in the query so `deal 4` doesn't show a result.   

---

IA Page:  http://duck.co/ia/view/playing_cards 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @therealkbhat

**Comment by Hestben** [comment]
Wasn't this issue resolved when the issue #2790 was merged?

Is the any more work to be done here?

**Comment by therealkbhat** [comment]
Yes, it was.
I think we can safely close this one.
