### ISSUE TITLE
SoundCloud: Unable to play audio

### ISSUE THREAD

**Issue by rasikapohankar** [duckduckgo/zeroclickinfo-spice#2797]
On trying to play a song, it is showing a 403 Forbidden response from nginx. For example, https://duckduckgo.com/audio_redirect/https://cf-media.sndcdn.com/dddC2JyLfHDG.128.mp3. I wasn't sure if it is happening only for me but tried it for a number of songs since yesterday, its returning the same response.
@moollaza @GuiltyDolphin @tagawa 

------
IA Page:  http://duck.co/ia/view/sound_cloud 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jdan

**Comment by edgesince84** [comment]
I'm getting "stream unavailable" for everything I try, too.

**Comment by rasikapohankar** [comment]
Hey @edgesince84, yes its saying 'stream unavailable' and the Network tab in the developer console shows 403 Forbidden from nginx, there are 3 requests every time we press play button, two have 301, 302 response codes and the one with `https://duckduckgo.com/audio_redirect/...` is giving a 403 response code. I could not figure out anything more for now. How do I confirm if it is a problem in communication with the API or something else?

**Comment by edgesince84** [comment]
@rasikapohankar I'm bringing in some more eyes from our internal staff to look at this one.  thank you very much!

**Comment by moollaza** [comment]
We've had problems with their API before, usually it's on their end. @jagtalon has fixed it previously and knows the most. @jagtalon can you please investigate? 

I'm going to take this IA offline for now. It will still be available on Beta.

**Comment by rasikapohankar** [comment]
@edgesince84 That'd be great, thanks! I know a lot people who will be happy once this IA starts working again, including me! :smile: 
@moollaza Ooh, I forgot to check if it's working on beta :anguished:

**Comment by moollaza** [comment]
Looks like this was the result of an Internal change. Ops team will be fixing shortly.

**Comment by moollaza** [comment]
All fixed 👍  -- Going to reenable the IA in the Metadata

**Comment by edgesince84** [comment]
thanks again @rasikapohankar!

**Comment by rasikapohankar** [comment]
Thank you for fixing it so quickly! :heart: :tada:
