### ISSUE TITLE
Random Words: show definition of result

### ISSUE THREAD

**Issue by NaveenKarippai** [duckduckgo/zeroclickinfo-spice#2807]
Could we also show [definition](https://wordnik.com/words/brangle) of (random word) result to the user? This might help the end-user to use `Random Words` IA for vocabulary improvement.

------
IA Page:  http://duck.co/ia/view/rand_word 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @hunterlang

**Comment by VeerpalBrar** [comment]
I think this sounds like a good idea. I'd like to give this a shot if that's possible.
