### ISSUE TITLE
Bitcoin Addresses, Blocks: Reduce caching time

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#2809]
It's [been pointed out](https://www.reddit.com/r/duckduckgo/comments/4nd0c7/spice_answers_outdated/) that information shown by the IA is sometimes out of date, probably because of caching, currently set at one day. The [Biteasy API limits](https://support.biteasy.com/kb/rest-api/rate-limiting) seem quite generous so could we try reducing it. Something like one hour perhaps?

---

IA Page:  http://duck.co/ia/view/bitcoin 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jmg

**Comment by lernae** [comment]
I was looking into this and I noticed that this IA's API responses are never cached based on below setting in lib/DDG/Spice/Bitcoin.pm:
spice proxy_cache_valid => "418 1d";
Does this IA continue to sometimes display out of date info?

**Comment by moollaza** [comment]
IA is no longer online.
