### ISSUE TITLE
METAR Information: Issue with API

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#2813]
This Instant Answer has been taken offline due to API issues.

Accessing http://avwx.rest/api/metar.php?station=ICAO&format=JSON&options=info,translate or http://avwx.rest/api/metar.php?station=KJFK&format=JSON&options=info,translate seems to time out.

@santigl would you be interested in contacting http://avwx.rest/ to see what the problem is?

Thank you!

**Comment by santigl** [comment]
Sure, I'm on it. 

It seems like the website is loading slow and the API isn't responding, so its definitely on that end.

**Comment by santigl** [comment]
I exchanged emails with Michael, the API maintainer, and he told me that he had noticed the timeouts and scaled out the number of instances.

Making a request just now seems a bit slow to load, though it may be my own connection. Would it be possible to bring it back up to test what happens under traffic?

**Comment by jagtalon** [comment]
@santigl Thank you! We'll re-enable the Spice.

**Comment by jagtalon** [comment]
Hey, @santigl! Would you be able to ask them if we can reduce the time to less then 5 seconds? It's a bit too slow and Nginx times out as a result. :)

**Comment by santigl** [comment]
I'll write back, @jagtalon. Meanwhile, I just checked, and I'm seeing up to 11 seconds. :(

**Comment by santigl** [comment]
Good news, Michael told me he has made some changes that should mitigate the delays. :D

From my end I'm now seeing 2 seconds on average to complete requests. Shall we give it another try?

**Comment by moollaza** [comment]
@santigl Thanks for the update! I've asked the team to re-enable this IA

**Comment by tagawa** [comment]
Looks like this is back working again: https://duckduckgo.com/?q=metar%20KLAX&ia=weather
Thanks @santigl!
