### ISSUE TITLE
Drinks: Title link doesn't go anywhere

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#2814]
We need to set the `url` attribute so that clicking on the title would go to TheCocktailDB.

<img width="572" alt="screen shot 2016-06-13 at 12 37 47 pm" src="https://cloud.githubusercontent.com/assets/81969/16015496/ecb9c31e-3163-11e6-9772-0e735ed07a43.png">

<img width="738" alt="screen shot 2016-06-13 at 12 40 01 pm" src="https://cloud.githubusercontent.com/assets/81969/16015506/f8e4bbda-3163-11e6-943b-f5df33d75edf.png">

---
IA Page: https://duck.co/ia/view/drinks
Maintainer: @mutilator

**Comment by sahildua2305** [comment]
@jagtalon I have created a PR to fix this. Please check, if I am missing anything related to the issue.
