### ISSUE TITLE
Code Search: Change API Endpoint

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#2818]
The Spice isn't working because the API endpoint has changed to:

`https://searchcode.com/api/jsonp_search_IV/?q=php&callback=myCallback`

from

`https://searchcode.com/api/jsonp_codesearch_I/?q=php&callback=myCallback`

Please double check if the data has changed, i.e., if the Spice is showing up properly or not as well!

Thanks!

---
Maintainer: @boyter
IA Page: https://duck.co/ia/view/code_search

**Comment by gaulrobe** [comment]
@jagtalon @boyter Don't the `jsonp_search_IV` endpoint and the `jsonp_codesearch_I ` endpoint have two different use cases? Per https://searchcode.com/api/, using the `jsonp_codesearch_I` endpoint is still what we want to use in this IA, right?

**Comment by sahildua2305** [comment]
@jagtalon @boyter I am working on updating this here - #2810 
And @gaulrobe you're right. I checked both the endpoints while working on this.

**Comment by boyter** [comment]
That's correct. Originally there were two endpoints. The first doing
documentation search (I released that code as fathead so it's probably not
required anymore) and the second doing code search.

I'll try and scale up the endpoint soon as well towels with response times
on your end.

**Comment by sahildua2305** [comment]
Thanks @boyter  :smile:

**Comment by jagtalon** [comment]
Thanks @boyter! That's my bad I misunderstood. :)

**Comment by jagtalon** [comment]
Thanks @gaulrobe @sahildua2305!
