### ISSUE TITLE
Last.fm Artist: Query "IT band" is triggering the IA

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#2819]
Last.fm Artist triggers on the word "band" which can surface unrelated results such as "IT band" (if you notice the links at the bottom it's all related to one's anatomy). Find a way to reject these types of irrelevant results from coming up. It may be the case where we'd have to implement this on our end by using the result links as triggers, i.e., if last.fm comes up as one of the links, this IA should show up)

<img width="838" alt="screen shot 2016-06-15 at 12 22 51 am" src="https://cloud.githubusercontent.com/assets/81969/16067971/ab97d510-328f-11e6-90e9-668af956d85b.png">

---

Maintainer: @jagtalon
IA Page: https://duck.co/ia/view/lastfm_artist

**Comment by moollaza** [comment]
IA is no longer online.
