### ISSUE TITLE
Bible: Add feature for random verse

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#2820]
The API currently being used supports random bible verses using this URL:
http://labs.bible.org/api/?passage=random&type=json

It shouldn't be too difficult to add this so that it's triggered by the search queries `bible verse` or `random bible verse`.

(Idea by @pnpninja and @gaulrobe)

---

IA Page:  http://duck.co/ia/view/bible 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @hunterlang

**Comment by pnpninja** [comment]
@MAMAMIA9 - lets start

**Comment by edgesince84** [comment]
Welcome, @MAMAMIA9!  thanks for taking this on @pnpninja 🏆

**Comment by pnpninja** [comment]
@edgesince84 no problemo

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
