### ISSUE TITLE
ExpandURL: Update to use Built-in Template

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2821]
This IA is using the `base` template with handlebars to display a clickable URL.

We should be able to use the `info` template with a `title` and `url` to recreate this functionality.

As well we can provide a subtitle, like we usually do, to give some context. E.g. "Expanded URL: https://bit.ly/a"

------
IA Page:  http://duck.co/ia/view/expand_url 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @adman

**Comment by Adman** [comment]
@moollaza What do we want to put into title?

**Comment by sahildua2305** [comment]
@Adman May be "Expand short URL"? (just a thought)

Also @moollaza it doesn't work for me at - https://duckduckgo.com/?q=http%3A%2F%2Fbit.ly%2Fa&ia=answer

**Comment by moollaza** [comment]
@Adman the `title` should be the expanded url. Setting the `url` property to the same value will make the title a clickable link.

The subtitle should indicate that the result is the expanded form of the input url

**Comment by moollaza** [comment]
> Also @moollaza it doesn't work for me at - https://duckduckgo.com/?q=http%3A%2F%2Fbit.ly%2Fa&ia=answer

It's not yet live again in Production. Should be by tomorrow though. It's live on Beta: https://beta.duckduckgo.com/?q=expand+http%3A%2F%2Fbit.ly%2Fa&ia=answer

**Comment by sahildua2305** [comment]
Doesn't work for me on beta either:
https://beta.duckduckgo.com/?q=expand+http%3A%2F%2Fbit.ly%2Fa&ia=answer

**Comment by Adman** [comment]
@moollaza I cannot find `title` and `url` properties in documentation.

**Comment by Adman** [comment]
@moollaza could you please clarify a bit where to put those properties ?

**Comment by sahildua2305** [comment]
@Adman You can try something like this
https://github.com/duckduckgo/zeroclickinfo-spice/blob/4c586975b008ad2d71afcdd45d314144e03b6f87/share/spice/emojipedia/emojipedia.js#L17

**Comment by Adman** [comment]
@sahildua2305 Feel free to do so.

**Comment by sahildua2305** [comment]
@Adman Please review #2829 :smile:
