### ISSUE TITLE
Timer: Recognise 'hour timer' etc as a request for a 1 hour timer

### ISSUE THREAD

**Issue by Petethegoat** [duckduckgo/zeroclickinfo-spice#2824]
When the singular form of a unit of time is searched, that should be recognised as a timer.

For example:
`hour timer` -> `1 hour timer`
`minute timer` -> `1 minute timer`

---

IA Page:  http://duck.co/ia/view/timer 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattr555

**Comment by mattr555** [comment]
@Petethegoat Thanks for the suggestion! I'm going to put this on hold until duckduckgo/zeroclickinfo-goodies#2253 is merged. cc @GuiltyDolphin

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
