### ISSUE TITLE
Forecast: Add support for the hourly forecast

### ISSUE THREAD

**Issue by tsimonq2** [duckduckgo/zeroclickinfo-spice#2827]
It would be very beneficial to support viewing of an hourly forecast instead of the generic weather IA. I typed [hourly forecast green bay wi](https://duckduckgo.com/?q=hourly+forecast+green+bay+wi) (the city that I live in) and I got a generic weather IA.

---

IA Page:  http://duck.co/ia/view/forecast 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @himanshu0113

**Comment by himanshu0113** [comment]
Thank you @tsimonq2 for bringing out this issue. But I am not sure if we can work on it. Maybe we can add an option there for someone who needs hourly forecast.
@moollaza can we do anything for it?

**Comment by moollaza** [comment]
@himanshu0113 I'm totally surprised, but looking at the API response actually have `hourly` and even `minutely` data! 

We could totally improve this IA to handle those kinds of queries!

@tsimonq2 thanks a lot for the suggestion 👍

**Comment by moollaza** [comment]
The fix may be as simple as replacing the title to indicate the hour, instead of the day, and of course using the hourly data in the API response.

**Comment by himanshu0113** [comment]
@moollaza I don't know to implement these changes. Can you or anyone help me?

**Comment by moollaza** [comment]
@himanshu0113 at a high level, you'll need to check if the query contains "hourly" and if so, use the hourly data, instead of the weekly data. 

@duckduckgo/duckduckhack-contributors would anyone be interested in working on these changes with @himanshu0113? This should only require changes to the JavaScript and possibly the template.

**Comment by sahildua2305** [comment]
I can take this up. @moollaza 

This is indeed a great suggestion. Thanks @tsimonq2

**Comment by alohaas** [comment]
Awesome @sahildua2305! We'll keep an eye out for your pull request.

**Comment by morinx** [comment]
+1 for hourly forecast as the default option. I don't think many people choose 7 day forecast as a zero-click feature over hourly.

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
