### ISSUE TITLE
IsItUp: Simplify design, remove custom CSS

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2831]
The design on this IA no longer matches the look and feel of our other Instant Answers.

We should switch this to the text template, and use a `title_content` subtemplate to create the title and subtitle.

The result should look like this:
![is_duckduckgo_up__at_duckduckgo](https://cloud.githubusercontent.com/assets/873785/16234690/2418142c-37a0-11e6-9569-f882ea8f4e72.png)

`is_it_up.css` should be **removed**

The template should be renamed to `title_content.handlebars`. The content should be:

```handlebars
{{#if_value status_code 1}}
    <h3 class="c-base__title text--primary">
		<a href='http://{{this.domain}}'>{{this.domain}}</a> seems up
	</h3>
    <h4 class="c-base__sub">
		It took us {{response_time}} seconds to get a <a href='/?q=http+{{response_code}}'>{{response_code}}</a> response from <a href='http://{{response_ip}}'>{{response_ip}}</a>
	</h4>
{{else}}
    <h3 class="c-base__title text--primary">
		<a href='http://{{this.domain}}'>{{this.domain}}</a> seems down
	</h3>
    <h4 class="c-base__sub"> We did not get a response from it</h4>
{{/if_value}}
```

The JS should be:

```js
Spice.add({
    id: 'is_it_up',
    name: 'Answer',
    data: api_result,
    meta: {
        sourceUrl: 'http://isitup.org/' + api_result['domain'],
        sourceName: 'Is it up?'
    },
    templates: {
        group: 'text',
        options: {
            title_content: Spice.is_it_up.title_content
        }
    }
});
```

------
IA Page:  http://duck.co/ia/view/is_it_up 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mrshu

**Comment by sahildua2305** [comment]
I will take this up.

**Comment by sahildua2305** [comment]
@moollaza Why not use `title` and `subtitle` only? How about not using `handlebars` at all?

`title` can be either - 
```html
<a href='http://{{this.domain}}'>{{this.domain}}</a> seems up.
```
or
```html
<a href='http://{{this.domain}}'>{{this.domain}}</a> seems down.
```
depending upon the website status.

And similarly, the text that you suggested for `h4` tag can go in `subtitle`.

Let me know what you think about this.
