### ISSUE TITLE
Pokemon: Reign in triggering; Check query against list of Pokemon Names

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2833]
This IA is over triggering a **_lot_**, however thankfully it is not returning irrelevant result.

We should still avoid making unnecessary API calls and we have a simple way to handle it in this case.

We should copy the list of accepted Pokemon (available [here](https://github.com/PokeAPI/pokeapi/blob/master/data/v2/csv/pokemon.csv)) and use it to lookup the candidate Pokemon name. If it matches we should move forward with the API call. If not we should `return`.

------
IA Page:  http://duck.co/ia/view/pokemon_data 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @AkA84

**Comment by sahildua2305** [comment]
So basically including the list of accepted Pokemon in a YAML file and doing a lookup for the candidate Pokemon name should suffice.
