### ISSUE TITLE
ISBN: Triggering should ignore 10-Digit phone numbers

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2834]
This IA currently triggers on queries that match a standard North American 10-digit phone number patter:

i.e. `###-###-####` -- We should not trigger if the query matches that pattern!

Also it looks like there are some ISBN libraries on CPAN that could be used to simplify the code, e.g. `ISBN::Test`.  

---

IA Page:  http://duck.co/ia/view/isbn 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nishanths

**Comment by mintsoft** [comment]
@moollaza ISBN10 also has a check digit; if it's not valid it also shouldn't show!
