### ISSUE TITLE
YachtSpecs: Move skip words into Perl package

### ISSUE THREAD

**Issue by sahildua2305** [duckduckgo/zeroclickinfo-spice#2836]
As we can see that there are only [5 skip words](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/yacht_specs/skipwords.txt), shouldn't we move these to the Perl module itself?

May be they are in a separate file to make sure it's easy to include more words?
<hr>
IA Page: https://duck.co/ia/view/yacht_specs
Maintainer: @elephantRunAway

**Comment by moollaza** [comment]
> May be they are in a separate file to make sure it's easy to include more words?

@sahildua2305 I believe this is the reason. I think we can leave as-is?

**Comment by sahildua2305** [comment]
Sure, let's leave it then.
