### ISSUE TITLE
IsItUp: Support 'is it down' forms

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-spice#2837]
I can never remember if its 'up' or 'down', so being able to type `is it down ...` would be mighty handy.

See, for example: https://duckduckgo.com/?q=isitdown+duckduckgo.com&ia=web

---

IA Page:  http://duck.co/ia/view/is_it_up 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @rasikapohankar

**Comment by edgesince84** [comment]
I just tried "is spotify down" about an hour ago 😢

**Comment by moollaza** [comment]
@edgesince84 that search should have surfaced a result...

https://duckduckgo.com/?q=is+spotify+down&ia=answer

**Comment by sahildua2305** [comment]
The regex that's being used currently looks for this format:
`is <domain> (up|online|down|working|status)`

We will have to edit it to make sure it captures following as well:
`is (it)? (up|down|working|online) <domain`

Adding an entirely new regex using `|` is one idea, which is not something we would be looking for, right?

**Comment by rasikapohankar** [comment]
@edgesince84 Yes, `is spotify down` does give an answer. 
@moollaza @GuiltyDolphin @edgesince84 I have fixed some few issues with others as maintainers, but its my first time as a maintainer :sweat_smile: What should I be doing next?

**Comment by rasikapohankar** [comment]
To do this, we could use `triggers end => "up", "down", "working" ...` and `triggers start => "isitup", "isitdown" ...` and use the regex inside the handle function to check the domain, as @moollaza had suggested before.

**Comment by moollaza** [comment]
> What should I be doing next?

@rasikapohankar if you like the idea (which I believe you do!) you can say so and you're welcome to fix it yourself or leave it to the community. When the PR comes we'll ask for your input there as well.
