### ISSUE TITLE
Elm Spice

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-spice#2840]
I think it's maybe time to implement a spice for the Elm programming language since it is becoming very popular. It seems to have package manager, but I can't find the endpoint. Is there one @elm-lang/packages, and if so, can we use it?

If not, we can implement this as a FatHead granted their terms and conditions are fine.

cc / @evancz

**Comment by tagawa** [comment]
@pjhampton Good idea. I agree, there doesn't seem to be an API for the packages but the doc's package pages seem to have a nice set pattern. Should be OK to make as a fathead IMO.

**Comment by gaulrobe** [comment]
@pjhampton @tagawa saw this call being made: http://package.elm-lang.org/all-packages

Might be worth reaching out to see if we could use it? :)

**Comment by pjhampton** [comment]
Good find @gaulrobe! Hopefully someone from the elm packages team will get back to us. I'm sure you'll agree @tagawa that a Spice is more desirable that a Fathead in this case (due to maintainability, etc).

**Comment by tagawa** [comment]
Oh yes, @gaulrobe, nice find! Could do with a bit more data - proper description, example, etc. - but I'll try to contact them to see if we can use it.

**Comment by pjhampton** [comment]
Thanks Daniel 💜  💛  ❤️

**Comment by tagawa** [comment]
Good news! As long as we cache it, for example once a day, we're fine to use the JSON endpoint @gaulrobe posted above: https://twitter.com/elmlang/status/746337553222098944

We should let them know if/when we get something on beta to make sure they're happy.

**Comment by pjhampton** [comment]
I'll take this forward over the weekend @tagawa

**Comment by tagawa** [comment]
Great, thank you @pjhampton. If you need help (yeah, right!) or want to share the load, just shout.

**Comment by pjhampton** [comment]
Closing this in favour for https://github.com/duckduckgo/zeroclickinfo-spice/issues/3101
