### ISSUE TITLE
Timer: count up

### ISSUE THREAD

**Issue by jrwren** [duckduckgo/zeroclickinfo-spice#2842]
---

IA Page:  http://duck.co/ia/view/timer 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattr555

**Comment by edgesince84** [comment]
To elaborate - you'd like a counter that starts at zero and counts up, not just a countdown option? @jrwren

**Comment by jrwren** [comment]
Yes, that is right.

I found it later, its !stopwatch.

It would be nice if there were a link to stopwatch from timer ;]
