### ISSUE TITLE
IA testing: combine fathead and longtail into api_result

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/zeroclickinfo-spice#2843]
To have fathead and longtail PRs show up we need to also combine them into the `api_result`.
https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/experimentalia/experimentalia.js#L9

------
IA Page:  http://duck.co/ia/view/experimentalia 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @vikashvverma

**Comment by vikashvverma** [comment]
@jdorweiler I will have a look in few days

**Comment by vikashvverma** [comment]
@jdorweiler I don't see longtail available in `api_result`
