### ISSUE TITLE
Currency Conversion: not converting, not displaying conversion result

### ISSUE THREAD

**Issue by dminca** [duckduckgo/zeroclickinfo-spice#2844]
The Currency Conversion IA **has a defect**, I did a conversion and it didn't work (ie. didn't convert or display anything). See photo below   

![selection_005](https://cloud.githubusercontent.com/assets/5355219/16330328/1182c20a-39f1-11e6-89fb-aaf5e14e36ef.png)
![selection_006](https://cloud.githubusercontent.com/assets/5355219/16330444/d951434c-39f1-11e6-90ce-944ca7ecad2f.png)

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by marcoslater** [comment]
Can also confirm, it does not appear to be working currently. Possibly due to the issues with xe.com after the UK EU referendum votes were announced?

**Comment by dminca** [comment]
First issue caused by the **BRexit** lol

**Comment by moollaza** [comment]
XE.had some downtime earlier so we had to take the Instant Answer offline. Now that it's working again I'll setup the IA to go live again 👍

**Comment by dminca** [comment]
Thanks @moollaza

**Comment by edgesince84** [comment]
Brexit! :shaking fist at sky:

**Comment by dminca** [comment]
Tested on Live, **defect is fixed** :white_check_mark:
