### ISSUE TITLE
Kwixer: Remove Instant Answer Code

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2847]
This API is scheduled to go offline and the Instant Answer has now been replaced.

The code needs to be removed from the repo now.

------
IA Page:  http://duck.co/ia/view/kwixer 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @rodrigue-h

**Comment by sahildua2305** [comment]
@vishivish18 Here!

This is a really low-hanging fruit that you were asking for. Just figure out the file structure of a spice and remove this IA. :smile:

**Comment by sahildua2305** [comment]
Due to lack of response, I'll get this done and submit a PR in a few hours. :)
