### ISSUE TITLE
Reddit Search: option to filter results - "top", "new", "relevance" reddit results

### ISSUE THREAD

**Issue by NaveenKarippai** [duckduckgo/zeroclickinfo-spice#2850]
Currently, IA shows results which are sorted according to "relevancy" by default (if I understood it correct). It would be awesome if we could make an option on IA results to sort according to "top", "new" reddit results.

---

IA Page:  http://duck.co/ia/view/reddit_search 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattr555

**Comment by moollaza** [comment]
IA is no longer online.
