### ISSUE TITLE
Amazon: localised amazon results

### ISSUE THREAD

**Issue by NaveenKarippai** [duckduckgo/zeroclickinfo-spice#2851]
Currently, the results are returned from "amazon.com" (by default). It would be **useful** if we could return **localized results**. For example, the user located in Germany should see results from "amazon.de" instead of "amazon.com".

---

IA Page:  http://duck.co/ia/view/products 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @bsstoner

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
