### ISSUE TITLE
Localized Currency Names - Currency IA

### ISSUE THREAD

**Issue by stefanopini** [duckduckgo/zeroclickinfo-spice#2858]
Consider to include international currency names into the currencyNames.txt list so it'll be possible to covert values writing the search query in a lot of different languages.
The most useful currency names dataset i found is this and covers European languages:
http://publications.europa.eu/mdr/resource/authority/currency/xml/currencies.xml
(From the EU Open Data Portal: http://data.europa.eu/euodp/en/data/dataset/currency)

------ 

IA Page: https://duck.co/ia/view/currency

**Comment by alohaas** [comment]
@stefano-93 which IA are you referring to? we have a few:
https://duck.co/ia/view/currency_cheat_sheet
https://duck.co/ia/view/currency
https://duck.co/ia/view/currency_in

**Comment by stefano-93** [comment]
I'm referring to "Currency Conversion": https://duck.co/ia/view/currency
But it should be applied to "Currency Cheat Sheet" and to "World Currencies" to show a localized name too.

**Comment by alohaas** [comment]
Hey @MrChrisW if you're available, your feedback would be appreciated. If not, we can bring in others.

**Comment by GuiltyDolphin** [comment]
Related are:

https://github.com/duckduckgo/zeroclickinfo-spice/issues/2735
https://github.com/duckduckgo/zeroclickinfo-spice/pull/2805

**Comment by MrChrisW** [comment]
Sounds 🔉 like a good idea to me, however I have no capacity 🔋 to make this change right now 👍

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
