### ISSUE TITLE
AlternativeTo: Listen for license type in query

### ISSUE THREAD

**Issue by Troupal** [duckduckgo/zeroclickinfo-spice#2860]
Hello dear **devs**! 

I think that's will be a good and great idea that we can make a search like that:

> only open source alternative to google translate

And the DuckDuckHack to make result for only open source alternative.

So think you for this wonderful DuckDuckHack!!!

---

PS: Sorry for my English, I'm French and I don't speak very well English… ^^'

---

IA Page:  http://duck.co/ia/view/alternative_to 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @vikashvverma

**Comment by vikashvverma** [comment]
@Troupal I don't think many people will type such a long phrase. 
The IA API does give us the license so we can filter out based on license.

@duckduckgo/community-leaders 
@duckduckgo/duckduckhack-contributors  any input regarding effectiveness of this trigger

**Comment by Gaurav2728** [comment]
@vikashvverma new users often search using long keywords, they have not familar with how search engine work.  @Troupal request make sence.

**Comment by tagawa** [comment]
Bonjour @Troupal! Merci beaucoup pour la suggestion.
We can probably listen for keywords such as "open source", "commercial" or "freemium" in the query using regex, so it wouldn't matter if the query was a long or short phrase. If the API supports this, as @vikashvverma says, then your suggestion seems possible - and a good idea!

**Comment by sahildua2305** [comment]
Great idea!

I can take it up, if @vikashvverma is not in mood of working on this :stuck_out_tongue_winking_eye:

**Comment by tagawa** [comment]
@sahildua2305 Thanks for the offer! I think @vikashvverma is pretty busy at the moment so I've assigned it to you to have a go.

**Comment by sahildua2305** [comment]
@vikashvverma I just checked the functionality of the IA in a bit detail and looks like it already listens for the license type in query and filters out the results based on that license type.

For example - [this](https://duckduckgo.com/?q=open+source+alternative+to+notepad&ia=software) generates results only for open source alternatives.

Not sure what needs to be done regarding this issue :confused: :question:

**Comment by Mylainos** [comment]
Maybe put the license at the bottom of the items/cards ?

**Comment by sahildua2305** [comment]
Good idea. I think it will make sense to put the license only when the search query is generic. Otherwise it would be obvious that the results must be according to the search query.

**Comment by Mylainos** [comment]
I'm not sure. I prefer if it's explicit.
(And it might be a good idea to put the number of likes, but that's for an other issue I guess)

**Comment by philipmiesbauer** [comment]
I think it is better to be explicit as well. Otherwise people might not
understand why it is shown sometimes and other times not.

**Comment by sahildua2305** [comment]
Great! I will create a PR soon for mentioning the license type explicitly in the results.

**Comment by sahildua2305** [comment]
@vikashvverma the issue states that the IA should listen to license type in the query. Was that already handled in some PR? I think this issue needs to be closed and it's sort of misleading.
Your input requested.

**Comment by vikashvverma** [comment]
@sahildua2305 @Troupal Currently this IA is showing result based on your query. It shows only open source if you add `free` or `open source` in search query. 
<img width="1439" alt="screen shot 2016-07-20 at 9 05 59 am" src="https://cloud.githubusercontent.com/assets/915277/16974357/789993de-4e59-11e6-9fce-c07cbf890015.png">

<img width="1440" alt="screen shot 2016-07-20 at 9 05 49 am" src="https://cloud.githubusercontent.com/assets/915277/16974366/8d296450-4e59-11e6-83d3-492b07d505b0.png">

However it needs some regex to handle query like `only open source alternative to google translate`

@sahildua2305 You can try adding regex to handle this.

Also there is one more issue https://github.com/duckduckgo/zeroclickinfo-spice/issues/2631 open with this IA related to triggers

**Comment by Troupal** [comment]
**YEAH!!! That's perfect!!!**
The query ***open source alternative to google translate*** work perfectly!
Very nice job'! And thank you all for your work ans answers.

**Comment by moollaza** [comment]
IA is no longer online.

**Comment by Troupal** [comment]
@moollaza 
Yeah, it's too sad…

**Comment by moollaza** [comment]
I checked that this IA still works correctly, and I've re-enabled it. Should be online shortly.

**Comment by Troupal** [comment]
@moollaza Thank's ! It's perfect.
