### ISSUE TITLE
Places: show working time range

### ISSUE THREAD

**Issue by NaveenKarippai** [duckduckgo/zeroclickinfo-spice#2867]
Could we also show opening/closing time on queries like "McDonalds nearby".    

---

IA Page:  http://duck.co/ia/view/maps_places 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nilnilnil

**Comment by nilnilnil** [comment]
Yes, this is a feature we plan on adding!

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
