### ISSUE TITLE
Add Ships and Sold by info to amazon info

### ISSUE THREAD

**Issue by drewschaeffer** [duckduckgo/zeroclickinfo-spice#2868]
An important piece of information when considering a product on Amazon is who is selling and shipping the item. For example, Amazon ships and sells many items and those tend to inspire more confidence (for those that are not Prime).

For example, 

https://www.amazon.com/dp/0545302021
Ships and Sold by PBShop US.

https://www.amazon.com/Scholastic-Teachers-Friend-Counting-TF7102/dp/0545301939
Ships and Sold by Amazon.com

---

IA Page:  http://duck.co/ia/view/products 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @bsstoner

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
