### ISSUE TITLE
Time: Overtriggering on 'month'

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-spice#2870]
If I use the query ["month"](https://duckduckgo.com/?q=month&ia=time), it triggers this Instant Answer. Is this expected behavior? I feel it is overtriggering somewhat.

["week"](https://duckduckgo.com/?q=week&ia=answer) triggers an entirely separate Instant Answer (perhaps one that could handle the query of "month"?).

---

IA Page:  http://duck.co/ia/view/time 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by edgesince84** [comment]
"month" does tell you the month, but not the same way "week" breaks it down ie "We are in the __th week of the year."

**Comment by MrChrisW** [comment]
Related https://github.com/duckduckgo/zeroclickinfo-spice/issues/2946

________

This was added in https://github.com/duckduckgo/zeroclickinfo-spice/pull/2524 - Looking at the tests it may have only been intended to trigger on `what\'s the month in <city>` not just `the month`. @Sayanc93 can you look into this?

**Comment by mrshu** [comment]
As far as I can see, `month` no longer triggers the `Time` Spice and this issue can therefore be closed.

**Comment by moollaza** [comment]
Priority has been given to the conversions Instant Answer now
