### ISSUE TITLE
Instant Answers on Beta: Display scrolls back to the first tile under the time frame

### ISSUE THREAD

**Issue by rasikapohankar** [duckduckgo/zeroclickinfo-spice#2872]
If we click on an IA tile, the details are of that IA are shown and the display scrolls back to the first tile for that time frame. For example, if I click 'Political Polls' which is the last IA under 'Last 30 Days' currently, the display scrolls back to 'Ace Editor Cheat Sheet'. Was this intended?
People to notify: @jdorweiler 

---

IA Page:  http://duck.co/ia/view/experimentalia 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @vikashvverma

**Comment by edgesince84** [comment]
That is weird, and I can't think of a reason why it'd be intentional.

**Comment by jdorweiler** [comment]
Nope not intentional. I think this might be a bug with the template.

**Comment by rasikapohankar** [comment]
@edgesince84 @jdorweiler Yes, it seems to happen for this too: https://duckduckgo.com/?q=apple&ia=meanings, if we come back to the first results page after clicking on a tile. I found this example in the documentation for `minTopicsForMenu`. I tried to look for the cause but didn't find anything useful. Can you tell me where should I look for the javascript that gets executed when we click on the tile?

**Comment by jdorweiler** [comment]
@rasikapohankar what browser and can you list the steps you took? I can't reproduce it.

**Comment by rasikapohankar** [comment]
@jdorweiler I was using Chrome, for https://duckduckgo.com/?q=apple&ia=meanings,
1. In the topics in `Meanings`, I went to `See Also` and clicked on the last tile under it.
2. It goes to a new page https://duckduckgo.com/d/Big_Apple?ia=meanings,
3. Then clicked the back button of the browser, the view scrolls. In this case the page itself changes when we click though, but I didn't find other examples.

**Comment by jdorweiler** [comment]
@rasikapohankar thanks, I was able to reproduce that. I'm not sure if the code for the meanings template is opensource or not. @andrey-p do you know?

**Comment by andrey-p** [comment]
@jdorweiler Yeah, that would be due to internal code. I guess we never noticed this problem on the Meanings IA since it redirects to a different page. Could you make an internal task for it?
