### ISSUE TITLE
Tides: Problem Triggering

### ISSUE THREAD

**Issue by sbdchd** [duckduckgo/zeroclickinfo-spice#2873]
As of roughly a few weeks or so, I have not been able to get the tides instant answer to trigger.

An example query:
https://duckduckgo.com/?q=tides+02210

------
IA Page:  http://duck.co/ia/view/tides 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattr555

**Comment by sahildua2305** [comment]
It works on [Beta](https://beta.duckduckgo.com/?q=tides+02210&ia=tides&iax=1).

The changes aren't live yet, @mattr555 ?

**Comment by sbdchd** [comment]
Seems to be working now. Thanks.
