### ISSUE TITLE
MetaCPAN: Add "mcpan" and "perl" as triggerwords

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2874]
@jbarrett I tried a search for "mcpan Color::Library" and noticed it didn't trigger the IA. Figured we should add "mcpan" and "perl" as trigger words?   

------
IA Page:  http://duck.co/ia/view/meta_cpan

**Comment by sahildua2305** [comment]
@moollaza Done ;)

**Comment by jbarrett** [comment]
@moollaza I questioned the value of adding just "perl" in #2877 - want to chime in over there? Thanks!
