### ISSUE TITLE
MetaCPAN: Poor relevancy on additional query words

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-spice#2877]
See: ["cpan Text::Trim"](https://beta.duckduckgo.com/?q=cpan+Text%3A%3ATrim&ia=software)

![screenshot-2016-07-04-22 21 02_743_289](https://cloud.githubusercontent.com/assets/8598426/16570049/112368bc-4236-11e6-857b-fdb8579120d1.png)

Vs. ["cpan Text::Trim install"](https://beta.duckduckgo.com/?q=cpan+Text%3A%3ATrim+install&ia=software)

![screenshot-2016-07-04-22 21 16_740_289](https://cloud.githubusercontent.com/assets/8598426/16570053/2be821ba-4236-11e6-8b02-ca9b597f7428.png)

cc @jbarrett 

------
IA Page:  http://duck.co/ia/view/meta_cpan

**Comment by sahildua2305** [comment]
@GuiltyDolphin How about removing `install` and more similar words from the query if present, to get the actual module name.

Can we use some regex to deduce only module name from the query?

**Comment by jbarrett** [comment]
I don't think we can filter out words like "install" - Module::Install springs to mind.

You also can't use '::' as a reliable indicator of module name, you miss out on single word modules such as JSON, Dancer, Catalyst... Relying on exact module names was one of the major issues with the previous version of this spice.

**Comment by sahildua2305** [comment]
@jbarrett I meant to filter out words like install if they occur separated by a space in the query. In that case a query for `Module::Install` won't be affected. What do you think?

**Comment by jbarrett** [comment]
The result for ["cpan module install"](https://beta.duckduckgo.com/?q=cpan+module+install&ia=software) isn't amazing, but it would be worse if we lost "install" in this query.

**Comment by sahildua2305** [comment]
Ah! Ok. Then for now I will just go ahead with `"perl module"`, `"perl dist"` and `"perl distribution"` trigger words instead of just `"perl"`. Please check #2874

**Comment by jbarrett** [comment]
Thanks @sahildua2305! I think we should leave this open, as the triggering for this can definitely use work, I'm just not sure what sort of work right now :smile:

**Comment by jbarrett** [comment]
Thinking on this further... After [line 17](https://github.com/duckduckgo/zeroclickinfo-spice/blob/9121959/lib/DDG/Spice/MetaCPAN.pm#L17) we could so something like:

```perl
$_ = ( grep { /::/ } split /\s+/, $_ )[0] || $_;
```

This should pull out the first thing that appears to be a module name (so in the "Text::Trim install" case you'd be left with "Test::Trim"), otherwise it leaves the query remainder untouched. It also means not curating a list of keywords like "install" to filter out.

Not perfect, but better? Thoughts?

**Comment by GuiltyDolphin** [comment]
@jbarrett Looks pretty good.

If I notice any more issues I'll re-open this and we can discuss further.
