### ISSUE TITLE
Ski Resorts: overtriggering

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-spice#2880]
A search for "[o'hare airport map](https://duckduckgo.com/?q=o%27hare+airport+map&ia=skiresort)" triggers the Ski Resort Åre in Sweden.

---

IA Page:  http://duck.co/ia/view/ski_resorts 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @felixpalmer

**Comment by moollaza** [comment]
An easy fix is to ignore any queries containing "airport map". A better fix is to do a relevancy check.

@felixpalmer would you be able to fix this? If not I can ask our community to help out 👍

**Comment by sahildua2305** [comment]
@moollaza Let me know if @felixpalmer isn't in mood of fixing this one. :smile:

**Comment by tagawa** [comment]
Thanks for the offer @sahildua2305. I think Felix is busy at the moment so feel free to have a go!

**Comment by bsstoner** [comment]
Another example of this:
<img width="1157" alt="screen shot 2016-11-15 at 6 35 26 am" src="https://cloud.githubusercontent.com/assets/126358/20304362/c158e4c0-aafd-11e6-94d9-84ec2ccac699.png">

**Comment by nalinbhardwaj** [comment]
Was this fixed or not? It seems to work fine now for me...

**Comment by moollaza** [comment]
IA is no longer online.
