### ISSUE TITLE
Goodreads: IA not showing up

### ISSUE THREAD

**Issue by daylenca** [duckduckgo/zeroclickinfo-spice#2882]
When I performed a search the instant answer did not show up. I was using Microsoft Edge with DDG Beta. URL - https://beta.duckduckgo.com/?q=books+by+melanie+watt. 
![2016-07-05_1935](https://cloud.githubusercontent.com/assets/10361755/16606006/10d51b90-42e9-11e6-92ac-412f7e40e6a0.png)

------
IA Page:  http://duck.co/ia/view/goodreads 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @iammrigank

**Comment by tagawa** [comment]
@daylenca Thanks for reporting. It seems the "goodreads" trigger word was not included in the example queries. I've added it so the beta server links should work now, e.g. https://beta.duckduckgo.com/?q=goodreads+books+by+cory+doctorow&ia=answer
