### ISSUE TITLE
Airlines: no longer triggering

### ISSUE THREAD

**Issue by dreamtimemix** [duckduckgo/zeroclickinfo-spice#2888]
Instant Answers Airlines broken on firefox mobile. No IA is displayed.

------
IA Page:  http://duck.co/ia/view/airlines 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @amoraleda

**Comment by dreamtimemix** [comment]
If i enter aa70 for example no airline ia is displayed on firefox mobile with duckduckgo as default search engine. Android 5.1.1/Firefox Mobile 47.0

**Comment by dreamtimemix** [comment]
![screenshot_2016-07-10-03-53-14](https://cloud.githubusercontent.com/assets/20379996/16712621/939b925e-4652-11e6-9e69-78932169f59e.png)

**Comment by edgesince84** [comment]
Thanks for the details and screenshot @dreamtimemix!

**Comment by dreamtimemix** [comment]
Any news on this issue? This problem has existed for several month now. I only made an issue out of it after seeing no fixes.

**Comment by dreamtimemix** [comment]
I'm in the airline industry and I can't believe this issue hasn't been fixed by now...is there a big underlying problem? The same issue exist on duckduckgo on chrome for mobile. Google had the same problem for a few weeks but has fixed it. Wish there was some feedback as to what the status of this problem is. Thanx!

**Comment by edgesince84** [comment]
hi @dreamtimemix - this IA seems to no longer be triggering at all.  none of the example queries from the IA page are working, either.  @amoraleda can this be addressed?

cc @moollaza a

**Comment by amoraleda** [comment]
Hi @edgesince84, I've been quite busy lately and will be until the end of this month. If nobody solves this by then, I'll tackle it.

**Comment by moollaza** [comment]
@dreamtimemix @edgesince84 this IA is offline right now. There is an error causing it not to show results that needs to be fixed.

There's more info in https://github.com/duckduckgo/zeroclickinfo-spice/issues/2771

Closing this as a duplicate.
