### ISSUE TITLE
How does Twitter Spice work?

### ISSUE THREAD

**Issue by sahildua2305** [duckduckgo/zeroclickinfo-spice#2893]
I stumbled upon this amazing [IA](https://duck.co/ia/view/twitter) today. Looked into the code and found something strange [here](https://github.com/duckduckgo/zeroclickinfo-spice/blob/04aaf11a04664c390accb8d5676618eacfa4b950/lib/DDG/Spice/Twitter.pm#L7)

I am not sure how this Twitter account information is being extracted?

/cc @moollaza @GuiltyDolphin @tagawa 

--- 
IA Page: https://duck.co/ia/view/twitter

**Comment by jagtalon** [comment]
@sahildua2305 hey! So Twitter's API uses OAuth, and Spice doesn't support this.

So what we did is that we do the OAuth on our servers and sort of "proxy" the API through https://duckduckgo.com/tw.js

Twitter -> DuckDuckGo Processes OAuth -> You

Hope that helps!

**Comment by sahildua2305** [comment]
That's awesome!

However, doesn't Twitter API have API call rate limits? How do you go with that?

**Comment by jagtalon** [comment]
@sahildua2305 mostly mediated through caching. We haven't run into any problems yet.

**Comment by sahildua2305** [comment]
That's crazy. Because the last time I checked the Twitter it had insane API call rate limits.

Anyway, I'd like to make a similar one for GitHub to cover the queries like `github sahildua2305`. Can you please share the tw.js code so that I can see if I get stuck doing the same thing?

**Comment by jagtalon** [comment]
@sahildua2305 I don't think the tw.js code will help because it's very different from a Spice and you wouldn't be able to test it. Maybe modifying https://github.com/duckduckgo/zeroclickinfo-spice/blob/820b42ee2164e4c93d347185c6de6af2afea04e2/lib/DDG/Spice/Github.pm to your needs will work--what do you think?

**Comment by sahildua2305** [comment]
Modifying Spice code won't help here because what I plan to do for GitHub is also similar to what you did for Twitter. It will also require OAuth.

**Comment by jagtalon** [comment]
@sahildua2305 I'm sorry--there are no plans for supporting OAuth at the moment for open source. We're trying to minimize the services that we run ourselves as well so currently we have it limited to Twitter and Amazon.

**Comment by sahildua2305** [comment]
Okay, makes sense! Thanks for answering my queries.
