### ISSUE TITLE
Create New CanIUse Spice

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2896]
## Background

Although the existing [CanIUse Fathead](https://duck.co/ia/view/caniuse) is capable of answering specific browser compatibility queries, we don't have a general reference for more generic queries. The CanIUse data is all available from a single JSON endpoint, and can be used to show a list of all browser features and their compatibilities.

### Objective

Use [the JSON data CanIUse provides](https://github.com/Fyrd/caniuse/blob/master/fulldata-json/data-2.0.json) to show a tile view of the various features for CSS, HTML, JS, SVG, etc that CanIUse covers

#### Example Queries
- [css browser compatibility](https://duckduckgo.com/?q=css+browser+compatibility&ia=web)
- [css3 browser compatibility](https://duckduckgo.com/?q=css3+browser+compatibility&ia=web)

### What to do: 
1. Comment here if you'd like to handle this task. 
2. Review any Related Discussions, Issues, and Pull Requests (below).
3. [Setup your Dev Environment](http://docs.duckduckhack.com/welcome/setup-dev-environment.html) (first-timers only)
4. Refer to the [Fathead documentation](http://docs.duckduckhack.com/resources/fathead-overview.html) and [other Fatheads](https://duck.co/ia?repo=fathead) as examples
5. [Submit a Pull Request](http://docs.duckduckhack.com/submitting/pull-request.html) with your completed changes

### Who to contact for help: 
Please contact @moollaza  or see [other contact info](http://docs.duckduckhack.com/resources/get-in-touch.html).

----

**Related Discussions, Issues, and Pull Requests:** 

Forum Topic: https://forum.duckduckhack.com/t/create-ia-caniuse-spice/229

**Comment by moollaza** [comment]
@duckduckgo/duckduckhack-contributors would anyone be interested in making this CanIUse Spice?

It will require some Perl and JavaScript skills. Ideally we can use existing templates, but we may need a custom item_detail template

**Comment by rasikapohankar** [comment]
@moollaza I would like to work on this.

**Comment by moollaza** [comment]
@rasikapohankar awesome! Thanks a lot for volunteering 👍 

If you haven't already, please sign up on the [forum](https://forum.duckduckhack.com) and feel free to join in the discussions! 

If you have any ideas for this Instant Answer we can  discuss them on the forum or here
