### ISSUE TITLE
METAR Information: API Endpoint not working 

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#2897]
Requesting http://avwx.rest/api/metar.php?station=klax&format=JSON&options=info,translate fails to load. See what the problem is or contact avwx.rest.

Thank you!

------
IA Page:  http://duck.co/ia/view/metar 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @santigl

**Comment by santigl** [comment]
I'm on it, @jagtalon. It seems to be an API problem again.

**Comment by santigl** [comment]
Unfortunately, the API has been getting overloaded. Michael, the API maintainer, has plans to do some architectural changes to mitigate them, but it is going to take a while.

He'll let me know and I'll let you guys know when they are implemented.

**Comment by santigl** [comment]
Hi @jagtalon. I was wondering if it would possible to use [Geo::WeatherNWS](http://search.cpan.org/~bobernst/Geo-WeatherNWS-1.053/lib/Geo/WeatherNWS.pm) to adquire the information directly from aviationweather.gov ourselves.  (The API they offer is xml only, so we would need that package to make the request.)

**Comment by jagtalon** [comment]
Hey, @santigl! Unfortunately requesting through Perl modules is synchronous which means it will block the search results from showing up on the page until the data is back. If we can use a JSON API instead that would be better!

**Comment by santigl** [comment]
I understand. And would the same thing happen with a regular http request for a text file with the data ready to print?

**Comment by jagtalon** [comment]
@santigl I'm not sure if I understand what you mean, but as long as the requests come from the client side, we're golden. If it happens server-side (in Perl), we can't have it. :(

**Comment by santigl** [comment]
I found that NOAA has a way of getting the observations in plain text. For example: [KJFK (raw metar)](http://tgftp.nws.noaa.gov/data/observations/metar/stations/KJFK.TXT) and [KJFK (decoded)](http://tgftp.nws.noaa.gov/data/observations/metar/decoded/KJFK.TXT)

We would have to do some parsing to display it in a table as with the current API. Could that be all implemented on the client's side?

**Comment by jagtalon** [comment]
@santigl I think we'd like to avoid text--we should stick to JSON or JSONP. The reason is that we'd have to add escaping functions in Nginx to make it compatible with our current system, and that takes time. Is there another source that you can find?

**Comment by santigl** [comment]
I couldn't find any other JSON source. However, today I got news from Michael: the new API version is implemented. :D

I have been doing some testing using duckpan and it seems to be working. Now we have to wait for Michael's green light, but we'll be able to bring it back up.

**Comment by jagtalon** [comment]
@santigl yes! Thank you so much!

**Comment by santigl** [comment]
Hi, @jagtalon. I am happy to tell you that the API backend has been renovated, and now  should support the traffic.  :D (Big thanks to Michael.)

I made a pull request with a couple of little changes, which aren't critical. Should we turn it back on and see what happens?

**Comment by santigl** [comment]
I just saw that there is another Instant Answer marked as *ghosted*, and that it is running at the beta site.

It has hijacked the link in my last pull request (#3005), so I was wondering: which version is it that is running?

**Comment by santigl** [comment]
It is live again. :D

Thank you @jagtalon and @moollaza for turning it back on!
