### ISSUE TITLE
MetaCPAN: Provide more information in the IA by showing the synopsis from the API

### ISSUE THREAD

**Issue by jbarrett** [duckduckgo/zeroclickinfo-spice#2905]
#2845 has been opened to track migration to [MetaCPAN API v1](https://github.com/CPAN-API/cpan-api/wiki/MetaCPAN-V1-announcement-and-migration-plan).

The current version of MetaCPAN spice was created basically as test load for [Spice POST support](https://github.com/duckduckgo/duckduckgo/pull/204) - it's not particularly advanced and doesn't offer a huge amount over organic search results.

Rather than simply link to metacpan.org, should this spice expand and provide the SYNOPSIS (or, failing that, DESCRIPTION) section for basic usage and information?

What else is directly useful? The side bar for e.g. [Dancer2](https://metacpan.org/pod/Dancer2) has links to issue tracking, smoke testing results, homepage...

Forum: https://forum.duckduckhack.com/t/improving-the-metacpan-spice/183/5

------ 

IA Page: https://duck.co/ia/view/meta_cpan

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
