### ISSUE TITLE
MetaCPAN: Update behaviour for an exact match to show a synopsis.

### ISSUE THREAD

**Issue by jbarrett** [duckduckgo/zeroclickinfo-spice#2906]
#2905 proposes expanding the behaviour of MetaCPAN to expand useful information upfront. We should probably consider triggering this behaviour upfront if the search remainder matches a module name exactly.

Since we're getting into areas of keyword triggering and relatively static data, should this be a fathead?

While we can get full pod and things like DESCRIPTION sections from the API, we then have to deal with that in js which may not be ideal...

Forum: https://forum.duckduckhack.com/t/improving-the-metacpan-spice/183/5
IA Page: https://duck.co/ia/view/meta_cpan

**Comment by jbarrett** [comment]
Scratch that, the API sends markup : https://fastapi.metacpan.org/v1/pod/JSON::MaybeXS so no need to handle POD.

**Comment by tagawa** [comment]
@jbarrett Not entirely sure I understand what's meant by "triggering the behaviour upfront". You mean the backend Perl code would change the API URL depending on the query remainder?

**Comment by jbarrett** [comment]
@tagawa That's a possibility, though I think it's easier to do on the frontend? We still need an `alt_to` configuration for the documentation endpoint.

Also, to be clear, #2905 is not a dependency of this issue.

**Comment by jbarrett** [comment]
"Triggering this behaviour upfront" means showing a synopsis section (or failing that, description) when we are confident that an exact module name has been searched.

**Comment by tagawa** [comment]
Thanks @jbarrett - that makes it clearer.

**Comment by pjhampton** [comment]
Closing as this is no longer high priority 👍
