### ISSUE TITLE
Actor Filmography: Examples not working

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#2908]
For example: https://duckduckgo.com/?q=Movies%20with%20Keira%20Knightley&ia=movies  
 

---

IA Page:  http://duck.co/ia/view/movies_filmography 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @whalenrp

**Comment by whalenrp** [comment]
@daxtheduck The same query seems to be working fine on the beta distribution: https://beta.duckduckgo.com/?q=Movies%20with%20Keira%20Knightley&ia=movies. Is it possible that our API key with TheMovieDb is hitting a rate limit? IIRC, the limit was fairly low.

@travisbell @moollaza -- Are either of you able to look into the state of our TMDb API key to see if this might be the case?

**Comment by travisbell** [comment]
Hi @whalenrp 

Hmm, yes, that could be the case. The limits are enforced by IP address, not API key. It seems to me I remember you saying it is the DDG servers that proxy requests, correct?

Let me think about this for a moment...

**Comment by travisbell** [comment]
Just an update, I'm working with our ops team to figure out the best solution here. I'll post an update when we've figured out the plan.

**Comment by moollaza** [comment]
Fixed
