### ISSUE TITLE
Maps: more specific address search

### ISSUE THREAD

**Issue by rwakulszowa** [duckduckgo/zeroclickinfo-spice#2912]
Hey, is it possible to search with more specific search queries, i.e. including an address?That would be much more useful than just a simple city name matching.

IA Page:  http://duck.co/ia/view/maps_maps 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nilnilnil

**Comment by nilnilnil** [comment]
We are in the process of improving the maps functionality, and will take this into consideration. Thank you!

**Comment by datafunk** [comment]
Are you guys working on this one actively ATM?

**Comment by moollaza** [comment]
Searching addresses should work. This is actively being improved internally.
