### ISSUE TITLE
Untappd: Update triggering? Example query not working 

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/zeroclickinfo-spice#2926]
One of the supplied example queries doesn't show the Untappd IA: https://duckduckgo.com/?q=bommen%20%26%20granaten%20barleywine&ia=food&drink

------
IA Page:  http://duck.co/ia/view/untappd 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @urbanserj

**Comment by urbanserj** [comment]
Hi, @zekiel!

I forgot to update example queries in Untappd IA page and I've just updated the page. As I mentioned [here](https://github.com/duckduckgo/zeroclickinfo-spice/pull/2746#issuecomment-222374710) this heuristics can work fine but not for all cases. So `bommen & granaten barleywine` is not good example :( These is no barleywine word in the title or the description of this beer.

**Comment by edgesince84** [comment]
The example queries aren't triggering this IA, unless you include "untappd" in the query as well.

**Comment by zekiel** [comment]
Looks fixed now! Thank you @urbanserj Looking forward to improving this over time -- it's really useful and fun to play around with.
