### ISSUE TITLE
Cocoapods Instant Answer

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#2927]
## Background

[CocoaPods](https://cocoapods.org/) has a great listing of third-party libraries that people can use. There's currently a CocoaPods Instant Answer that you can find in https://github.com/duckduckgo/zeroclickinfo-spice/pull/2224, but it hasn't been released because of HTTP request problems. See if you can finish it off!

### Objective

To get the Spice working again so that we can answer Cocoapods related queries such as "cocoapods alamofire".

#### Example Queries
- [cocoapods alamofire](https://duckduckgo.com/?q=cocoapods+alamofire&t=ffab&ia=software)

### What to do: 
1. Comment here if you'd like to handle this task. 
2. Review any Related Discussions, Issues, and Pull Requests (below).
3. [Setup your Dev Environment](http://docs.duckduckhack.com/welcome/setup-dev-environment.html) (first-timers only)
4. Refer to the [Spice documentation](http://docs.duckduckhack.com/walkthroughs/forum-lookup.html) and [other Spices](https://duck.co/ia?repo=spice) as examples
5. [Submit a Pull Request](http://docs.duckduckhack.com/submitting/pull-request.html) with your completed changes

### Who to contact for help: 
Please contact @jagtalon  or see [other contact info](http://docs.duckduckhack.com/resources/get-in-touch.html).

----

**Related Discussions, Issues, and Pull Requests:** 

Forum Topic: https://forum.duckduckhack.com/t/cocoapods-instant-answer/241

**Comment by soleo** [comment]
Looks like the issue can be closed once #2224 is deployed

**Comment by jagtalon** [comment]
@soleo would you be interested in doing it once https://github.com/duckduckgo/duckduckgo/pull/208 gets deployed?

**Comment by soleo** [comment]
Sure.
