### ISSUE TITLE
What3Words Geocoder: Should accept space-separated co-ordinates

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#2928]
For example https://duckduckgo.com/?q=what3words++51.9985+-0.7439&ia=map

---

IA Page:  http://duck.co/ia/view/what3words 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @moollaza

**Comment by moollaza** [comment]
This should be fairly simple to support, but @tagawa do you have any examples of where you might get space-separated coordinates from?

I feel like anytime I see a lat/lon it's always formatted with a `,` separating the two.

**Comment by tagawa** [comment]
@moollaza Yes, from this page - scroll down, just above the map: http://www.atlasobscura.com/places/skellig-michael
I agree it's very much an edge case though.

**Comment by moollaza** [comment]
Closing due to DDH entering Maintenance Mode. We are only accepting issues for essential bugs.
