### ISSUE TITLE
Bible verse of the day

### ISSUE THREAD

**Issue by gerlachry** [duckduckgo/zeroclickinfo-spice#2929]
@hunterlang @MAMAMIA9 @pnpninja I was experimenting with learning about the IAs and made some updates to the Bible spice for verse of the day if wanted to include this in the IA.  I can open a pull request if want to include.
https://github.com/gerlachry/zeroclickinfo-spice/tree/gerlachry/bible-verse-of-day2

**Comment by pnpninja** [comment]
sure..  go ahead... but follow the template as we have discussed in https://github.com/duckduckgo/zeroclickinfo-spice/pull/2826 .. see what @tagawa has said in the last comment and follow the structure specified
