### ISSUE TITLE
Dictionary Definition: raw food

### ISSUE THREAD

**Issue by Fabijenna** [duckduckgo/zeroclickinfo-spice#2930]
Food that was not heated above 42 Celsius or 107.60000 Fahrenheit
Examples: fresh fruit, vegetables, sprouts (also sprouted grains), grasses
Further examples of raw "gourmet" food: nuts and seeds; soaked grains

---

IA Page:  http://duck.co/ia/view/dictionary_definition 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon

**Comment by edgesince84** [comment]
@Fabijenna I'm confused - this is for the dictionary IA.  What are you suggesting is the issue?
