### ISSUE TITLE
Imdb Ratings: 

### ISSUE THREAD

**Issue by vidhan13j07** [duckduckgo/zeroclickinfo-spice#2933]
Hi, I am new to duckduckgo.
I want to build IA for teh imdb_ratings.
Can I take up this IA?

------
IA Page:  http://duck.co/ia/view/imdb_ratings

**Comment by moollaza** [comment]
Unfortunately this is not possible. IMDb will only allow us to show ratings if we get them directly from IMDb. This requires a license (and licensing fees) which we are not currently interested in. Until something changes we are unable to show IMDb ratings on DuckDuckGo
