### ISSUE TITLE
What3Words Geocoder: Fallback to StandardBlend (autosuggest) API when no results for three-word address

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2935]
When a user misspells a three word address they will currently see no results. The What3Words team suggested we try faling back to their [StandardBlend](https://docs.what3words.com/api/v2/#standardblend) (Autocomplete) API in those cases to show potential matches for the given address.

If the first API call returns no results, we can make another API call and if it has results, display a Places tile view (similar to the [BikeShare Spices](https://duckduckgo.com/?q=nyc+bike+share+locations&ia=bikesharing)) which provides the similar addresses.

This will require creating another `Spice alt_to` endpoint for the StandardBlend API Endpoint.

We should use the `text` template for the tiles. The title should be the 3-Word address, and the subtitle should be the location the place is near to (provided by the API). If possible, it would be nice to use our flag icons as well, if possible but that might be difficult.

---

IA Page:  http://duck.co/ia/view/what3words 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @moollaza

**Comment by vovkman** [comment]
I have a problem using the StandardBlend api (I think). Should this URL work? 

['https://api.what3words.com/v2/standardblend?addr=$3&lang=en&key={{ENV{DDG_SPICE_W3W_APIKEY}}}&callback={{callback}}'](url)

I call it in getJSON with this 

`$.getJSON('/js/spice/standard_blend/' + words, function(data) {...`

where `var words = encodeURIComponent(api_result.words)`

and the fail callback is triggered. Does this work for anyone else?

**Comment by moollaza** [comment]
@vovkman I've left some feedback on your PR.

Please update the code there to match what you had when it wasn't working. Then I can determine the problem, but what you have there _**should**_ work..

**Comment by vovkman** [comment]
@moollaza where are the flag icons you were talking about?
