### ISSUE TITLE
No IA triggered while searching queries like 'Today in history' or 'Historical events on xx-xx-xxxx'

### ISSUE THREAD

**Issue by shubh1m** [duckduckgo/zeroclickinfo-spice#2939]
Responsible file https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/TodayInHistory.pm 

------ 

IA Page: https://duck.co/ia/view/today_in_history

**Comment by pjhampton** [comment]
It seems to me that these queries are now working. See attached. If there are still not working for you we can reopen this issue 👍 

![screen shot 2017-03-09 at 6 46 29 pm](https://cloud.githubusercontent.com/assets/8960296/23765336/cd3cba64-04f8-11e7-849a-dae0071face8.png)


![screen shot 2017-03-09 at 6 46 09 pm](https://cloud.githubusercontent.com/assets/8960296/23765340/cff98156-04f8-11e7-9454-0de23d4d73e0.png)
