### ISSUE TITLE
Public Holidays: under-triggering?

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-spice#2944]
Should this IA cover queries such as "when is labor day 2016?" 

---

IA Page:  http://duck.co/ia/view/public_holidays 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sekhavati

**Comment by sekhavati** [comment]
@edgesince84 No this IA only provides a list of public holidays for a given country. The [holiday IA](https://duck.co/ia/view/holiday) covers those sorts of queries.
