### ISSUE TITLE
IA Request: WhoSampled

### ISSUE THREAD

**Issue by emanresusername** [duckduckgo/zeroclickinfo-spice#2945]
Just getting started here, forgive me if this isn't the appropriate channel, but it would be awesome to get instant answers from [whosampled](http://www.whosampled.com) for various songs to find the original songs they were inspired by and the songs that sampled from them later on.
The [availability/existence of their api is a little uncertain](http://www.whosampled.com/metadata/) but i see there is already a `!bang` for it, maybe somebody here's already got a foot in the door?

**Comment by pjhampton** [comment]
Hey @emanresusername 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
