### ISSUE TITLE
Time: overtriggering on `the day` 

### ISSUE THREAD

**Issue by mrshu** [duckduckgo/zeroclickinfo-spice#2946]
This IA triggers on [`the day`](https://duckduckgo.com/?q=the+day&ia=time). This seems to be expected given the [triggers](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Time.pm#L12) but I am not sure if it makes sense from the user's perspective.
---

IA Page:  http://duck.co/ia/view/time 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by MrChrisW** [comment]
This was added in https://github.com/duckduckgo/zeroclickinfo-spice/pull/2524 - Looking at the tests it may have only been intended to trigger on `what\'s the day in <city>` not just `the day`. @Sayanc93 can you look into this?

**Comment by mrshu** [comment]
`the day` no longer triggers the `Time` Spice for me -- I believe this issue can be closed.
