### ISSUE TITLE
Forecast: Rounding Issue

### ISSUE THREAD

**Issue by plan-nine** [duckduckgo/zeroclickinfo-spice#2947]
The humidity has a rounding issue - a long series of 9's. See the attached screen shot (far left box).

![weather-forecast-error](https://cloud.githubusercontent.com/assets/20889157/17463377/ebb95408-5c91-11e6-9598-9d643bedaea7.png)

---

IA Page:  http://duck.co/ia/view/forecast 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @himanshu0113

**Comment by davidofferman** [comment]
Hello,
I fixed this in PR #2942, it just needs to be merged.

**Comment by moollaza** [comment]
Fixed
