### ISSUE TITLE
Untappd: SyntaxError: unterminated string literal

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#2952]
Some requests such as https://duckduckgo.com/?q=untappd+golden+ale returns a JSON response that has an unterminated string literal:

<img width="1467" alt="screen shot 2016-08-10 at 3 21 20 pm" src="https://cloud.githubusercontent.com/assets/81969/17567792/d3b01426-5f0e-11e6-899f-4ed5f8fa0f77.png">

<img width="1467" alt="screen shot 2016-08-10 at 3 21 27 pm" src="https://cloud.githubusercontent.com/assets/81969/17567793/d3bd8fca-5f0e-11e6-9747-271d3e8f71f8.png">

Please contact Untappd to see if it's something that can be done on their end.

---

IA Page: https://duck.co/ia/view/untappd

**Comment by davidofferman** [comment]
This appears to be an API endpoint issue, but an internal fix may be able to fix it. There is a flaw with the JSON encoding where some UTF-8 characters are not being encoded properly.

For instance, the Golden Ale response contains the character `\u2028`, but it isn't encoded and is causing issue.

**Comment by moollaza** [comment]
IA is no longer online.
