### ISSUE TITLE
Forecast: Text can overlap images

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#2953]
I searched for the weather in my city, and the up-to-the-minute weather predictions overlap with the image assets:

<img width="1792" alt="screen shot 2016-08-11 at 8 29 48 am" src="https://cloud.githubusercontent.com/assets/81969/17588577/09d716be-5f9e-11e6-8c55-b10ccf67c0a0.png">

<img width="1792" alt="screen shot 2016-08-11 at 8 30 01 am" src="https://cloud.githubusercontent.com/assets/81969/17588578/09e3bf54-5f9e-11e6-8887-1e9d7d4ec23c.png">

This not only happens in FF, but in Chrome and Safari as well.

---

IA Page: https://duck.co/ia/view/forecast

**Comment by sahildua2305** [comment]
This is more of a template issue, no? @jagtalon

**Comment by moollaza** [comment]
Fixed
