### ISSUE TITLE
Just Delete Me: wrong account info displayed

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-spice#2961]
When I search for "delete icloud account," I'm shown instructions on deleting a JoliCloud / JoiliDrive account.

https://duckduckgo.com/?q=delete+icloud+account&t=ffab&ia=answer

---

IA Page:  http://duck.co/ia/view/just_delete_me 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @riqpe

**Comment by riqpe** [comment]
The IA shows also partial matches, in the same way as the original JustDelete.me service does. [[1]] (http://justdelete.me/#icloud)
This also means that if there are multiple matches, all of them are shown, e.g. searching with just "cloud". [[2]] (https://duckduckgo.com/?q=delete+cloud+account&ia=answer)
When available, exact match is selected over partial matches. 

Perhaps we could add an indicator when only partial matches are found to help with possible confusion.

[1] http://justdelete.me/#icloud
[2] https://duckduckgo.com/?q=delete+cloud+account&ia=answer

**Comment by tagawa** [comment]
@riqpe I agree - even for exact matches we should show a list from the API including partial matches. If we can highlight the exact match that would be good (not sure if the template allows it) but even if we can't, the exact match being first in a list would be better than when it's the only answer but incorrect.

**Comment by mrshu** [comment]
Hello everyone, I have another example of this: https://duckduckgo.com/?q=how+to+cancel+your+homeowners+insurance+from+going+into+an+escrow+account&ia=answer

I strongly believe that it would be better not to show anything in cases line these -- I was kind of surprised with the Instant Answer I got to be honest.

**Comment by riqpe** [comment]
I do agree. After the original issue I tried out a couple of different ways of indicating partial and exact matches, but I was not satisfied with the results. 

I vote for removing the support for partial matches all together, only showing exact name and domain matches.

@moollaza do you want to run this by someone before I make a PR?

**Comment by moollaza** [comment]
@riqpe you're the maintainer so you have say here. I agree that we can ignore partial matches.

If we're not already, we should be using our built-in relevancy checking to ensure only highly relevant results come through.

**Comment by riqpe** [comment]
@moollaza, ok I will remove the partial matches.

The IA is not using the built-in relevancy checking as that lead to even less relevant results.
