### ISSUE TITLE
Maps: Language 

### ISSUE THREAD

**Issue by DPAUTH** [duckduckgo/zeroclickinfo-spice#2963]
When I turn the region button on (ex. France) the language of the maps is still in English while mapbox has a French, German, Spanish, Russian and Chinese version available. I believe these links will come in handy  https://www.mapbox.com/help/change-language/    https://www.mapbox.com/mapbox-gl-js/example/language-switch/

---

IA Page:  http://duck.co/ia/view/maps_maps 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nilnilnil

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
