### ISSUE TITLE
Whois: IA not displaying

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#2964]
According to their API response, we've run out of credits: https://beta.duckduckgo.com/js/spice/whois/duckduckgo.com

We also don't seem to be using caching, hence how we used up all our credits.   

---

IA Page:  http://duck.co/ia/view/whois 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @b1ake

**Comment by davidofferman** [comment]
I was under the impression that all spice API calls are cached for 1 day by default. [DuckDuckHack Caching documentation](http://docs.duckduckhack.com/backend-reference/api-reference.html#caching-api-responses).

Also, when I perform the API request directly but with a different domain (because duckduckgo.com is probably cached), I get a new error.

    ddg_spice_whois({"ErrorMessage": {
        "msg": "Username and password combination does not match."
    }})

**Comment by pjhampton** [comment]
It might be worth contacting the API maintainers if multiple different errors are coming up for the users.

**Comment by tagawa** [comment]
Re. the username/password error, this is because I changed the password earlier (it was an embarrassingly weak one!). The live code hasn't been updated yet but I thought as the IA is not displaying anyway, it was a good time to do it.

Regarding the lack of credits, we're looking into getting some more.

**Comment by b1ake** [comment]
@tagawa Can I help in any way with this? Sounds like we need to request more credits and that you're on top of it.

**Comment by tagawa** [comment]
Thanks for the offer @b1ake. There's an internal task for this and @moollaza has been asking about how we can proceed.

**Comment by moollaza** [comment]
The BD team fired off an email today, waiting for a response from WhoisAPi

**Comment by altern8tif** [comment]
Any update on this?  Seems like it's still not working.

**Comment by moollaza** [comment]
Seems to be fixed
