### ISSUE TITLE
InTheaters and Movie needs a new API

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#2976]
Currently, they both use Rotten Tomatoes for data. But sadly, RT is slowly removing data in their API. It started with the images, and now the IMDB IDs (which we use to get images).

I think a better solution for this is to switch to a new provider either GoWatchIt or TMDB.

https://duck.co/ia/view/in_theaters
https://duck.co/ia/view/movie

**Comment by akuks** [comment]
I am interested in and try to solve this issue.

**Comment by devanshdalal** [comment]
Hi guys, what's the status on this one?
"InTheaters" IA is not live anymore. reasons ?


I am willing to work on this one to make it live again. Or do you guys have any other plans?
