### ISSUE TITLE
CourseBuffet: Remove from repo

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#2977]
The API has been offline for many months. We should remove this IA from the repo.

---
https://duck.co/ia/view/coursebuffet

**Comment by moollaza** [comment]
Looks like the `/ddg` API endpoint no longer exists?

We should see if they have a public API we can use, or delete the Instant Answer

**Comment by sahildua2305** [comment]
@moollaza Seems like there's no public API that they provide. Should we delete the IA then?

**Comment by moollaza** [comment]
@rubydubee is the `/ddg` API permanently offline?

**Comment by moollaza** [comment]
Let's remove this IA. API has been offline for months
