### ISSUE TITLE
Couprex: API is down

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#2978]
The API endpoint (http://couprex.com/?json=get_search_results&search=electronics) seems to be down. Please contact them to see what's up. :)

---

IA Page: https://duck.co/ia/view/couprex

**Comment by moollaza** [comment]
This is @AdamSC1-ddg 's API. He was working on it, but I believe the IA has been offline for a while due to triggering/relevancy issues
