### ISSUE TITLE
Videos: Youtube channel page link not working with newer channel link formats

### ISSUE THREAD

**Issue by theniels17** [duckduckgo/zeroclickinfo-spice#2979]
after searching for an video the link to the uploaders youtube channel does not work with newer /channel/XXXXX channels it goes to the /user/XXXXX page which often does not exist

how to reproduce the problem:
search something (example search: "duckduckgo")
click the "video's" tab
select a result (for example the first one)
click on the channel name (in the example its "Tekzilla")
you will be redirected to youtube.com/user/Tekzilla and it will give an error the real page for the uploader is using the new youtube channel page link format: https://www.youtube.com/channel/UCMkhrrPkmx7xxlolSP9qEsA

---

IA Page:  http://duck.co/ia/view/videos 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @bsstoner

**Comment by adentranter** [comment]
Having a look at the source code at https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Videos.pm and https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/videos/videos.js

Anyone know where the data for the youtube videos is being processed? (file)

**Comment by moollaza** [comment]
This has been fixed
