### ISSUE TITLE
Forecast: Shows weather for wrong city

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#2981]
## Steps to reproduce:
1. Search for the weather in Shanghai: https://duckduckgo.com/?q=weather+in+shanghai&ia=weather
2. Check the Instant Answer that's displayed.
## What should happen:

The weather for Shanghai should be shown.
## What actually happens:

The weather for Changchun is shown.

Originally reported here: http://blog.lerner.co.il/fun-with-floats/

**Comment by sriranganathan** [comment]
@tagawa Can I take up this Issue?

**Comment by nalinbhardwaj** [comment]
Seems fixed. Please close this @tagawa.
