### ISSUE TITLE
What3Words Geocoder: Triggering for technical queries

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#2986]
For example: https://duckduckgo.com/?q=system.diagnostics.process (from .NET)

[Reported on Twitter](https://twitter.com/chucker/status/770190994453176320)

---

IA Page:  http://duck.co/ia/view/what3words 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @moollaza

**Comment by bsstoner** [comment]
Another complaint of over-triggering on technical queries:

system.windows.controls
https://duckduckgo.com/?q=system.windows.controls

**Comment by bsstoner** [comment]
@moollaza we need to make the trigger include `what3words` or some other qualifier. The majority of queries this is triggering on are false positive technical searches.
