### ISSUE TITLE
Search Code: Overtriggering on `perl <`

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-spice#2992]
This seems a bit weird, if you search for [perl <](https://duckduckgo.com/?q=perl+%3C&ia=answer), it comes up with a Hello World example, which seemingly has _nothing_ to do with the query.

This also happens on [perl ,](https://duckduckgo.com/?q=perl+%2C&ia=answer) (and possibly other queries too).

---

IA Page:  http://duck.co/ia/view/search_code 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sahildua2305

**Comment by sahildua2305** [comment]
Escaping new line in the API response can be added as a separate issue because it has nothing to do with over triggering so that both issues can be solved separately. @GuiltyDolphin What do you think?

**Comment by moollaza** [comment]
IA is no longer online.
