### ISSUE TITLE
Places: Support specifying base location (non-US)

### ISSUE THREAD

**Issue by dotanrs** [duckduckgo/zeroclickinfo-spice#2993]
What about manually setting a place for search?
i.e. instead of 'bars near me' search for 'bars near (/in) Tel Aviv'
like in google https://encrypted.google.com/search?hl=en&q=bars%20in%20jaffa 

---

IA Page:  http://duck.co/ia/view/maps_places 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nilnilnil

**Comment by nilnilnil** [comment]
Can you give me an example DDG query you'd like to roughly replicate what Google is doing?

**Comment by dotanrs** [comment]
Actually I see now that it already exists,
e.g. [cafes near Harlem](https://duckduckgo.com/?q=cafes+near+harlem&t=ffab&ia=places&iax=1)
But it seems to only work for US cities, which is why I didn't see it

**Comment by dotanrs** [comment]
I think what's requires is an additional (replacement?) source to YELP since it simply has no entries from places outside the US..
IMO the best source by far is google maps

**Comment by pjhampton** [comment]
Hey @dotanrs 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
