### ISSUE TITLE
Chuck Norris Jokes:  Unable to see results

### ISSUE THREAD

**Issue by iammayankg** [duckduckgo/zeroclickinfo-spice#2997]
This plugin was working fine earlier with the !safeoff option but has stopped working recently. Shows up the wiki page instead, but that's not supposed to show with safeoff.

---

IA Page:  http://duck.co/ia/view/chuck_norris 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @iammayankg

**Comment by pjhampton** [comment]
This [IA's production state](https://duck.co/ia/view/chuck_norris/json) has been knocked offline.
