### ISSUE TITLE
Dictionary Definition: Empty Result

### ISSUE THREAD

**Issue by viluon** [duckduckgo/zeroclickinfo-spice#2998]
The search query "[define to fall out](https://duckduckgo.com/?q=define+to+fall+out&t=ffab&ia=definition)" results in an empty "Definition" answer:
![](https://i.imgur.com/ix3IL9I.png)

---

IA Page:  http://duck.co/ia/view/dictionary_definition 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon

**Comment by marianosimone** [comment]
@jagtalon @GuiltyDolphin seemed like an easy fix, so I went ahead and tackled it

**Comment by sahildua2305** [comment]
@marianosimone can you please create a PR for this so that we can test your changes?

**Comment by marianosimone** [comment]
@sahildua2305 somehow I forgot to create the PR when I commited the change to my fork. Thanks for calling it out :D

**Comment by marianosimone** [comment]
@GuiltyDolphin @sahildua2305 any news on reviewing my PR?

**Comment by bsstoner** [comment]
This was released to production 🚀
