### ISSUE TITLE
Forecast: No results for "Weather Chernivtsi"

### ISSUE THREAD

**Issue by D3sl0nG3r** [duckduckgo/zeroclickinfo-spice#3000]
When you type "Weather Kyiv" or "Weather Lviv" it works perfectly. (I'm ukrainian). But when you type "Weather Chernivtsi" there's no IA. Only search results. If you can, please, make all cities available on IA (not only Ukraine ones, but every single one).  
(I don't know how to write code, that's why i'm asking for help)
![screenshot_1](https://cloud.githubusercontent.com/assets/11181091/18560217/502eec76-7b83-11e6-9b60-e613743e545a.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/11181091/18560218/50308cca-7b83-11e6-9310-eeaf348106d7.png)
---

IA Page:  http://duck.co/ia/view/forecast 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @himanshu0113

**Comment by mrshu** [comment]
@himanshu0113 @D3sl0nG3r @moollaza all of the following should work now:

- https://duckduckgo.com/?q=weather+kyiv&ia=weather
- https://duckduckgo.com/?q=Weather+Chernivtsi&ia=weather
- https://duckduckgo.com/?q=Weather+Lviv&ia=weather
