### ISSUE TITLE
Time: Does not trigger for "current time new york" or "time in new york"

### ISSUE THREAD

**Issue by tmlye** [duckduckgo/zeroclickinfo-spice#3001]
This instant answer is not triggered for the above queries. It also doesn't work for Boston. If I type "current time frankfurt", it displays it correctly.

------
IA Page:  http://duck.co/ia/view/time 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by MrChrisW** [comment]
@tmlye Thanks! We're tracking a number of non-working queries in https://github.com/duckduckgo/zeroclickinfo-spice/issues/1730
