### ISSUE TITLE
Forecast: Triggered by unrelated query

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#3004]
### Steps to reproduce:
1. Search for [ga experiment](https://duckduckgo.com/?q=ga+experiment&ia=weather)
2. Look at the search results
### What should happen:

There should be no weather Instant Answer.
### What actually happens:

The weather IA triggers and a forecast is shown for Experimentgatan in Sweden.

[Reported on Twitter](https://twitter.com/soleoshao/status/778329458361065472)

---

IA Page:  http://duck.co/ia/view/forecast 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @himanshu0113

**Comment by mrshu** [comment]
This will be a slight problem, as there actually is [Experiment in Georgia](https://en.wikipedia.org/wiki/Experiment,_Georgia) and it is a place for which weather forecast might be in order =)

**Comment by moollaza** [comment]
Seems Fixed
