### ISSUE TITLE
Forecast: API changing to DarkSky

### ISSUE THREAD

**Issue by tommytommytommy** [duckduckgo/zeroclickinfo-spice#3008]
API change mentioned in a blog post at http://blog.darksky.net/introducing-darksky-net/

Looks like the current endpoint will continue to work through the end of the year. Not sure how much of the old API has been duplicated/how much work exists to convert to the new endpoint/API...   

This will probably also require some internal coordination...
cc: @b2ddg @bsstoner 

---

IA Page:  http://duck.co/ia/view/forecast 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @himanshu0113

**Comment by b2ddg** [comment]
PR to update the endpoint: https://github.com/duckduckgo/zeroclickinfo-spice/pull/3026
