### ISSUE TITLE
Search Code: Newlines treated literally

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-spice#3011]
When searching for https://duckduckgo.com/?q=perl+%3C&ia=answer the `Search Code` Instant Answer triggers, but the output is different to what it should be.

Shown result:

``` perl
# Hello world in perl

print "Hello World!
";
```

Expected:

``` perl
# Hello world in perl

print "Hello World!\n";
```

It looks like the newline is being treated literally.

(cc @sahildua2305)

---

IA Page:  http://duck.co/ia/view/search_code 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sahildua2305

**Comment by sahildua2305** [comment]
Will fix soon! Thanks @GuiltyDolphin 😄

**Comment by moollaza** [comment]
Removing the Programming Mission label as this IA isn't directly connected to any specific language or it's goals, it's also fairly low-priority and low-triggering

**Comment by sahildua2305** [comment]
@GuiltyDolphin In particular case of query `perl <`, we get this response from API - 
```
\n# Hello world in perl\n\nprint \"Hello World!\n\";\n
```

I'm not sure we can fix this issue because we can't escape all newline characters. We just don't know which ones are required and which ones aren't.

Let me know if you have an idea!

**Comment by moollaza** [comment]
@GuiltyDolphin @sahildua2305 this IA is undergoing changes for the programming mission anyway. It will be switched to a new API and focused on Python searches for now.

See #2999

**Comment by moollaza** [comment]
IA is no longer online.
