### ISSUE TITLE
Forecast: 

### ISSUE THREAD

**Issue by Toorero** [duckduckgo/zeroclickinfo-spice#3013]
I noticed, cause i am a German, that this instant answer and plenty more aren't translated into German for instance. To improve this i would suggest to add the trigger 'wetter', cause it's sucks so hard to think over every time when i await a instant answer.

Stay tuned guys.    

------
IA Page:  http://duck.co/ia/view/forecast 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @himanshu0113

**Comment by moollaza** [comment]
@Toorero thanks for pointing this out. We don't currently have plans to add non-english triggers yet, but internationalization of Instant Answers and their triggering is something we intend to achieve in the future.

For now I'm marking this as a tolerated issue.
