### ISSUE TITLE
Advanced Calculator: overtriggering

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-spice#3017]
This IA is triggering on queries related to C++, trying to solve the equation.  An example would be "java c++ integration."

---

IA Page:  http://duck.co/ia/view/symbolab 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @levaly

**Comment by russellholt** [comment]
@moollaza thoughts?

**Comment by moollaza** [comment]
We could add a check for the specific keyword "c++" and ignore that.

There has been an open issues to fix the triggering of this IA for a long time. It almost never triggers currently..

**Comment by levaly** [comment]
I will add a more sophisticated triggering regex.
