### ISSUE TITLE
Emojipedia: Looking up flags shows info about a regional indicator

### ISSUE THREAD

**Issue by robrobinbin** [duckduckgo/zeroclickinfo-spice#3018]
Example: searching for the European flag 🇪🇺gives following page

https://duckduckgo.com/?q=%F0%9F%87%AA%F0%9F%87%BA&ia=answer

The zero click answer refers to [Regional Indicator Symbol Let­ter U](http://emojipedia.org/regional-indicator-symbol-letter-u/) instead of [Flag for European Union](http://emojipedia.org/flag-for-european-union/)

------
IA Page:  http://duck.co/ia/view/emojipedia 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mathewbyrne

**Comment by RetroCraft** [comment]
Correct me if I'm wrong, but national flags are created with two Unicode characters, so that is the correct (single) Unicode character showing up.

**Comment by robrobinbin** [comment]
Correct, but that shouldn't be the desired behavior. The emojipedia page of the flag as a whole is more relevant than the page of one of two regional indicators making the flag.

**Comment by Boldewyn** [comment]
Sorry for the delay! Yes, that is indeed a bug, related to how our regular expression matches. Thanks for the report! I'll update the regexp.
