### ISSUE TITLE
Emojipedia: Switch maintainer

### ISSUE THREAD

**Issue by Boldewyn** [duckduckgo/zeroclickinfo-spice#3019]
As per the docs: "I’d like to maintain this." :smile:

@mathewbyrne and me switched responsibilities. Please add me as maintainer for the Emojipedia IA.

------
IA Page:  http://duck.co/ia/view/emojipedia 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mathewbyrne

**Comment by moollaza** [comment]
IA Page has been updated 👍
