### ISSUE TITLE
Search query "US news" opens images tab

### ISSUE THREAD

**Issue by kumarankit0411** [duckduckgo/zeroclickinfo-spice#3020]
Searching for "US news" returned images of US News Corporation which seemed **irrelevant**. A more appropriate answer should have been latest news result from United States.
Here is the screenshot :
![anoymous_bug](https://cloud.githubusercontent.com/assets/19763730/19248919/6132910e-8f50-11e6-9a4b-3d5a4e0d26bd.png)
One more issue is that, for the same search term, sometimes the images tab opens and sometimes it does not.

**Comment by moollaza** [comment]
This is being worked on internally 👍
