### ISSUE TITLE
Keybase: Not seeing IA

### ISSUE THREAD

**Issue by jonathancross** [duckduckgo/zeroclickinfo-spice#3028]
None of the example queries produce the keybase IA for me:
- https://duckduckgo.com/?q=keybase%20chris&ia=keybase
- https://duckduckgo.com/?q=keybase%20github%3Amaxtaco&ia=keybase
- https://duckduckgo.com/?q=keybase%20twitter%3Ajeresig&ia=keybase
- https://duckduckgo.com/?q=keybase%20jeresig&ia=keybase

---

IA Page:  http://duck.co/ia/view/keybase 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @soleo

**Comment by soleo** [comment]
@jonathancross Thanks for reporting this issue. I'll look into it soon.

**Comment by moollaza** [comment]
This IA was disabled, likely because the API was unreachable at some point. I'll have it scheduled to go back online 👍

**Comment by pjhampton** [comment]
Looks like this is back up and running https://duckduckgo.com/?q=keybase+pjhampton&ia=keybase

**Comment by jonathancross** [comment]
Fantastic!
