### ISSUE TITLE
Videos: Should have tooltips

### ISSUE THREAD

**Issue by pavkum** [duckduckgo/zeroclickinfo-spice#3030]
Any search for videos generally result in multiple videos. Since the card size is fixed one cannot see the full title. One might prefer to watch from a particular publisher or just want to confirm the full title.

A tooltip with relevant details on hover would be a very nice enhancement.    

---

IA Page:  http://duck.co/ia/view/videos 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @bsstoner

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
