### ISSUE TITLE
Time: Not triggering for American cities

### ISSUE THREAD

**Issue by x-15a2** [duckduckgo/zeroclickinfo-spice#3032]
This IA does not seem to work with American Cities, even when forced. Example: https://duckduckgo.com/?q=what+is+the+time+in+Minneapolis&ia=web
I've tried several triggers: time, Time In, What Time Is It In,  What Is The Time In, Time For, but none work for US cities.

Works: https://duckduckgo.com/?q=time+for+Toronto&ia=time

Fails: https://duckduckgo.com/?q=time+for+Indianapolis&ia=time  

As reported here: https://www.reddit.com/r/duckduckgo/comments/5992sx/whats_going_on_here/ 

------
IA Page:  http://duck.co/ia/view/time 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by mrshu** [comment]
@x-15a2 @MrChrisW @tagawa This should be fixed now.

**Comment by tagawa** [comment]
Great! Thank you @mrshu and team.
