### ISSUE TITLE
Movie:  API call is failing

### ISSUE THREAD

**Issue by vikashvverma** [duckduckgo/zeroclickinfo-spice#3040]
Rotten Tomatoes API call seems to be failing. This might be the issue because of expired API KEYS.
As a result non of the trigger is working.

@moollaza Can you look into this?

------
IA Page:  http://duck.co/ia/view/movie 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @vikashvverma

**Comment by moollaza** [comment]
IA is no longer online.
