### ISSUE TITLE
arXiv: JS Error causing Image Fallbacks

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#3045]
<img width="1195" alt="screen shot 2016-11-15 at 6 30 08 am" src="https://cloud.githubusercontent.com/assets/126358/20304205/044b2c12-aafd-11e6-98ff-4f9817bfa5b2.png">
   

------
IA Page:  http://duck.co/ia/view/arxiv 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jbarrett

**Comment by jbarrett** [comment]
@bsstoner Seems I'm accessing properties before asserting the result actually exists - D'oh - https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/arxiv/arxiv.js#L36-L41

Would returning `Spice.failed` properly here also result in image fallback?

**Comment by bsstoner** [comment]
Yup, that should do it

**Comment by jbarrett** [comment]
I've made this [fix](https://github.com/duckduckgo/zeroclickinfo-spice/compare/4f967f62d2dedda14229746d2a72041fe0c25cc9)  ...but it seemingly throws an error on the empty spice response:

![image_fallback](https://cloud.githubusercontent.com/assets/444449/20348643/63b078ae-abfe-11e6-9b9a-6891a022c88e.png)

**Comment by jbarrett** [comment]
@bsstoner Are you available to review #3057? Thanks!
