### ISSUE TITLE
Net Worth: Working on making a pretty useful IA on DuckDuckGo. ~NOOB~ Please guide me.

### ISSUE THREAD

**Issue by HarshInvader** [duckduckgo/zeroclickinfo-spice#3048]
------
IA Page:  http://duck.co/ia/view/net_worth 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @HarshInvader

**Comment by HarshInvader** [comment]
How do I go about using the API? https://github.com/abresler/forbesListR

**Comment by DanielCornea** [comment]
Hi I find this interesting I would like to work on this

**Comment by pjhampton** [comment]
Hey guys,
Let's keep the issue pages for issues 👍 
DuckDuckHack has some really [great documentation](https://docs.duckduckhack.com/) which you should check out. There is also [some videos](https://vimeo.com/search?q=duckduckhack) that can guide you.
