### ISSUE TITLE
Maven: Add "library" "package", "repository" and "repo" to trigger words

### ISSUE THREAD

**Issue by jbarrett** [duckduckgo/zeroclickinfo-spice#3050]
### Description
As with, e.g. [MetaCPAN](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/MetaCPAN.pm#L13) adding additional triggers can help surface an IA more effectively.

This should possibly trigger on more terms, e.g.:

- maven repo
- maven repository
- maven package
- java package
- ...

## People to notify
@nicoulaj 

------ 

IA Page:  https://duck.co/ia/view/maven

**Comment by nalinbhardwaj** [comment]
This seems to have been fixed. Please close this issue. @moollaza

**Comment by pjhampton** [comment]
@nalinbhardwaj The PR is still open: https://github.com/duckduckgo/zeroclickinfo-spice/pull/3066 - It will automatically close once it's been merged 👍

**Comment by nalinbhardwaj** [comment]
@pjhampton That's weird. The terms seem to be working on duckduckgo.com:

https://duckduckgo.com/?q=maven+repo
https://duckduckgo.com/?q=maven+package

**Comment by pjhampton** [comment]
I think you are mistaken, @nalinbhardwaj. In your example `repo` and `package` are treated as the library name :+1:. Below are examples of the open issue. Don't worry though! I have pinged the developer :smile: hopefully he will finish this up soon.

Triggers: https://duckduckgo.com/?q=maven+spark&ia=software
Doesn't Trigger: https://duckduckgo.com/?q=maven+repo+spark

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
