### ISSUE TITLE
MetaCPAN: issues testing due to URL encode of ::, but no decode for JSON post

### ISSUE THREAD

**Issue by deserted** [duckduckgo/zeroclickinfo-spice#3055]
Testing the meta_cpan IA, have found that testing with DuckPAN returns no results due to `::` within module names to be sent to the MetaCPAN API still URL encoded, returning a false no result set. URL decode for variables used in JSON body POST needs to be done to accurately test with things like MetaCPAN, returning `%3A%3A` to `::`  

------
IA Page:  http://duck.co/ia/view/meta_cpan 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sahildua2305

**Comment by devanshdalal** [comment]
What's the status of this? I want to take this one.

**Comment by deserted** [comment]
hey @devanshdalal, sorry I should have come back to this sooner.

The issue unfortunately isn't on the Spice side, more investigation is needed but the double encode is occurring either within DuckPAN or on the DDG beta server, haven't had a chance to follow through on it yet.

**Comment by devanshdalal** [comment]
@deserted  no worries, have a nice day.

**Comment by moollaza** [comment]
Seems to be fixed
