### ISSUE TITLE
Have I Been Pwned: Seems to have stopped working

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#3058]
This doesn't seem to appear for our example queries:
* https://duckduckgo.com/?q=Have%20I%20Been%20Pwned%20test%40hotmail.com&ia=answer
* https://duckduckgo.com/?q=Pwned%20test%40hotmail.com&ia=answer

Reported via Twitter: https://twitter.com/rgggn/status/801395391270977536

------
IA Page:  http://duck.co/ia/view/pwned 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @b2ddg

**Comment by nkhanhtrn** [comment]
Funny thing is that on Codio the plugin is working fine. Maybe this is an internal issue @moollaza ?

**Comment by pjhampton** [comment]
Put back online for next release. If it doesn't come back online then there is an issue with the upstream most likely.
