### ISSUE TITLE
MetaCPAN: Not displaying for example queries

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#3062]
Not sure if it's a triggering issue or something else, but this is not showing for queries such as [cpan midi](https://duckduckgo.com/?q=cpan%20midi&ia=software) and [cpan json::xs](https://duckduckgo.com/?q=cpan%20json%3A%3Axs&ia=software)

cc @jbarrett 

------
IA Page:  http://duck.co/ia/view/meta_cpan 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sahildua2305

**Comment by jbarrett** [comment]
Thanks @tagawa! I suspect this was taken offline due to the issues fixed in #3053 - we can enable it again once this fix is released.

**Comment by tagawa** [comment]
@jbarrett Indeed - it looks like it's been re-enabled now that #3053  is merged and deployed. Thanks.
