### ISSUE TITLE
Graphical Calculator: actively developed?

### ISSUE THREAD

**Issue by conte91** [duckduckgo/zeroclickinfo-spice#3064]
Hello, are you actively working on this? If not, I would be glad to start helping!

------
IA Page:  http://duck.co/ia/view/graphical_calculator

**Comment by GuiltyDolphin** [comment]
@conte91 Feel free to make issues/PRs against the https://github.com/duckduckgo/zeroclickinfo-goodies/tree/gd/interactive-calculator branch on the Goodies repo - there are a list of to-dos in https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2848 as well as an overview of how it currently functions.

If you want to discuss ideas relating to this then please feel free to comment on that PR or ping me on Slack :)
