### ISSUE TITLE
OpenNIC DNS: Wonky display

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-spice#3075]
The front-end for this IA appears to be messed up (at least on FireFox 50.0.2):

(Unfortunately I cannot upload files at the moment, but try this search: https://duckduckgo.com/?q=opennic+42.42.42.42&ia=dns)

------
IA Page:  http://duck.co/ia/view/open_nic 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @cylgom

**Comment by cylgom** [comment]
Thank you for your report, I already pushed some changes to fix this a few months ago, but the PR seems frozen in an eternal validation phase : https://github.com/duckduckgo/zeroclickinfo-spice/pull/3031

**Comment by moollaza** [comment]
IA is no longer online.

**Comment by cylgom** [comment]
Hi, Why is it offline ? I can still access it on [beta](https://beta.duckduckgo.com/?q=opennic&t=hz&ia=dns). This is not the first time, something must be wrong :(

**Comment by moollaza** [comment]
It likely was taken offline because there was an API outage. I've re-enabled the IA.
