### ISSUE TITLE
Dictionary definition: doesn't always work

### ISSUE THREAD

**Issue by keyf4xdJ** [duckduckgo/zeroclickinfo-spice#3078]
When I search for a word, say 'define holistic' nothing shows up. Sometimes 'Define holistic' will work, or just 'holistic' will come up with a definition. I'm not sure how to provide an example of this, because after a few minutes an entry appears. It is a minor annoyance while reading to have to wait a couple of minutes to define a word!

To reproduce this just look up a relatively uncommon word.

This started happening around the beginning of November.

---
IA Page: http://duck.co/ia/view/dictionary_definition
Maintainer: @jagtalon

**Comment by keyf4xdJ** [comment]
I'm really not sure what's going on here, the last twenty words I've tried worked fine, but this feature hasn't been working all day!

**Comment by moollaza** [comment]
Closing. This doesn't seem to be happening anymore. Please re-open if necessary.
