### ISSUE TITLE
Bitcoin Addresses, Blocks 

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#3079]
More at link not working:
https://duckduckgo.com/?q=098e606cee543f86ccc90dccbfef6f5605b7eb654795896d95db44add0fd4431&kp=-1&kad=wt_WT&kl=wt-wt&t=&ia=answer

------
IA Page:  http://duck.co/ia/view/bitcoin 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jmg

**Comment by nalinbhardwaj** [comment]
Fixed via #3133. Please review.

**Comment by nalinbhardwaj** [comment]
Fixed via #3133. Also, transactions date time stamp was incorrect. It showed current time instead.

Example:
![screen shot 2017-02-07 at 11 05 40 pm](https://cloud.githubusercontent.com/assets/6984346/22703421/1dbea4f6-ed8a-11e6-988f-a5201bbf866b.png)

Please review. :)
