### ISSUE TITLE
Anime: No longer works after change from Hummingbird to Kitsu

### ISSUE THREAD

**Issue by eye-sigil** [duckduckgo/zeroclickinfo-spice#3082]
The change in domain and API broke this Spice and no triggers work.

------
IA Page:  http://duck.co/ia/view/anime 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @iambibhas

**Comment by gillesdemey** [comment]
Some documentation can be found over at https://forums.hummingbird.me/t/kitsu-api-documentation/33367 and http://docs.kitsu17.apiary.io/#introduction/json-api/general-info

Search string queries can be executed as such:

`https://kitsu.io/api/edge/anime?filter[text]=naruto`
