### ISSUE TITLE
Forecast: Show wind speeds on Beaufort scale

### ISSUE THREAD

**Issue by AlbertJP** [duckduckgo/zeroclickinfo-spice#3086]
I like the "weather utrecht" search query, it quickly shows me the weather in my location. However the wind speeds are in m/s, a unit which isn't used in The Netherlands, where wind speeds are always on the Beaufort scale. I don't really have an idea what "2 m/s", the current wind speed for my city, feels like. Would it be possible to add an option for wind speeds on the Beaufort scale?

(Right now the weather shows "clear" while it is very misty outside, but that is an unrelated issue ☺️)

------
IA Page:  http://duck.co/ia/view/forecast 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @himanshu0113

**Comment by PuneetGupta123** [comment]
Hello, I am a newbie. Can I work on this?

**Comment by moollaza** [comment]
Hey @AlbertJP 

DuckDuckHack is now in Maintenance Mode and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
