### ISSUE TITLE
Bitcoin: Replacement of Biteasy.com API due to end of life

### ISSUE THREAD

**Issue by alolis** [duckduckgo/zeroclickinfo-spice#3087]
Hello,

I would like to inform whoever is responsible for the bitcoin spice, that Biteasy.com is planning to pull the plug on January 20th and an immediate switch to a different API provider is required

Please check the following link for further info:
https://blog.biteasy.com/end-of-life

------ 

IA Page: https://duck.co/ia/view/bitcoin

**Comment by pjhampton** [comment]
Hey @alolis!

Thanks for bringing this to our attention! It seems like the API is still providing a response. Is the API just no longer being maintained but still running?

**Comment by DGMurdockIII** [comment]
A list of Block Explorers, more than 10 alternatives of blockchain.info
https://www.reddit.com/r/Bitcoin/comments/3fvoxm/a_list_of_block_explorers_more_than_10/

**Comment by pjhampton** [comment]
Oh, nice! @DGMurdockIII thanks for sharing 😄

**Comment by DGMurdockIII** [comment]
No problem just like to help out where I can

**Comment by nalinbhardwaj** [comment]
I'd suggest we switch to [blockr API](http://blockr.io/documentation/api), which has a nice API available and is run by CoinBase(so should be active for a long period). Although they don't mention any limits to API calls, for which we might need to [contact them](http://blockr.io/documentation/contact).

**Comment by pjhampton** [comment]
Ok, @nalinbhardwaj. That sounds like a good plan. If you need DDG to contact them, reach out to me and I can get something sorted

**Comment by tossj** [comment]
I've been looking at replacement APIs and [Blockexplorer](https://blockexplorer.com/api-ref) has most of the existing fields of the `record_data`. It doesn't have an endpoint to generate a QR code though, and no other API does except for Blockchain.com (but they are missing some `record_data` fields such as number of confirmations of a transaction).

So, instead, we could generate a QR code using a JS library, and then supply the image as a data URI image. The library that most JS QR code repositories use is https://github.com/kazuhikoarase/qrcode-generator/blob/master/js/qrcode.js. It is MIT licensed, and it is a little over 19KB when minified (and the license comments are still included). Would this library be allowed on DDG?

@pjhampton @moollaza

**Comment by moollaza** [comment]
I am closing this issue as the Instant Answer is offline and DuckDuckHack is currently in Maintenance mode.
