### ISSUE TITLE
Islamic Prayer Times: Unable to see the result

### ISSUE THREAD

**Issue by luthfii** [duckduckgo/zeroclickinfo-spice#3093]
I think the problem is the API is outdated. The new API is is simpler. http://muslimsalat.com/api/   

------
IA Page:  http://duck.co/ia/view/islamic_prayer_times 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @ozdemirburak

**Comment by ozdemirburak** [comment]
Just checked it. It's working as expected but seems like it's not online on the production server.

You can also see it's working on the beta as well: https://beta.duckduckgo.com/?q=Salat+Times+In+London&ia=islamicprayertimes

**Comment by luthfii** [comment]
Then how to fix it? Should we ask someone to help? 
I'm newbie here, but i'm eagerly to help

**Comment by ozdemirburak** [comment]
I think that's related to something internal. Probably, there was a time that API did not work and the system or someone from the team disabled the IA.

Ping @moollaza

**Comment by moollaza** [comment]
I've set it to be re-enabled. Should be online within the next few hours 👍
