### ISSUE TITLE
Forecast: "nyc weather" shows weather for London, England

### ISSUE THREAD

**Issue by alexpelan** [duckduckgo/zeroclickinfo-spice#3094]
Searching issues lead to some related discussion here: https://github.com/duckduckgo/zeroclickinfo-spice/pull/1359

For me, this is easily reproducible. Just type in "[nyc weather](https://duckduckgo.com/?q=nyc+weather)" and press enter. Seems like an obvious bug to me - 'nyc' is an unambiguous abbreviation for New York City. 

------
IA Page:  http://duck.co/ia/view/forecast 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @himanshu0113

**Comment by tagawa** [comment]
Thanks for submitting this @alexpelan - I got the same results for London. Interestingly reversing the query to "[weather nyc](https://duckduckgo.com/?q=weather+nyc)" shows the correct result.

**Comment by bsstoner** [comment]
Thanks for the report. There are some triggering issues with weather that we're looking into internally. Closing because I don't think we can do anything here.
