### ISSUE TITLE
Currency Conversion: BTC Ticker wrong

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#3096]
https://duckduckgo.com/?q=btc%20usd

We're getting a lot of complaints that the data is wrong:
_"The ticker shows wrong data on your site. It's good over at XE, Pls. fix it!"_
_"Your bitcoin price ticker is broken, while it's working at XE.com"_

It seems like it's right to me? Could use a second set of eyes, maybe I'm missing something.

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by MrChrisW** [comment]
This looks right to me. I think we cache the request for 5mins so maybe that's caused some confusion.
