### ISSUE TITLE
JavaScript: Improving the NPM Package Search

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-spice#3098]
It seems that this is a popular IA, but is failing to trigger on a lot of queries in the search space. It currently represents [1.81% of the search space](https://forum.duckduckhack.com/t/javascript-search-overview/94/14). We can improve this. I think this is because of:

  1) Triggers
  2) Spaces in package names
  3) People using DDG as if it were npm's onsite search engine.

The final point is important here. It seems there aren't a lot of queries looking for something specific, but rather a suggestion. ie. `json pretty print npm` or `npm json web token`. If we update the API endpoint to the below link, this should solve this problem and the specifics will still show up.

http://npmsearch.com/query?q=json+web+tokens&fields=name,description,repository,homepage,author

Documentation: https://github.com/nodesource/npmsearch

This should make it work just like the [CPAN spice](https://duckduckgo.com/?q=metacpan+WWW%3A%3ADuckDuckGo&ia=software&iai=9). 

One thing I have noticed about this API though, is it doesn't direct a link back to npm, rather both *homepage* and *repository* return the github source which is no good. Appending the package name to the URL `https://www.npmjs.com/package/` will redirect that though. 

------
IA Page:  https://duck.co/ia/view/npm
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @remixz

**Comment by remixz** [comment]
👍  It'd be great to improve this! My recommendation would be to use https://npms.io/, as that's what's powering the search on npm's website. The API docs are here: https://api-docs.npms.io/ Their API also includes a link to the npm page, so that solves that little issue of npmsearch not including it.

Unless someone else is interested, I think I could make these improvements soon!

**Comment by pjhampton** [comment]
Sweet! That would be awesome @remixz 
I will let you use your professional judgement on the source

**Comment by pjhampton** [comment]
Hey @remixz, just checking in 😄  How are you getting on with this?

**Comment by adampolar** [comment]
Hi, is this still available to take? I'd like to take it if so. I'm new to open source but I've made an attempt already which roughly matches the CPAN spice.
