### ISSUE TITLE
Timer: Allow setting alarms (e.g. "alarm at 5pm")

### ISSUE THREAD

**Issue by M-Schiller** [duckduckgo/zeroclickinfo-spice#3100]
It would be nice if I could enter something like the query in the title ("alarm at 5pm") and have the timer calculate the time difference  between now and the requested time, set up the timer and start it for easier access.

------
IA Page:  http://duck.co/ia/view/timer 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattr555

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
