### ISSUE TITLE
Libraries.io: Comprehensive Package Manager Search 

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-spice#3101]
## Description

There is still a lot of package managers that we don't any have any Spice / Fathead for. This includes:

  - Go Search
  - WordPress Plugins Search
  - Sublime Plugins Search
  - and so on...

Using this API should [hopefully] improve coverage of a few of the languages and be fairly easy to maintain in the long run.

## People to notify
   - @moollaza 
   - @pjhampton

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [x] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

------
IA Page:  http://duck.co/ia/view/libraries 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by karuppiah7890** [comment]
@pjhampton Yeah, I actually tried a bit of code. And then got stuck in some places and then stopped after that. And I don't think I can continue that work immediately.

**Comment by karuppiah7890** [comment]
@pjhampton Give me a day. And I will update you more on this and see what I did. It's been two months and I don't remember a thing now.

**Comment by pjhampton** [comment]
Hey @karuppiah7890, 

How are you getting on? 😄

**Comment by karuppiah7890** [comment]
Ah, I was caught up. Yet to try renaming all files and trying. I planned to use the IA name of your IA page just for checking how the Duckpan server works and if my code runs. But I didn't do it.

By the way, my code is entirely different. It simply searches for libraries in all languages given a "description of the functionality", hoping libraries.io searches even description attribute in it's search API - most probably it does.

But your IA page mentions that it's for searching libraries from different languages, using their names. And looks like we gotta write code from scratch. Or does it search based on description too ? And show many results

**Comment by pjhampton** [comment]
Hey @karuppiah7890 

That's awesome 😄 , but yeah we want to go the direction I initially stated. This is an effort to improve the overall [coverage in the programming mission](https://forum.duckduckhack.com/t/duckduckhack-getting-started/53). So we want to create a new spice rather than do what you were originally doing.

So the idea is that you should have triggers named after each platform. When a platform name is specific, we can use that in the API call to ensure we only get packages that exist on that platform. E.g.

### Examples

- `go get math` should search the "Go Packages" platform for “math” packages
- `SwiftPM nosql` should search the “SwiftPM” platform for “nosql” packages

### Languages / PMs that need support:

- go
- WordPress
- Clojars
- Atom
- Homebrew
- Elm
- Scala
- Dart
- Groovy
- Emacs

### Don't need support:

- NPM
- Hackage
- CocoaPods
- SublimeText
- CPAN
- RubyGems
- Bower
- PyPi
- Maven
- Packagist
- NuGet

**Comment by karuppiah7890** [comment]
Ah, Nice. I get it now :smile:

**Comment by karuppiah7890** [comment]
So, not just languages, but package managers too. And we are searching for packages based on exact name or based on a domain or description, like "math" and "nosql" packages

**Comment by pjhampton** [comment]
@karuppiah7890  Exact names are how we have been handling it in the past. Check out these two IAs for inspiration 👍 

- https://duck.co/ia/view/meta_cpan
- https://duck.co/ia/view/npm

**Comment by moollaza** [comment]
@pjhampton @karuppiah7890 I made a couple changes to the platforms we need support for.

I added in Bower and PyPi -- I thought we had a Bower Spice but I was wrong, and @pjhampton and I discussed that we'd like to migrate PyPi from a static Fathead to a Spice. We'll start by testing them and if the Spice shows promise we'll deprecate the Fathead 👍

**Comment by pjhampton** [comment]
Hey @karuppiah7890! 😃  Any update?

**Comment by moollaza** [comment]
@duckduckgo/duckduckhack-contributors would anyone be interested in taking this up and greatly expanding the DDG package search capabilities? We'd love to see this go live!

**Comment by karuppiah7890** [comment]
@pjhampton Hey, sorry. No. No updates. And this is high end for a newbie like me.

**Comment by knowledgewarrior** [comment]
Ok, ok. Twist my arm :)  I'll make this higher priority than the ember.js fathead.

**Comment by pjhampton** [comment]
🎸 🤘 Thanks @knowledgewarrior

**Comment by andrew** [comment]
Hi @andrew from https://libraries.io here, this is awesome, do let me know if there's anything I can do to help!

We're also rolling out search across gitlab and bitbucket repositories at the moment if that's useful?

**Comment by pjhampton** [comment]
Awesome! Thanks for reaching out @andrew, and thanks for libraries.io! It's awesome!

**Comment by knowledgewarrior** [comment]
@andrew Re:  https://libraries.io/api - rate limiting.  It would be nice to have an account each for duckduckgo (production) and duckduckhack (dev/test) with > 60 reqs/min limit.  What's the maximum for setting in production?  @pjhampton or @moollaza would know what the expected reqs/min would be.  Dev/Test could be set just a little higher - say 120.  Thanks in advance!

**Comment by knowledgewarrior** [comment]
I opened:  https://github.com/librariesio/libraries.io/issues/1226

to obtain api keys for test and prod.  Is there a doc link for using secrets?  I'm not sure I've seen a doc on how duckduckgo uses secrets like passwords, api keys, etc in IAs AFAIK...

**Comment by pjhampton** [comment]
Hey @knowledgewarrior! @moollaza wrote some documentation on this. You can see it here: https://docs.duckduckhack.com/backend-reference/api-reference.html#api-keys
