### ISSUE TITLE
GitHub: Not showing for explicit github repo query

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#3103]
User Feedback:
**usbarmory mac os x github**
[https://duckduckgo.com/?q=usbarmory%20mac%20os%20x%20github&kp=1&kad=wt_WT&kl=wt-wt](https://duckduckgo.com/?q=usbarmory%20mac%20os%20x%20github&kp=1&kad=wt_WT&kl=wt-wt)
_I'd expect to see this here https://github.com/inversepath/usbarmory/wiki/Host-communication_

------
IA Page:  http://duck.co/ia/view/github 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by moollaza** [comment]
Looks like this is a relevancy issue.

Without the USBArmory we still show that result: https://duckduckgo.com/?q=mac+os+x+github&ia=software

However, without the `mac os x` we show the correct result:
- https://duckduckgo.com/?q=usbarmory+github&ia=software
