### ISSUE TITLE
Nutrition: Wanted result in specific serving size

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#3104]
User Feedback:
**green beans calories per 100 g**
[https://duckduckgo.com/?q=green%20beans%20calories%20per%20100%20g&kp=1&kad=wt_WT&kl=wt-wt](https://duckduckgo.com/?q=green%20beans%20calories%20per%20100%20g&kp=1&kad=wt_WT&kl=wt-wt)
_when adding per 100 gram, a result per 10 is displayed not per 100 g_   

------
IA Page:  http://duck.co/ia/view/nutrition 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @bsstoner

**Comment by pjhampton** [comment]
Hmm, I'm not sure if v1.1 of their API supports custom quantities from this [Google Docs Spreadsheet](https://docs.google.com/spreadsheets/d/1jZSa039OfpQOiRzaS980nPKCvVe2TRKRPZk7ZbaH7kE/edit#gid=0)

**Comment by pjhampton** [comment]
Closing due to 2 open issues:

- https://github.com/duckduckgo/zeroclickinfo-spice/issues/3195
- https://github.com/duckduckgo/zeroclickinfo-spice/issues/3196
