### ISSUE TITLE
GitHub: Ability to surface relevant github issues

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#3105]
This might be a new/different IA, but there's a lot of desire for us to do a better job surfacing github issues in the results when relevant to the query. A few examples from recent feedback:

**rails invalid authenticity token internet explorer 11**
[https://duckduckgo.com/?q=rails%20invalid%20authenticity%20token%20internet%20explorer%2011&kp=1&kad=wt_WT&kl=us-en](https://duckduckgo.com/?q=rails%20invalid%20authenticity%20token%20internet%20explorer%2011&kp=1&kad=wt_WT&kl=us-en)
_I wish I would've gotten to this link, which was Google's number 3: https://github.com/rails/rails/issues/21948_

**orphaned pod but error occured during reading volume dir from disk**
[https://duckduckgo.com/?q=orphaned+pod+but+error+occured+during+reading+volume+dir+from+disk&t=h_&ia=web
](https://duckduckgo.com/?q=orphaned+pod+but+error+occured+during+reading+volume+dir+from+disk&t=h_&ia=web
)
_run that same query with !g and observe the links to github and even into irc archiving sites_

------
IA Page:  http://duck.co/ia/view/github 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by pjhampton** [comment]
Closing due to https://github.com/duckduckgo/zeroclickinfo-spice/issues/3170
