### ISSUE TITLE
Airlines: Not triggering

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#3106]
There seem to be a lot of cases where the IA isn't triggering:

https://duckduckgo.com/?q=DL3313
https://duckduckgo.com/?q=Flight+TK1986
https://duckduckgo.com/?q=aa+729

------
IA Page:  http://duck.co/ia/view/airlines 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @amoraleda

**Comment by moollaza** [comment]
This IA is currently offline, our internal tests are failing so I'm unable to re-enable it as it will be automatically disabled again.

**Comment by moollaza** [comment]
This is back online and working:

- https://duckduckgo.com/?q=aa+729&ia=flights
- https://duckduckgo.com/?q=Flight+TK1986&ia=flights
