### ISSUE TITLE
Forecast: Default to C for people outside the US

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#3107]
We're defaulting to fahrenheit and get consistent complaints from people outside the US that don't like it. Ideally the default should be based on location.

**sydneys current weather**
[https://duckduckgo.com/?q=sydneys%20current%20weather&kp=1&kad=wt_WT&kl=wt-wt](https://duckduckgo.com/?q=sydneys%20current%20weather&kp=1&kad=wt_WT&kl=wt-wt)
_"In the south pacific we use celsius not fahrenheit"

**nanaimo weather**
[https://duckduckgo.com/?q=nanaimo%20weather&kp=1&kad=wt_WT&kl=wt-wt](https://duckduckgo.com/?q=nanaimo%20weather&kp=1&kad=wt_WT&kl=wt-wt)
_"Why in hell would you give temperature in Fahrenheit by default at a Canadian location? You DO realise that only four countries in the world use Fahrenheit these days, and Canada isn't one of them?"_

**wheather berlin**
[https://duckduckgo.com/?q=wheather%20berlin&kp=1&kad=wt_WT&kl=wt-wt](https://duckduckgo.com/?q=wheather%20berlin&kp=1&kad=wt_WT&kl=wt-wt)
_"Not everyone lives in USA."_

------
IA Page:  http://duck.co/ia/view/forecast 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @himanshu0113

**Comment by bsstoner** [comment]
Another complaint here:
**hourly weather white rock bc**
[https://duckduckgo.com/?q=hourly%20weather%20white%20rock%20bc](https://duckduckgo.com/?q=hourly%20weather%20white%20rock%20bc)
_Comment: When giving local weather results in Canada, results should be given in Metric units (degrees in Celcius, etc.)_

**Comment by nalinbhardwaj** [comment]
I think it's a better idea if the IA detects a person's location(using the country setting) instead of the location of the forecast. A lot of travellers may search for weather out of town and get results in an unexpected format the other way. Thoughts?

**Comment by nalinbhardwaj** [comment]
The IA actually checks the user's settings to decide the unit. I don't see why we should decide unit based on location in query, a lot of travellers could use this IA too.

Thoughts?

**Comment by bsstoner** [comment]
It would be a smarter default for people that haven't touched the settings (which is the vast majority of users).

I think it would be based on user country, not location in the query. Similar to what we did for Currency in #3072

**Comment by nalinbhardwaj** [comment]
@bsstoner Hmm, that makes sense, I'll make a PR soon. I think though it is a good idea that DDG auto-changes those settings based on location(nearly all people in Europe/Asia use metric).

**Comment by nalinbhardwaj** [comment]
Fixed via #3151. Please review
