### ISSUE TITLE
Thesaurus: Only show the IA when we have the result the user asked for

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#3111]
This Instant Answer triggers on the word "antonym", but antonyms are not always available. In those cases, we end up showing synonyms and related words. This should be considered a false-positive result, because it's not what the user asked for. In cases like this, where we don't have what the user requested, we should not show anything.

E.g. https://duckduckgo.com/?q=antonyms+of+shy&ia=thesaurus

------
IA Page:  http://duck.co/ia/view/thesaurus 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @lactose

**Comment by nkhanhtrn** [comment]
I'll give it a try. Although in terms of UX it's better to notify the user that the antonym is not found.
