### ISSUE TITLE
Track Lister: Display the tracks in a given album 

### ISSUE THREAD

**Issue by Swailem95** [duckduckgo/zeroclickinfo-spice#3126]
Similar to what Google is [already doing](https://encrypted.google.com/search?hl=en&q=dark%20side%20of%20the%20moon%20track%20listing). I use this feature often and I believe it would be a useful addition to DDG. 

------
IA Page:  http://duck.co/ia/view/track_lister 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Swailem95

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
