### ISSUE TITLE
Currency Conversion: Trigger more for bitcoin queries

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#3129]
I don't know if it should be this IA or one of the others, but there's a bunch of queries where people are looking for the price of bitcoin and we're not triggering:

[https://duckduckgo.com/?q=bitcoin+price](https://duckduckgo.com/?q=bitcoin+price)
[https://duckduckgo.com/?q=bitcoin+value](https://duckduckgo.com/?q=bitcoin+value)
[https://duckduckgo.com/?q=price+of+bitcoin](https://duckduckgo.com/?q=price+of+bitcoin)

User Feedback:
_"These searches should yield the price up top without additionally clicking on a link to find it."_

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by nalinbhardwaj** [comment]
Queries of all formats `currency`+price/value don't get triggered.

https://duckduckgo.com/?q=usd+price
https://duckduckgo.com/?q=usd+value
https://duckduckgo.com/?q=value+of+usd

**Comment by adityatandon007** [comment]
@moollaza . Can I give it a try

**Comment by pjhampton** [comment]
Thanks @adityatandon007

**Comment by moollaza** [comment]
`bitcoin value` has been taken care of in #3259

**Comment by moollaza** [comment]
@adityatandon007 you can add "price" as a keyword using the same approach I did, by modifying the `$keyword_qr`. I think you just need to add `|price` beside `|value` 👍
