### ISSUE TITLE
Forecast: San Antonio, TX

### ISSUE THREAD

**Issue by Rick-2CA** [duckduckgo/zeroclickinfo-spice#3130]
Several query methods for San Antonio, TX show results for San Isidro, Veracruz:
  weather <local zip codes>
  weather san antonio
  weather san antonio, tx

However the proper forecast results if you do:
  weather
  weather "san antonio"

I wasn't able to replicate the behavior with several other "San" city names tested.

------
IA Page:  http://duck.co/ia/view/forecast 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @himanshu0113

**Comment by bsstoner** [comment]
This appears to be fixed now.
