### ISSUE TITLE
AlternativeTo: Not triggering/working

### ISSUE THREAD

**Issue by valdotdev** [duckduckgo/zeroclickinfo-spice#3131]
AlternativeTo instant answer not working. No suggestions are given for any app that you type in. Even with the example triggers like "Alternative To Notepad", etc.

------
IA Page:  http://duck.co/ia/view/alternative_to 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @vikashvverma

**Comment by Troupal** [comment]
Hello !
It is true that it is long enough that the instant answer is no longer working, someone would know why and how to fix it? It really is a shame (it is a pity, sorry, I'm french ^^) because it was really convenient. Thank you in advance for your response !

**Comment by ManrajGrover** [comment]
@Troupal The [API](http://alternativeto.net/about/api/) is down. Hence, it is not triggering. If you know any alternate api, please share it with us. 😄

**Comment by Troupal** [comment]
@ManrajGrover Ok ! And sorry, I do not know, alas, no other API to share with you… ^^

**Comment by pjhampton** [comment]
@ManrajGrover is this an End of Life situation?

**Comment by ManrajGrover** [comment]
@pjhampton Looks so for now. We can remove the IA for now till we find an alternate source for serving this.
