### ISSUE TITLE
Forecast: Text overlapping in the tile

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#3132]
https://duckduckgo.com/?q=hourly%20weather%20white%20rock%20bc

![screen shot 2017-02-06 at 10 40 15 am](https://cloud.githubusercontent.com/assets/126358/22653849/baea1de2-ec58-11e6-8da0-8fc1287acd7e.png)

------
IA Page:  http://duck.co/ia/view/forecast 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @himanshu0113

**Comment by pjhampton** [comment]
Closing in favour of https://github.com/duckduckgo/zeroclickinfo-spice/issues/3167
