### ISSUE TITLE
IsItUp: False positive triggering

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#3136]
It shouldn't trigger here:
https://duckduckgo.com/?q=t-online.de

<img width="1224" alt="screen shot 2017-02-11 at 8 06 02 am" src="https://cloud.githubusercontent.com/assets/126358/22853963/03cd5b42-f031-11e6-925e-177d9e23e466.png">

------
IA Page:  http://duck.co/ia/view/is_it_up 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @rasikapohankar

**Comment by rasikapohankar** [comment]
I'll fix this in #3135. It seems to be triggering for any website name having the trigger words :confused:

**Comment by andschwa** [comment]
Ah, yeah, another example: `isitdown` triggers it (but awesome project!).
