### ISSUE TITLE
Currency Conversion: Not triggering when amount's after currency

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#3139]
**CHF 2.95 in eur**
[https://duckduckgo.com/?q=CHF%202.95%20in%20eur](https://duckduckgo.com/?q=CHF%202.95%20in%20eur)
_"why don't covnert :("_

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by bsstoner** [comment]
This works: https://duckduckgo.com/?q=2.95+CHF+in+eur

**Comment by pjhampton** [comment]
Closing this because of https://github.com/duckduckgo/zeroclickinfo-spice/issues/3165
