### ISSUE TITLE
Gitbook Status: 

### ISSUE THREAD

**Issue by renato67** [duckduckgo/zeroclickinfo-spice#3142]
what markup  pre compiler use gitbook?
------
IA Page:  http://duck.co/ia/view/git_book_status 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @qqq3

**Comment by gautamkrishnar** [comment]
The IA doesnt use any markup compilers... Please check the gitbook documentation to know any details about it....
