### ISSUE TITLE
Currency Conversion: doesn't recognize "rubles"

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#3147]
**500 rubles in dollars**
[https://duckduckgo.com/?q=500%20rubles%20in%20dollars](https://duckduckgo.com/?q=500%20rubles%20in%20dollars)
_Comment: it would be very helpful to have currency converter widgets for queries like this one, thank you, and keep up the good work._   

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by pjhampton** [comment]
Closing due to #3168
