### ISSUE TITLE
NPM Search: links to wrong documentation page

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#3148]
**npm publish**
[https://duckduckgo.com/?q=npm%20publish](https://duckduckgo.com/?q=npm%20publish)
_Comment: the instant answer links to the wrong documentation page_   

------
IA Page:  http://duck.co/ia/view/npm 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @remixz

**Comment by pjhampton** [comment]
Hey @bsstoner, 

This isn't http://duck.co/ia/view/npm, it's http://duck.co/ia/view/npm_cli (Fathead for CLI). We are aware of this issue and have a patch ready to go (https://github.com/duckduckgo/zeroclickinfo-fathead/pull/800). Closing as there is nothing we can do here.

**Comment by bsstoner** [comment]
Thanks 👍
