### ISSUE TITLE
Forecast: UI in dark mode inconsistent with the theme

### ISSUE THREAD

**Issue by nalinbhardwaj** [duckduckgo/zeroclickinfo-spice#3150]
### Description

The hover state of the forecast makes URLs blue. That makes sense when the theme is the default one, but in dark mode, it should just underline it(similar to what regular search links look like).

I'll be making a PR fixing this in a few hours.

## Steps to recreate

- Change theme to dark
- Search "weather"
- Hover over links

## People to notify

@himanshu0113 

---

Instant Answer Page: https://duck.co/ia/view/forecast

**Comment by adityatandon007** [comment]
@nalinbhardwaj I was able to recreate the bug as you mentioned and you were right in dark theme the url on hover goes blue

**Comment by nalinbhardwaj** [comment]
@adityatandon007 Thanks for the verification. Will make a PR soon.
