### ISSUE TITLE
Places: Overtriggering for local search

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#3155]
**Search query:** [Japanese Cultural and Community Center of Northern California](https://duckduckgo.com/?q=Japanese%20Cultural%20and%20Community%20Center%20of%20Northern%20California&kp=1&kad=wt_WT&kl=wt-wt)

**Issue:** IA shows unrelated business/amenities in my local area, not Northern California.

------
IA Page:  http://duck.co/ia/view/maps_places 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nilnilnil

**Comment by bsstoner** [comment]
We're addressing this internally
