### ISSUE TITLE
Tor Node Instant Answer: Not working 

### ISSUE THREAD

**Issue by Someguy123** [duckduckgo/zeroclickinfo-spice#3158]
Didn't see an issue, so I decided to open one. When attempting to use the search terms, nothing happens.   

------
IA Page:  http://duck.co/ia/view/tor_node 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mogigoma

**Comment by pjhampton** [comment]
It seems like the production state is [set to offline](https://duck.co/ia/view/tor_node/json). It must have got knocked offline.

cc @moollaza

**Comment by pjhampton** [comment]
I have set this to online. Hopefully it will go out in the next release. If not, there is a deeper issue with the api that we will have to investigate.

**Comment by moollaza** [comment]
I'll have to re-enable internally @pjhampton 👍 

Need to ensure the internal tests pass as well otherwise it will go offline again

**Comment by moollaza** [comment]
OK re-enabled 👍
