### ISSUE TITLE
ExpandURL: Find a better URL expanding API

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#3164]
Safari and Chrome claim that the domain https://untiny.me contains malware. We should stop using this API service in favour of one that is safer for our users.

As well, we received some feedback about unsupported domains (e.g. amp.gs) which the Untiny API cannot expand.

------
IA Page:  http://duck.co/ia/view/expand_url 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @adman

**Comment by moollaza** [comment]
I am going to disable the IA for now.

**Comment by BillyBarbaro** [comment]
Don't know if alternatives have been discussed elsewhere, but I came across this site.  [Link Expander](http://www.linkexpander.com/api).

**Comment by BillyBarbaro** [comment]
It looks like an alternative to finding an API would be to use perl on the backend to make a request to the url, then just grab the url from the header of the redirect.  This answer on [StackOverflow](http://stackoverflow.com/questions/7153096/how-can-i-un-shorten-a-url-using-python/7153185#7153185) describes a way to do it using Python.  This would prevent the need to hit someone else's API.  What are your thoughts on this?

**Comment by moollaza** [comment]
> What are your thoughts on this?

@BillyBarbaro Unfortunately we don't allow Goodies to make web requests. If we did, we'd have to wait, or stop the Goodie from executing in order to display the results as fast as we'd need to.

This is why we prefer APIs -- because we load the SERP, and show the link results, while the client makes an API call. Once the response is returned we can just add the IA to the page

**Comment by BillyBarbaro** [comment]
That makes sense.  I found a couple other options.

1.  [unshorten.me](https://unshorten.me/api) looks like they provide a pretty nice API.  They are rate limited, but they say to contact them if you need to make more requests.  I assume it would be up to someone on the team like @moollaza to reach out to them?

2. [URL Expander](http://urlex.org) offers an API it looks like we could use; however, I think we would need to get access to a Pro account.  Someone would need to contact them to see if they'd be willing to let DDG have access.

Let me know what you think of the options and what else I can do to help on this one.

**Comment by ellisonleao** [comment]
Hey guys, do we need a third party api or DDG can have its own?

**Comment by moollaza** [comment]
>I assume it would be up to someone on the team like @moollaza to reach out to them?

@BillyBarbaro it doesn't have to be. Would you like to reach out to unshorten.me to see if they're willing to increase the limit for us?

FWIW, the "malware" warning is gone from Untiny.me so I feel like we may not need to replace it unless these alternatives prove to be better

>Someone would need to contact them to see if they'd be willing to let DDG have access.
Do you mean get us free access? Our policy is to only use Free APIs so paid APIs are out of the question. 

>Hey guys, do we need a third party api or DDG can have its own?

@ellisonleao yes we rely on third party services -- we don't build/host our own APIs for IAs.

@BillyBarbaro @ellisonleao However, it may be possible to use https://stdlib.com/ (or something similar) to build an endpoint we can use as an API, but I'm not sure it will work.

I think that should be our last resort.

**Comment by BillyBarbaro** [comment]
Sure, I can reach out and at least see what they're willing to say.  What would be an appropriate limit to ask for?

Additionally, it looks like untiny.me is still marked as malicious by safari.

**Comment by moollaza** [comment]
> What would be an appropriate limit to ask for?

It's hard to say, but right now this IA isn't triggering very often. It appears to trigger ~500 times per day, but only shows a result < 200. I guess if they could allow us 1000 calls per day that should suffice. 

>Additionally, it looks like untiny.me is still marked as malicious by safari.

Dang. It looks like it's actively maintained so we could also check with the creator if he's able to fix that.

**Comment by ellisonleao** [comment]
> Dang. It looks like it's actively maintained so we could also check with the creator if he's able to fix that.
![screen shot 2017-03-17 at 12 06 03 am](https://cloud.githubusercontent.com/assets/178641/24027338/8bf51cf6-0aa5-11e7-8554-5e0d64067aed.png)

It is marked as malicious on Chrome as well

**Comment by Adman** [comment]
@moollaza when you decide which API will we use, I'm able to fix that.

**Comment by moollaza** [comment]
> It is marked as malicious on Chrome as well

@ellisonleao yup I'm now seeing that again. ☹️

**Comment by BillyBarbaro** [comment]
Quick update on this.  I got in contact with the owner of the site and he's willing to give us 1000 unique requests per day.  Any request we make that's already cached won't count as part of those 1000.

@moollaza Where do I put the key so it's secure, but I can make the necessary modifications to the existing Spice and start testing it?

**Comment by moollaza** [comment]
> I got in contact with the owner of the site and he's willing to give us 1000 unique requests per day.

@BillyBarbaro this is excellent news! Thanks so much for getting in touch on our behalf. Nicely done 💯 

> Where do I put the key so it's secure, but I can make the necessary modifications to the existing Spice and start testing it?

@BillyBarbaro I will need to manually add the new API key to our systems before it will work on Beta.

Would it be possible to have them send me a production use API Key?

moollaza@duckduckgo.com

Thanks again!

**Comment by eladkarako** [comment]
<h3><code>http&#x003A;//9inchurl.com/api.php?url=&#x005F;&#x005F;&#x005F;</code> and <code>https&#x003A;//unshorten.me/s/&#x005F;&#x005F;&#x005F;</code></h3>

I use them in https://github.com/eladkarako/chrome_extensions/tree/store/Remove-Redirects-Plus
I try to resolve them offline, then locally (HTTP 302...), then one and then the other API (if needed).

I know this is old (and closed) issue but it still comes up in Google, 
so I've thought it might be useful to someone...
