### ISSUE TITLE
Currency Conversion: Enable Triggering for symbol before amount

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-spice#3165]
### Description

Based on [user feedback](https://github.com/duckduckgo/zeroclickinfo-spice/issues/3139), we have found that `<amount> <symbol> to <symbol>` triggers like in **Screenshot 1**. But doesn't trigger when the query is `<symbol> <amount> to <symbol>` as seen in **Screenshot 2**. 

### Screenshot 1
![screen shot 2017-03-02 at 12 05 14 pm](https://cloud.githubusercontent.com/assets/8960296/23506517/953fad00-ff40-11e6-9db9-8fd129fb29eb.png)

### Screenshot 2
![screen shot 2017-03-02 at 12 05 31 pm](https://cloud.githubusercontent.com/assets/8960296/23506520/96949f76-ff40-11e6-9567-aa478e4fb400.png)

In this issue, we need someone to alter the [Currency Conversion IA](http://duck.co/ia/view/currency) to support this type of query. 

## Get Started
- [x] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: http://duck.co/ia/view/currency

**Comment by BillyBarbaro** [comment]
@pjhampton I'd like to take a go at this one!

**Comment by pjhampton** [comment]
Awesome! Thanks @BillyBarbaro

**Comment by BillyBarbaro** [comment]
@pjhampton Went ahead and made the change and it looks like all the existing unit tests are passing.  Just wanted to clear up a quick ambiguity before I finished things up.

There's a test for the query "euro 400 jpy" which has the correct result as converting 400 jpy into euros; however, with the addition of this new trigger, the query could also be interpreted as converting 400 euro to jpy.  Which one should the IA display in this case?

**Comment by pjhampton** [comment]
I think we should keep the test for **euro 400 jpy**. As there have been no complaints from the users to date (AFAIK), it's meeting their needs. I'm not entirely sure I'm seeing the prediciment. `Original Currency> -> <New Currency>` is the same as **euro 400 jpy**. `euro 400` = `<original currency>`, `jpy` = `<new currency>`

**Comment by BillyBarbaro** [comment]
The current version of the IA would convert 400 jpy to euros on this query.  But if we add the ability to have the currency before the amount, the result would be converting 400 euros to jpy.

Original: `euro ? = 400 jpy`
New Triggering: `euro 400 = ? jpy`

I'm planning to keep the test, but if this is how we intend to interpret the query, I would need to change the expected value.

**Comment by pjhampton** [comment]
Yeah, I would say `euro 400 = ? jpy` makes much more sense than `euro ? = 400 jpy`. Also, based on user feedback, this is what the users want. 😄
