### ISSUE TITLE
Reformat Geometry Formula

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-spice#3166]
### Description

Based on [user feedback](https://github.com/duckduckgo/zeroclickinfo-spice/issues/3138), it could be a good idea to format the formula in the Geometry IA. Currently it reads:

```
V=4/3pi()r^3.
```

But to make things clearer, it should read:

```
V = (4/3) * pi()r^3.
```

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: http://duck.co/ia/view/geometry

**Comment by nalinbhardwaj** [comment]
Not completely sure, but I think I read that we can use libraries like mathjax in spices. If so, I think the best idea might be to completely shift to latex for such IAs. Thoughts?
