### ISSUE TITLE
Currency Conversion: RUB aliases needed

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-spice#3168]
### Description

Based on user feedback, the Currency Conversion IA is not reaching the way some people are searching for conversions. [One example](https://github.com/duckduckgo/zeroclickinfo-spice/issues/3147) was **Russian Rubbles => US Dollars**.

#### Screenshot 1 (Good 👍 )

![screen shot 2017-03-02 at 5 23 11 pm](https://cloud.githubusercontent.com/assets/8960296/23519064/864195d4-ff6d-11e6-90d6-5bd6e920601d.png)

#### Screenshot 2 (Not so good 👎 )

![screen shot 2017-03-02 at 5 22 46 pm](https://cloud.githubusercontent.com/assets/8960296/23519067/8ac76e4e-ff6d-11e6-8e85-1d2dda400773.png)

The developer should research how users would typically search for these type of conversions and update the [Currency Names file](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/currency/currencyNames.txt).

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [x] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: http://duck.co/ia/view/currency

**Comment by BillyBarbaro** [comment]
By the looks of the Currency Names File, it appears there is both the "belarus ruble" (line 24) and the "russia ruble" (line 120).  My guess is the original author didn't include rubles as a keyword for either to avoid the ambiguity.  Do we want to just go ahead and assume a search for "ruble" alone means the Russian Ruble?  Seems to me like that would be the more common search for users, but I don't know if there's any search data to back that up.

**Comment by pjhampton** [comment]
Hmm, well-spotted @BillyBarbaro! Based on the feedback that we received the user was expecting the conversion from Russian Rubles. And not to be copy cats, but Google automatically assumes Russian Rubles:

![screen shot 2017-03-08 at 10 52 08 am](https://cloud.githubusercontent.com/assets/8960296/23701139/5ff012b4-03ed-11e7-9219-b8685b0418de.png)
