### ISSUE TITLE
Github: Extend IA to search issues

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-spice#3170]
### Description

Based on [user feedback](https://github.com/duckduckgo/zeroclickinfo-spice/issues/3105), we're not doing a good enough job at surfacing relevant Github issues. I propose we extend the existing Github Instant Answer to search for issues or creating a new one. The first approach, although not perfect, would be to list issues from the Github API - https://api.github.com/search/issues?q=rails%20invalid%20authenticity and list relevant issues to the user. 

Currently, there are two separate IAs. One for the [Github status](https://duck.co/ia/view/github_status) and another for [Github Projects](https://duck.co/ia/view/github). 

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/github

**Comment by ManrajGrover** [comment]
@pjhampton I can take this one up. :smile: Would this be a separate IA or will be combined with [Github IA](https://duck.co/ia/view/github)?

**Comment by pjhampton** [comment]
Awesome! Thanks so much @ManrajGrover!! 

> Would this be a separate IA or will be combined with Github IA?

Either is fine, but advancing the current IA makes the most sense 😄

**Comment by ManrajGrover** [comment]
@moollaza @pjhampton Given Github IA triggers on `triggers startend => "github"` which I feel is generic considering it searches for repositories only. If one adds `github issues` as trigger for this issue, it will trigger both IAs. Should we fix the former?

**Comment by moollaza** [comment]
> Should we fix the former?

@ManrajGrover yeah that sounds find. We can make a separte PR to prevent the GitHub Spice from triggering on "github issues" 👍
