### ISSUE TITLE
Bitcoin Addresses, Blocks 

### ISSUE THREAD

**Issue by 1KFHE7w8BhaENAswwryaoccDb6qcT6DbYY** [duckduckgo/zeroclickinfo-spice#3174]
------
IA Page:  http://duck.co/ia/view/bitcoin 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jmg

**Comment by pjhampton** [comment]
This isn't descriptive enough to be actionable. Closing.
