### ISSUE TITLE
METAR Information: Not working (on main site)

### ISSUE THREAD

**Issue by santigl** [duckduckgo/zeroclickinfo-spice#3175]
### Description

The METAR IA is not being displayed on the main site. However, it does work in beta.duckduckgo.com (though it is running a minor modification from a newer PR, #3005, which changes the API's url to HTTPs).

## Steps to recreate

* Does not work: https://duckduckgo.com/?q=metar+KLAX&ia=weather
* Works: https://beta.duckduckgo.com/?q=metar+KLAX&ia=weather

## People to notify

@moollaza 

---

Instant Answer Page: https://duck.co/ia/view/metar

**Comment by pjhampton** [comment]
The [production state is set to offline](https://duck.co/ia/view/metar/json). It just needs to be put online (unless there is some weird underlying problem).

cc. @moollaza

**Comment by santigl** [comment]
Thanks for the quick reply, @pjhampton. Could it have failed at some point and that caused it to be taken offline?

**Comment by pjhampton** [comment]
Yep, it's possible @santigl

**Comment by santigl** [comment]
I see. If there isn't a bigger underlying problem, could we take this opportunity to update the IA code before bringing it back online? (It has been running on beta for close to a month.)

**Comment by pjhampton** [comment]
I said possible, it's more probable 😄 

> could we take this opportunity to update the IA code before bringing it back online?

Sounds like an idea 👍  What have you got in mind?

**Comment by santigl** [comment]
Just to deploy what is currently running in beta (PR #3005). It is just a minor usability change and, most importantly, it uses the new API's url format and enables HTTPs.

**Comment by pjhampton** [comment]
Online now ❤️
