### ISSUE TITLE
Places: Not working without qutotation

### ISSUE THREAD

**Issue by zappe** [duckduckgo/zeroclickinfo-spice#3177]
"Hair Salons Porto" doesn't work but ""Hair Salons" Porto" work.

------
IA Page:  http://duck.co/ia/view/maps_places 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nilnilnil

**Comment by pjhampton** [comment]
That's odd @zappe, because it works for me. It's possible it just trigger for some reason. Can you verify by trying again?

![screen shot 2017-03-07 at 8 41 18 pm](https://cloud.githubusercontent.com/assets/8960296/23677016/756becc0-0376-11e7-8859-d5c91669a785.png)

**Comment by zappe** [comment]
Strange, didn't work today but is working now.

Btw, any plans on adding more than Yelp?
Like Facebook or Foursquare?

Yelp is pretty limited.

**Comment by pjhampton** [comment]
No, no plans but I can add it to the feedback pipeline! 😄  Thanks!
