### ISSUE TITLE
xkcd Bug: Not working

### ISSUE THREAD

**Issue by electricduck** [duckduckgo/zeroclickinfo-spice#3178]
### Description

When I use "xkcd {comicID}", nothing is returned

---

Instant Answer Page: https://duck.co/ia/view/xkcd

**Comment by pjhampton** [comment]
Hey @electricduck! Thanks for reporting 😄 

It seems that this has been knocked offline for some reason - https://duck.co/ia/view/xkcd/json
cc. @moollaza
