### ISSUE TITLE
Forecast: Default to Celsius outside of US

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-spice#3180]
### Description

There have been user queries as to why this Instant Answer is showing them Fahrenheit over Celsius. It would be great if someone could extend this IA to default to Celsius if the user is not in the United States. 

#### Good default (US) 👍 

![screen shot 2017-03-08 at 2 56 23 pm](https://cloud.githubusercontent.com/assets/8960296/23709283/d0731932-0410-11e7-9d4f-b6325fc5c697.png)

#### Not so good default (US) 👎 

![screen shot 2017-03-08 at 2 56 33 pm](https://cloud.githubusercontent.com/assets/8960296/23709297/d976e16c-0410-11e7-9c74-8d34a36be51e.png)

#### Good default (Outside-US) 👍 

![screen shot 2017-03-08 at 2 55 46 pm](https://cloud.githubusercontent.com/assets/8960296/23709318/e99826b4-0410-11e7-9bb1-aa1e630cddb9.png)

#### Not so good default (Outside-US) 👎 

![screen shot 2017-03-08 at 2 55 29 pm](https://cloud.githubusercontent.com/assets/8960296/23709311/e1fab61a-0410-11e7-9803-91075a1497e9.png)

---

Instant Answer Page: https://duck.co/ia/view/forecast

**Comment by nalinbhardwaj** [comment]
Hey @pjhampton I fixed this already in #3151. I think it's not pushed to production yet however.

**Comment by pjhampton** [comment]
Oh, nice! Thanks @nalinbhardwaj

**Comment by nalinbhardwaj** [comment]
I have another pending improvement to the forecast IA if you could review it: #3153 :)
