### ISSUE TITLE
SoundCloud: Autoplay

### ISSUE THREAD

**Issue by in0rdr** [duckduckgo/zeroclickinfo-spice#3183]
How can I integrate autoplay functionality?

------
IA Page:  http://duck.co/ia/view/sound_cloud 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jdan

**Comment by pjhampton** [comment]
I'm not sure if autoplay is a good idea. We don't want to shock the user if they weren't expecting it and also, it might not be the sought after track.

**Comment by in0rdr** [comment]
You are right, it might not. I was just searching for a music author today and thought it would be neat if I could continue my browsing in another tab and Duckduckgo would just autoplay the rest of the search results. I think it was suggested also last year, #1692

**Comment by pjhampton** [comment]
awesome - nice find! Let's continue the convo there 😄
