### ISSUE TITLE
 Astrobin Apod: Doesn't trigger

### ISSUE THREAD

**Issue by nalinbhardwaj** [duckduckgo/zeroclickinfo-spice#3184]
### Description

The Astrobin Apod IA doesn't trigger on duckduckgo.com . It seems to work fine on beta however.

## Steps to recreate

Query : [astronomy picture of the day](https://duckduckgo.com/?q=astronomy%20picture%20of%20the%20day&ia=astronomy)

## People to notify

@killerfish 

---

Instant Answer Page: https://duck.co/ia/view/apod

**Comment by pjhampton** [comment]
@nalinbhardwaj it's production state is set to offline: https://duck.co/ia/view/apod/json
It needs to be reactivated internally

**Comment by pjhampton** [comment]
I have re-enabled this and should go out in the next release. If it fails, then there is an issue with the upstream.
