### ISSUE TITLE
Dictionary Definition: IPA support (pronunciation)

### ISSUE THREAD

**Issue by Chinggis6** [duckduckgo/zeroclickinfo-spice#3185]
Please, offer [IPA](https://en.wikipedia.org/wiki/International_Phonetic_Alphabet) too, and not only US-style pronunciation transcription (characters).

Google does that, and I used to use google.co.uk specifically for that very reason before I switched to DDG.

![DDG example](http://i.imgur.com/QvaMY6j.png "DDG definition with US-style pronunciation transcription")

![Google example](http://i.imgur.com/rZFNY96.png "Google definition with IPA")

Thanks in advance.

------
IA Page:  http://duck.co/ia/view/dictionary_definition 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon

**Comment by pjhampton** [comment]
Hey @Chinggis6 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
