### ISSUE TITLE
Recipes: Incorrect star ratings displayed

### ISSUE THREAD

**Issue by tilapiameister** [duckduckgo/zeroclickinfo-spice#3193]
Hello, almost all recipes are previewed with 5 stars even though when you click on the recipe and go to the site the recipe will have less than 5 stars.

------
IA Page:  http://duck.co/ia/view/recipes 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @bsstoner

**Comment by pjhampton** [comment]
Hey @tilapiameister!

Thanks for reporting this! Can you please give us specific example[s]?

**Comment by tilapiameister** [comment]
Well when you search a red velvet cake recipe for example every single recipe is labeled 5 stars but then I opened a link to yumly and it was rated 2 stars there.
It would be nice to know what the real rating is and how many people voted for it.

**Comment by pjhampton** [comment]
https://duckduckgo.com/?q=red+velvet+cake+recipe&t=hd&ia=recipes&iai=2

**Comment by tilapiameister** [comment]
They are all 5 stars http://imgur.com/K16TKpO
But when you open the first link its only 1 star!
http://www.yummly.co/recipe/Red-velvet-cake-324797?prm-v1 and its been only reviewed once.

**Comment by moollaza** [comment]
This seems to be an error in the API as the data is incorrect in the JSON response.

**Comment by moollaza** [comment]
This appears to be correct now?
