### ISSUE TITLE
Geometry: This is the list of issues for geometry IA

### ISSUE THREAD

**Issue by adityatandon007** [duckduckgo/zeroclickinfo-spice#3194]
**Issues**

1. **Bug:** geometry of hemisphere gives the answer for geometry of sphere

![screenshot from 2017-03-17 02-01-05](https://cloud.githubusercontent.com/assets/25108385/24017529/6de29f0c-0ab6-11e7-929b-e51f0e5bcdcd.png)

2. *Triggering Issue* Typing `geometry nonsense square formula` and similar irrelevant queries triggers this IA

![screenshot from 2017-03-17 02-12-49](https://cloud.githubusercontent.com/assets/25108385/24017868/be45504c-0ab7-11e7-8859-301ffb473734.png)

3. **Hovering Issue** While hovering over the results of `geometry of square` works fine, individual hovering like `geometry of perimeter of square` or `perimeter of square formula` shows incorrect colors

People to Notify @moollaza @pjhampton @pixunil 

------
IA Page:  http://duck.co/ia/view/geometry 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pixunil

**Comment by adityatandon007** [comment]
@duckduckgo/duckduckhack-contributors  These task can be split and various contributors can work on these individually, but please let others know before you start working

**Comment by agunay** [comment]
@adityatandon007 Hello, I am new here. I would like to fix the first bug (about the hemisphere) if it's okay.

**Comment by mintsoft** [comment]
@agunay That's great, open a PR for your fix and we'll get cracking!

**Comment by nalinbhardwaj** [comment]
Another bug, SVG is made of black strokes, which makes it completely invisible in the dark theme. Needs to replaced by grey/white.

**Comment by adityatandon007** [comment]
closing because this has been converted into a goodie
