### ISSUE TITLE
Nutrition: Update with appropriate triggers

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-spice#3195]
## Problem

This Instant Answer is great, but it's not triggering as much as it should be. This is because the triggering hasn't been optimized. In https://github.com/duckduckgo/zeroclickinfo-spice/commit/ff29bd391b2a836ee3214338d2b67bbd7aaa560a, @jdorweiler removed a series of trigger words because this IA was **over-triggering**. However, it's now **under-triggering**.  This Pull Request should build on top of his work!

## Solution

The developer should analyze the [Nutritionix API](https://www.nutritionix.com/) and update the trigger words as appropriate in [Nutrition.pm](https://github.com/duckduckgo/zeroclickinfo-spice/tree/master/lib/DDG/Spice/Nutrition.pm). Because you will be changing the behaviour of the Instant Answer, please don't forget to update the [tests](https://github.com/duckduckgo/zeroclickinfo-spice/tree/master/t/Nutrition.t).

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/nutrition

**Comment by apoorvnandan** [comment]
Hey, I would like to work on this!
In [ff29bd3](https://github.com/duckduckgo/zeroclickinfo-spice/commit/ff29bd391b2a836ee3214338d2b67bbd7aaa560a) the following trigger words were removed.
`'kcals', 'cals','dietary fiber','trans-fat','trans fat','trans fatty acid','calories from fat','saturated fat','monosaturated fat','polyunsaturated fat','cholesterol','sodium','sugar','protein','carbs','carbohydrates','vitamin c','vitamin a','calcium'`
I am unable to understand how these were responsible for the over triggering?

**Comment by pjhampton** [comment]
Yes, please @apoorvnandan 

I'll put this on hold for now, but I will reserve it for you. I'm pushing a PR tonight which overhauls this IA and upgrades the API from 1.1 => 2. I will let you know when that's done 😄

**Comment by apoorvnandan** [comment]
Okay, sure.

**Comment by DGMurdockIII** [comment]
Have a look at these three sites migh help get this done 
http://openfoodfacts.org/
http://ndb.nal.usda.gov/ndb/doc/
https://product.okfn.org
