### ISSUE TITLE
Currency: Update alias for Bulgarian Lev

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-spice#3207]
## Problem

Based on User Feedback, this Instant Answer isn't triggering how it should on Bulgaria's official currency. 

**Triggering:** 👍 

![screen shot 2017-03-24 at 4 33 48 pm](https://cloud.githubusercontent.com/assets/8960296/24304024/f17c5b1a-10af-11e7-871c-7f54f28bbeaa.png)

**Not Triggering**: 👎 
![screen shot 2017-03-24 at 4 33 21 pm](https://cloud.githubusercontent.com/assets/8960296/24304025/f17f784a-10af-11e7-9552-eaf48fa49d54.png)

## Solution

1. Add a test for this, or two!
2. Update the [currencyNames](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/currency/currencyNames.txt#L14) file to make this triggering more lenient. 

## People to notify

@pjhampton

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [x] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/currency

**Comment by BillyBarbaro** [comment]
@pjhampton I can get this one real quick.
