### ISSUE TITLE
Nutrition: Add lists and update triggering

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-spice#3209]
## Problem

The Nutrition Instant Answer doesn't trigger for **single-word food item searches**, such as `avocado`, `beef`, or `steak`:

![screen shot 2017-03-24 at 7 28 58 pm](https://cloud.githubusercontent.com/assets/8960296/24310622/8f3e057a-10c8-11e7-85c4-c7ca1330af0d.png)

We should trigger on these queries and show an Instant Answer.

## Solution

1. Find one or more lists of popular food items
    - Wikipedia is a good place to start: https://simple.wikipedia.org/wiki/List_of_fruits
2. Update the code to load in each food item as a trigger (see [Currency IA](https://duck.co/ia/view/currency) for an example)
3. Add tests to `t/Nutrition.t` to confirm changes work as expect

## People to notify

@pjhampton

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/nutrition

**Comment by fraed** [comment]
I would love to claim this issue.
After setting up the development environment i am ready to get instant answers but this doesn't work with the Nutrition API. 
Are there any restriction issues in a local environment or am i missing some docs or something else?
Or am i just working against "duckpan query"?

Eg: chicken Taco (works)
![image](https://cloud.githubusercontent.com/assets/1233223/25071224/e20aed4a-22b1-11e7-8aaf-6df21d2243e8.png)

 Eg: banana calories (throws error)
![image](https://cloud.githubusercontent.com/assets/1233223/25071233/06eda6f2-22b2-11e7-99e7-1c5192a7465e.png)

If you help me out i can give it a try. Thanks.

**Comment by moollaza** [comment]
@fraed thanks for volunteering! We really appreciate it 😄 

Unfortunately I'm unable to reproduce the failure you're seeing. Can you show me the output of the DuckPAN console? Can you also show me the network tab (specifically the JS content)

Also, have you modified any code yet?

**Comment by pjhampton** [comment]
Could it be because the api keys @moollaza, @fraed?

**Comment by moollaza** [comment]
@pjhampton @fraed I see the issues now. Because @fraed doesn't have an API key installed, we fallback to using the API endpoint on beta.duckduckgo.com. Currently, that API endpoint has been modified by another Pull Request, so the `api_result` doesn't pass the first check in the Nutrition.js file.

@fraed are you able to signup for a free Nutritionix API key?

Once you have your own API Key you can add it to your shell environment (or via duckpan with `duckpan add DDG_SPICE_NUTRITIONIX_APIKEY {val}`)

Then the API call will go straight the API instead of using the beta endpoint 👍

**Comment by fraed** [comment]
Thank you. My development environment works now 👍.

**Comment by fraed** [comment]
Hey @pjhampton, @moollaza,
I figured out that this file https://github.com/fraed/zeroclickinfo-spice/blob/3209-nutrition-triggering/share/spice/nutrition/nutrition.js can't handle single word ia as it needs measurement infos. I solved it quick using a default value in line 38. Let me know if you have further instructions here or the using "calories" as a default value works for you. Thanks.

**Comment by moollaza** [comment]
> Let me know if you have further instructions here or the using "calories" as a default value works for you. Thanks.

@fraed I'm not too sure what you mean, but it sounds Ok. Please open a PR and we can discuss further there 👍
