### ISSUE TITLE
Currency: Add GBP aliases

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-spice#3213]
## Problem

We are not currently supporting the aliases `sterling` and `pound sterling` in [currencyNames.txt](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/currency/currencyNames.txt#L47). From user feedback and unanswered query data, we can see that this is something that needs patched. This issue would be perfect for a newcomer who hasn't yet contributed to DuckDuckHack!

## Solution

1. Add 2 or 3 tests
2. Add the aliases in currencyNames.txt
3. Run tests / test of duckpan
4. Send Pull Request

## People to notify
@pjhampton

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/currency

**Comment by TheresaWilkin** [comment]
I would like to do this please.

**Comment by pjhampton** [comment]
Awesome, thanks so much @TheresaWilkin! 😄  ping me if you have any questions or need any help

**Comment by abuhussain** [comment]
Would like to help, but no idea where and how to start!

**Comment by pjhampton** [comment]
Hey @abuhussain,

This issue has been completed essentially, we just need to [merge the PR](https://github.com/duckduckgo/zeroclickinfo-spice/issues/3215). 

If you are interested in contributing, please check out duckduckhack.com/issues 😄  Feel free to reach out to me personally on slack
