### ISSUE TITLE
Currency: Add "peso" as alias for Mexican Peso

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#3217]
## Problem

The word `peso` should exist as an alias for "Mexican Peso" (which seems to be the most popular Peso) in [currencyNames.txt](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/currency/currencyNames.txt#L100).

From user feedback and unanswered query data, we can see that this is something we need.

This issue would be perfect for a newcomer who hasn't yet contributed to DuckDuckHack!

## Solution

1. Add 2 or 3 tests to `t/Currency.t`
  - e.g. `1 peso to usd`
2. Add the aliases in currencyNames.txt
3. Verify tests pass by running `duckpan test currency`
4. Send Pull Request

## People to notify
@pjhampton

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/currency

**Comment by mkw2000** [comment]
I would like to give this a go !

**Comment by pjhampton** [comment]
Thanks @mkw2000... it's all yours! reach out if you need some help

**Comment by moollaza** [comment]
@mkw2000 I've invited you to the DDG org, once you accept, we can set you as the Assignee on the task 👍

**Comment by mkw2000** [comment]
@moollaza Thank you , just joined !
