### ISSUE TITLE
Currency: Add "yuan" as alias for Chinese Yuan

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#3220]
## Problem

The word `yuan` should exist as an alias for "Chinese Yuan" (which seems to be the most popular Peso) in [currencyNames.txt](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/currency/currencyNames.txt#L30).

From user feedback and unanswered query data, we can see that this is something we need.

This issue would be perfect for a newcomer who hasn't yet contributed to DuckDuckHack!

## Solution

1. Add 2 or 3 tests to `t/Currency.t`
  - e.g. `1 yuan to usd`
2. Add the aliases in currencyNames.txt
3. Verify tests pass by running `duckpan test currency`
4. Send Pull Request

## People to notify
@pjhampton

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [x] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/currency

**Comment by adityatandon007** [comment]
@moollaza I would like to try

**Comment by pjhampton** [comment]
Thanks @adityatandon007 💙  💛  💜
