### ISSUE TITLE
Dictionary Definition: Audio unavailable for the query "define aspiration"

### ISSUE THREAD

**Issue by gautamkrishnar** [duckduckgo/zeroclickinfo-spice#3222]
When i searched for "define aspiration" its shows audio unavailable when i click the play pronunciation button... 🔪 

Browser: Firefox

![screenshot 334](https://cloud.githubusercontent.com/assets/8397274/24588757/8c61fbb0-17ec-11e7-8f01-877bf164de1e.png)

------
IA Page:  http://duck.co/ia/view/dictionary_definition 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon #

**Comment by moollaza** [comment]
Seems to be working now.
