### ISSUE TITLE
BayAreaBikeShareCA Bug: doesn't trigger in production

### ISSUE THREAD

**Issue by marianosimone** [duckduckgo/zeroclickinfo-spice#3228]
### Description

Even though it works in dev boxes (tried in Codio), "bike share san francisco" doesn't trigger the IA

Note that `CitiBikeNYC` and `IndegoPHL` do work

## Steps to recreate

Search for "bike share san francisco" (https://duckduckgo.com/?q=bikeshare+san+francisco)

## People to notify

I'm the maintainer for this IA... but don't really understand what's going on. Maybe @moollaza can point in the right direction?

---

Instant Answer Page: https://duck.co/ia/view/bay_area_bike_share_ca

**Comment by moollaza** [comment]
@marianosimone this IA has gone offline. Our automated system probably disabled it due to an API outage.

I'll reenable it 👍

**Comment by marianosimone** [comment]
@moollaza is there any way to get notified when the systems disables an IA?

**Comment by moollaza** [comment]
@marianosimone not yet, it's something I would like to add though.

I was about to re-enable this but it seems that we're not getting an API response right now:

https://beta.duckduckgo.com/?q=bike+share+bay+area&ia=web

Care to investigate?

**Comment by marianosimone** [comment]
@moollaza it's still showing up without issues in dev... Maybe it's a problem with them blocking via IP/domain?

data@bayareabikeshare.com could be a good point of contact if that's the case

**Comment by moollaza** [comment]
Closing. This Instant Answer is offline and DuckDuckHack is in maintenance mode. Further, Map-based Instant Answers are not currently working as we have made some breaking changes internally so this will not be able to come back online for now.
