### ISSUE TITLE
OpenNIC DNS: Can't trigger IA

### ISSUE THREAD

**Issue by cylgom** [duckduckgo/zeroclickinfo-spice#3229]
I couldn't trigger the IA today: the "DNS" tab that used to appear after "Videos" seems gone. It still works on the [beta](https://beta.duckduckgo.com/?q=censor+free+dns&ia=dns) server, though. I also had a look at the perl file just to check the critical line and nothing surprised me, the triggers are still here:
`triggers any => "neutral dns", "opennic", "open nic", "censor free dns";`   

------
IA Page:  http://duck.co/ia/view/open_nic 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @cylgom

**Comment by moollaza** [comment]
@cylgom thanks for reporting. Our automated system likely took it offline due to some API downtime.

I'll get it back online shortly 👍

**Comment by moollaza** [comment]
@cylgom it should be back online shortly. Please ping me here if it's not online in the next few hours 👍

**Comment by cylgom** [comment]
@moollaza it's still not online 😞

**Comment by moollaza** [comment]
Hmm seems like it went online, then back offline. We had an issue with our metadata which I believe was fixed. I'll set it up to go online again. Should be online soon!
