### ISSUE TITLE
Currency: Update aliases

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-spice#3232]
## Problem

From past [anonymized] search data we aren't covering all the ways to express GBP and MYR currencies. We should add more cases to cover these. **This would be a good first time contributors issue.** 

## Solution

1. Add a couple of tests to [Currency.t](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/t/Currency.t)

2. Add `malyasian rupees` and `malyasian rupee` to [currencyNames.txt](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/currency/currencyNames.txt#L101)

3. Add `uk pounds` and `uk pound` to [currencyNames.txt](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/currency/currencyNames.txt#L47)

4. Send a PR

## People to notify

@pjhampton

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/currency

**Comment by fendatr** [comment]
Hey, I've added the two aliases. Wasn't sure where to put the tests or what specifically I should test, so I just added them to a test that was also had a 'gbp' in it.

Tests:
```
    '1 malaysian rupee to uk pounds' => test_spice(
        '/js/spice/currency/1/myr/gbp',
        call_type => 'include',
        caller => 'DDG::Spice::Currency',
        is_cached => 0
    ),
    '100 uk pound in malaysian rupees' => test_spice(
       '/js/spice/currency/100/gbp/myr',
       call_type => 'include',
       caller => 'DDG::Spice::Currency',
       is_cached => 0
    ), ```
