### ISSUE TITLE
Currency: Support new pattern

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-spice#3233]
## Problem

It seems that users are submitting queries that have the following form:

`<currency_name> <amount> to <currency_name>`

We should support that form.

## Solution

1. Add a couple of tests to [Currency.t](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/t/Currency.t)

2. Support the new query pattern in [Currency.pm](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Currency.pm)

3. Send a PR

## People to notify

@pjhampton

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/currency

**Comment by nalinbhardwaj** [comment]
Isn't this the same as #3165 ? If so, is @BillyBarbaro not working on it anymore?

**Comment by BillyBarbaro** [comment]
Good catch.  I believe the PR I just updated today addresses this issue.  You can check the tests I updated to see some of the new queries it covers.

**Comment by pjhampton** [comment]
We'll close in favour of the old one!
