### ISSUE TITLE
item Template Bug: The 'Click to expand' button font-family doesn't work 

### ISSUE THREAD

**Issue by Louistwee** [duckduckgo/zeroclickinfo-spice#3246]
Hi,

When I click  on this ![untitleed](https://cloud.githubusercontent.com/assets/27563848/25087268/d8f0a062-236d-11e7-8e6d-b0cf54841c28.png) button it transforms into this ![untitleed](https://cloud.githubusercontent.com/assets/27563848/25087324/485df12a-236e-11e7-899d-78dd054a4388.png) button. 
But when I click a second time to hide the grid the the button changes in this ![untitleed](https://cloud.githubusercontent.com/assets/27563848/25087358/a5cdd0fa-236e-11e7-9f17-1e86dd3b3d9a.png).

**Comment by pjhampton** [comment]
Hey @Louistwee,

Can you please reopen this issue here: https://github.com/duckduckgo/duckduckgo-answerbar-templates

Also, if you could be more descriptive on how to replicate, that would be awesome 👍
