### ISSUE TITLE
Weather: Tile link doesn't match text link

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#3248]
In #3153 we changed the links to point to URL's that are specific to the right day. Those work, but if you click the tile it still goes to the old URL's. They should both go to the same place.

------
IA Page:  http://duck.co/ia/view/forecast 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @himanshu0113

**Comment by rasikapohankar** [comment]
Fixed in #3244..
