### ISSUE TITLE
Currency: Update triggering patterns & aliases

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-spice#3254]
## Problem

The currency IA is undertriggering. We need to open up the patterns to allow broader triggering. The new patterns we need to support are:

```
<currency_name> exchange rate
<currency_name> conversion rate
<currency_name> price
<currency_name> to <currency_name> exchange rate
<currency_name> to <currency_name> conversion
<currency_name> to <currency_name> conversion rate
<currency_name> to <currency_name> converter
<currency_name> to <currency_name> price
```

Further, we need to update the aliases.

**mex** --> `mex peso` and `mexican peso`
**cny**  --> `chinese yuan` and `yuan`
**gbp** --> `uk`

## Solution

1. Add the following test queries to the [Currency.t](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/t/Currency.t).

- 140 chinese yuan to u.s. dollars
- us to mexican peso
- mex peso to dollar
- yuan exchange rate
- cny to usd exchange rate
- euro to usd conversion
- yuan conversion rate

2. Add the aliases mentioned in the above problem statement to [currencyNames.txt](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/currency/currencyNames.txt)

3. Update the triggering in [Currency.pm](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Currency.pm)

4. Send a Pull Request

## People to notify

@pjhampton

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/calculator

**Comment by adityatandon007** [comment]
@pjhampton I'm already working on some of these. 
One more thing `cny` alias is already updated in #3221 and `mexican peso` is working though `mex peso` seems to be not added. I will add those and others and regarding triggering thing I am already working on that too. 
So just to avoid conflict can you assign this to me so that others don't get confused.
