### ISSUE TITLE
Advanced Calculator: Reduce triggering to prevent overlap with Interactive Calculator

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#3281]
## Problem
We've made big improvements to the interactive calculator and its triggering and now in many cases, we show duplicate results from the Symbolab Spice
 and the interactive Calculator.

## Solution
We should remove the triggers related to trig functions and others that the Interactive Calc now handles and leave this Spice to handle more complex math that the other calculator can't handle

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

------
IA Page:  http://duck.co/ia/view/symbolab 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @levaly

**Comment by levaly** [comment]
@moollaza what cases do you want our calculator not to handle? I also noticed that for a query such as 'sin(x)=0' the interactive calculator is triggering although not solving this problem.

I also wonder, is it possible to slightly change the template used to present Symbolab results, to better indicate there is a step by step solution under the link?

**Comment by moollaza** [comment]
> what cases do you want our calculator not to handle?

Anything the existing calculator can handle, shouldn't trigger Symbolab. Basically equations _without_ unknowns or variables. Right now there seems to be an overlap with trig.

> I also noticed that for a query such as 'sin(x)=0' the interactive calculator is triggering although not solving this problem.

Yup, that's a bug we'll be fixing soon.  

>I also wonder, is it possible to slightly change the template used to present Symbolab results, to better indicate there is a step by step solution under the link?

We don't have much room for modification because our presentation of the More at link is standarized by our templates. What did you have in mind?

**Comment by levaly** [comment]
@moollaza maybe since now there are 2 calculators, we should change the name of the Spice to 'Symbolab Calculator', instead of just 'Calculator'. Also, I would like to change the wording of 'Step by step solution' to 'Show all steps'

**Comment by moollaza** [comment]
> maybe since now there are 2 calculators, we should change the name of the Spice to 'Symbolab Calculator', instead of just 'Calculator'.

@levaly we don't put Brand names in the tabs. We can change the tab name from "Calculator" to "Answer" though. These two IAs shouldn't trigger at the same time though so the current tab name should be OK.

> Also, I would like to change the wording of 'Step by step solution' to 'Show all steps'

That sounds fine, please do!
