### ISSUE TITLE
Currency Conversion: e-notation showing in conversion field

### ISSUE THREAD

**Issue by spekulatius** [duckduckgo/zeroclickinfo-spice#3283]
Some currencies with very low values will be displayed with "E-5", etc. See the left of the screenshot:
    
![image](https://cloud.githubusercontent.com/assets/8433587/25886196/b83c4544-3586-11e7-9c08-04a32f36c61f.png)

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by pjhampton** [comment]
Yeah, this is a valid issue. Thanks for reporting @spekulatius 👍 
As for fixing it, nobody should patch this. We're deprecating this IA for a v2 in the coming weeks like we have done with the Conversions and Calculator IA.

**Comment by spekulatius** [comment]
Thanks for your reply and update on the bug @pjhampton! Feel free to close the issue if you consider this not relevant anymore.

**Comment by pjhampton** [comment]
Thanks @spekulatius. I will keep it open for now. when it comes to testing the new IA we can see see if we address all the legacy issues 💛  💜

**Comment by spekulatius** [comment]
Awesome :)

**Comment by pjhampton** [comment]
This is now fixed 👍

**Comment by spekulatius** [comment]
Awesome! Thanks for building this awesome search engine!
