### ISSUE TITLE
PubMed: seems to have stopped working

### ISSUE THREAD

**Issue by bnewbold** [duckduckgo/zeroclickinfo-spice#3286]
The examples (eg, "Pubmed CRISPR") no longer result in abstracts showing.

------
IA Page:  http://duck.co/ia/view/pubmed 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @b2ddg

**Comment by pjhampton** [comment]
Thanks @bnewbold and thanks for your suggestion! It seems that this has been knocked offline. I have applied the `offiline` label and hopefully a member of staff with pick it up soon

**Comment by pjhampton** [comment]
Thanks @bnewbold. I have re-enabled this and should go out in the next release. If it fails, then there is an issue with the upstream.
