### ISSUE TITLE
PubMed: trigger on pmid prefix

### ISSUE THREAD

**Issue by bnewbold** [duckduckgo/zeroclickinfo-spice#3287]
PubMed IDs (eg, "PMID: 21466082" or "pmid:21466082") seem to be frequently used in citations and other contexts when referencing a paper in PubMed. It would be nice to detect and handle these cases more directly that returning a list of search results (aka, only display the single valid result).

------
IA Page:  http://duck.co/ia/view/pubmed 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @b2ddg

**Comment by pjhampton** [comment]
Hey @bnewbold 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
