### ISSUE TITLE
Currency Conversion: This IA is showing incorrect answers

### ISSUE THREAD

**Issue by adityatandon007** [duckduckgo/zeroclickinfo-spice#3295]
**Issue**: While testing the PR #3294 (thanks to @pjhampton for inviting me to test his PR), I found that the our IA is showing incorrect answer for conversion, though I have only checked this for bitcoins conversion. I don't think it is happening because of that PR, I think we are serving stale results from our API, though not sure.

**Screenshots:** 
**DDG Answer**:

![screenshot from 2017-05-19 19-59-16](https://cloud.githubusercontent.com/assets/25108385/26252804/e5221e90-3cce-11e7-9835-6600af5e3aa6.png)

**More at links answer (or xe.com site answer)**:

![screenshot from 2017-05-19 20-00-25](https://cloud.githubusercontent.com/assets/25108385/26253136/e96a9c10-3ccf-11e7-949f-ea84dc770d9d.png)

**Strangely LOL :  Google answer**

![screenshot from 2017-05-19 19-59-59](https://cloud.githubusercontent.com/assets/25108385/26252932/47eff7ea-3ccf-11e7-91bd-08c9cc959704.png)

**Whom to Believe?**

People to notify:
@pjhampton @moollaza 

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by pjhampton** [comment]
Notice the mid-market rates are different dude.
