### ISSUE TITLE
Just Delete Me: Switch to new API

### ISSUE THREAD

**Issue by katzrkool** [duckduckgo/zeroclickinfo-spice#3309]
Justdelete.me, the current data source, has been abandoned. The community has created a fork 
[here](https://github.com/jdm-contrib/justdelete.me) that is being updated with new information. I suggest the data source for just delete me is switched from http://justdelete.me/# to http://justdeleteme.xyz/# to provide the most updated date.

------
IA Page:  http://duck.co/ia/view/just_delete_me 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @riqpe

**Comment by riqpe** [comment]
I fully agree. Naturally we need to confirm that the new maintainers are ok with us using the data. This agreement existed with the previous maintainer. In addition is must be checked that the format of the file hasn't been changed too much.

**Comment by riqpe** [comment]
Great. Thanks @tupaschoal. I'll take care of this soon (tm).

**Comment by pjhampton** [comment]
Thanks @riqpe ❤️

**Comment by PyroSamurai** [comment]
@riqpe It appears to me that your app uses the sites.json directly. If this is the case, there shouldn't be too much of a problem with the switch but its location will change when I implement the new layout/backend. It will be located in the _data folder. 

If you are pulling from the website instead, I'm not sure how it will affect you. 

It will be helpful to me if you would confirm which of these is the case.

**Comment by riqpe** [comment]
The app pulls it directly from GitHub over http.

**Comment by PyroSamurai** [comment]
@riqpe okay, sounds good. Thanks for confirming that for me.

**Comment by PyroSamurai** [comment]
Just letting you know, the new layout/backend for JDM was implemented at the end of last month. Sorry for the delay. The sites.json is in the _data folder now like I said it would be.
