### ISSUE TITLE
Air quality index: Use new API, add IA for air pollen

### ISSUE THREAD

**Issue by nalinbhardwaj** [duckduckgo/zeroclickinfo-spice#3310]
### Description

Currently, the IA only works for US city pincodes. The [breezometer API
](https://breezometer.com) supports queries for latitude longitude worldwide. We can use that to support a lot more queries.

Also, they provide pollen content, which can be included/made a separate IA.

## Steps to recreate

n/a

## People to notify

@schluchc

---

Instant Answer Page: https://duck.co/ia/view/aqi

**Comment by pjhampton** [comment]
Hey @nalinbhardwaj 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
