### ISSUE TITLE
DetectLang: Wrong use of `confidence` value and lack of languages  

### ISSUE THREAD

**Issue by nalinbhardwaj** [duckduckgo/zeroclickinfo-spice#3311]
### Description

The [API FAQ](https://detectlanguage.com/faq) clearly states

> Confidence value depends on how much text you pass and how well it is identified. The more text you pass, the higher confidence value will be. It is not a range, it can be higher than 100.

However, we still seem to be referring it to be a "percentage" which we shouldn't be doing.

Also, the current IA doesn't identify codes of a number of languages(almost half of them) from [language list](http://ws.detectlanguage.com/0.2/languages) which I believe is updated regularly, the best solution here might be to switch to loading the JSON with jQuery.

This is not a very complicated fix, I can make it if everyone agrees to it.

## Steps to recreate

n/a

## People to notify

@ghedo

---

Instant Answer Page: https://duck.co/ia/view/detect_lang

**Comment by pjhampton** [comment]
Hey @nalinbhardwaj 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
