### ISSUE TITLE
Why only Amazon?

### ISSUE THREAD

**Issue by 1tremer** [duckduckgo/zeroclickinfo-spice#3314]
Why does the products view only show Amazon products. Amazon ist not the world!

regards Michael

------
IA Page:  http://duck.co/ia/view/products 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @bsstoner

**Comment by pjhampton** [comment]
Hi @1tremer,

I believe there to be some sort of business relationship between DuckDuckGo and Amazon. I will pass your feedback onto the internal team 👍
