### ISSUE TITLE
Random Cat Facts: It's down

### ISSUE THREAD

**Issue by Uriei** [duckduckgo/zeroclickinfo-spice#3318]
> Support for Python 2.5 has turned off. Please refer to https://goo.gl/aESk5L for more information

------
IA Page:  http://duck.co/ia/view/catfacts 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @RomainLG

**Comment by ioanmoldovan** [comment]
Please assign this issue to me. I like cats!

**Comment by kirkins** [comment]
I don't see any code for this Spice in the repo, so I guess it's just in planning stages now?

Either way @RomainLG you might find this alternative source useful http://www.catfact.info/

**Comment by pjhampton** [comment]
Yeah, this never made it into production. Closing for now.
