### ISSUE TITLE
Currency Conversion: *Suggestion* Defaulting to uae dirham for dirham 

### ISSUE THREAD

**Issue by adityatandon007** [duckduckgo/zeroclickinfo-spice#3321]
**Suggestion:**

In Pr #3320 I have added an alias `uae dirham` so that queries like `1 usd to uae dirham` could also trigger. I was thinking of supporting the queries like `1 usd to dirham` too but for that I have to add `dirham` as an alias. We have to two countries that have dirham in their currency the `moroccan dirham` and `uae dirham`. I was thinking of adding the `dirham` to uae currency.

People to notify:
@moollaza @mintsoft 

**P.S.** 
G defaults to `uae dirham` for `dirham` 
![screenshot from 2017-06-08 16-17-26](https://user-images.githubusercontent.com/25108385/26925128-25cbf0d2-4c66-11e7-93f8-7ac879fb776a.png)

and :duck: response for ` 1 usd to dirham` (Do not trigger)
![screenshot from 2017-06-08 16-18-00](https://user-images.githubusercontent.com/25108385/26925148-3eaaf9fe-4c66-11e7-91dc-24f9c1b95b95.png)

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by pjhampton** [comment]
Thanks @adityatandon007! I see this has been merged, so closing. 
In future, you don't need to create issues for minor changes 👍 

Thanks again 🎉

**Comment by adityatandon007** [comment]
@pjhampton I haven't made the PR for this. The merged PR #3320 was for `uae dirham` not for `dirham`. I was asking about whether to add `dirham` too along with `uae dirham`

**Comment by pjhampton** [comment]
This seems minor. In future, I would just package it into the one PR 👍
