### ISSUE TITLE
Dictionary Definition: Shows durham for dirham

### ISSUE THREAD

**Issue by adityatandon007** [duckduckgo/zeroclickinfo-spice#3322]
**Issue**
I was searching for the currency `dirham` because I was working on currency IA and when I searched `dirham` this IA triggered and showed the result for `durham`

**Screenshot**

![screenshot from 2017-06-08 16-36-48](https://user-images.githubusercontent.com/25108385/26925782-b71a0d42-4c68-11e7-89b1-f196cca36d14.png)

**People to notify**
@moollaza @mintsoft

------
IA Page:  http://duck.co/ia/view/dictionary_definition 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon

**Comment by pjhampton** [comment]
Yeah, I'm fine for you to take this forward @adityatandon007. I think that currency should have a higher signal that the dictionary IA.

**Comment by adityatandon007** [comment]
@pjhampton I didn't get what you meant in the previous comment.

> I'm fine for you to take this forward @adityatandon007

You closed the issue and wanted me to take this forward. How I am gonna take this forward if the issue itself is closed.

**Comment by pjhampton** [comment]
As I mentioned here https://github.com/duckduckgo/zeroclickinfo-spice/issues/3321#issuecomment-308046715

For minor, incremental improvements we don't need to create issues. Just submit an unsolicited PR in future.

**Comment by adityatandon007** [comment]
@pjhampton thanks for clearing that. I would remember this next time
