### ISSUE TITLE
Forecast: zip codes again not working

### ISSUE THREAD

**Issue by Suaiden** [duckduckgo/zeroclickinfo-spice#3323]
Unsure why, but Forecast once again thinks Zip Code 18702 is Harrisburg, PA. Is it based on state capitals? Because there can be huge variances with distances just a couple hundred kilometers away. It seemed to have worked with the last few fixes, but something keeps reverting. Thanks!

------
IA Page:  http://duck.co/ia/view/forecast 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @himanshu0113

**Comment by kirkins** [comment]
Reference for future readers. The city weather is displayed for is close but off by an hour and forty-five minutes.

![untitled](https://user-images.githubusercontent.com/9503662/27996716-4f371aba-64b6-11e7-9a6d-9bc3ef49baac.png)

Google gives weather for exact city: Wilkes-Barre, PA 18702

**Comment by Suaiden** [comment]
It worked previously on DDG. Why is it not working now? And why suggest Google? Anyway, maybe it's a Dark Sky issue? I can't see why pinging by zip code is problematic?

**Comment by pjhampton** [comment]
Hey @Suaiden 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
