### ISSUE TITLE
Twitter: Latest tweet not being displayed

### ISSUE THREAD

**Issue by radioactive73** [duckduckgo/zeroclickinfo-spice#3324]
I noticed the latest tweet is not being displayed as per the [instant answer description](https://duck.co/ia/view/twitter), instead the channel description is displayed.

Example query: _southwest airlines twitter_ or _@southwestair_
Query URL: https://duckduckgo.com/?q=%40southwestair&t=ffab&ia=twitter

![twitter_ia](https://user-images.githubusercontent.com/1937243/26960583-a4121cf8-4c95-11e7-8afe-c021ee29aad1.JPG)

------
IA Page:  http://duck.co/ia/view/twitter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon

**Comment by willyb321** [comment]
I should be able to fix this.

**Comment by moollaza** [comment]
Closing. See explanation in #3331
