### ISSUE TITLE
GitHub Suggestion: Swap `Stars` and `SSH URL` in the GitHub infobox

### ISSUE THREAD

**Issue by perryprog** [duckduckgo/zeroclickinfo-spice#3333]
### Description

Often when I'm searching for a repo, I have to click on the dropdown arrow on the infobox to show all the details, specifically `Stars`. On some repos that have a longer description you can see the `Stars` info, but [on others](https://duckduckgo.com/?q=git+hub+awesome&t=osx&ia=software) you can't see the stars info. 

I think that the SSH URL entry and the Stars entry should be switched, I'm not sure if that's the best choice, so please let me know if it should be a different change.

If anyone wants, I can make a PR.

## Steps to recreate

[This](https://duckduckgo.com/?q=git+hub+awesome&t=osx&ia=software) doesn't shows the star count, but [this](https://duckduckgo.com/?q=bootstrap+repo&ia=software) does.

---

Instant Answer Page: https://duck.co/ia/view/github

**Comment by pjhampton** [comment]
Sure @perryprog. Send a PR and I will ping the community for a review 👍

**Comment by perryprog** [comment]
@pjhampton sounds good! I should be able to get the PR around in maybe this weekend.
