### ISSUE TITLE
Forecast: location misidentified (city name and zip code)

### ISSUE THREAD

**Issue by joshcartme** [duckduckgo/zeroclickinfo-spice#3334]
I was trying to look up the weather for Alameda, CA and instead am given the weather for Sunol, CA. Sunol is about 20 miles south east and a good bit warmer.

Searches I tried include:

weather Alameda, CA
weather in Alameda
weather 94501
weather 94502

and all give the weather for Sunol, CA.

------
IA Page:  http://duck.co/ia/view/forecast 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @himanshu0113

**Comment by nkonk** [comment]
This IA depends on forecast.io for forecast results.
And a quick search on forecast.io reveals that it returns weather for Kilkare Road, Sunol, CA.
When queried for Alameda, CA as the query.

Maybe their closest weather source or Alameda is Sunol, but then, thats just a maybe.

**Comment by joshcartme** [comment]
@nkonk thanks for pointing me towards forecast.io, I couldn't tell what was doing the actual locating. 

It's strange because they have results for say "Oakland, CA" which is right next to Alameda.  But that's not the spice's fault, I can try to file an issue with forecast.io.

I'm not exactly sure what the process is here, but I'd be comfortable with this being closed.

**Comment by pjhampton** [comment]
Thanks guys 👍
