### ISSUE TITLE
AlternativeTo: The DuckDuckHack «Alternative to» not working since a long time

### ISSUE THREAD

**Issue by Troupal** [duckduckgo/zeroclickinfo-spice#3343]
### Hello !
It is true that it is long enough that *the instant answer is no longer working*, someone would know ***why and how to fix it?*** It really is a shame (or "it is a pity", *sorry, I'm french* ***^^*** ) because it was really convenient. 
**Thank you in advance for your response !**

------
IA Page:  http://duck.co/ia/view/alternative_to 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @vikashvverma

**Comment by ManrajGrover** [comment]
Let's move the discussion to #3131.

**Comment by pjhampton** [comment]
Agreed, thanks @ManrajGrover @Troupal
