### ISSUE TITLE
Cryptocurrency: Making browser requests to cryptonator.com

### ISSUE THREAD

**Issue by betterlaef** [duckduckgo/zeroclickinfo-spice#3349]
It seems that the Cryptocurrency IA makes an API request to cryptonator.com whenever one of the currencies used for conversion is changed (by clicking the down arrow next to the currency and selecting a new one). The API request is to a URL for doing the new conversion, and it is the response received that is used to repopulate the info.

I've attached a screenshot showing the results after changing the currency on the left from Bitcoin to Litecoin. You can see a NoScript menu in the top right, and the network request that was just made on the bottom.

Fortunately Cryptonator doesn't leave any cookies for API requests, but this still seems to be a somewhat undesired way of requesting new data, as API requests to third-party sources should, as I understand, be made using DuckDuckGo as a proxy, so as to protect the user's privacy.

------
IA Page:  http://duck.co/ia/view/cryptocurrency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @claytonspinner
![screenshot from 2017-06-28 20 45 13](https://user-images.githubusercontent.com/17970173/27670629-efb52b16-5c42-11e7-9ae6-8bcb53119b75.png)

**Comment by pjhampton** [comment]
Thanks for finding this @betterlaef - I have dropped an urgent patch for this in #3350. Hopefully we can get it out later today.
