### ISSUE TITLE
Forecast: Detect whether to use Celsius

### ISSUE THREAD

**Issue by platypro** [duckduckgo/zeroclickinfo-spice#3353]
When searching for weather forecasts, the forecasts always show Fahrenheit. I am in Canada, so I prefer to see the forecast in Celsius. For now I have to switch to Celsius manually. It should be detected automatically either when viewing weather for a city which uses Celsius, or when detecting the user's region.

------
IA Page:  http://duck.co/ia/view/forecast 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @himanshu0113

**Comment by tagawa** [comment]
Changing the labe to bug as the behaviour used to be like this but looks like something's changed or broken.

**Comment by ashwinvis** [comment]
Kudos to @platypro for bringing that up. It was always annoying to switch to Celsius.

> Fahrenheit was used as the official temperature scale only in the United States (including its unincorporated territories), its freely associated states in the Western Pacific (Palau, the Federated States of Micronesia and the Marshall Islands), the Bahamas, Belize, and the Cayman Islands. All other countries in the world now use the Celsius scale.

If true, it should be pretty easy to implement. I cannot find any official sources though. This is all I can find:

* https://en.wikipedia.org/wiki/Fahrenheit
* http://sciencing.com/countries-use-celsius-8077428.html
* https://www.reference.com/science/countries-use-fahrenheit-scale-7a4a7a83dbf56f01
* http://www.metric-conversions.org/temperature/fahrenheit-conversion.htm

**Comment by pjhampton** [comment]
Weird, the code exists. It just doesn't work. I'm on it.

**Comment by ashwinvis** [comment]
Is this bug fix online? Doesn't work for me 😞 !

https://screenshots.firefox.com/M2e3B2IxkItQaaFz/duckduckgo.com

**Comment by moollaza** [comment]
Not yet 👍
