### ISSUE TITLE
Must show local weather if location is on on front page of duckduckgo

### ISSUE THREAD

**Issue by glearner** [duckduckgo/zeroclickinfo-spice#3355]
It very convenient to so some interesting things like weather, sen-sex or the things might user be interested

**Comment by pjhampton** [comment]
Hi @glearner! Thanks for reaching out. 
Can you please edit this issue with our issues template after referring to our [CONTRIBUTING.md](https://duckduckhack.com/contributing.html). 👍  Please feel free to ping me when you're done.

**Comment by glearner** [comment]
I think I corrected the problem @pjhampton
