### ISSUE TITLE
Currency: Convert € into CHF

### ISSUE THREAD

**Issue by Janjoch** [duckduckgo/zeroclickinfo-spice#3356]
Steps to reproduce error:

1. type in DuckDuckGo "Euro CHF" (to convert Euro into Swiss Franc)
2. Enter in the "Euro"-Field 50
=> The Result is 45,65. But this is when you convert 50 CHF into €. The real value should be around 55CHF

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by pjhampton** [comment]
@Janjoch like this? Does this issue still exist? 

![screen shot 2017-07-04 at 9 39 38 pm](https://user-images.githubusercontent.com/8960296/27842362-55092522-6101-11e7-950f-3ba39de97984.png)

**Comment by Janjoch** [comment]
On my devices (iPhone and Mac, both with Firefox), it looks loke this: https://www.dropbox.com/s/rrw5lyboews7u6w/BugReport.png?dl=0

**Comment by pjhampton** [comment]
Thanks @Janjoch 

I have reproduced this! Thanks. I will fix very soon

**Comment by adityatandon007** [comment]
@pjhampton It's showing right in my browser(Firefox) in desktop as well as mobile view :smile: 
![screenshot from 2017-07-06 12-24-43](https://user-images.githubusercontent.com/25108385/27899085-6822ea58-6246-11e7-91da-47e79b10ae30.png)

**Comment by pjhampton** [comment]
Thanks @adityatandon007. I reproduced this.

**Comment by pjhampton** [comment]
This should be fixed now. Some of the DDG employees looked into this internally 👍
