### ISSUE TITLE
Currency Conversion: Bug, ZMW (Zambian Kwacha)

### ISSUE THREAD

**Issue by twoSeats** [duckduckgo/zeroclickinfo-spice#3357]
Queries for ZMW conversions bring up rates for old phased out ZMK instead of current legal tender ZMW.

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by twoSeats** [comment]
Hi, 
Sorry, not sure this was fixed...
## Actual:
![screenshot from 2017-07-08 15 02 00](https://user-images.githubusercontent.com/536306/27985621-c673736c-63ee-11e7-873a-0506998dfa7a.jpeg)

## VS expected:
![screenshot from 2017-07-08 15 04 12](https://user-images.githubusercontent.com/536306/27985620-c67239ac-63ee-11e7-9c78-53bf1e79e878.jpeg)

**Comment by moollaza** [comment]
Thanks for pointing this out. I will open a PR shortly to properly solve this 👍

**Comment by moollaza** [comment]
@twoSeats this has now been fixed and released 👍
