### ISSUE TITLE
SoundCloud Bug: Example not triggering

### ISSUE THREAD

**Issue by kirkins** [duckduckgo/zeroclickinfo-spice#3359]
### Description

When I click through the links on the IA page for SoundCloud the spice isn't triggered. It works on beta, but it says status live so it should work on the main search, no?

## Steps to recreate

https://duckduckgo.com/?q=soundcloud%20MGMT&ia=audio

## People to notify

@jdan 

---

Instant Answer Page: https://duck.co/ia/view/sound_cloud

**Comment by pjhampton** [comment]
Thanks @kirkins. I turned this back on.
