### ISSUE TITLE
Currency Conversion: 

### ISSUE THREAD

**Issue by Michal-Sitarz** [duckduckgo/zeroclickinfo-spice#3361]
NZD to GBP doesn't work right...
It shows (at the time I was checking it) 1 to 0.56 (NZD to GBP) , but it converts by 1 to 1.77,
since I'll start typing the digits... 
GBP to NZD works OK, and this is 1 to 1.77...

Conclusion: it looks like formula for NZD to GBP is the same as GBP to NZD...
cause the source: XE.com shows everything OK.

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by kirkins** [comment]
@Michal-Sitarz Can you clarify the issue here?

I converted NZD to GBP and vise-versa, both times the results matched that of Google.

**Comment by Michal-Sitarz** [comment]
I've done it right now and 50000 NZD gives me 88522 GBPP
https://duckduckgo.com/?q=nzd+to+gbp&t=h_&ia=currency

**Comment by kirkins** [comment]
I don't get that can you post a link and screenshot:
![untitled](https://user-images.githubusercontent.com/9503662/27998222-da9ec988-64d7-11e7-944c-fe8ad14b294f.png)


https://duckduckgo.com/?q=50000+NZD+to+gbp&t=h_&ia=currency

**Comment by Michal-Sitarz** [comment]
![duckduckgo-nzd-to-gbp](https://user-images.githubusercontent.com/27778608/27998236-2889eafe-6502-11e7-8140-05f83f85a16b.PNG)

**Comment by Michal-Sitarz** [comment]
Checked in Firefox and Chrome - both with the same result, as above...

**Comment by kirkins** [comment]
@Michal-Sitarz I see what you mean now. It works when you do a search query but there is an issue with the interactive part.

**Comment by Michal-Sitarz** [comment]
Yes, when you try to increase/decrease the value, it will be wrong...

**Comment by Michal-Sitarz** [comment]
Looks like it uses same formula as for GBP to NZD (reverse to what I want).

**Comment by kirkins** [comment]
@Michal-Sitarz I'm wondering if a recent pull request fixed the issue because I can't replicate the bug on the beta server: https://duckduckgo.com/?q=NZD+to+GBP&t=h_&ia=currency

**Comment by kirkins** [comment]
_Edit: accidentally linked non-beta version. Link updated._

**Comment by Michal-Sitarz** [comment]
Yes, on beta version (using above link) it works OK.

// I've noticed that you had some issues with reverse-conversion, cause it looked like that.
// Thanks for super-fast reply for this issue :)

**Comment by pjhampton** [comment]
Thanks @Michal-Sitarz and @kirkins!

We're aware of this issue and have a fix ready to go. For some context, DuckDuckGo have some special internal triggering modules that they can attach to IAs. This _type of triggering_ is making an additional api call that is overriding the logic in the IA - making the exchange rate the inverse rate. I didn't take us that long to get to the bottom of this, but we didn't do a release on Friday so that's why this persists. Hopefully, we can get it out today! I'm going to close this because of https://github.com/duckduckgo/zeroclickinfo-spice/issues/3356
