### ISSUE TITLE
Twitter: links in Twitter bios not clickable

### ISSUE THREAD

**Issue by da2x** [duckduckgo/zeroclickinfo-spice#3363]
Links in Twitter bios aren’t clickable. Secondarily, the Twitter short-link is displayed instead of the actual human-readable link.   

[Example](https://duckduckgo.com/?q=ctrl+blog+twitter&t=ffab&ia=twitter)

The t-co-shortlinks come in both expanded and display styles. Either would be preferable to showing the T.co-shortlink itself. [docs](https://dev.twitter.com/basics/tco).

If DuckDuckGo doesn’t want clickable links in the Twitter bio, then please use an unclickable display-link instead of the shortlink. [URLs are UI](https://www.hanselman.com/blog/URLsAreUI.aspx), after all. Especially when displayed so prominently on top of the search results.

------
IA Page:  http://duck.co/ia/view/twitter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon

**Comment by pjhampton** [comment]
For something so minor, we don't need two issues. Merged into https://github.com/duckduckgo/zeroclickinfo-spice/issues/3364
