### ISSUE TITLE
Twitter: @otherpeople and links not clickable in Twitter bios

### ISSUE THREAD

**Issue by da2x** [duckduckgo/zeroclickinfo-spice#3364]
It’s quite common to reference employers or other people in Twitter bios. On Twitter, these references are clickable and point to the user account in question.

E.g. “I work @DuckDuckGo” (they’re even clickable here on GitHub!) [Live example](https://duckduckgo.com/?q=majornelson+twitter&t=ffab&ia=twitter).

These user references are not clickable in DuckDuckGo’s Twitter bios, and I beleive they should be. Then I don’t need to do another search for that name, or don’t need to click-through to that profile before I can click the other username.

**2nd Issue**

Links in Twitter bios aren’t clickable. Secondarily, the Twitter short-link is displayed instead of the actual human-readable link.

Example

The t-co-shortlinks come in both expanded and display styles. Either would be preferable to showing the T.co-shortlink itself. docs.

If DuckDuckGo doesn’t want clickable links in the Twitter bio, then please use an unclickable display-link instead of the shortlink. URLs are UI, after all. Especially when displayed so prominently on top of the search results.

# Summary

* clickable @mentions for all.
* clickable URLs for verified accounts only?
* human readable URLs (with max-length…) for all?

------
IA Page:  http://duck.co/ia/view/twitter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon

**Comment by pjhampton** [comment]
I get the `@mentions`, but I'm not sure about the links. After all, twitter is known for harboring large spam networks and there is also plenty of abuse on their platform. Making links clickable might not be in the best interest of the user as it could lead to somewhere undesirable - such as a phishing site so something completely unexpected.

**Comment by da2x** [comment]
At least switch to showing the display link instead of the obscure t-co links. "mycopany.com" is more informative to humans than"t.co/asdf12342" even when it's not clickable.

**Comment by pjhampton** [comment]
yeah, but links can get insanely long. 
Anybody want to weigh in here? cc/ @duckduckgo/duckduckhack-contributors

**Comment by kirkins** [comment]
I prefer the Google goodie for twitter names to that of DuckDuckGo.

Someone made a push request to show latest tweet but it was a problem because we didn't want to hit the API too many times. I would have preferred that to just the description as we have it now. _Even if the tweets get cached for 24 hours._

For URLs google shows the real link but if it's too long they do `http://mylink.com/wor...`. They are also click-able.

This is what I think would be ideal, but I understand resources are not unlimited.

**Comment by pjhampton** [comment]
> I prefer the Google goodie for twitter names to that of DuckDuckGo.

Can you send me a link to an example? I can't seem to trigger it on that search engine

**Comment by kirkins** [comment]
It's not always right at the top but it looks like this:

![untitled](https://user-images.githubusercontent.com/9503662/28227716-32be6fae-68a9-11e7-99c3-bee437a521ef.png)

https://www.google.ca/search?client=ubuntu&channel=fs&ie=utf-8&q=@duckduckgo

**Comment by pjhampton** [comment]
Ahh, I see. Thanks @kirkins 👍 
I will do some thinking regarding this over the weekend.

**Comment by kirkins** [comment]
@pjhampton I think you're right about the verified part. That might be due to the security issue you mentioned above.

**Comment by pjhampton** [comment]
Hey all,

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
