### ISSUE TITLE
Airlines: Doesn't trigger for all relevant queries

### ISSUE THREAD

**Issue by sahildua2305** [duckduckgo/zeroclickinfo-spice#3365]
### Description

The mentioned IA gets triggered for query [`ai 502`](https://duckduckgo.com/?q=ai+502&atb=v73-4_q&ia=flights). However, it doesn't get triggered for either of [`ai 137`](https://duckduckgo.com/?q=ai+137&atb=v73-4_q&ia=web) and [`ai 138`](https://duckduckgo.com/?q=ai+138&atb=v73-4_q&ia=web) queries.

## People to notify

@amoraleda 

---

Instant Answer Page: https://duck.co/ia/view/airlines

**Comment by moollaza** [comment]
Seems to be working for 2 out of 3 searches. In the 3rd case the API doesn't have results.

I'm not sure there's much we can do here for now.
