### ISSUE TITLE
Images: size filter

### ISSUE THREAD

**Issue by meaz** [duckduckgo/zeroclickinfo-spice#3366]
Hi,

I just have a quick question: when I choose to filter the images by size, if I choose "Large", do I also see the "Extra-large" images? Or just the ones that match what you have set as "large"?

Thanks

------
IA Page:  http://duck.co/ia/view/images 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon

**Comment by moollaza** [comment]
This has been implemented
