### ISSUE TITLE
Recipes: 

### ISSUE THREAD

**Issue by truehatch** [duckduckgo/zeroclickinfo-spice#3368]
yummly.com is a **_TERRIBLE_** website. Please STOP INFESTING MY SEARCH RESULTS WITH IT. This extension is very well made and all, but yummly is awful and it's driving me nuts trying to look for a recipe with this extension filling my search results with yummly spam. At least ALLOW ME to disable it if I want to.

------
IA Page:  http://duck.co/ia/view/recipes 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @bsstoner

**Comment by pjhampton** [comment]
Hey @truehatch!

Thanks for your issue. Unfortunately, this doesn't meet our standards for a PR / Issue. Please see our [Contributing Guide](https://duckduckhack.com/contributing.html). Please feel free to reopen with our issues template.

---

As for disabling this IA, it might be overkill but you can disable all IAs from your settings:

![screen shot 2017-07-19 at 9 01 26 am](https://user-images.githubusercontent.com/8960296/28356792-32a290f2-6c61-11e7-8d07-13b948c0b40c.png)
