### ISSUE TITLE
Dictionary Definition: allow "meaning" as keyword

### ISSUE THREAD

**Issue by santosh** [duckduckgo/zeroclickinfo-spice#3371]
For example, we can do [privacy definition](https://duckduckgo.com/?q=privacy+definition) to get open definition tab straight away. Case is not same when we do [privacy meaning](https://duckduckgo.com/?q=privacy+meaning), and we have to click on definition tab. Is this intended behavior? Could we add that feature?

------
IA Page:  http://duck.co/ia/view/dictionary_definition 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon

**Comment by pjhampton** [comment]
Hey @santosh 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.

**Comment by santosh** [comment]
It's fine. I'm glad DuckDuckGo has grown so much that it has made essential bug fixes only we could do in it's development. I'm glad I was part of it. 😄 👍
