### ISSUE TITLE
Currency Conversion: inverted result

### ISSUE THREAD

**Issue by fzzr-** [duckduckgo/zeroclickinfo-spice#3372]
_affected version: production_

Query `100 UDS in RUR` returns 100 RUR in USD - inverted result.

Query `100 UDS in RUB` returns correct result.

Current:
![screen shot 2017-07-20 at 19 35 48](https://user-images.githubusercontent.com/888526/28430004-83d63060-6d87-11e7-95aa-90c273c5468a.png)

Expected:
![screen shot 2017-07-20 at 19 35 33](https://user-images.githubusercontent.com/888526/28429986-7268f740-6d87-11e7-94ec-aa9f25c75beb.png)

There `RUR` = `RUB` = Russian Ruble.

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by adityatandon007** [comment]
@pjhampton can I take this

**Comment by pjhampton** [comment]
@adityatandon007 Sure thing. You will notice that you can't reproduce this bug in duckpan / beta. This is because it's actually a special triggering mechanism that DuckDuckGo have. 
All you need to do is update the alias to override it 👍

**Comment by fzzr-** [comment]
![screen shot 2017-07-26 at 17 17 15](https://user-images.githubusercontent.com/888526/28625955-66e34f26-7226-11e7-9d1d-2176ccca1e46.png)

@pjhampton, @adityatandon007,
Should I create new issue for it? I don't understand why and from where there `EUR`. Maybe it's something such as Levinstein's metric based correction `RUR -> EUR`. Looks like it is.

[link](https://duckduckgo.com/?q=%2449.00+in+RUR&t=osx&ia=currency)

**Comment by adityatandon007** [comment]
@fzzr- it will take some time to get it online. It is working fine in development environment. 
![screenshot from 2017-07-27 14-56-36](https://user-images.githubusercontent.com/25108385/28663957-7b42a208-72dc-11e7-89c5-a015f0a6b23a.png)

@pjhampton can you sent this to production env. 
@fzzr- it is not ideal to comment on closed issue. You can create a new issue if you want some help or you can join us on slack in #ask-anything channel for asking anything.

**Comment by fzzr-** [comment]
> it is not ideal to comment on closed issue. 

I'm not agree. Issue can be reopened if it needed. Also all subscribers get a notification. Why not?
_Entities must not be multiplied beyond necessity._

Anyway thanks you all 👍
