### ISSUE TITLE
Currency Conversion: Currency IA doesn't support "₽'" as Russian Ruble symbol

### ISSUE THREAD

**Issue by adityatandon007** [duckduckgo/zeroclickinfo-spice#3380]
The queries like `100 $ in £` trigger 

![screenshot from 2017-07-27 18-05-10](https://user-images.githubusercontent.com/25108385/28670440-4cf5e148-72f6-11e7-8da3-14f98f70cb04.png)

but queries like `100 $ in ₽` **doesn't**

![screenshot from 2017-07-27 18-05-53](https://user-images.githubusercontent.com/25108385/28670466-6933670e-72f6-11e7-8c1d-b2c1dafbaab1.png)

**My view** : I tried to look into this problem as I was expecting it to trigger for russian ruble query. I noticed that in `Currency.pm` we are using `\p{Currency_Symbol}` class selector and using it in regex. I don't get it first why we are doing that we have our own `currency codes` in `currencySymbols.yml` file. In fact what I deducted is that we aren't using `my $currencyCodes = LoadFile share("currencySymbols.yml");`, we have just loaded this but instead of using it we are using `\p{Currency_Symbol}`. So, what I can deduct is that `₽` sign is not present in that class selector. Now, I might be wrong, let me know if I am.

People to notify:
@pjhampton @moollaza  

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
@adityatandon007 Please see this comment: https://github.com/duckduckgo/zeroclickinfo-spice/issues/3379#issuecomment-318326790
I want to try and avoid creating issues for edge cases. Just create a master issue for Currency Edge cases and add all of these to that.
