### ISSUE TITLE
Cryptocurrency: Edge Cases

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-spice#3383]
### Description

For Cryptocurrency IA edge cases, please **comment them below** this issue and someone will fix them in due course.

![cryptocurrency_converter](https://user-images.githubusercontent.com/8960296/28711294-09d90a3c-737f-11e7-8907-dc1db4c6d5a8.png)

## People to notify

@duckduckgo/duckduckhack-contributors 

---

Instant Answer Page: https://duck.co/ia/view/cryptocurrency

**Comment by J-tt** [comment]
- Allows values to be inputted that are not numbers (should be a number field).
- Input field does not have `type="number"`.
- 100000000 BLK is 414798851 FTC, 1000000000 BLK (one extra zero) is 4147988510.0000005 FTC. Adding another zero brings the FTC to 41479885100 (note: this is a huge edgecase).
- Selecting BLK to BTC, then changing BLK to BTC will switch them, but doing it in reverse straight after will not cause a switch. (this applies to all combinations).
- Missing a space (eg 1btc to ltc vs 1 btc to ltc)  does not trigger the IA.
- Does not accept any mathematical formulas (not necessarily a bug)
- Does not accept written numbers in search string (eg: ten BTC to LTC)
- Does not trigger on the search term "cryptocurrency converter"

That's all I could find, thanks for your awesome contributions to Duck Duck Go!

**Comment by nalinbhardwaj** [comment]
> Does not trigger on the search term "cryptocurrency converter"

This is extremely weird since this case is checked for triggering in the test file as well. @pjhampton / @moollaza  can you check if something has changed in the internal files or something since this shouldn't happen(and doesn't on the beta server too).

**Comment by pjhampton** [comment]
Yeah, I can have a look 💛  
I need to look through my notes, but there was a reason why we didn't use number types. I will find it and comment when reviewing your PR 👍
