### ISSUE TITLE
Images: Broken layout

### ISSUE THREAD

**Issue by fzzr-** [duckduckgo/zeroclickinfo-spice#3384]
First row of previews is broken. The second and following lines is OK.

Activated (clicked) preview is oversized.

[Theme settings](https://duckduckgo.com/?kaj=m&kak=-1&kao=-1&kaq=-1&ko=s&kp=-2)
[Query](https://duckduckgo.com/?q=lion&iax=1&ia=images)

- **Safari** Version 10.1 (12603.1.30.0.34)
- **macOS** Version 10.12.4 (16E195)

![screen shot 2017-07-29 at 19 58 06](https://user-images.githubusercontent.com/888526/28746718-4701ed0a-7499-11e7-976f-8ca0d90e4936.png)

![screen shot 2017-07-29 at 20 11 12](https://user-images.githubusercontent.com/888526/28746816-1feb3c16-749a-11e7-9a65-b236b0193017.png)

------
IA Page:  http://duck.co/ia/view/images 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon

**Comment by moollaza** [comment]
@fzzr- I'm unable to reproduce. Is this still happening for you?

**Comment by fzzr-** [comment]
@moollaza No. Thx. Now all right.
![screen shot 2017-08-31 at 18 58 13](https://user-images.githubusercontent.com/888526/29932939-78b68906-8e7e-11e7-9e4a-be90d4025e23.png)
