### ISSUE TITLE
Forecast: results are for wrong location

### ISSUE THREAD

**Issue by kazcw** [duckduckgo/zeroclickinfo-spice#3386]
Searches for "weather Arlington, WA" or "weather 98223" return results for Washington, D.C. I'm not sure if this is the same issue as any of the other displacement bugs. #3323 refers only to zip codes and they seem to be only a short distance off; #2362 relates to city names being resolved to the wrong cities.

------
IA Page:  http://duck.co/ia/view/forecast 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @himanshu0113

**Comment by souravsingh** [comment]
@pjhampton Is the issue open?

**Comment by pjhampton** [comment]
Hey @souravsingh. No, I'm currently working through them. The DDG employees are currently working on this internally 👍
