### ISSUE TITLE
Stocks: Show after-hours price

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#3390]
In addition to the market hours price quote, we should show an after-hours price quote. See Google for example:

![google-stock-quote](https://user-images.githubusercontent.com/94173/28853684-3e00284e-776d-11e7-9c8a-609d992e1c7a.jpg)

[Requested on Twitter](https://twitter.com/dannybrooms/status/892503347466350592).

------
IA Page:  http://duck.co/ia/view/stocks 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @bsstoner

**Comment by pjhampton** [comment]
This info isn't in the API's response atm. I know the internal guys are currently in discussions to improve this IA. I'll place on hold for now.
