### ISSUE TITLE
Places: Potential Privacy Issue

### ISSUE THREAD

**Issue by jesusislord3** [duckduckgo/zeroclickinfo-spice#3392]
yelp remembers my details.

------
IA Page:  http://duck.co/ia/view/maps_places 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nilnilnil

**Comment by pjhampton** [comment]
@jesusislord3 Can you please tell me more? This can't be considered a good issue because I can't action on it.

**Comment by pjhampton** [comment]
Closing this for now...
