### ISSUE TITLE
Dictionary Definition: 

### ISSUE THREAD

**Issue by Movva** [duckduckgo/zeroclickinfo-spice#3393]
Not getting phonetics and also pronunciation.   

------
IA Page:  http://duck.co/ia/view/dictionary_definition 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon

**Comment by J-tt** [comment]
I see what you mean.

In the use case, 'define inundate' it shows a result that includes pronunciation and phonetics, whereas when that search term is actually used those elements are no longer present.

My best guess is that the wordnik API has stopped providing the required data (or may have changed their schema).

This is incorrectly flagged as suggestion, as it a regression.

@pjhampton unless I am missing something the label should probably be changed.

**Comment by moollaza** [comment]
@Movva Thanks for reporting. It looks like this is a bug on our end.

@J-tt The API responses look good so something else is breaking here.

**Comment by pjhampton** [comment]
I'm on it, thanks guys.

**Comment by moollaza** [comment]
This has been fixed. Fix should be live in a few hours
