### ISSUE TITLE
Currency Conversion: converts wrong way for Forint to GBP

### ISSUE THREAD

**Issue by spagy** [duckduckgo/zeroclickinfo-spice#3394]
these searches convert from GBP to HUF but they should convert the other way

10 forint to pounds
10 forint to gbp

replacing forint with huf fixes this

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
Thanks @spagy!
As this is an edge case I'm moving it to https://github.com/duckduckgo/zeroclickinfo-spice/issues/3382. Will fix soon 👍
