### ISSUE TITLE
Videos: Link to Github Issue is incorrect...

### ISSUE THREAD

**Issue by busticated** [duckduckgo/zeroclickinfo-spice#3395]
Hey there :wave:

Minor thing I noticed - the first link within the issues section over on the IA Page for the Videos IA is broken. 

<img width="750" alt="broken-link-videos" src="https://user-images.githubusercontent.com/367674/29087173-e883c4d6-7c29-11e7-9a4a-118c34536337.png">

Actual: `https://github.com/duckduckgo/zeroclickinfo-spice/issues/4329` 
Expected: `https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4329` [[4329]](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4329)

I'm happy to fix it but I'm not sure if these bits are editable by non-employee contributors. If so, feel free to point me in the right direction :)

-matt

------
IA Page:  http://duck.co/ia/view/videos 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @bsstoner

**Comment by kirkins** [comment]
@busticated it seems to me the videos IA is a spice https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Videos.pm

I think the duck.co is editable at this repo https://github.com/duckduckgo/community-platform

**Comment by kirkins** [comment]
@busticated though the bug you reference does seem to be in the wrong place.

**Comment by busticated** [comment]
ah, got it. thanks @kirkins

fwiw, i found this seemingly [related issue](https://github.com/duckduckgo/community-platform/issues/1485). seems like issues are collected across multiple repos but only the IA's home repo is used when rendering these links [[1]](https://github.com/duckduckgo/community-platform/blob/master/src/templates/github.handlebars#L20) [[2]](https://github.com/duckduckgo/community-platform/blob/master/lib/DDGC/Web/Controller/InstantAnswer.pm#L348) [[3]](https://github.com/duckduckgo/community-platform/blob/master/lib/DDGC/GitHub.pm#L472).

in this case the broken link will go away once the issue is resolved so i think it's ok to close this out for now.
