### ISSUE TITLE
Stocks: TSX results

### ISSUE THREAD

**Issue by TychoAI** [duckduckgo/zeroclickinfo-spice#3399]
I apologize for not knowing where to send a suggestion. My "issue" is that the Stocks instant answer would be well suited to pull stock prices from other markets. I'm interested in the Toronto Stock Exchange (TSX). A stock symbol for Blackberry would be BB.TO or TSX:BB. Currently, neither of these brings up stock price. BBRY brings up the Blackberry listing on Nasdaq.

------
IA Page:  http://duck.co/ia/view/stocks 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @bsstoner

**Comment by TychoAI** [comment]
Oh man...apologies for not labeling the issue correctly. Egg on my face. Should be Stocks: TSX results

**Comment by J-tt** [comment]
TSX may have to be a separate answer, as the existing stocks answer pulls from one API, which doesn't have data for TSX.

I have had a look around, but couldn't find a free to use API that would provide other market data.

If someone could point me in the right direction I would be happy to do the rest.

**Comment by TychoAI** [comment]
I can't find an obvious free-to-use API either, but I really don't know how DDG's pricing/funding for all this would go. It seems like the main quote results for TSX is from either:

- http://www.quotemedia.com/apifeeds/web_services
- https://www.xignite.com/product/global-stock-quote-data#/productoverview. 

The xignite has a free trial, so at least it can be tested, but it's limited for sure.

**Comment by pjhampton** [comment]
Hey @TychoAI 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.

**Comment by TychoAI** [comment]
Thanks for letting me know. A bit of a bummer, but hopefully it will come around in the future in some other form. Good luck.
