### ISSUE TITLE
METAR Information: 

### ISSUE THREAD

**Issue by royjr** [duckduckgo/zeroclickinfo-spice#3401]
Add support for 3 letter ICAO

------
IA Page:  http://duck.co/ia/view/metar 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @santigl

**Comment by santigl** [comment]
That would be a nice thing to have, @royjr.

@pjhampton, @moollaza: Would it be possible to use [Geo::IATA](https://metacpan.org/pod/Geo::IATA) to do the conversion? Unlike Geo::ICAO it has an SQLite backend.

**Comment by pjhampton** [comment]
Hey guys

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
