### ISSUE TITLE
IsItUp: Should this work for 504 cases?

### ISSUE THREAD

**Issue by sahiljuneja** [duckduckgo/zeroclickinfo-spice#3404]
Quora was opening up but threw the following on the website -

```
504. Gateway Timeout.

Quora is temporarily unavailable.

Please wait a few minutes and try again.
```

But when searching if the website is down on DDG, it said it was up. I have no knowledge about how exactly this works, honestly. But is this discrepancy because the website technically opens but throws a Gateway Error on the website itself?

------
IA Page:  http://duck.co/ia/view/is_it_up 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @rasikapohankar

**Comment by J-tt** [comment]
I personally think, that since the server returning the HTTP status is most likely acting as a load balancer and is telling you that the website is unavailable that the DDG Instant Answer should return down.

**Comment by rasikapohankar** [comment]
I'm wondering what other information the API returns, if it returns
something which helps to identify that the site is up but not functional we
can use that. I'll check what is returned.

**Comment by moollaza** [comment]
Closing. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
