### ISSUE TITLE
Currency Conversion:  wrong conversion for Belarusian Ruble.

### ISSUE THREAD

**Issue by Zettroke** [duckduckgo/zeroclickinfo-spice#3405]
Using wrong wallet code for Belarusian Ruble. BYR instead of BYN.
![2017-08-18_22-18-49](https://user-images.githubusercontent.com/15730710/29474175-3dc57c0a-8463-11e7-8ecd-be21c5313899.png)

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by kirkins** [comment]
Related information on BYR vs BYN

https://en.wikipedia.org/wiki/Belarusian_ruble#Third_ruble.2C_2016_-_present

**Comment by pjhampton** [comment]
Nice find guys. I'm on it!

**Comment by pjhampton** [comment]
Just an update here. There is an error with the current upstream preventing this from being solved. Hopefully, we can patch this soon 💛

**Comment by pjhampton** [comment]
Unfortunately, we can't solve with the current API 😞  Hopefully in the future!
