### ISSUE TITLE
Update Locale::Country Module

### ISSUE THREAD

**Issue by kirkins** [duckduckgo/zeroclickinfo-spice#3406]
### Description

I noticed that the new name of Czech Republic ("Czechia") doesn't trigger on apps that depend on the perl module `Locale::Country`.

https://duckduckgo.com/?q=country+code+Czechia&ia=web

I was able to download the source for this module and Czechia is there. So I think just updating this module will improve all Goodies and Spices which use it.

I'm not sure if there are some compatibility issues that will stop us from using the latest version of this module, if not it would be worth updating.

## People to notify

---

Instant Answer Page: https://duck.co/ia/view/{ID}

**Comment by kirkins** [comment]
I tried upgrading it myself and it seems like this would require upgrading to 5.24.

So this might not be possible without a lot of work in other places.

**Comment by moollaza** [comment]
@kirkins for now a manual alias can be created here: https://github.com/duckduckgo/duckduckgo/blob/db8acebf4a5fc17df47170117c4a49cf1025005f/lib/DDG/Meta/CountryCodes.pm

I swear I looked into this a while back. There was a related issue and I remember trying to solve it. I can't find whatever work I did on it though...

**Comment by mintsoft** [comment]
@moollaza @kirkins I think this is what you're looking for: https://github.com/SBECK-github/Locale-Codes/issues/3

**Comment by moollaza** [comment]
Closing. I'll make a task for the ops team to update the module internally.

Thanks

**Comment by moollaza** [comment]
Installed new version on my dev machine to confirm this will work:
https://moollaza.duckduckgo.com/?q=country+code+Czechia&t=h_&ia=answer
