### ISSUE TITLE
Stocks: Indian stock market feeds

### ISSUE THREAD

**Issue by mr-karan** [duckduckgo/zeroclickinfo-spice#3410]
Currently the IA is only for US equities. We can extend this IA to the Indian stock markets as well (NSE/BSE).

If the maintainers feel it's okay, I'd like to be assigned for this task 👍 

------
IA Page:  http://duck.co/ia/view/stocks 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @bsstoner

**Comment by pjhampton** [comment]
Hey @mr-karan. I'm sorry, we don't have access to that data 😢  There is no way to extend it through the current API. Also, only part of this IA is open source. The rest of the code is held and maintained internally. 

Another issue here is that we can't use another API as DDG is currently in an agreement with the upstream provider. 

Never say never, but just not now 👍 
Keep those suggestions coming!
