### ISSUE TITLE
Currency Conversion Bug: Non-integer values have title attribute falsely indicating error

### ISSUE THREAD

**Issue by jc86035** [duckduckgo/zeroclickinfo-spice#3413]
### Description
The currency converter works fine with non-integers, so the title text giving errors for values with 1 decimal place is a bit off.

## Steps to recreate
Search for [10.1 gbp to eur](https://duckduckgo.com/?q=10.1+gbp+to+eur) and hover over the box on the right. Title text is "Please select a valid value. The two nearest values are 10 and 11.". Change the value of the box on the left to 10.2. That box will then also have the title text. (The right box changes to 11.02 regardless, so it still works.)

## People to notify
none

---

Instant Answer Page: https://duck.co/ia/view/currency

**Comment by pjhampton** [comment]
@jc86035 what browser are you using + os?

**Comment by jc86035** [comment]
I am using Firefox 55.0.3 (the latest version) on macOS Sierra 10.12.6 (the latest version). It seems Firefox is adding the tooltip due to `type=number`.

**Comment by StefanoOrdine** [comment]
Also Chrome 60.0.3112.101 OS X 10.11.6 El Capitan.
