### ISSUE TITLE
NFL Games: not working

### ISSUE THREAD

**Issue by atestu** [duckduckgo/zeroclickinfo-spice#3422]
None of the example queries work.

![screenshot 2017-09-07 22 25 07](https://user-images.githubusercontent.com/22851/30193488-6d76ed90-941b-11e7-8167-36dda60610cc.png)   

------
IA Page:  http://duck.co/ia/view/sports_nfl_games 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @b1ake

**Comment by pjhampton** [comment]
Looks like we're back in business! Thanks for letting us know. 

![screen shot 2017-09-14 at 5 48 57 pm](https://user-images.githubusercontent.com/8960296/30442683-0d99316c-9975-11e7-99de-ab79fa736eb6.png)
