### ISSUE TITLE
Maps: Latitude switched with Longitude

### ISSUE THREAD

**Issue by Bilkow** [duckduckgo/zeroclickinfo-spice#3430]
When I search for a name of a city and "latitude", the data displays "switched"...
e.g. https://duckduckgo.com/?q=berlin+latitude&ia=maps shows in the bottom of the map `13.38333" N, 52.51667" E` when it should be `52°31′27″ N 13°24′37″ E`.

------
IA Page:  http://duck.co/ia/view/maps_maps 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nilnilnil

**Comment by javathunderman** [comment]
@Bilkow not able to replicate this. What browser are you using?

**Comment by Bilkow** [comment]
Firefox, but I'm not able to reproduce it anymore. Maybe it was a problem with the data source?
I'm closing it for now.
