### ISSUE TITLE
Islamic Prayer Times: 

### ISSUE THREAD

**Issue by abouadam90** [duckduckgo/zeroclickinfo-spice#3432]
Hi ! 
Can we display prayer times in 24h format for french people ?
Thanks

------
IA Page:  http://duck.co/ia/view/islamic_prayer_times 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @ozdemirburak

**Comment by abouadam90** [comment]
Can we also add queries for french people :
* horaires priere
* horaires salat
* salat al fajr
* salat al dohr
* salat al asr
* salat al maghrib
* salat al icha

Thanks

**Comment by abouadam90** [comment]
And finally, I can translate sentences from English to French.

Thanks

**Comment by ozdemirburak** [comment]
Language based triggers are not an option currently, it was discussed before here in the issue #3119. And the time format was discussed here in the issue #2372, but I don't know if it's OK to do so as that issue is still open.

**Comment by moollaza** [comment]
@abouadam90 thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports. 

I'm going to mark this as tolerated and close.
