### ISSUE TITLE
Goodreads: Switch API to HTTPS before Dec 4 to prevent breakage

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#3435]
From Goodreads:

>To better protect user privacy and security, we will be enabling HTTP to HTTPS redirection for all requests to goodreads.com on December 4th.
>
>To prevent your applications from breaking, please do one of the following before December 4th:
>
>    - Make sure your applications support HTTPS redirects
>    - **Update your applications to make only HTTPS requests**

We'll need to update all urls to use HTTPS as we do not support redirection from HTTP

------
IA Page:  http://duck.co/ia/view/goodreads 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @iammrigank

**Comment by azhz** [comment]
@moollaza Can I take this as a beginner?

**Comment by moollaza** [comment]
@azhz it's all yours!
