### ISSUE TITLE
Currency Conversion: BYN to UAH

### ISSUE THREAD

**Issue by molny** [duckduckgo/zeroclickinfo-spice#3443]
On the results page, there is no BYN currency in the zero-click info block, although it is present on Xe.com

DDG: ![image](https://user-images.githubusercontent.com/1726455/31708813-cae5e6dc-b3f8-11e7-88ef-0cad6d281fd1.png)

XE.COM: ![image](https://user-images.githubusercontent.com/1726455/31708941-2c3910da-b3f9-11e7-8f2c-31f35bb46748.png)

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
Hi there.

Yes, this is omitted from their API that is being used. I believe DDG would have to reach out to XE to ask them to add it in.

**Comment by moollaza** [comment]
This is a known issue. Marking as tolerated as we don't have an easy way to fix this currently.
