### ISSUE TITLE
Currency Conversion: 

### ISSUE THREAD

**Issue by heyVic** [duckduckgo/zeroclickinfo-spice#3446]
Hey, in the example it shows https://i.imgur.com/ztZLNRs.png the ratios on the side but when I do a search now for 500 USD to CAD for example, it doesn't https://i.imgur.com/VbkQc9L.png

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
Hey @heyVic 

Yes, this was removed.
