### ISSUE TITLE
GitHub: Support Emoji

### ISSUE THREAD

**Issue by b3nab** [duckduckgo/zeroclickinfo-spice#3449]
Very good work! 👍 
However, there is the possibility to support out-of-the-box emoji displayed on title's repository?
This would be a great and simple feature. :)
My 2cents.

------
IA Page:  http://duck.co/ia/view/github 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
