### ISSUE TITLE
DNS spice is not working

### ISSUE THREAD

**Issue by x-15a2** [duckduckgo/zeroclickinfo-spice#3452]
There is no IA return with MX Records or DNS records.

------
IA Page:  http://duck.co/ia/view/dns 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @OndroNR

**Comment by OndroNR** [comment]
Duplicate of #2727, which was not updated for year.

**Comment by moollaza** [comment]
I've re-enabled this Spice. Should be online in the next few hours.
