### ISSUE TITLE
Cryptocurrency: 

### ISSUE THREAD

**Issue by Joyggy** [duckduckgo/zeroclickinfo-spice#3456]
Ethereum Classic (ETC) would be great. ETC is currently in the top ten of the crypto currencies with the highest market cap. ETC exchange prices are also available at cryptonator.com.

------
IA Page:  http://duck.co/ia/view/cryptocurrency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
