### ISSUE TITLE
Yummly is a terrible web site and its integration into DuckDuckGo should be removed.

### ISSUE THREAD

**Issue by cooksey** [duckduckgo/zeroclickinfo-spice#3457]
------
IA Page:  http://duck.co/ia/view/recipes 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @bsstoner

**Comment by janasoroczak** [comment]
Agreed. Please give users the options to either turn it off or replace it with a better integration.

**Comment by ab810** [comment]
I would also like the option to remove the yummly feature. It's primarily a social media platform and requires login to be functional.

**Comment by moollaza** [comment]
Thanks for the comments. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports. However, feedback is welcome and can be reported through the "Feedback" button on DuckDuckGo.com

>Please give users the options to either turn it off

You can enable/disable all Instant Answers via the DDG settings, however, individual Instant Answers cannot be enabled or disabled currently.

> and requires login to be functional.

You shouldn't have to login to see the recipe. Yummly shouldn't prompt a login to visitors who click through the Instant Answer.

This will be marked as tolerated and closed.
