### ISSUE TITLE
Time: wrong location detected

### ISSUE THREAD

**Issue by riczorn** [duckduckgo/zeroclickinfo-spice#3460]
Please see the screenshot: I asked for local time and date, city and region were right, country was wrong, and so was timezone: I am in GMT+1 (Rome, Lazio, Italy) and not in (Rome, Lazio, US)

The search was: "What day is it"
Browser is FF 57.0 / canonical for Ubuntu, o.s. is Xubuntu 16.04

![istantanea_2017-11-22_09-41-03](https://user-images.githubusercontent.com/3932841/33117637-7bb9ad6e-cf69-11e7-8d97-c41cbacac005.png)

------
IA Page:  http://duck.co/ia/view/time 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by JamieKitson** [comment]
Similar issue here, I do live in Hemel Hempstead, but in the UK, not Canada.

![image](https://user-images.githubusercontent.com/1188974/33441066-aa81c4a2-d5e9-11e7-9236-19beff7c91d1.png)

**Comment by JamieKitson** [comment]
btw I do have DDG set to UK:

![image](https://user-images.githubusercontent.com/1188974/33441227-16558222-d5ea-11e7-8ef0-1ea016331153.png)

**Comment by johndunnf** [comment]
I had a similar problem today where it seems to have calculated the correct location almost (Toronto vs Ottawa) but since we are both in the same time zone that is ok. The problem was just the time of year and it said -6hrs instead of -5hrs. I have a separate Issue submitted on this now as well which has been assigned to @MrChrisW

**Comment by StewAlexanderACC** [comment]
Could this be related to the browser permissions? If you do not allow the browser to access your location, it will probably use an IP lookup to see where you are, if you are using a VPN or if your ISP is nowhere near you then the time will be off, right?
