### ISSUE TITLE
Actor Filmography: 

### ISSUE THREAD

**Issue by carmenpaez61** [duckduckgo/zeroclickinfo-spice#3462]
Keira Christina Knightley  esta en las peliculas Star Wars I, toda la saga de Piratas del Caribe a excepción de las 2 ultimas

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.


This will be marked as tolerated and closed.
