### ISSUE TITLE
Random Words: Refused to execute script ... because its MIME type ('application/json') is not executable

### ISSUE THREAD

**Issue by omegadrh** [duckduckgo/zeroclickinfo-spice#3466]
When attempting to use the spice/rand_word feature in DDG (e.g. https://duckduckgo.com/?q=random+words&ia=answer ) in my primary browser (Chromium | 62.0.3202.94 (Official Build) Built on Ubuntu , running on Ubuntu 17.04 (64-bit)), the results do not load. In the browser's console, an error message is present: ```Refused to execute script from 'https://duckduckgo.com/js/spice/rand_word/1-100-10' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.```

If it's possible to force that page to be served with a text/javascript MIME type, I assume it would be sufficient to resolve the issue. Otherwise, I'd think the script needs to be refactored to pull down just _actual_ JSON during its execution, and pass that returned data into the ```ddg_spice_rand_word(...)``` function, rather than inserting a new <script> DOM node.

------
IA Page:  http://duck.co/ia/view/rand_word 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @hunterlang

**Comment by moollaza** [comment]
Thanks! We made some changes recently and found a few APIs are sending us the wrong MIME type. As a result some stopped working. I will fix 👍

**Comment by moollaza** [comment]
@omegadrh @x-15a2 actually, I'm seeing this IA is working fine for me right now. 

https://duckduckgo.com/?q=random+words&t=ffab&atb=v91-1_j&ia=answer

Are you still experiencing issues?

**Comment by moollaza** [comment]
Ah I see it now in Chrome, Safari. Will fix 👍
