### ISSUE TITLE
Currency Conversion: 

### ISSUE THREAD

**Issue by vasanthaganeshk** [duckduckgo/zeroclickinfo-spice#3474]
Instead of mid-market values, can we have current values?

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
Sorry, but no. The upstream restricts DDG to the mid-market rates.
Thanks for the suggestion though 😄
