### ISSUE TITLE
Currency Conversion: 

### ISSUE THREAD

**Issue by Connor-Knabe** [duckduckgo/zeroclickinfo-spice#3479]
BTC price is not being updated correctly.

To replicate issue type BTC price in DDG it will show 13740 USD however actual price from xe.com is 14942 currently.

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
Hey @Connor-Knabe

Thanks! 13740 USD is the mid-market rate, which is what DDG are unfortunately bound to by the current agreement they have with XE. BTC is, as you can imagine a very volatile asset so it will have erratic deviations. 

There is a Cryptocurrency converter which should have a more up to date BTC price as they are live market rates https://duckduckgo.com/?q=ltc+to+btc&t=hg&ia=cryptocurrency
