### ISSUE TITLE
Cryptocurrency: Bitcoin Cash broken

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-spice#3480]
### Description

The upstream has changed the symbol from BCC to BCH, in turn, breaking the DDG cryptocurrency converter when selected.

## Steps to recreate

https://duckduckgo.com/?q=5+bitcoin+to+litecoin&t=hg&ia=cryptocurrency

and select BCC

## People to notify

---

Instant Answer Page: https://duck.co/ia/view/cryptocurrency

**Comment by moollaza** [comment]
@pjhampton thanks for reporting.

Is the fix simply replacing instances of `bcc` with `bch`?

**Comment by pjhampton** [comment]
Yep - simple fix @moollaza
