### ISSUE TITLE
XKCD: Alt text is being screwed up

### ISSUE THREAD

**Issue by Droobledores** [duckduckgo/zeroclickinfo-spice#3484]
Whenever I hover over the text, the symbols and (some) punctuation marks are being screwed up. Attached is a photo of what is happening. 
![screenshot 2018-01-10 at 10 58 42 am](https://user-images.githubusercontent.com/23317696/34782107-b15c7336-f5f5-11e7-8a8b-a48583223136.png)

------
IA Page:  http://duck.co/ia/view/xkcd 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @gaulrobe

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.

**Comment by moollaza** [comment]
@Droobledores  looks like this is an external API issue FWIW.

https://xkcd.com/1923/info.0.json
