### ISSUE TITLE
Currency Conversion: Bitcoin conversion does not match stated time

### ISSUE THREAD

**Issue by isaacmorgan** [duckduckgo/zeroclickinfo-spice#3487]
Bitcoin conversion rate reads:
    Mid-Market Rates: 2018-01-23 at 12:00 UTC
    1 XBT = 11186.4 USD
https://duckduckgo.com/?q=bitcoin+price&t=ffab&ia=currency

XE.com reads:
    23 Jan 2018 12:00 UTC XBT/USD close: 10195
https://www.xe.com/currencycharts/?from=XBT&to=USD&view=1D

The conversion rate and datetime do not match the recorded data. This is very confusing.
------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
Hey @isaacmorgan 
Please see: https://github.com/duckduckgo/zeroclickinfo-spice/issues/3479
