### ISSUE TITLE
Time: there should be an option to show times in 24h format. AM/PM is confusing for some of us

### ISSUE THREAD

**Issue by varepsilon** [duckduckgo/zeroclickinfo-spice#3488]
------
IA Page:  http://duck.co/ia/view/time 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
