### ISSUE TITLE
Time: Wrong Time Zone Info (Forgetting Daylight Savings Time)

### ISSUE THREAD

**Issue by ghost** [duckduckgo/zeroclickinfo-spice#3489]
I just searched the time for my area  by typing into duckduckgo.com "Current Time" and I live in Ottawa Canada. The search came back with Toronto not Ottawa but that is ok since we are in the same time zone...  the real problem was not that.. I am in the same time zone as Toronto, but it said -6 when it should say -5 (it is currently January 29th, 2018 at 04:51am  so it seems maybe it is or is not calculating what is called Daylight Savings Time or ) that is my guess as this would make the 1hr incorrect calculation as well. I am a regular non-programmer, but read some other error reports on this which mention the AI or script or something. So maybe it is not able to tell which days of the year we are in Daylight Savings Time (DST) which adjusts the hour back or forward one hour)

I have attached the correct settings from the world date and time webpage if that helps @MrChrisW 

Have a great day :) 

![duckducktime](https://user-images.githubusercontent.com/24431244/35504201-67b3e4ca-04b0-11e8-9c3c-739f10aa79a7.png)

and the incorrect info below (NOTICE -6) should be (-5)

![duckducktimewrong](https://user-images.githubusercontent.com/24431244/35504907-5f8dac52-04b2-11e8-83f3-3c5d8032b4fe.png)

The following page may provide helpful if any scripts need correction as it shows dates and time that the daylight savings time start and end etc. 
https://www.timeanddate.com/time/zone/canada/ottawa

(CORRECT DATE INFO BELOW FOR BI-ANNUAL 1 HOUR TIME CHANGE) 
I hope I have helped a little for a non-programmer type :) Thanks for all your hard work 

![duckducktime3](https://user-images.githubusercontent.com/24431244/35505213-654bdc76-04b3-11e8-8f6a-a948b950ede8.png)

------
IA Page:  http://duck.co/ia/view/time 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by Jaysds1** [comment]
This would be more of an TimeAndDate.com bug.

**Comment by johndunnf** [comment]
well the date and time website is accurate.. the only place it shows
incorrectly is on the duckduckgo webpage when that page showed the time
with the wrong timezone in the duckduckgo results page.. Once I go out to
the actual date and time.com website everything is accurate. So duckduckgo
pulls info from the dateandtime.com website but somehow changes it to be in
the wrong -6 instead of -5 hours for daylight savings
