### ISSUE TITLE
Air Quality Index: only includes AQI data for the USA

### ISSUE THREAD

**Issue by cawleybg** [duckduckgo/zeroclickinfo-spice#3493]
We should be able to get AQI info for cities across the globe, most of which are readily available. https://aqicn.org/

------
IA Page:  http://duck.co/ia/view/aqi 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @schluchc

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.

**Comment by moollaza** [comment]
AFAIK there isn't an available API that provides this info for the globe anyways. I tried looking years ago when this was created.
