### ISSUE TITLE
NPM Search: RunKit Integration Missing?

### ISSUE THREAD

**Issue by tolmasky** [duckduckgo/zeroclickinfo-spice#3499]
The DuckDuckGo npm instant answer used to have a link to try the package right in your browser through npm.runkit.com/package-name (this is the same link that appears on the npm website itself), but now seems to no longer be there. Any chance we can put it back in? I'm happy to provide the image resources, etc.

------
IA Page:  http://duck.co/ia/view/npm 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @remixz

**Comment by moollaza** [comment]
@tolmasky Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
