### ISSUE TITLE
Editor: None of the examples seem to work.

### ISSUE THREAD

**Issue by ghost** [duckduckgo/zeroclickinfo-spice#3500]
When I search for
Ruby Scratchpad, Ruby Syntax Highlighter, or rubyscript scratchpad or syntax highlighter it doesn't work. 
This is also the case for python and JavaScript.

------
IA Page:  http://duck.co/ia/view/editor 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jmg

**Comment by moollaza** [comment]
This IA is offline. DuckDuckHack is in maintenance mode and this IA will not be re-enabled for now.
