### ISSUE TITLE
Currency Conversion: Is this IA offline?

### ISSUE THREAD

**Issue by geekpete** [duckduckgo/zeroclickinfo-spice#3505]
Sample seems not to work:
https://duckduckgo.com/?q=convert%20499%20usd%20to%20cad&ia=currency

and no other combinations seem to work, also tried a few browsers.   

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
Hi @geekpete 

It seems that this IA is offline. I'm sure somebody will reactive soon.

**Comment by thewilloftheshadow** [comment]
dyk why it is offline?

**Comment by moollaza** [comment]
Looks like the API switched to HTTPS. I'll update the code accordingly as we can't follow the redirect.

**Comment by moollaza** [comment]
We're releasing the fix. Should be back online shortly.
