### ISSUE TITLE
Time: Jerusalem

### ISSUE THREAD

**Issue by Daliaothman** [duckduckgo/zeroclickinfo-spice#3507]
Hi @MrChrisW, 
For political reasons and in keeping with International Law, it is highly problematic to add Israel to Jerusalem. This is not recognized internationally and in fact normalizes the occupation of a city. It would be great if this is adjusted to the name of the city without the country and much appreciated by millions of people across the world. 
Thank you, 
D.

------
IA Page:  http://duck.co/ia/view/time 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by moollaza** [comment]
@Daliaothman thanks for sharing your concern. 

I suspect you mean that when you search for "Time Jerusalem" the instant answer shows "Jerusalem, Israel". 

![time jerusalem at duckduckgo 2018-04-17 12-41-47](https://user-images.githubusercontent.com/873785/38884214-ea03e578-423c-11e8-8dad-eadd8163b799.png)

If this is what you're referring to, unfortunately this data is not something we're in control of. We get these results, including the the city and country from TimeAndDate.com.

I would suggest you approach them to have that changed. If they do, it would reflect on DuckDuckGo, as well as any other website using their data.

As well, DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports. I don't believe this is a critical issue (this Instant Answers isn't broken) so this will be marked as tolerated and closed.
