### ISSUE TITLE
GitHub: Option to keep snippit open

### ISSUE THREAD

**Issue by 1e4** [duckduckgo/zeroclickinfo-spice#3509]
It would be great if there was an option to keep the repo info open, it becomes quite annoying when searching to open it on every new search.

![firefox_2018-04-22_16-29-56](https://user-images.githubusercontent.com/3780490/39096038-6b0c0d06-464a-11e8-901d-2aa2f43df75a.png)

------
IA Page:  http://duck.co/ia/view/github 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
