### ISSUE TITLE
Rounding error with currency

### ISSUE THREAD

**Issue by peletiah** [duckduckgo/zeroclickinfo-spice#3514]
It seems there is a rounding error when displaying currencies.
In the past few days 1 GBP was around 1.145xx EUR, DuckDuckGo displayed it as 1.14 (So does Google btw). I copied this value to a spreadsheet and was surprised today when there was a discrepancy between a calculation in my spreadsheet and what I got from an online-source.

Since a properly rounded value of 1.15 would have led to a similarly wrong result, I guess this can't really be fixed in a satisfying way, but I think a third or even fourth decimal place would help to get more accurate results.

[Here are screenshots](https://imgur.com/a/4nMVVAU) of the issue.

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by moollaza** [comment]
@peletiah thanks for reporting.

As far as I can tell though, there isn't a rounding error. The API response we're getting shows 
`"conversion-rate": "1 GBP = 1.14499 EUR",`.

It looks like Google now shows 1.15. Our result should change today depending on what the value is when the XE API updates.

https://duckduckgo.com/js/spice/currency/1/gbp/eur

**Comment by moollaza** [comment]
@peletiah it looks like we're rounding after multiplying the input amt by the rate from the API. Then we round the result to 2 decimal places:

1 GBP to EUR = 1.14499 * 1 = 1.14499; Rounded = **$1.14**
1 GBP to EUR = 1.14499 * 2 = 2.28998; Rounded = **$2.29**

I think this approach is more accurate? 

**Code:** https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/cryptocurrency/cryptocurrency.js#L64
