### ISSUE TITLE
SoundCloud: 

### ISSUE THREAD

**Issue by WichalRangai** [duckduckgo/zeroclickinfo-spice#3515]
all the streams are unavailable!?

https://duckduckgo.com/?q=DOIN%27+THE+VOOM+VOOM&t=osx&ia=audio&iai=https%3A%2F%2Fsoundcloud.com%2Fnindicapinion%2Fin-the-voom-red-add
   
------
IA Page:  http://duck.co/ia/view/sound_cloud 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jdan

**Comment by moollaza** [comment]
Thanks for reporting. Looks like the API is having issues.

I will take this offline for now.
