### ISSUE TITLE
AlternativeTo: 

### ISSUE THREAD

**Issue by x-15a1** [duckduckgo/zeroclickinfo-spice#3519]
This SPICE IA is not working, no alternatives are returned and no IA UI is displayed.

------
IA Page:  http://duck.co/ia/view/alternative_to 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @vikashvverma

**Comment by moollaza** [comment]
@x-15a1 I've re-enabled this IA. Please let me know if it's not working in the next few hours 👍

**Comment by x-15a1** [comment]
Hey Zaahir,
How have you been doing? It's great hearing from you.
OK, I did some testing on this an here's what I've found:

Using the samples from https://duck.co/ia/view/alternative_to here's what I find:

- None of the samples work as posted, using "alternative"
- If "alternative" is changed to "alternatives" the IA seems to work but it gives all answers from the Images IA: https://duckduckgo.com/?q=alternatives+to+notepad&atb=v105-7&ia=images

- The sample on https://duck.co/ia/view/alternative_to shows results from AlternativeTo using the Software IA: https://duckduckgo.com/?q=alternative%20to%20notepad&ia=software

- I'm unable to get any results that are not displayed from the Images IA

John Mustain
Death is Conquered Though We Slumber- Seven is the Perfect Number

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by moollaza** [comment]
Thanks for digging deeper into this! I've found the problem and am working on a fix now. Should be able to get it out today 👍

**Comment by x-15a1** [comment]
Hey Zaahir,
I have a couple of things to run past you, if I may:

- Can you give me the status on the Alternative To IA? I'm using the samples at https://duck.co/ia/view/alternative_to and the IA isn't triggering.
- I've verified what [this subReddit post](https://www.reddit.com/r/duckduckgo/comments/8lm6tb/forward_slash_goes_straight_to_ddg_search_field/) is saying about forward slash not working as intended when using Firefox. Can one of the Devs give this a look?

I thought that I had 1 other, but I'm not finding it now. Thanks for your help on these, have a great weekend!

John Mustain
Death is Conquered Though We Slumber- Seven is the Perfect Number

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by moollaza** [comment]
> - Can you give me the status on the Alternative To IA? I'm using the samples at https://duck.co/ia/view/alternative_to and the IA isn't triggering.

@x-15a1 sorry about the delay, I forgot to finish fixing the IA. I'm releasing the Spice repo now. The fix will go out during our next release on Monday.

> I've verified what [this subReddit post](https://www.reddit.com/r/duckduckgo/comments/8lm6tb/forward_slash_goes_straight_to_ddg_search_field/) is saying about forward slash not working as intended when using Firefox. Can one of the Devs give this a look?

I'll make an internal issue for this, but it sounds like very low priority. If we see more complaints the priority will bubble up but we haven't seen anything yet AFAIK.

**Comment by x-15a1** [comment]
Hey Zaahir,
Thanks for the info. If you have a minute, let me know when the release goes out and I'll test on my end.
I agree with your note regarding forward slash in Firefox, especially since they can use the H key as an alternate.

Thanks!
John

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by moollaza** [comment]
@x-15a1 this IA is now online and working for me 👍 

https://duckduckgo.com/?q=alternative+to+vim&t=ffab&atb=v120-6x_&ia=software

**Comment by x-15a1** [comment]
👍👍👍 Thanks, I really appreciate your work on this and thanks for keeping me in the loop!

John Mustain
Death is Conquered Though We Slumber- Seven is the Perfect Number

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
