### ISSUE TITLE
Currency Conversion: 

### ISSUE THREAD

**Issue by Hornstinger** [duckduckgo/zeroclickinfo-spice#3521]
More of a feature than an issue: when you input a number can both the input and output auto display commas so 1000000 (1 million) is displayed as 1,000,000 and so on?

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by samuellawrentz** [comment]
Hi,
I'm new to open source contribution. Can someone please guide me or give me an head-start for this issue. I would love to contribute. 
I went through this thread and found it useful - https://stackoverflow.com/q/2901102/8252164

Can the same methodology be applied for inserting commas?

**Comment by moollaza** [comment]
@Hornstinger Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.

---

@samuellawrentz as mentioned, DuckDuckHack is not currently accepting contributions except for critical bugs. Please visit https://duckduckhack.com for more details. We'll update that site when we know what the future of DuckDuckHack will look like.
