### ISSUE TITLE
Airlines: displayed flight information is correct, however click-through is showing the next scheduled, not current flight

### ISSUE THREAD

**Issue by sychare** [duckduckgo/zeroclickinfo-spice#3522]
## Search term
BA0208

## Result
![image](https://user-images.githubusercontent.com/731250/42023092-efd24780-7ab6-11e8-8023-8f8e0f98d122.png)

Clicking on that takes me through to https://www.flightstats.com/v2/flight-tracker/BA/208 which is listing the next *scheduled* flight (departing on the 28th), not the current flight:
![image](https://user-images.githubusercontent.com/731250/42023213-34028866-7ab7-11e8-84e4-57e145d6b232.png)

Not a huge issue, but all the same it's not what I'd expect to happen.

## Expected outcome
(If possible) link through to the same flight details as shown in the instant answer, e.g. https://www.flightstats.com/v2/flight-tracker/BA/208?year=2018&month=6&date=27&flightId=964065139 in this case.

------
IA Page:  http://duck.co/ia/view/airlines 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @amoraleda

**Comment by moollaza** [comment]
@sychare 
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
