### ISSUE TITLE
Time: 

### ISSUE THREAD

**Issue by x-15a2** [duckduckgo/zeroclickinfo-spice#3523]
It appears that in some instances, the local time returned is off by 1 hour, but if the same location is specified, the correct time is displayed. [Please see this subReddit post for details.](https://www.reddit.com/r/duckduckgo/comments/8w55z6/time_query_off_by_one_hour/)   

------
IA Page:  http://duck.co/ia/view/time 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by moollaza** [comment]
Duplicate of #3489
