### ISSUE TITLE
Currency Conversion: Issue with decimals

### ISSUE THREAD

**Issue by h4z4rd0uSm1ke** [duckduckgo/zeroclickinfo-spice#3524]
If you enter decimals with '.' instead of ','  it doesn't show the result of the conversion, when trying to convert from BTC to EUR. However it works wih ',' (Which is not bad beacuse we do like that in Spain, but I think it should work both ways). Tested from Spain.
------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
Yeah, I think that is a good idea. But the community development effort is on ice at the moment. Maybe one day 😄
