### ISSUE TITLE
Air Quality Index Instant Answer not displaying

### ISSUE THREAD

**Issue by L33TN3RD** [duckduckgo/zeroclickinfo-spice#3526]
Air Quality Index not displaying on duckduckgo.com
Only available for USA???

------
IA Page:  http://duck.co/ia/view/aqi 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @schluchc

**Comment by moollaza** [comment]
@L33TN3RD it looks like the API has gone offline for maintenance, so the IA will not work for now.

> Only available for USA???
Yes, this API only supports queries for US Zip Codes
