### ISSUE TITLE
Indeed Jobs: no context menu

### ISSUE THREAD

**Issue by stubhead** [duckduckgo/zeroclickinfo-spice#3528]
right-clicking on one of the instant entries doesn't provide the ability to open the corresponding link in a new window, and the js default action for left-clicking is to open the link in the same window, forcing navigation away from the duck duck go results page.

proposed change : either
1- change default action to open link in new page or tab, or
2- re-context right click

------
IA Page:  http://duck.co/ia/view/indeed_jobs 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @tagawa

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

In order to open the link in a new tab, CTRL+Click works. I think a middle click will work again.

This will be marked as tolerated and closed.
