### ISSUE TITLE
Maven: the links to access content on Maven are broken

### ISSUE THREAD

**Issue by yoeo** [duckduckgo/zeroclickinfo-spice#3533]
## Steps to reproduce the issue

Goto https://duckduckgo.com/?q=maven+elasticsearch-spark&ia=software
Click on "More at Maven"

### Expected
Opens Maven search result page for `elasticsearch-spark`
https://search.maven.org/search?q=elasticsearch-spark

### Current
Opens Maven search home page
https://search.maven.org/#search%7Cga%7C1%7Celasticsearch-spark

### Note
All the other links in the Maven view are broken too.

--
Thank you.

------
IA Page:  http://duck.co/ia/view/maven 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nicoulaj

**Comment by adityatandon007** [comment]
I confirm that this issue can be closed as it shows the correct page now.
