### ISSUE TITLE
Wrong conversion rate for small amounts 

### ISSUE THREAD

**Issue by CruiseMan** [duckduckgo/zeroclickinfo-spice#3537]
Notice when query price for decimal value gives wrong rate !
OK
![screenshot 2018-08-29 12 11 53](https://user-images.githubusercontent.com/15807643/44809880-dad19080-ab84-11e8-8b0a-4f1e5171c485.png)

WRONG
0.007428/0.01 = 0.7428 - Duck version
0.007428/0.0063 = 1.179047619 - google verion
![screenshot 2018-08-29 12 12 34](https://user-images.githubusercontent.com/15807643/44809882-db6a2700-ab84-11e8-8ca2-34bd72dc966f.png)

**Comment by raufabr** [comment]
If this issue is still open, I would like to have a go at fixing this.

**Comment by moollaza** [comment]
Hi @raufabr, it's still open so please go ahead!

**Comment by raufabr** [comment]
@moollaza I need some help with setting up my Dev environment. 

I'm following the documentation here https://duckduckhack.gitbook.io/duckduckhack-docs/setup-dev-environment.

I can't create a copy of the DuckDuckGo environment. This link is broken -> https://codio.com/duckduckgo/duckduckhack

Is this something that has expired, and do I need to set up my environment locally now?

**Comment by moollaza** [comment]
@raufabr sorry, DuckDuckHack is in maintenance mode so the dev environment isn't really supported anymore. Codio was removed when maintenance mode began.

Unfortunately if you're unfamiliar with DuckDuckHack, and the dev setup, now isn't the best time to get involved. 

If you'd like to try setting up DuckPAN on linux or in a VM (I'm not sure if the VM still works), there are instructions here: https://github.com/duckduckgo/p5-app-duckpan/blob/master/README.md
