### ISSUE TITLE
Currency Conversion: Display the used exchange rate

### ISSUE THREAD

**Issue by anohren** [duckduckgo/zeroclickinfo-spice#3538]
It wouldn't hurt to display the exchange rate used for a currency conversion, so that I don't have to manually change my amount to "1" just to see it after doing a "123.45 ABC to XYZ" search. Perhaps as a footnote immediately below the respective drop-down boxes?

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by moollaza** [comment]
@anohren Thanks for the suggestion. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
