### ISSUE TITLE
SoundCloud: IA Not Working

### ISSUE THREAD

**Issue by x-15a2** [duckduckgo/zeroclickinfo-spice#3541]
this spice IA is not returning any results from SoundCloud (including using the example queries. 
https://duckduckgo.com/?q=soundcloud%20MGMT&ia=audio
https://duckduckgo.com/?q=sc%20the%20new%20yorker&ia=audio  

Reported on DDG subReddit at: https://www.reddit.com/r/duckduckgo/comments/9eq5fh/the_soundcloud_ia_doesnt_seem_to_be_working/

------
IA Page:  http://duck.co/ia/view/sound_cloud 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jdan

**Comment by moollaza** [comment]
Thanks @x-15a2 . Unfortunately this IA has gone offline for the forseeable future. 
Spotify has changed the API and new requires OAuth which Spices are not capable of handling.

I'll comment on the Reddit post.
