### ISSUE TITLE
Actor Filmography: 

### ISSUE THREAD

**Issue by h34dless** [duckduckgo/zeroclickinfo-spice#3544]
**Current Behaviour:**
Normal results are showed

   **Expected Behaviour:**
A Filmographie with the searcht actor/actress should appear

------
IA Page:  http://duck.co/ia/view/movies_filmography 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @whalenrp

**Comment by moollaza** [comment]
This instant answer is offline. Closing as tolerated.
