### ISSUE TITLE
Forecast: Support more languages

### ISSUE THREAD

**Issue by pablojimpas** [duckduckgo/zeroclickinfo-spice#3545]
It would be great if Forecast supported keywords of more languages instead of just "weather".

Any chance of adding this improvement?

------
IA Page:  http://duck.co/ia/view/forecast 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @himanshu0113

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

I believe there was a previous issue opened about doing this and possibly some work done. It's something we'd like to do, but given the current state of DuckDuckHack, it's not critical so it's not a current focus.

This will be marked as tolerated and closed.
