### ISSUE TITLE
Forvo: Not launching

### ISSUE THREAD

**Issue by x-15a2** [duckduckgo/zeroclickinfo-spice#3551]
This IA does not respond to any of the samples given.

------
IA Page:  http://duck.co/ia/view/forvo 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @alexbaforvo

**Comment by moollaza** [comment]
This IA has gone offline. I don't think we have API access anymore so I don't expect it to come back online anytime soon.
