### ISSUE TITLE
Spotify: Doesn't work anymore

### ISSUE THREAD

**Issue by samuelwight** [duckduckgo/zeroclickinfo-spice#3556]
This instant answer no longer works anymore, with the example given or otherwise. Might be an upgraded API issue?

------
IA Page:  http://duck.co/ia/view/spotify 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jmperez

**Comment by JMPerez** [comment]
@samuelwight you are right. There was a breaking change in Spotify's Web API.

[The requests need to be signed with an access token](https://developer.spotify.com/community/news/2017/01/27/removing-unauthenticated-calls-to-the-web-api/), which means we would need to add some logic that fetches an access token and caches it until it expires to avoid obtaining a new one per request.

I don't know how to implement this and whether this is possible to do. Do you happen to know about similar IAs that need authentication?

**Comment by moollaza** [comment]
@samuelwight this Instant Answer is offline, which is mostly why it's not working. Our automated system likely took it offline when the API calls stopped working.

@JMPerez unfortunately open source Spice Instant Answers can't currently handle OAuth style requests that require multiple calls. 

Given that DuckDuckHack is in maintenance mode this is unlikely to come back online in the near future.
