### ISSUE TITLE
Dictionary Definition: Wrong word defined

### ISSUE THREAD

**Issue by Nibbler999** [duckduckgo/zeroclickinfo-spice#3557]
### Description

Searching `define rort` returns the definition of the word `tort` which is a different word.

## Steps to recreate
https://duckduckgo.com/?q=define+rort&ia=definition

---

Instant Answer Page: https://duck.co/ia/view/dictionary_definition

**Comment by moollaza** [comment]
@Nibbler999 Thanks for reporting. It looks like this is an edge-case where the API is returning the wrong result. 

Given that DuckDuckHack is in maintenance mode and this is an edge case, I'm going to mark this as tolerated and close it.

If we notice any more issues I will reach out to Wordnik, or possibly update the code.
