### ISSUE TITLE
Forecast: Searching for Tel Aviv returns weather for Chicago

### ISSUE THREAD

**Issue by cascer1** [duckduckgo/zeroclickinfo-spice#3560]
searching for `weather for Tel Aviv` and `weather for Tel Aviv Israel` returns the weather forecast for Chicago, IL.

I expected to receive the weather forecats of Tel Aviv, Israel.

![image](https://user-images.githubusercontent.com/7243299/47956304-b0e08400-dfa2-11e8-9d72-60f9d9379ab6.png)

------
IA Page:  http://duck.co/ia/view/forecast 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @himanshu0113

**Comment by moollaza** [comment]
@cascer1 thanks for reporting. We are aware of the issue and currently working on a fix. Marking as duplicate of #3561 where I am combining similar issues.

**Comment by moollaza** [comment]
Duplicate of #3561
