### ISSUE TITLE
Forecast: Relevancy Issues -- Please Read Before Opening New Forecast Issues

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#3561]
### Description
There are known relevancy issues with the Forecast Instant Answer which we are investigating and fixing.

The best way to report any new relevancy issues is via the "Feedback" button on the Search Results page. This feedback is monitored more closely now that DuckDuckHack is in [Maintenance Mode](https://duckduckhack.com), and compiled into daily reports which is reviewed internally.

If needed, you can also leave a comment here.

---
Instant Answer Page: https://duck.co/ia/view/forecast

**Comment by moollaza** [comment]
**Update:** 
We've released a fix which should address several of these and other reported issues. Still some bugs though we plan to iron out 👍

**Comment by gardon** [comment]
I can't get it to return Weather for São Paulo city, no matter how I write it, it always returns some small town called Iacanga, São Paulo (São Paulo in this is the state name)

**Comment by moollaza** [comment]
> I can't get it to return Weather for São Paulo city, no matter how I write it, it always returns some small town called Iacanga, São Paulo (São Paulo in this is the state name)

@gardon it looks like that's an upstream issue. Searching Sao Paulo City on darksy.net produces the same result unfortunately. If you'd like to contact them they might be able to fix or offer an explanation?

**Comment by gardon** [comment]
I was going to mention that @moollaza, however, if you type "São Paulo, São Paulo" on DarkSky (City, state) it works, but not within DDG
