### ISSUE TITLE
GitHub: [Feature] "Copy to clipboard" fuction

### ISSUE THREAD

**Issue by muuvmuuv** [duckduckgo/zeroclickinfo-spice#3563]
Would be nice to just click on the link an it will be copied to the clipboard

------
IA Page:  http://duck.co/ia/view/github 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by moollaza** [comment]
@muuvmuuv Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
