### ISSUE TITLE
Location Sunrise/Sunset: Wrong time format

### ISSUE THREAD

**Issue by ehamberg** [duckduckgo/zeroclickinfo-spice#3565]
Even though my language is set to _English United Kingdom_ and my location is set to Norway (and my browser sends `en-UK` in its `Accept-Language` header) the times are still shown in a `en-US` format (12-hour, AM/PM).

------
IA Page:  http://duck.co/ia/view/sun_rise_set 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @iambibhas

**Comment by moollaza** [comment]
Thanks for the suggestions. I don't believe this Instant Answer has support for showing the time in other formats currently. It looks like AM/PM is hardcoded.

Seeing as DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports, this will be marked as tolerated and closed.
