### ISSUE TITLE
Currency Conversion: Wrong result for HUF-BTC (XBT)

### ISSUE THREAD

**Issue by kelna** [duckduckgo/zeroclickinfo-spice#3566]
For the search query "x HUF in BTC" or "x HUF in XBT" where x is any number, the result is wrong. It shows x HUF = x BTC, so the two values match.

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by moollaza** [comment]
@kelna thanks for reporting. Certainly looks like a bug, I assume its related to how small the exchange rate is and a rounding error.

For reference: https://www.xe.com/currencyconverter/convert/?Amount=123456&From=HUF&To=XBT
