### ISSUE TITLE
Maps: 

### ISSUE THREAD

**Issue by joshuaneedham** [duckduckgo/zeroclickinfo-spice#3572]
A pop-up asked me which app to open when clicking on maps in the search results I inadvertanly selected Apple Maps and I would like to set it to Google maps but cannot find any information on either unsetting or selecting a new app to use.

------
IA Page:  http://duck.co/ia/view/maps_maps 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nilnilnil

**Comment by moollaza** [comment]
@joshuaneedham are you referring to the 'Directions' button we display?
![maps example](https://user-images.githubusercontent.com/873785/50303881-751f5200-045c-11e9-9106-f0142a04f3e7.png)

You can click the small down arrow/triangle below that to choose a different map provider, such as Apple, Bing, etc. After that clicking 'Directions' will open that result using the selected map provider.

**Comment by joshuaneedham** [comment]
I've tried multiple times without success it keeps happening Apple Maps
regardless of selection.

Sincerely,
Joshua Needham
(801)452-1836

Sent from a mobile device that has a mind of own so please excuse the
random use of odd words, and enjoy deciphering.

**Comment by moollaza** [comment]
@joshuaneedham thanks, on what device?

**Comment by moollaza** [comment]
I just tried on my mac (Firefox) and iPhone, and both worked fine. I was able to choose different providers, and clicking the Directions button opened in the selected provider.

**Comment by joshuaneedham** [comment]
It did with today I'm on a Mac. It previously was not working properly. My
main inquiry was the wrong of the default via a pop-up that I received
once. I'm not able to reset the default was my main concern. I want it to
default to Google maps not require a selection.

Sincerely,
Joshua Needham
(801)452-1836

Sent from a mobile device that has a mind of own so please excuse the
random use of odd words, and enjoy deciphering.

**Comment by moollaza** [comment]
> I'm not able to reset the default was my main concern. I want it to default to Google maps not require a selection.

When you change the Maps provider from that dropdown, or from the [Settings Page](https://ddg.gg/settings) it should be remembered. We use an anonymous settings cookie for this. If you delete the cookie though it won't be remembered.

On the settings page we explain how you can use a bookmarklet, or our anonymous cloud-save as alternatives if you frequently clear your cookies.

For any Apple devices, the default maps provider is set to Apple if the setting doesn't have a user-selected default.
