### ISSUE TITLE
Time: Consider having the result "live" by continuously tracking the time

### ISSUE THREAD

**Issue by leonid-s-usov** [duckduckgo/zeroclickinfo-spice#3578]
Would be nice IMO if the result was not static time at the moment of the search, but rather a real clock counting on.

------
IA Page:  http://duck.co/ia/view/time 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.

**Comment by leonid-s-usov** [comment]
Yeah, I've read about the maintenance mode after the issue was created. Maybe you should consider removing the feedback button, cause that's what I used to generate this issue.
![image](https://user-images.githubusercontent.com/3144935/52371776-12f7cc00-2a5f-11e9-93d2-bad0e6be7265.png)
