### ISSUE TITLE
Forecast: 

### ISSUE THREAD

**Issue by webmind** [duckduckgo/zeroclickinfo-spice#3579]
when requesting the weather for 'hell' in duckduckgo, it responds with the weather for Michigan, instead of 'Hell, Norway' 

------
IA Page:  http://duck.co/ia/view/forecast 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @himanshu0113

**Comment by moollaza** [comment]
@webmind it looks like there's a "Hell, Michigan" which is why you're seeing this result. Unfortunately you'll need to specify "Norway" in your query to see the results for that country.
