### ISSUE TITLE
Nutrition: Ensure units in query match selected unit in result

### ISSUE THREAD

**Issue by nikgervae** [duckduckgo/zeroclickinfo-spice#3585]
I did a duckduckgo search of "olive oil calories per tablespoon" and was shown 39.78 Calories in nice, large type at the top of the results page (courtesy of Nutritonix).

Fortunately, I'm the type to keep reading, and saw every other result below quoting 119 Calories.

Turns out that nice, large 39.78 was for a TEASPOON of olive oil, which was not what I had searched for. I searched for a TABLESPOON. There was an oh-so-unobtrusive pop-up menu under the nice, learge 39.78 that let me choose other measures, but, you know, I had already included the measure in my search.

If duckduckgo is going to put an answer right up front in great big type, it could at least try to be correct.

------
IA Page:  http://duck.co/ia/view/nutrition 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @bsstoner

**Comment by moollaza** [comment]
@nikgervae thanks for reporting and sorry the answer wasn't correct.

It looks like there is a bug in the triggering of this Instant Answer. We don't appear to pass along any specified units or check that the selected option matches the unit specified

**Comment by sinscary** [comment]
@moollaza I will look into this.
