### ISSUE TITLE
Twitter: Having this appear at the top of search results in my browser gives me a rash. Can it be made optional, or even better, opt-in?

### ISSUE THREAD

**Issue by acmdas** [duckduckgo/zeroclickinfo-spice#3586]
------
IA Page:  http://duck.co/ia/view/twitter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon

**Comment by moollaza** [comment]
@acmdas Instant Answers can be disabled in the DuckDuckGo settings: https://duckduckgo.com/settings

**Comment by acmdas** [comment]
Thank you.
