### ISSUE TITLE
Location Sunrise/Sunset Bug: Not display info for many cities

### ISSUE THREAD

**Issue by ivan-borisov** [duckduckgo/zeroclickinfo-spice#3588]
When i type many cities it not display info for them. For example Varna, Bulgaria
https://duckduckgo.com/?q=sunrise+varna&t=h_&ia=web

Vladivostok, Rusia
https://duckduckgo.com/?q=sunrise+vladivostok&t=h_&ia=web

Instant Answer Page: https://duck.co/ia/view/sun_rise_set

Maintainer: @iambibhas

Also may be is good to improve ia description. for example "sunset" also work and display sunset time for current location. Where is possible to suggest description edit for ia. Here or may be in reddit community?

**Comment by moollaza** [comment]
@ivan-borisov This Instant Answer currently supports a limited set of cities. Specifically Capitals of all countries.

DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
