### ISSUE TITLE
Flights by Route: Sometimes not display info

### ISSUE THREAD

**Issue by ivan-borisov** [duckduckgo/zeroclickinfo-spice#3589]
Yesterday user post info in reddit for problem

https://www.reddit.com/r/duckduckgo/comments/bew7tf/could_ddg_add_flight_status_in_search_results/

When I try all be OK, now again not display info. 
https://duckduckgo.com/?q=madrid+to+delhi+air+india&ia=route

Flight now is scheduled as google say
![Screenshot_2019-04-20 madrid to delhi air india - Google Search](https://user-images.githubusercontent.com/5180111/56454632-65f1d780-635c-11e9-9b23-170a675cb069.png)

BTW now i see in url `ia=web `instead `ia=route` but even when force to be route not work
https://duckduckgo.com/?q=madrid+to+delhi+air+india&ia=web

------
IA Page:  http://duck.co/ia/view/route 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @tommytommytommy

**Comment by borisov87** [comment]
Now works again  so as I see may be for any reason works only when flight is active, in air
![Screenshot_2019-04-20 madrid to delhi air india at DuckDuckGo](https://user-images.githubusercontent.com/5180111/56457170-7798a680-637f-11e9-9cb8-774b1ced699d.png)

**Comment by moollaza** [comment]
Thanks for reporting this @ivan-borisov.

> Now works again so as I see may be for any reason works only when flight is active, in air

Correct. Depending on whether the flight is active, or scheduled, the Instant Answer adjusts the window. I don't recall what exactly the window is but I think it defaults to checking if a flight is going to depart or land within 24hours?

Given DuckDuckHack is in Maintenance Mode, we are only fixing bugs that are critical, so I will mark this as tolerated and close.
