### ISSUE TITLE
Goodreads IA searches not showing up

### ISSUE THREAD

**Issue by iammrigank** [duckduckgo/zeroclickinfo-spice#3592]
Goodreads IA searches not showing up. Here are some valid search strings:
> - Goodreads Books By Cory Doctorow 
> - Gr Books On India

as mentioned in IA details page: https://duck.co/ia/view/goodreads

How can we go about troubleshooting this issue?

------
IA Page:  http://duck.co/ia/view/goodreads 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @iammrigank

**Comment by moollaza** [comment]
@iammrigank it looks like this IA is disabled. Likely due to an API issue. If you can confirm the API still works I can re-enable.

**Comment by iammrigank** [comment]
It could be the Amazon API that has stopped working. I will see what can be done. This could be closed or left open.
