### ISSUE TITLE
Stocks: price doesn't show up automatically for certain symbols

### ISSUE THREAD

**Issue by hyfather** [duckduckgo/zeroclickinfo-spice#3593]
Stock prices don't show up for all ticker symbols automatically.
For example, https://duckduckgo.com/?q=splk&t=ffab&ia=web

Perhaps being able to search for `$symbol` might make this easier? (e.g. `$splk`)

------
IA Page:  http://duck.co/ia/view/stocks 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @bsstoner

**Comment by moollaza** [comment]
@hyfather I'm seeing a "Stock" tab? Care to try again? It may not have opened it automatically which might be an internal bug, but I see a result at least in the Answer Bar.
