### ISSUE TITLE
Cryptocurrency: 

### ISSUE THREAD

**Issue by gschranz** [duckduckgo/zeroclickinfo-spice#3595]
Please add xrp.

Thank you!
------
IA Page:  http://duck.co/ia/view/cryptocurrency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
