### ISSUE TITLE
SoundCloud: Is this IA working?

### ISSUE THREAD

**Issue by frisbee00** [duckduckgo/zeroclickinfo-spice#3596]
I don't get the Audio results anymore.
Has this stopped working?

------
IA Page:  http://duck.co/ia/view/sound_cloud 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jdan

**Comment by moollaza** [comment]
@frisbee00 this Instant Answer has been offline for some time. I think we ran into issues with the API.

DuckDuckHack is currently in maintenance mode so this won't be turned back online.
