### ISSUE TITLE
Air Quality Index: 

### ISSUE THREAD

**Issue by ChrisG0x20** [duckduckgo/zeroclickinfo-spice#3600]
This doesn't appear to work.   

------
IA Page:  http://duck.co/ia/view/aqi 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @schluchc

**Comment by moollaza** [comment]
This Instant Answer is offline, there may have been an API outage that cause it to be disabled. I'm not sure if the API currently works but given that DuckDuckHack is in maintenance this won't be turned back on.
