### ISSUE TITLE
Congress: None of the example queries work

### ISSUE THREAD

**Issue by ChrisG0x20** [duckduckgo/zeroclickinfo-spice#3601]
None of the example queries work.

------
IA Page:  http://duck.co/ia/view/congress 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @kevinschaul

**Comment by moollaza** [comment]
This IA has been offline for some time. It looks like the API migrated to a new domain and likely needs to be setup again.

Given DuckDuckHack is in maintenance this will remain offline.
