### ISSUE TITLE
Cryptocurrency: 

### ISSUE THREAD

**Issue by briannyeko** [duckduckgo/zeroclickinfo-spice#3610]
When will you a currency converter(sort of like a calculator) that converts the value of a cryptocurrency (through Coinmarketcap(www.coinmarketcap.com) / Messari  /Coingecko(www.coingecko.com) API) to fiat. (A Crypto-to-Fiat exchange rate)?

Coinmarketcap, Coingecko and Messari have more coins added than Cryptonator. 

------
IA Page:  http://duck.co/ia/view/cryptocurrency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by moollaza** [comment]
@briannyeko thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

Our existing currency calculator handles crypto to fiat conversions for some of the more popular crypto currencies: https://duckduckgo.com/?q=btc+to+cad&t=ffab&ia=currency

We're unlikely to switch the API source anytime soon given we're in maintenance mode and Cryptonator seems to handle most queries. It looks like CoinMarketCap also wouldn't be free and we usually use free APIs for Instant Answers.

This will be marked as tolerated and closed.

**Comment by tmlee** [comment]
Hi @moollaza , I am from CoinGecko, our API is publicly available and is helping to power most open source apps out there that needs market data.

We are definitely happy to help expand the crypto price calculator on ddg and implement this if given the opportunity to do so once it goes out of maintenance

**Comment by moollaza** [comment]
@tmlee thanks, we appreciate the offer! I'll be sure to reach out if anything changes.
