### ISSUE TITLE
Instant answer feature not working for all stocks

### ISSUE THREAD

**Issue by rbabur** [duckduckgo/zeroclickinfo-spice#3612]
I am unable to see the instant answer for some of the stocks listed in US stock exchange.
For instance, Stocks:AMD doesnt show the instant answer with AMD stock price, instead it is listing out the websites only.   

------
IA Page:  http://duck.co/ia/view/stocks 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @bsstoner

**Comment by moollaza** [comment]
@rbabur Thanks for pointing this out. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

FWIW, removing the colon from your query seems to work. In most cases, just searching the stock symbol (eg. "AMD") will trigger the Instant Answer.

This will be marked as tolerated and closed.
