### ISSUE TITLE
Word definitions can't be copied

### ISSUE THREAD

**Issue by jash11** [duckduckgo/zeroclickinfo-spice#3614]
When the dictionary definition instant answer is triggered, the word has dots "`•`" in between the syllables. This is really not useful in any way. It only makes it harder to read the word, and also you can't highlight just the letters to copy-paste it (which is a big use-case: searching a misspelled word and copy-pasting the correct spelling). The dots should be removed to restore usability of the instant answer.

![image](https://user-images.githubusercontent.com/48420449/77000162-4d07f280-692e-11ea-9874-a5af2a77715d.png)

**Comment by moollaza** [comment]
@jash11 thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

I think breaking the word down into syllables is definitely helpful for knowing how to pronounce the word. For now your best option is to copy the word and remove the dots, or click the "More at" link to Wordnik where they provide the word as you'd like it.

This will be marked as tolerated and closed.
