### ISSUE TITLE
Translation: Instant answer doesn't work

### ISSUE THREAD

**Issue by BlueManCZ** [duckduckgo/zeroclickinfo-spice#3615]
Hello,
I don't know if this problem is only on my side, but an instant answer of `translate` doesn't seem to work. :eyes: 

![Snímek z 2020-04-09 17-20-15](https://user-images.githubusercontent.com/17854950/78911317-72e46b00-7a86-11ea-953a-b5cd0ad3f838.png)

------
IA Page:  http://duck.co/ia/view/translation 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @moollaza

**Comment by moollaza** [comment]
@BlueManCZ apologies, I had re-enabled that Instant Answer page to experiment with creating a translation Instant Answer. We don't have one available currently. I'll mark the IA as offline again.

**Comment by BlueManCZ** [comment]
That's a shame. I understand. Thank you for the information.

**Comment by victorsosa** [comment]
Hello,
Can we have this please, :+1:

**Comment by moollaza** [comment]
> Hello,
> 
> Can we have this please, :+1: 
> 
> Any help I can develop too.

Thanks for the offer. Unfortunately this will have to be built internally. It’s not a current focus, but on our radar, given how useful it could be. 

Hopefully we’ll be able to get to it soon!
