### ISSUE TITLE
Congress: 

### ISSUE THREAD

**Issue by StewAlexanderACC** [duckduckgo/zeroclickinfo-spice#3619]
Typing in "NC Congress" just pops up a bunch of website search results, so is this broken?

------
IA Page:  http://duck.co/ia/view/congress 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @kevinschaul

**Comment by moollaza** [comment]
@StewAlexanderACC thanks for reporting this. It appears this Instant Answer is offline. I think the API might have gone away, but regardless DuckDuckHack is currently in maintenance mode so this will have to stay offline.

I will mark this as tolerated and close the issue.
