### ISSUE TITLE
Editor: doesnt show up after searching "editor"

### ISSUE THREAD

**Issue by Sznio** [duckduckgo/zeroclickinfo-spice#3623]
------
IA Page:  http://duck.co/ia/view/editor 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jmg

**Comment by moollaza** [comment]
@Sznio thanks for reporting. This IA is offline so it's not currently working at all.

I don't believe "Editor" alone though is meant to trigger the IA as that's quite a broad term.
