### ISSUE TITLE
Currency Conversion: 

### ISSUE THREAD

**Issue by x-15a2** [duckduckgo/zeroclickinfo-spice#3624]
When trying to convert BYN (New Belarusian ruble) the conversion is for BYR (obsolete Belarusian ruble).

![image](https://user-images.githubusercontent.com/6061680/97498120-ff327e80-1941-11eb-8460-3a66e2669f28.png)

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by moollaza** [comment]
@x-15a2 looks like this is a duplicate of #3405

It's a known issue, but the issue is upstream with the XE API.

An XE rep reached out recently to me and I've been waiting to hear back from them regarding a fix in the API.

**Comment by ascrazy** [comment]
The bug is still there. Any plans to finally fix it?
