### ISSUE TITLE
BBC: Access is currently only available to BBC employees

### ISSUE THREAD

**Issue by noahmaranesi** [duckduckgo/zeroclickinfo-spice#3625]
BBC’s developer portal ([developer.bbc.com](https://developer.bbc.com/)) is currently only available to BBC employees.

> ### Getting Started
>
> The BBC Developer Portal is a hub for developers across the BBC to access and contribute to APIs and relevant documentation.
>
> **Access is currently only available to BBC employees.**

------
IA Page:  http://duck.co/ia/view/bbc

**Comment by moollaza** [comment]
@noahmaranesi thanks for pointing this out. The Instant Answer is already offline and given we're in maintenance mode it won't be coming online. There's not much to do here so I'm going to close this issue.
