### ISSUE TITLE
Actor Filmography: 

### ISSUE THREAD

**Issue by McBruno712** [duckduckgo/zeroclickinfo-spice#3628]
Simply does not work.

------
IA Page:  http://duck.co/ia/view/movies_filmography 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @whalenrp

**Comment by moollaza** [comment]
@McBruno712 Thanks for reporting.

This Instant Answer is offline and won't be coming back online as DuckDuckHack is in maintenance mode.
