### ISSUE TITLE
Editor: not working

### ISSUE THREAD

**Issue by palbecki** [duckduckgo/zeroclickinfo-spice#3629]
No editor appears. Tested on chrome 88 and firefox 85.

------
IA Page:  http://duck.co/ia/view/editor 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jmg

**Comment by cscottyb** [comment]
Not working on:
- Safari: Version 14.0.3 (16610.4.3.1.4)
-  Brave: Version 1.21.74 Chromium: 89.0.4389.72 (Official Build) (x86_64)

**Comment by moollaza** [comment]
Thanks for reporting. This Instant Answer is offline, so it won't appear. Given that DuckDuckHack is in maintenance mode, we aren't likely to re-enable this.

**Comment by cscottyb** [comment]
@moollaza thanks for the update.
