### ISSUE TITLE
Translation Suggestion: Amazon Translate as upstream provider

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-spice#3630]
### Description

My annual suggestion incoming... I know this has been talked about a couple of times internally, and namely:

  - https://github.com/duckduckgo/zeroclickinfo-spice/issues/3615

But AWS has now released a cheap service called Amazon Translate: https://aws.amazon.com/translate/
Presuming DDG is still hosted off AWS infrastructure this would be simple enough to hit from client to nginx. 

It would save me a couple of clicks to google and back 🙏 

## People to notify

@moollaza

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/{ID}

**Comment by moollaza** [comment]
Hey @pjhampton we actually just started an investigation last week into building a translation Instant Answer, which I too have been wanting for a long time. If you don't mind I'm going to mark this as internal and close it out.

We're leaning towards the Bing API but will let the team know about Amazon's

**Comment by pjhampton** [comment]
Rock on. Look forward to it!
