### ISSUE TITLE
Currency Conversion Not Working

### ISSUE THREAD

**Issue by x-15a2** [duckduckgo/zeroclickinfo-spice#3632]
This IA is not triggering on DDG. I used the sample queiry `Convert 499 Usd To Cad`

![image](https://user-images.githubusercontent.com/6061680/114270383-07efac00-99da-11eb-9ac6-61069eb778ca.png)
   

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
Looks like the IA is offline. Maybe someone internal at DDG can reenable?

**Comment by moollaza** [comment]
Whoops, I swear I left a comment on this thread when I saw it!

Anyways, it was an external issue, which has now been resolved. :)

Thanks as always for flagging this @x-15a2 , @pjhampton
