### ISSUE TITLE
Amazon: 

### ISSUE THREAD

**Issue by snehilprakash** [duckduckgo/zeroclickinfo-spice#3633]
may be some issue with amazon s3. I Checked that https://www.wpoven.com gives amazon s3 backup daily

------
IA Page:  http://duck.co/ia/view/products 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @bsstoner

**Comment by moollaza** [comment]
@snehilprakash it's not clear what this issue is about. Can you provide more details or example URLs, please?

We're not experiencing any problems with the Amazon Instant Answer as far as I know so I'm going to close this out for now.
