### ISSUE TITLE
Cryptocurrency: Not rendering IA results

### ISSUE THREAD

**Issue by nuke-web3** [duckduckgo/zeroclickinfo-spice#3635]
Example:
![image](https://user-images.githubusercontent.com/35669742/119179672-72115d00-ba2c-11eb-9749-6f2656433a01.png)

With or without the `ai=cryptocurrency`

Related thread: https://www.reddit.com/r/duckduckgo/comments/n9i0w1/crypto_converter_issue/

------
IA Page:  http://duck.co/ia/view/cryptocurrency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by moollaza** [comment]
Thanks for reporting @NukeManDan  -- this should be online again as of a couple hours ago 👍 

Note: the `ia=cryptocurrency` won't do anything in the query. It's a URL parameter that specifies to us what tab should be open on page load. It can't force any particular instant answer to appear, so in this case, with the IA being offline, it won't have any effect.
