### ISSUE TITLE
Flight: "Departed ago"

### ISSUE THREAD

**Issue by loganom** [duckduckgo/zeroclickinfo-spice#386]
By chance I noticed this while investigating other Flight IA bugs

Query submitted at 10:44pm local time. 

![screen shot 2014-01-19 at 10 45 02 pm](https://f.cloud.github.com/assets/2434012/1951726/e92be4b2-818d-11e3-88be-cc8f78e48a27.png)

**Comment by javathunderman** [comment]
@jagtalon Just saw this and checked it out on the site. The wording was changed, so this can be closed.

**Comment by moollaza** [comment]
The design of this IA has also changed, so we should be good.
