### ISSUE TITLE
Hayoo instant answer not showing for any related queries. 

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/zeroclickinfo-spice#399]
https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Hayoo.pm?source=cc

primary example not showing instant answer: https://duckduckgo.com/?q=hayoo+Prelude.map 

Can't get any to generate :(

**Comment by jagtalon** [comment]
Hayoo's API is not available: https://github.com/duckduckgo/zeroclickinfo-spice/pull/1376. Closing this.
