### ISSUE TITLE
Make topics work for the Brainy Quote instant answer

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#430]
The instant answer currently works if we specify an author, e.g., "gandhi quotes". But Brainy Quote should also handle topics such as "physics quotes". Problem with that is it can be too broad sometimes--it can trigger on things like "apple quotes" or "stock quotes".

We should explore the idea of using the top 120 topic quotes on http://www.brainyquote.com/quotes/topics.html and only accept those (it would be the JS code that will do the checking).

https://duck.co/ia/view/brainy_quote

**Comment by killerfish** [comment]
What template do we use for this? I mean tile view might just look awkward.

**Comment by moollaza** [comment]
I think a tile view could work if we're showing multiple quotes. We might want to go with taller, narrow tiles likes our News tile, or maybe wider ones, like we're doing for TodayInHistory.

I'd say start basic, with no customization and let's see how it works. We can go from there with the design team :)

**Comment by killerfish** [comment]
Well, we could allow only a certain length quotes for tiles, and use view like todayinhistory, that might fit, but dont we break the standard of showing one quote? Or do we split views based whether query is 'quote' or 'quotes'?

**Comment by gaulrobe** [comment]
@moollaza looks like topical queries are working for this IA

https://duckduckgo.com/?q=physics+quotes&ia=quotations

Is there anything left to do here?

**Comment by moollaza** [comment]
> Is there anything left to do here?

I don't think so!
