### ISSUE TITLE
Switch Octopart API 

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#455]
Upgrade to their new API http://octopart.com/api/home

https://duck.co/ia/view/octopart

**Comment by moollaza** [comment]
I actually made an issue for this already: https://github.com/duckduckgo/zeroclickinfo-spice/issues/1595

@killerfish can you get your own key for development? https://octopart.com/auth/create

**Comment by moollaza** [comment]
Whoops, just realized this issue is much older! We can continue discussion in the new thread, it outlines more details.
