### ISSUE TITLE
Stopwatch - Should use a fixed-width font

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#492]
Not sure how I didn't notice before but when running the stopwatch, because we're not using a fixed-width font the text area constantly jiggles around. I find this really annoying and makes the page seem almost broken.

@chrismorast do we have a go-to fixed-width font we can use here? Alternatively we can just let let the browser choose by setting `font-family: monospace`

//cc @jagtalon @mattr555

**Comment by javathunderman** [comment]
@jagtalon Should this be closed off?

**Comment by moollaza** [comment]
@mattr555 @javathunderman I'm still seeing issues here in Firefox, but they're very minor. Closing this.
