### ISSUE TITLE
Expatistan: The information in the parenthesis should be styled differently

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#687]
The current one looks like this:
![screen shot 2014-05-05 at 6 51 03 pm](https://cloud.githubusercontent.com/assets/81969/2892041/a49d3e28-d538-11e3-8da4-acc0ce134c42.png)

Now instead of italics, it should be styled like the subheading on the IsItUp instant answer (the part in grey):
![text](https://cloud.githubusercontent.com/assets/81969/2892053/cead860a-d538-11e3-9a97-eab89f993038.jpg)

**Comment by MariagraziaAlastra** [comment]
This was fixed in #1041
