### ISSUE TITLE
Rename amazon to products

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/zeroclickinfo-spice#689]

**Comment by killerfish** [comment]
Do we want to rename the instant answer to products, or the name displayed (which it already does).

**Comment by moollaza** [comment]
I think we wanted to rename just the tab. I'm not sure if renaming the package would cause problems, but I fear it may require a lot of internal changes.

@nilnilnil should we rename the Package to `DDG::Spice::Products`?

**Comment by altern8tif** [comment]
Should we close this?  Seems to have been resolved already.
