### ISSUE TITLE
Quixey: Some buttons in the detail view gets pushed too far down

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#772]
This happens on mobile.

![screen shot 2014-05-16 at 6 03 15 pm](https://cloud.githubusercontent.com/assets/81969/3002831/012af986-dd46-11e3-9b2c-e6f126303f02.png)

https://duck.co/ia/view/quixey

**Comment by moollaza** [comment]
Fixed! Templates now have reduced image/font sizes it seems.
