### ISSUE TITLE
Release Gify

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#816]
We should see if https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Gifs.pm is ready for launch or not.

**Comment by javathunderman** [comment]
@jagtalon @bsstoner @russellholt Probably should contact them on this. Love to see this IA back up and running.

**Comment by moollaza** [comment]
@javathunderman we were actually talking about this IA internally last week and I plan to launch it soon!

**Comment by javathunderman** [comment]
@moollaza Awesome, looking forward to it.

**Comment by jagtalon** [comment]
Done! https://duckduckgo.com/?q=cat+giphy&ia=gifs
