### ISSUE TITLE
Release OpenSNP

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#870]
https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/open_snp/open_snp.js

**Comment by javathunderman** [comment]
@jagtalon I think this can be closed...

**Comment by moollaza** [comment]
@javathunderman this IA doesn't seem to be live? https://duckduckgo.com/?q=rs7903146&ia=answer (sadly that's not the best result either..)

**Comment by javathunderman** [comment]
Correct me if I'm wrong, but the code looks OK. I believe that the only issue is that it isn't up.

**Comment by moollaza** [comment]
@javathunderman actually, now that I took a second look the code isn't updated. The `Spice.add()` call needs to be updated to use the new, required parameters. (i.e. `header1` is old, etc)
