### ISSUE TITLE
Forecast Spice: Wrong location?

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#893]
From Duck.co, https://duck.co/forum/thread/7105/location-tracking-not-working

> When I search weather on duckduckgo it gives me weather for kriens Switzerland. When I search where am I it gives my correct location (Wellington, New Zealand).

------ 

IA Page: https://duck.co/ia/view/forecast

**Comment by javathunderman** [comment]
@moollaza Seems like this is still an issue.

**Comment by joaquinlpereyra** [comment]
Confirming this is still an issue.

Where I am correctly states 'Buenos Aires', weather giving me weather for a little-known city called Federal some 1.000 kilometers north.

**Comment by moollaza** [comment]
Closing. Duplicate of #899
