### ISSUE TITLE
MetaCPAN - Switch to new API, show more data

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#898]
Currently we are using an older API which only surfaces information for a given module. The API we're using is also case sensitive,  so "app::duckpan" will not show any results for "App::DuckPAN": https://duckduckgo.com/?q=cpanm+App%3A%3ADuckPAN, https://duckduckgo.com/?q=cpanm+app%3A%3Aduckpan.

It seems that the API has since been updated allowing for a general search endpoint:
http://api.metacpan.org/v0/release/_search?q=cpanminus

I suggest we switch to the new API to allow for true "search" of MetaCPAN Packages. In the event that the search does not exactly match a module name we could return a list of results and in the event that a module name is correctly indicated we should only show that result.

The API currently provides tons of info, most of which we probably don't need. You can choose which elements to return by indicating, for example `&fields=name,id` in the URL. `&fields=version,name,author,date,distribution` seems like a good start :)

E.g. http://api.metacpan.org/v0/release/_search?q=string%20trim&fields=name,abstract,version,metadata,author,download_url,date,distribution

This doc provides some insight into all the available fields:https://github.com/CPAN-API/cpan-api/blob/master/lib/MetaCPAN/Document/File.pm

https://duck.co/ia/view/meta_cpan

**Comment by moollaza** [comment]
@heytitle just wondering if you still interested in working on this? I just updated my comment https://github.com/duckduckgo/zeroclickinfo-spice/issues/898#issuecomment-48227527 -- we should be able to move forward with this :+1:

**Comment by heytitle** [comment]
@moollaza Oh, sorry it was done already. I'll have a look. :)

**Comment by altern8tif** [comment]
@heytitle @moollaza Is this still being worked on? Wouldn't mind taking it up (together with #1706) to close the issue...

**Comment by moollaza** [comment]
@altern8tif no it's not, please do take it up! We don't have Package names does the CPAN results and it's been driving me crazy. I nearly fixed that myself last week :smile:

**Comment by altern8tif** [comment]
Having a bit of trouble with the MetaCPAN API... I've got this endpoint but it doesn't seem to filter out the results that don't return a `module`.

```
http://api.metacpan.org/v0/module/_search?q=duckduckgo+status:latest&fields=abstract,module,date,status&filter={"exists":{"field":"module"}}
```
Been using the [MetaCPAN Explorer](https://explorer.metacpan.org/) to get the resultant JSON but I still see results that are not showing the module information.

Anyone care to advise?

**Comment by moollaza** [comment]
@altern8tif I believe the API is open source on GitHub? Maybe we need to open an issue for them to fix it?

**Comment by altern8tif** [comment]
@moollaza thanks... I've opened an issue.  Will wait for their reply first then.

**Comment by altern8tif** [comment]
Been mucking through the [MetaCPan API](https://github.com/CPAN-API/cpan-api/blob/master/docs/API-docs.md) and trying to see if I can use a single URI to plug into DDG's Spice endpoint (as opposed to using `curl`).  Using the search results without filtering will cause the JSON to return results which don't have module names or abstracts/descriptions – which is not ideal for the user experience.

<img width="1214" alt="screen shot 2015-12-18 at 4 00 40 pm" src="https://cloud.githubusercontent.com/assets/5793364/11892173/9cb02f1a-a5a0-11e5-9544-a0f8d12b8796.png">
<img width="1214" alt="screen shot 2015-12-18 at 4 01 00 pm" src="https://cloud.githubusercontent.com/assets/5793364/11892174/9ce51c84-a5a0-11e5-996b-17dd504f9685.png">

This is what I have so far, but mixing JSON & query parameters [don't seem to work](https://github.com/CPAN-API/cpan-api/issues/426#issuecomment-154718572):
`http://api.metacpan.org/v0/module/_search?q=$1+status:latest&fields=abstract,module.name,module.version,date&filter={"exists":{"field":"module"}}
`

Anyone familiar with Elastic Search and able to advise?

**Comment by moollaza** [comment]
@altern8tif sorry for the delay -- depending on how the API works, if we can get a list of package names that are relevant to a query, we could load additional info as the tile renders using a 2nd endpoint -- would that make things easier?

**Comment by zachthompson** [comment]
@ghedo are you around and interested in maintaining this?
