### ISSUE TITLE
Forecast - Gives weather for incorrect country

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#899]
Moved from https://github.com/duckduckgo/duckduckgo/issues/54

> When I search: "Vancouver Weather" in DDG, I get weather for Vancouver, WA. I'm actually looking for Vancouver, BC weather. I can fix this by searching for "Vancouver, BC Weather", but that is annoying, considering this is a search I might make quite often.
> 
> Perhaps a solution for this is to prioritize cities based on your region in settings. Since I set my region to Canada, perhaps it should prioritize the Vancouver in Canada.

I agree with @penguinvasion's recommendation -- we should prioritize locations that are physically closer to the user when multiple results with the same name exist

------ 

IA Page: https://duck.co/ia/view/forecast

**Comment by zilespiral** [comment]
Haven't you found any solution yet? I too keep getting the weather from Rochester, NY, even though I have my results localized to Mexico. The "where am I?" instant answer is finding my approximate location correctly, though.

**Comment by iambibhas** [comment]
@moollaza maybe ask forecast.io to provide an extra param in the endpoint to provide a state/country and prioritize results close to it?

**Comment by halosbe** [comment]
Searching for "costa rica weather" returns "Weather for San José, Uruguay" (should be San José, Costa Rica)

**Comment by eggpi** [comment]
For what it's worth, I'm seeing what appears to be the same problem when searching for "weather in Dublin". When no region is set, I get an instant answer for Dublin, TX even though I'm on an Irish IP address, which should presumably be enough to resolve the query to Dublin, Ireland. I get no instant answer at all after setting my region to Ireland.

**Comment by mrshu** [comment]
The triggering fro the `Forecast` Spice got improved a bit from the inside. Can you please check whether the problems described in this issue still persist? 

I tried "Vancouver Weather" for instance, and the result seems to be in line with the desired outcome described in the first comment.

**Comment by eggpi** [comment]
Yep, "weather in Dublin" now does the right thing when not filtering by region (still no instant answer when filtering).

It actually seems to resolve the query to a very specific landmark in the city ("Weather for Spire of Dublin, North Earl Street, Dublin, County Dublin, Ireland"), which I'm not sure is intended, but the result looks fine regardless of that :)

**Comment by mrshu** [comment]
@eggpi unfortunately, the very specific landmark is what `forecast.io` returns -- there is not really much we can do about that.

Thanks for confirming that `weather in Dublin` does the right thing now (at least for the "World traveler").

**Comment by UninterestinAcc** [comment]
I also want to note that `weather for melbourne` returns results for `Melbourne, Florida` (population 76k) and not `Melbourne, Australia` (population 4.6m; *way* bigger city). This can error can be corrected in two ways.

1. If I search `weather for melbourne australia` instead.
2. If I check the switch for Australian results.

**Comment by moollaza** [comment]
I've created a new issue, #3561 where I've combined similar issues as well. I'm closing this in favour of that newer issue.

We are aware of the relevancy issues here and are currently working on improvements.
