### ISSUE TITLE
Make sure we're using Sort blocks where applicable

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#988]
Many Spice IA's sort their results but aren't using a sorting block, which they really should.

A quick check shows several Spice's that aren't correctly sorting their results:

- [x] Airlines
- [ ] Book
- [ ] Detect Lang
- [x] People In Space
- [ ] DNS
- [ ] Bootic
- [x] GitHub
- [x] Congress
- [x] Recipes

```js
share/spice/book/book.js
67:                recommendedBy.sort(function(){return (4*Math.random()>2)?1:-1});

share/spice/bootic/bootic.js
14:        for(var i = 0; i < api_result.sorted.length; i++) {
15:            result.push(api_result.products[api_result.sorted[i]]);

share/spice/detect_lang/detect_lang.js
21:    api_result.data.detections.sort(function(a, b) {

share/spice/dns/dns.js
10:        api_result.response.records.sort(function(a, b) {

share/spice/recipes/recipes.js
109:        return sparse.sort(function(a,b){
```

**Comment by sahildua2305** [comment]
@jdorweiler Can you please point me at an updated doc for Sorting block? The link you mentioned doesn't work now.

**Comment by moollaza** [comment]
@sahildua2305 please see http://docs.duckduckhack.com/frontend-reference/display-reference.html#sortfields-object-optional

Examples: https://github.com/duckduckgo/zeroclickinfo-spice/search?utf8=%E2%9C%93&q=sort_fields&type=Code

**Comment by sahildua2305** [comment]
@moollaza I started with `Detect Lang` and found that it's not necessary to use the sorting block in this case. The `data` it returns to the front end contains one object having two values each of which is an object. If we have to use sorting block here, that will change the entire structure of `content.handlers` as well as the data being sent to front-end. Let me know what you think about this. I will go ahead with this one only if you approve it.

**Comment by sahildua2305** [comment]
@moollaza Same goes for `DNS` as well. It's using template group `base` and it is sending a list of objects to the content handler. Using Sorting block doesn't work here because we actually want to sort the response.records not the response itself, that's being sent. 

Please have a look and let me know if I am testing the changes correctly or not.
See here - https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/dns/dns.js#L10

**Comment by sahildua2305** [comment]
@moollaza `Recipes` is already using the `sort_fields` as can be seen here - https://github.com/duckduckgo/zeroclickinfo-spice/blob/04aaf11a04664c390accb8d5676618eacfa4b950/share/spice/recipes/recipes.js#L142

**Comment by moollaza** [comment]
> @moollaza I started with Detect Lang and found that it's not necessary to use the sorting block in this case.

@sahildua2305 it looks like you're correct here -- we're only returning 2 results instead of all of them. However, looking at this IA, the code is quite old and should be updated to match the format where the spice callback is defined inside a closure. As well, this IA is using the `Base` template, which isn't necessary given how simple the template logic is.

Would you be interested in updating the code to the new format and having it use the `text` template with a `title`? (and `subtitle` if necessary)

> @moollaza Same goes for DNS as well. It's using template group base and it is sending a list of objects to the content handler. Using Sorting block doesn't work here because we actually want to sort the response.records not the response itself, that's being sent.

It looks like in this case we _technically_ could use the sort block. Instead of sending the whole response as the `data` we could set `data: api_result.response.records` then sort that and iterate over `this` in the template. However, it looks like this IA is currently offline because we're having problems with the API so you may not even be able to test any changes. As well, this AI doesn't need to be using the `base` template. It would be ideal to switch it to the `text` template with a `title` providing some context, e.g. "DNS Records for: <url>"

**Comment by sahildua2305** [comment]
> Would you be interested in updating the code to the new format and having it use the text template with a title? (and subtitle if necessary)
Yes, I will be interested in doing so. Can you please point me to the new format and how to use the text template for I am new to this and don't really know about differences between the old and the new template?

**Comment by sahildua2305** [comment]
I figured it out and have created this PR #2806 @moollaza 
Please review.
