### ISSUE TITLE
Flash version doesn't show the last 3 numbers. 

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/zeroclickinfo-spice#99]
DDG can tell you your flash version but it doesn't give you the last 3 numbers:

Example: On DDG:  "Your Flash Player version: 11.1.102 More at Adobe". 

Full version: "11.1.102.62" 

Also, it would be useful to have the version table available on Adobe at: http://kb2.adobe.com/cps/155/tn_15507.html

**Comment by javathunderman** [comment]
@jagtalon @zekiel @bsstoner Seems like this can be closed then?

**Comment by moollaza** [comment]
@javathunderman I don't think we've resolved it yet, so we should keep it open.

**Comment by MrChrisW** [comment]
Fixed in #2373

**Comment by javathunderman** [comment]
@MrChrisW nice :+1:
