### ISSUE TITLE
XKCD: Breaks for "Dynamic" Comics

### ISSUE THREAD

**Issue by zgrep** [duckduckgo/zeroclickinfo-spice#992]
The way I see it, to have interactive xkcd's work, I see two options:
- Completely ignore the interactive xkcd's
  - Or provide a link to the xkcd with some text saying something along the lines of  
    `this xkcd is interactive, click here for more`
- For each interactive xkcd, work out a way to build it in... (this is probably _extremely_ time consuming, and maybe not always possible)

For more information, what currently happens is it shows the previous xkcd. Not sure if this is xkcd's doing or built in...

---

IA Page: https://duck.co/ia/view/xkcd
Maintainer: @sdball

**Comment by moollaza** [comment]
I just realized that for all but one of these "Dynamic" Comics the Instant Answer looks is broken:

- [1037](https://duckduckgo.com?q=kxcd+1037)
- [1190](https://duckduckgo.com?q=kxcd+1190)
- [1193](https://duckduckgo.com?q=kxcd+1193)
- [1335](https://duckduckgo.com?q=kxcd+1335) (image renders, but it’s a static PNG)
- [1446](https://duckduckgo.com?q=kxcd+1446)
- [1608](https://duckduckgo.com?q=kxcd+1608)

We should implement a check for these and alter the display to provide a link or something so that it doesn't look broken.

**Comment by moollaza** [comment]
This AI is breaking again today, showing an empty space where he comic would be.

@duckduckgo/duckduckhack-contributors anyone interested in investigating a better way to handle they interactive comics?

We should at least provide a message that explains we can't display the comic so the user understands what's going on.

**Comment by riqpe** [comment]
I gave it a quick look, and some of those issues could be solved quite easily. 
No image happens when the JSON returned by xkcd contains img url without actual image (commonly just "http:\/\/imgs.xkcd.com\/comics\/", simple to catch and inform the user.
Unfortunately for some of the cases xkcd will return a link to an actual placeholder image, as is the case with Landing comic [1446](https://duckduckgo.com/?q=xkcd+1446), where the link is to http:\/\/imgs.xkcd.com\/comics\/%3F%3F%3F.png , a valid blank white image. Handling a case like this would be considerably more difficult.

**Comment by prasadram** [comment]
Hi All,
I am interested

**Comment by philipmiesbauer** [comment]
How about framing the image of to show that the picture is there but white?

**Comment by riqpe** [comment]
@philipmiesbauer I took that approach on another project displays images from multiple sources, but while it makes it easier to see that the image "exists", this really adds little value as the blank image is not what the artist meant to publish. In addition, adding visual frames can have a negative effect on what the artist wanted to convey with the image. Consider comics where the 4th wall is physically broken. In those cases adding the frame would break the illusion.

**Comment by EpicWolverine** [comment]
Just a note: 1335 is already hard-coded to be static, despite the xkcd JSON API returning the correct current comic (`http://imgs.xkcd.com/comics/now.png`, which always redirects to the current one). 

In xkcd_display.js:

> `// Add exception for comic 1335.`
> `if(api_result.num === 1335) {`
> `api_result.img = 'http://imgs.xkcd.com/comics/now/12h30m.png';`
> `}`

While hard-coding placeholders (or even working versions for comics like 1335 and 1331) of all the dynamic or interactive comics is not ideal, it may be a good temporary solution. I wonder if we could even get in touch with Randall or davean the sysadmin (https://xkcd.com/about/) to see if they can add some sort of flag or other indicator to the API to tell us it is a dynamic comic so it can be handled better.

**Comment by riqpe** [comment]
I'd say a combination of these would be the best option. Naturally when the img url is obviously incorrect, such as linking just to https://imgs.xkcd.com/comics/, or missing completely, some indication could be shown to the user, as proposed in the original issue. 
However, the link being invalid can't be assumed to mean that the corresponding comic is interactive. Having a proper indicator for this in the JSON retrieved from xkcd would be optimal.
Anyone know if davean is on GitHub?

**Comment by soleo** [comment]
According to https://keybase.io/davean, This(https://github.com/davean) is hime

**Comment by sdball** [comment]
Five years ago I was a front end developer and wrote the first spice PR to add xkcd comics to DDG. It was a fun project and I'd love to continue maintaining it (although it's changed quite a bit since 2011). Unfortunately I simply don't have the time to volunteer. I'm going to unplug from this.

**Comment by MrChrisW** [comment]
No problem @sdball, thanks for letting us know!

We're in the process of pinging the creators of various IA's to see if people would like to continue maintaining them, if not someone else will jump on board! 

Thanks for your original contribution (5 years ago) - I'm sure this IA will continue to be improved by the DDG community. :+1:

**Comment by MrChrisW** [comment]
Ultimately this needs an upstream API change to indicate if the comic is dynamic or not, as suggested by several members.

As a workaround I'd suggest we check the `title` value matches the filename of the image returned in the `url` value, this will resolve issues with the returning the previous comic [1350](https://duckduckgo.com/?q=xkcd+1350) and with displaying a placeholder [1446](https://duckduckgo.com/?q=xkcd+1446)

**1662** - Normal comic
````json
    "num": 1662,
    "img": "http://imgs.xkcd.com/comics/jack_and_jill.png",
    "title": "Jack and Jill",
````

**1446** - Dynamic comic with placholder
````json
    "num": 1446,
    "img": "http://imgs.xkcd.com/comics/%3F%3F%3F.png",
    "title": "Landing",
````

**1350** - Dynamic comic with previous comic image
````json
    "num": 1350,
    "img": "http://imgs.xkcd.com/comics/shouldnt_be_hard.png",
    "title": "Lorenz",
````

**Comment by zgrep** [comment]
Unfortunately, that workaround would fail for earlier comics such as [1](http://xkcd.com/1/), [2](http://xkcd.com/2/), [3](http://xkcd.com/3/), etc.

**Comment by MrChrisW** [comment]
@zgrep You're correct! I manged to get past the matching of comics 1,2 & 3 (with some [painful code](https://gist.github.com/MrChrisW/0d752f951142fcbad92dbd71df9f9e86#file-xkcd_read-js-L25-L45))  -Unfortunately there's a few more `titles` that [don't match the `url` filename at all](https://gist.github.com/MrChrisW/081b03d6be2011b36da7488d9fe78f67) so this isn't a solution, it also feels like an anti-pattern..

**Comment by MrChrisW** [comment]
Ok... After some more testing I think the best way to processed as a **temporary solution** (in the absence of an API update) is to create a `blacklist.txt` file with a list of dynamic/non-working comics, we can then avoid triggering the IA or display a message as suggested by @zgrep if a comic id is found in the blacklist.

Current comics that cannot be displayed/are dynamic 

+ [1331](https://duckduckgo.com/?q=xkcd+1331)
+ [1350](https://duckduckgo.com/?q=xkcd+1350)
+ [1416](https://duckduckgo.com/?q=xkcd+1416)
+ [1525](https://duckduckgo.com/?q=xkcd+1525)
+ [1608](https://duckduckgo.com/?q=xkcd+1608)
+ [1663](https://duckduckgo.com/?q=xkcd+1663)
+ [1037](https://duckduckgo.com/?q=xkcd+1037)
+ [1190](https://duckduckgo.com/?q=xkcd+1190)
+ [1193](https://duckduckgo.com/?q=xkcd+1193])
+ [1335](https://duckduckgo.com/?q=xkcd+1335])
+ [1446](https://duckduckgo.com/?q=xkcd+1446)
+ [1608](https://duckduckgo.com/?q=xkcd+1608)

Let me know if I'm missing any non-working comics

**Comment by zgrep** [comment]
According to @davean, the API is in the process of being rewritten, along with the website itself. Hopefully a more permanent and supposedly better solution will present itself in the future.

I also asked if it was possible to add a "dynamic" part to the current JSON API. The answer is, of course, that it's possible. But, it turns out that any comic that changes the page around it would be considered dynamic, such as [1005: SOPA](https://xkcd.com/1005/), which probably isn't what's considered to be dynamic in human terms and/or DuckDuckGo-successfully-embeddable-images terms.

For now, however, until the future manages to bestow itself upon us, there aren't so many dynamic comics that it's not unthinkable of simply coding in a list of exceptions, as mentioned by @MrChrisW. Any dynamic comics that we wish to support in some way, such as [1335: Now](http://xkcd.com/1335/), could simply have hard-coded exceptions, as 1335 has at the moment (even though personally I don't agree with the way in which it's handled).

Also, @MrChrisW, some of those links have an extra `]` in them.

**Comment by moollaza** [comment]
Closing due to DDH entering Maintenance Mode. We are only accepting issues for essential bugs.

It doesn't look like the XKCD API has changed yet anyways.
